/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=doCreateTypeDeclaration_9969b4479b
ROOST_METHOD_SIG_HASH=doCreateTypeDeclaration_e44b1e3869

```plaintext
Scenario 1: Verify that doCreateTypeDeclaration creates a KotlinTypeDeclaration with the given name

Details:
  TestName: createsKotlinTypeDeclarationWithGivenName
  Description: This test ensures that the doCreateTypeDeclaration method correctly creates a KotlinTypeDeclaration instance with the provided name.

Execution:
  Arrange: Set up a KotlinCompilationUnit instance.
  Act: Invoke the doCreateTypeDeclaration method with a sample name.
  Assert: Verify that the returned KotlinTypeDeclaration has the expected name.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Verify that doCreateTypeDeclaration handles null input gracefully

Details:
  TestName: handlesNullInputGracefully
  Description: This test ensures that the doCreateTypeDeclaration method handles null input gracefully by either returning null or throwing an appropriate exception.

Execution:
  Arrange: Set up a KotlinCompilationUnit instance.
  Act: Invoke the doCreateTypeDeclaration method with a null value.
  Assert: Verify that the method either returns null or throws an IllegalArgumentException.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Verify that doCreateTypeDeclaration creates a unique KotlinTypeDeclaration for each unique name

Details:
  TestName: createsUniqueKotlinTypeDeclarationForEachUniqueName
  Description: This test ensures that the doCreateTypeDeclaration method creates a unique KotlinTypeDeclaration instance for each unique name provided.

Execution:
  Arrange: Set up a KotlinCompilationUnit instance.
  Act: Invoke the doCreateTypeDeclaration method with two different names.
  Assert: Verify that the returned KotlinTypeDeclaration instances are not the same and have the expected names.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Verify that doCreateTypeDeclaration is idempotent for the same name

Details:
  TestName: isIdempotentForSameName
  Description: This test ensures that the doCreateTypeDeclaration method returns the same KotlinTypeDeclaration instance when invoked multiple times with the same name.

Execution:
  Arrange: Set up a KotlinCompilationUnit instance.
  Act: Invoke the doCreateTypeDeclaration method with the same name multiple times.
  Assert: Verify that the returned KotlinTypeDeclaration instances are the same.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import io.spring.initializr.generator.language.CompilationUnit;
import io.spring.initializr.generator.language.kotlin.KotlinCompilationUnit;
import io.spring.initializr.generator.language.kotlin.KotlinFunctionDeclaration;
import io.spring.initializr.generator.language.kotlin.KotlinTypeDeclaration;
import org.junit.jupiter.api.*;

public class KotlinCompilationUnitDoCreateTypeDeclarationTest extends CompilationUnit<KotlinTypeDeclaration> {

	private KotlinCompilationUnit kotlinCompilationUnit;

	@BeforeEach
	void setUp() {
		kotlinCompilationUnit = new KotlinCompilationUnit("com.example", "TestCompilationUnit");
	}

	@Test
	@Tag("valid")
	public void createsKotlinTypeDeclarationWithGivenName() {
		String name = "TestType";
		KotlinTypeDeclaration typeDeclaration = kotlinCompilationUnit.doCreateTypeDeclaration(name);
		assertThat(typeDeclaration).isNotNull();
		assertThat(typeDeclaration.getName()).isEqualTo(name);
	}

	@Test
	@Tag("invalid")
	public void handlesNullInputGracefully() {
		assertThatThrownBy(() -> kotlinCompilationUnit.doCreateTypeDeclaration(null))
			.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	@Tag("valid")
	public void createsUniqueKotlinTypeDeclarationForEachUniqueName() {
		String name1 = "Type1";
		String name2 = "Type2";
		KotlinTypeDeclaration typeDeclaration1 = kotlinCompilationUnit.doCreateTypeDeclaration(name1);
		KotlinTypeDeclaration typeDeclaration2 = kotlinCompilationUnit.doCreateTypeDeclaration(name2);
		assertThat(typeDeclaration1).isNotNull();
		assertThat(typeDeclaration2).isNotNull();
		assertThat(typeDeclaration1).isNotSameAs(typeDeclaration2);
		assertThat(typeDeclaration1.getName()).isEqualTo(name1);
		assertThat(typeDeclaration2.getName()).isEqualTo(name2);
	}

	@Test
	@Tag("valid")
	public void isIdempotentForSameName() {
		String name = "TestType";
		KotlinTypeDeclaration typeDeclaration1 = kotlinCompilationUnit.doCreateTypeDeclaration(name);
		KotlinTypeDeclaration typeDeclaration2 = kotlinCompilationUnit.doCreateTypeDeclaration(name);
		assertThat(typeDeclaration1).isNotNull();
		assertThat(typeDeclaration2).isNotNull();
		assertThat(typeDeclaration1).isSameAs(typeDeclaration2);
		assertThat(typeDeclaration1.getName()).isEqualTo(name);
		assertThat(typeDeclaration2.getName()).isEqualTo(name);
	}

}