/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=isKeyword_ec745f5e02
ROOST_METHOD_SIG_HASH=isKeyword_c1f16451c3

```plaintext
Scenario 1: Verify that the method returns true for a valid Kotlin keyword.

Details:
  TestName: returnsTrueForValidKeyword
  Description: This test checks if the isKeyword method returns true when a valid Kotlin keyword is provided as input.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a valid Kotlin keyword, e.g., "fun".
  Assert: Assert that the method returns true.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Verify that the method returns false for a non-Kotlin keyword.

Details:
  TestName: returnsFalseForNonKeyword
  Description: This test ensures that the isKeyword method returns false when a string that is not a Kotlin keyword is provided.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a non-Kotlin keyword, e.g., "hello".
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Verify that the method handles null input gracefully.

Details:
  TestName: handlesNullInput
  Description: This test checks if the isKeyword method handles null input gracefully by returning false without throwing an exception.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with null as input.
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Verify that the method returns false for an empty string input.

Details:
  TestName: returnsFalseForEmptyString
  Description: This test ensures that the isKeyword method returns false when an empty string is provided as input.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with an empty string.
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Verify that the method returns true for a case-sensitive valid Kotlin keyword.

Details:
  TestName: returnsTrueForCaseSensitiveKeyword
  Description: This test checks if the isKeyword method returns true for a valid Kotlin keyword that is case-sensitive, ensuring that the method differentiates between upper and lower case letters.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a valid Kotlin keyword in a different case, e.g., "Fun".
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Verify that the method returns false for a substring of a valid Kotlin keyword.

Details:
  TestName: returnsFalseForSubstringOfKeyword
  Description: This test ensures that the isKeyword method returns false when a substring of a valid Kotlin keyword is provided as input.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a substring of a valid Kotlin keyword, e.g., "fu".
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: Verify that the method returns false for a valid Kotlin keyword with leading or trailing whitespaces.

Details:
  TestName: returnsFalseForKeywordWithWhitespaces
  Description: This test checks if the isKeyword method returns false when a valid Kotlin keyword with leading or trailing whitespaces is provided as input.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a valid Kotlin keyword that has leading or trailing whitespaces, e.g., " fun " or "fun ".
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 8: Verify that the method returns false for a valid Kotlin keyword with special characters appended.

Details:
  TestName: returnsFalseForKeywordWithSpecialCharacters
  Description: This test ensures that the isKeyword method returns false when a valid Kotlin keyword with special characters appended is provided as input.
Execution:
  Arrange: No specific setup is required for this test.
  Act: Call the isKeyword method with a valid Kotlin keyword that has special characters appended, e.g., "fun!" or "fun@".
  Assert: Assert that the method returns false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import io.spring.initializr.generator.language.AbstractLanguage;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.Set;
import io.spring.initializr.generator.language.Language;

public class KotlinLanguageIsKeywordTest extends AbstractLanguage {

	public KotlinLanguageIsKeywordTest() {
		super(ID, DEFAULT_JVM_VERSION, "kt");
	}

	private static final Set<String> KEYWORDS = Set.of("fun", "class", "val", "var", "if", "else");

	@Override
	public boolean supportsEscapingKeywordsInPackage() {
		return true;
	}

	@Override
	public boolean isKeyword(String input) {
		return KEYWORDS.contains(input);
	}

	@Test
	@Tag("valid")
	public void returnsTrueForValidKeyword() {
		assertTrue(isKeyword("fun"));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForNonKeyword() {
		assertFalse(isKeyword("hello"));
	}

	@Test
	@Tag("invalid")
	public void handlesNullInput() {
		assertFalse(isKeyword(null));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForEmptyString() {
		assertFalse(isKeyword(""));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForCaseSensitiveKeyword() {
		assertFalse(isKeyword("Fun"));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForSubstringOfKeyword() {
		assertFalse(isKeyword("fu"));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForKeywordWithWhitespaces() {
		assertFalse(isKeyword(" fun "));
		assertFalse(isKeyword("fun "));
	}

	@Test
	@Tag("invalid")
	public void returnsFalseForKeywordWithSpecialCharacters() {
		assertFalse(isKeyword("fun!"));
		assertFalse(isKeyword("fun@"));
	}

}