/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=function_37580a5f52
ROOST_METHOD_SIG_HASH=function_790b76c929

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void function() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("reverse").returning("java.lang.String").parameters(Parameter.of("echo", String.class)).body(CodeBlock.ofStatement("return echo.reversed()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    fun reverse(echo: String): String {", "        return echo.reversed()", "    }", "", "}");
}
"
    "@Test
@Test
void functionModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("toString").modifiers(KotlinModifier.OVERRIDE, KotlinModifier.PUBLIC, KotlinModifier.OPEN).returning("java.lang.String").body(CodeBlock.ofStatement("return super.toString()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    open override fun toString(): String {", "        return super.toString()", "    }", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    compilationUnit.addTopLevelFunction(KotlinFunctionDeclaration.function("main").parameters(Parameter.of("args", "Array<String>")).body(CodeBlock.ofStatement("$T<$L>(*args)", "org.springframework.boot.runApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.autoconfigure.SpringBootApplication", "import org.springframework.boot.runApplication", "", "@SpringBootApplication", "class Test", "", "fun main(args: Array<String>) {", "    runApplication<Test>(*args)", "}");
}
"
    "@Test
@Test
void functionWithSimpleAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    KotlinFunctionDeclaration function = KotlinFunctionDeclaration.function("something").body(CodeBlock.of(""));
    function.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addFunctionDeclaration(function);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.test.TestAnnotation", "", "class Test {", "", "    @TestAnnotation", "    fun something() {", "    }", "", "}");
}
"
    "@Test
@Test
void functionWithParameterAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("something").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    fun something(@Service service: MyService) {", "    }", "", "}");
}
"```plaintext
Scenario 1: Verify that the Builder instance is created with the provided function name

Details:
  TestName: functionCreatesBuilderWithName
  Description: This test ensures that invoking the function method with a name creates a Builder instance with the specified name.
Execution:
  Arrange: Prepare a string variable to be used as the function name.
  Act: Invoke the function method with the prepared name.
  Assert: Verify that the created Builder instance has the correct name.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Check that the function method handles null input gracefully

Details:
  TestName: functionHandlesNullNameGracefully
  Description: This test checks that the function method can handle null input for the function name without throwing an exception.
Execution:
  Arrange: Prepare a null value.
  Act: Invoke the function method with the null value.
  Assert: Ensure that the function method does not throw an exception.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Verify that the Builder instance can be configured with modifiers

Details:
  TestName: builderConfiguresModifiers
  Description: This test ensures that the Builder instance can be configured with Kotlin modifiers and that the modifiers are correctly set.
Execution:
  Arrange: Create a Builder instance and prepare a list of Kotlin modifiers.
  Act: Configure the Builder instance with the prepared modifiers.
  Assert: Verify that the Builder instance has the configured modifiers.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Check that the function method handles empty string input

Details:
  TestName: functionHandlesEmptyStringName
  Description: This test checks that the function method can handle an empty string input for the function name without throwing an exception.
Execution:
  Arrange: Prepare an empty string.
  Act: Invoke the function method with the empty string.
  Assert: Ensure that the function method does not throw an exception and the Builder instance is created with the empty string.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Verify that the Builder instance can be configured with a return type

Details:
  TestName: builderConfiguresReturnType
  Description: This test ensures that the Builder instance can be configured with a return type and that the return type is correctly set.
Execution:
  Arrange: Create a Builder instance and prepare a return type string.
  Act: Configure the Builder instance with the prepared return type.
  Assert: Verify that the Builder instance has the configured return type.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Check that the function method handles special characters in the function name

Details:
  TestName: functionHandlesSpecialCharactersInName
  Description: This test checks that the function method can handle special characters in the function name without throwing an exception.
Execution:
  Arrange: Prepare a string with special characters.
  Act: Invoke the function method with the prepared string.
  Assert: Ensure that the function method does not throw an exception and the Builder instance is created with the special characters.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: Verify that the Builder instance can be configured with parameters

Details:
  TestName: builderConfiguresParameters
  Description: This test ensures that the Builder instance can be configured with parameters and that the parameters are correctly set.
Execution:
  Arrange: Create a Builder instance and prepare a list of parameters.
  Act: Configure the Builder instance with the prepared parameters.
  Assert: Verify that the Builder instance has the configured parameters.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 8: Check that the function method handles very long function names

Details:
  TestName: functionHandlesLongName
  Description: This test checks that the function method can handle very long function names without throwing an exception.
Execution:
  Arrange: Prepare a very long string.
  Act: Invoke the function method with the prepared string.
  Assert: Ensure that the function method does not throw an exception and the Builder instance is created with the long string.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 9: Verify that the Builder instance can be configured with a code block

Details:
  TestName: builderConfiguresCodeBlock
  Description: This test ensures that the Builder instance can be configured with a code block and that the code block is correctly set.
Execution:
  Arrange: Create a Builder instance and prepare a code block.
  Act: Configure the Builder instance with the prepared code block.
  Assert: Verify that the KotlinFunctionDeclaration instance has the configured code block.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 10: Check that the function method handles whitespace in the function name

Details:
  TestName: functionHandlesWhitespaceInName
  Description: This test checks that the function method can handle whitespace in the function name without throwing an exception.
Execution:
  Arrange: Prepare a string with whitespace.
  Act: Invoke the function method with the prepared string.
  Assert: Ensure that the function method does not throw an exception and the Builder instance is created with the whitespace.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import io.spring.initializr.generator.language.Parameter;
import io.spring.initializr.generator.language.CodeBlock;
import io.spring.initializr.generator.language.Annotatable;
import io.spring.initializr.generator.language.AnnotationContainer;
import io.spring.initializr.generator.language.kotlin.KotlinFunctionDeclaration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.*;

public class KotlinFunctionDeclarationFunctionTest {

	@Test
	@Tag("valid")
	public void functionCreatesBuilderWithName() {
		String functionName = "testFunction";
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function(functionName);
		assertEquals(functionName, builder.getName());
	}

	@Test
	@Tag("invalid")
	public void functionHandlesNullNameGracefully() {
		assertDoesNotThrow(() -> {
			KotlinFunctionDeclaration.function(null);
		});
	}

	@Test
	@Tag("valid")
	public void builderConfiguresModifiers() {
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function("testFunction");
		KotlinModifier[] modifiers = { KotlinModifier.PUBLIC, KotlinModifier.FINAL };
		builder.modifiers(modifiers);
		assertArrayEquals(modifiers, builder.getModifiers().toArray());
	}

	@Test
	@Tag("invalid")
	public void functionHandlesEmptyStringName() {
		String functionName = "";
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function(functionName);
		assertEquals(functionName, builder.getName());
	}

	@Test
	@Tag("valid")
	public void builderConfiguresReturnType() {
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function("testFunction");
		String returnType = "String";
		builder.returning(returnType);
		assertEquals(returnType, builder.getReturnType());
	}

	@Test
	@Tag("invalid")
	public void functionHandlesSpecialCharactersInName() {
		String functionName = "test@Function";
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function(functionName);
		assertEquals(functionName, builder.getName());
	}

	@Test
	@Tag("valid")
	public void builderConfiguresParameters() {
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function("testFunction");
		Parameter[] parameters = { new Parameter("param1", "String"), new Parameter("param2", "int") };
		builder.parameters(parameters);
		assertArrayEquals(parameters, builder.getParameters().toArray());
	}

	@Test
	@Tag("invalid")
	public void functionHandlesLongName() {
		String functionName = new String(new char[1000]).replace('\0', 'a');
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function(functionName);
		assertEquals(functionName, builder.getName());
	}

	@Test
	@Tag("valid")
	public void builderConfiguresCodeBlock() {
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function("testFunction");
		CodeBlock codeBlock = new CodeBlock("System.out.println(\"Hello, World!\");");
		KotlinFunctionDeclaration kotlinFunction = builder.body(codeBlock);
		assertEquals(codeBlock, kotlinFunction.getCode());
	}

	@Test
	@Tag("invalid")
	public void functionHandlesWhitespaceInName() {
		String functionName = " testFunction ";
		KotlinFunctionDeclaration.Builder builder = KotlinFunctionDeclaration.function(functionName);
		assertEquals(functionName, builder.getName());
	}

}