/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=val_72e4e73488
ROOST_METHOD_SIG_HASH=val_5bc2cee5d5

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void valProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("java.lang.String").emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    val testProp: String", "", "}");
}
"
    "@Test
@Test
void valPropertyImport() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("com.example.another.One").emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.One", "", "class Test {", "", "    val testProp: One", "", "}");
}
"
    "@Test
@Test
void valGetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a TEST")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("withGetter").returning("java.lang.String").getter().withBody(CodeBlock.of("testProp.toLowerCase()")).buildAccessor().emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    val testProp: String = \"This is a TEST\"", "", "    val withGetter: String", "        get() = testProp.toLowerCase()", "", "}");
}
"```plaintext
Scenario 1: Create a val property with basic return type

Details:
  TestName: valPropertyBasicReturnType
  Description: This test checks if a val property with a basic return type (e.g., java.lang.String) is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "testProp" and return type "java.lang.String".
  Assert: Verify that the generated source code contains the correct val property declaration.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Create a val property with a custom return type

Details:
  TestName: valPropertyCustomReturnType
  Description: This test checks if a val property with a custom return type (e.g., com.example.another.One) is created correctly and includes the necessary import statement.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "testProp" and return type "com.example.another.One".
  Assert: Verify that the generated source code contains the correct val property declaration and the import statement for the custom type.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Create a val property with a getter

Details:
  TestName: valPropertyWithGetter
  Description: This test checks if a val property with a custom getter is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "withGetter" and return type "java.lang.String", and define a getter that returns the property value in lowercase.
  Assert: Verify that the generated source code contains the correct val property declaration with the custom getter.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Create a val property with annotations

Details:
  TestName: valPropertyWithAnnotations
  Description: This test checks if a val property with annotations is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "annotatedProp" and return type "java.lang.String", and add annotations to it.
  Assert: Verify that the generated source code contains the correct val property declaration with the specified annotations.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Create a val property with modifiers

Details:
  TestName: valPropertyWithModifiers
  Description: This test checks if a val property with modifiers (e.g., private, final) is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "modifiedProp" and return type "java.lang.String", and add modifiers to it.
  Assert: Verify that the generated source code contains the correct val property declaration with the specified modifiers.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Create a val property with null value code

Details:
  TestName: valPropertyWithNullValue
  Description: This test checks if a val property with a null value code is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "nullValueProp" and return type "java.lang.String", and set the value code to null.
  Assert: Verify that the generated source code contains the correct val property declaration with the null value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: Create a val property with empty value

Details:
  TestName: valPropertyWithEmptyValue
  Description: This test checks if a val property with an empty value is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "emptyValueProp" and return type "java.lang.String", and set the value code to an empty code block.
  Assert: Verify that the generated source code contains the correct val property declaration with the empty value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 8: Create a val property with complex value code

Details:
  TestName: valPropertyWithComplexValue
  Description: This test checks if a val property with a complex value code is created correctly.
Execution:
  Arrange: Set up a KotlinSourceCode and KotlinCompilationUnit.
  Act: Create a val property with the name "complexValueProp" and return type "java.lang.String", and set the value code to a complex code block.
  Assert: Verify that the generated source code contains the correct val property declaration with the complex value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.springframework.test.util.AssertionErrors.assertEquals;
import static org.springframework.test.util.AssertionErrors.assertNotNull;
import static org.springframework.test.util.AssertionErrors.assertTrue;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import io.spring.initializr.generator.language.Annotatable;
import io.spring.initializr.generator.language.Annotation;
import io.spring.initializr.generator.language.AnnotationContainer;
import io.spring.initializr.generator.language.ClassName;
import io.spring.initializr.generator.language.CodeBlock;

public class KotlinPropertyDeclarationValTest {

	@Test
	@Tag("valid")
	public void valPropertyBasicReturnType() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("testProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String").empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "testProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
	}

	@Test
	@Tag("valid")
	public void valPropertyCustomReturnType() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("testProp");
		KotlinPropertyDeclaration property = valBuilder.returning("com.example.another.One").empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "testProp", property.getName());
		assertEquals("Return type should match", "com.example.another.One", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
	}

	@Test
	@Tag("valid")
	public void valPropertyWithGetter() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("withGetter");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String")
			.getter()
			.withBody(CodeBlock.of("return this.toLowerCase()"))
			.buildAccessor()
			.empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "withGetter", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertNotNull("Getter should not be null", property.getGetter());
	}

	@Test
	@Tag("valid")
	public void valPropertyWithAnnotations() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("annotatedProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String")
			.getter()
			.withAnnotation(ClassName.of("com.example.Annotation"))
			.buildAccessor()
			.empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "annotatedProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertNotNull("Annotations should not be null", property.getGetter().annotations());
	}

	@Test
	@Tag("valid")
	public void valPropertyWithModifiers() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("modifiedProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String")
			.modifiers(KotlinModifier.PRIVATE, KotlinModifier.FINAL)
			.empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "modifiedProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertTrue("Modifiers should match", property.getModifiers().contains(KotlinModifier.PRIVATE));
		assertTrue("Modifiers should match", property.getModifiers().contains(KotlinModifier.FINAL));
	}

	@Test
	@Tag("valid")
	public void valPropertyWithNullValue() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("nullValueProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String").emptyValue();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "nullValueProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertNull("Value code should be null", property.getValueCode());
	}

	@Test
	@Tag("valid")
	public void valPropertyWithEmptyValue() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("emptyValueProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String").value(CodeBlock.empty()).empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "emptyValueProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertNotNull("Value code should not be null", property.getValueCode());
		assertTrue("Value code should be empty", property.getValueCode().isEmpty());
	}

	@Test
	@Tag("valid")
	public void valPropertyWithComplexValue() {
		ValBuilder valBuilder = KotlinPropertyDeclaration.val("complexValueProp");
		KotlinPropertyDeclaration property = valBuilder.returning("java.lang.String")
			.value(CodeBlock.of("some complex code"))
			.empty();
		assertNotNull("Property should not be null", property);
		assertEquals("Property name should match", "complexValueProp", property.getName());
		assertEquals("Return type should match", "java.lang.String", property.getReturnType());
		assertTrue("Property should be val", property.isVal());
		assertNotNull("Value code should not be null", property.getValueCode());
		assertFalse("Value code should not be empty", property.getValueCode().isEmpty());
	}

}