/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=var_a742905785
ROOST_METHOD_SIG_HASH=var_20480e74ce

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void varProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "", "}");
}
"
    "@Test
@Test
void varSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        set", "", "}");
}
"
    "@Test
@Test
void varAnnotateSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().withAnnotation(ClassName.of("org.springframework.beans.factory.annotation.Autowired")).buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        @Autowired set", "", "}");
}
"
    "@Test
@Test
void varProperties() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("Int").value(CodeBlock.of("42")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testDouble").returning("Double").value(CodeBlock.of("1986.0")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testFloat").value(CodeBlock.of("99.999f")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testLong").returning("Long").value(CodeBlock.of("1986L")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: Int = 42", "", "    var testDouble: Double = 1986.0", "", "    var testFloat = 99.999f", "", "    var testLong: Long = 1986L", "", "}");
}
"
    "@Test
@Test
void varEmptyProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("Int").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: Int", "", "}");
}
"
    "@Test
@Test
void varLateinitProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").modifiers(KotlinModifier.LATEINIT).returning("Int").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    lateinit var testProp: Int", "", "}");
}
"
    "@Test
@Test
void importsFromSamePackageAreDiscarded() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("another").returning("com.example.Another").empty());
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("sibling").returning("com.example.Sibling").empty());
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("external").returning("com.example.another.External").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).doesNotContain("import com.example.Another").doesNotContain("import com.example.Sibling").contains("import com.example.another.External");
}
"```markdown
Scenario 1: Basic VarBuilder Creation

Details:
  TestName: basicVarBuilderCreation
  Description: This test checks if a VarBuilder instance is correctly created with a specified name.
Execution:
  Arrange: None
  Act: Invoke the var method with a sample name.
  Assert: Ensure that the created VarBuilder instance is not null and has the expected name.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: VarBuilder with Return Type

Details:
  TestName: varBuilderWithReturnType
  Description: This test verifies that the VarBuilder can be configured with a return type.
Execution:
  Arrange: None
  Act: Invoke the var method, chain the returning method with a sample return type, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has the expected return type.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: VarBuilder with Modifiers

Details:
  TestName: varBuilderWithModifiers
  Description: This test checks if the VarBuilder can be configured with Kotlin modifiers.
Execution:
  Arrange: Define a list of Kotlin modifiers.
  Act: Invoke the var method, chain the modifiers method with the defined modifiers, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has the expected modifiers.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: VarBuilder with Value Code

Details:
  TestName: varBuilderWithValueCode
  Description: This test ensures that the VarBuilder can be configured with a value code.
Execution:
  Arrange: Create a sample CodeBlock instance.
  Act: Invoke the var method, chain the value method with the sample CodeBlock, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has the expected value code.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: VarBuilder with Getter

Details:
  TestName: varBuilderWithGetter
  Description: This test verifies that the VarBuilder can be configured with a getter.
Execution:
  Arrange: None
  Act: Invoke the var method, chain the getter method, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has a getter configured.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: VarBuilder with Setter

Details:
  TestName: varBuilderWithSetter
  Description: This test checks if the VarBuilder can be configured with a setter.
Execution:
  Arrange: None
  Act: Invoke the var method, chain the setter method, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has a setter configured.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: VarBuilder with Annotations on Setter

Details:
  TestName: varBuilderWithAnnotationsOnSetter
  Description: This test ensures that annotations can be added to the setter of the VarBuilder.
Execution:
  Arrange: Create a sample ClassName and Annotation.Builder instance.
  Act: Invoke the var method, chain the setter method, add an annotation with the sample ClassName, and build the VarBuilder.
  Assert: Ensure that the setter in the VarBuilder instance has the expected annotation.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 8: VarBuilder with Empty Value

Details:
  TestName: varBuilderWithEmptyValue
  Description: This test checks if the VarBuilder can be configured with an empty value.
Execution:
  Arrange: None
  Act: Invoke the var method and chain the emptyValue method.
  Assert: Ensure that the VarBuilder instance is configured with an empty value.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 9: VarBuilder with Empty Configuration

Details:
  TestName: varBuilderWithEmptyConfiguration
  Description: This test verifies that the VarBuilder can be created with an empty configuration.
Execution:
  Arrange: None
  Act: Invoke the var method and chain the empty method.
  Assert: Ensure that the VarBuilder instance is created with an empty configuration.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 10: VarBuilder with Lateinit Modifier

Details:
  TestName: varBuilderWithLateinitModifier
  Description: This test checks if the VarBuilder can be configured with the lateinit modifier.
Execution:
  Arrange: None
  Act: Invoke the var method, chain the modifiers method with the LATEINIT modifier, and build the VarBuilder.
  Assert: Ensure that the VarBuilder instance has the lateinit modifier.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import io.spring.initializr.generator.language.ClassName;
import io.spring.initializr.generator.language.CodeBlock;
import io.spring.initializr.generator.language.Annotation;
import io.spring.initializr.generator.language.KotlinModifier;
import java.util.List;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.function.Consumer;
import io.spring.initializr.generator.language.Annotatable;
import io.spring.initializr.generator.language.AnnotationContainer;

public class KotlinPropertyDeclarationVarTest {

	@Test
	@Tag("valid")
	public void testBasicVarBuilderCreation() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar");
		assertNotNull(varBuilder);
		assertEquals("testVar", varBuilder.getName());
		assertFalse(varBuilder.isVal());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithReturnType() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar").returning("String");
		assertNotNull(varBuilder);
		assertEquals("String", varBuilder.getReturnType());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithModifiers() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar")
			.modifiers(KotlinModifier.PUBLIC, KotlinModifier.FINAL);
		assertNotNull(varBuilder);
		List<KotlinModifier> modifiers = varBuilder.getModifiers();
		assertNotNull(modifiers);
		assertTrue(modifiers.contains(KotlinModifier.PUBLIC));
		assertTrue(modifiers.contains(KotlinModifier.FINAL));
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithValueCode() {
		CodeBlock codeBlock = CodeBlock.of("valueCode");
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar").value(codeBlock);
		assertNotNull(varBuilder);
		assertEquals(codeBlock, varBuilder.getValueCode());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithGetter() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar")
			.getter()
			.withBody(CodeBlock.of("return value"))
			.buildAccessor();
		assertNotNull(varBuilder);
		assertNotNull(varBuilder.getGetter());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithSetter() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar")
			.setter()
			.withBody(CodeBlock.of("value = it"))
			.buildAccessor();
		assertNotNull(varBuilder);
		assertNotNull(varBuilder.getSetter());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithAnnotationsOnSetter() {
		ClassName annotationClassName = ClassName.of("AnnotationClass");
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar")
			.setter()
			.withAnnotation(annotationClassName)
			.buildAccessor();
		assertNotNull(varBuilder);
		assertNotNull(varBuilder.getSetter());
		assertTrue(varBuilder.getSetter().annotations().contains(annotationClassName));
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithEmptyValue() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar").emptyValue();
		assertNotNull(varBuilder);
		assertNotNull(varBuilder.getValueCode());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithEmptyConfiguration() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar").empty();
		assertNotNull(varBuilder);
		assertNotNull(varBuilder.getValueCode());
	}

	@Test
	@Tag("valid")
	public void testVarBuilderWithLateinitModifier() {
		VarBuilder varBuilder = KotlinPropertyDeclaration.var("testVar").modifiers(KotlinModifier.LATEINIT);
		assertNotNull(varBuilder);
		List<KotlinModifier> modifiers = varBuilder.getModifiers();
		assertNotNull(modifiers);
		assertTrue(modifiers.contains(KotlinModifier.LATEINIT));
	}

}