/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getTopLevelFunctions_92c31406d2
ROOST_METHOD_SIG_HASH=getTopLevelFunctions_e12f56fe99

```java
Scenario 1: Verify that getTopLevelFunctions returns an empty list when no functions are added.

Details:
  TestName: getTopLevelFunctionsReturnsEmptyListWhenNoFunctionsAdded
  Description: This test verifies that the getTopLevelFunctions method returns an empty list when no functions have been added to the topLevelFunctions list.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit.
  Act: Invoke the getTopLevelFunctions method.
  Assert: Use JUnit assertions to verify that the returned list is empty.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 2: Verify that getTopLevelFunctions returns a list with one function when a single function is added.

Details:
  TestName: getTopLevelFunctionsReturnsListWithOneFunction
  Description: This test verifies that the getTopLevelFunctions method returns a list containing a single function when exactly one function is added to the topLevelFunctions list.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add one KotlinFunctionDeclaration to it.
  Act: Invoke the getTopLevelFunctions method.
  Assert: Use JUnit assertions to verify that the returned list contains exactly one element.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 3: Verify that getTopLevelFunctions returns a list with multiple functions when multiple functions are added.

Details:
  TestName: getTopLevelFunctionsReturnsListWithMultipleFunctions
  Description: This test verifies that the getTopLevelFunctions method returns a list containing multiple functions when multiple functions are added to the topLevelFunctions list.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add multiple KotlinFunctionDeclaration instances to it.
  Act: Invoke the getTopLevelFunctions method.
  Assert: Use JUnit assertions to verify that the returned list contains exactly the number of elements that were added.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 4: Verify that getTopLevelFunctions returns the same list instance after adding functions.

Details:
  TestName: getTopLevelFunctionsReturnsSameListInstanceAfterAddingFunctions
  Description: This test verifies that the getTopLevelFunctions method returns the same list instance after adding functions, ensuring that the list is mutable and not a copy.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add one or more KotlinFunctionDeclaration instances to it.
  Act: Invoke the getTopLevelFunctions method and add another function to the list returned by the method.
  Assert: Use JUnit assertions to verify that the list contains the newly added function.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 5: Verify that getTopLevelFunctions returns an empty list after adding and removing all functions.

Details:
  TestName: getTopLevelFunctionsReturnsEmptyListAfterAddingAndRemovingAllFunctions
  Description: This test verifies that the getTopLevelFunctions method returns an empty list after adding and subsequently removing all functions from the topLevelFunctions list.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add one or more KotlinFunctionDeclaration instances to it.
  Act: Remove all functions from the list and then invoke the getTopLevelFunctions method.
  Assert: Use JUnit assertions to verify that the returned list is empty.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 6: Verify that getTopLevelFunctions returns the correct list even after modifying the original list.

Details:
  TestName: getTopLevelFunctionsReturnsCorrectListAfterModifyingOriginalList
  Description: This test verifies that the getTopLevelFunctions method returns the correct list even after modifying the original list, ensuring that the returned list is not affected by external modifications.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add one or more KotlinFunctionDeclaration instances to it.
  Act: Get the list using getTopLevelFunctions, modify the original list, and then invoke getTopLevelFunctions again.
  Assert: Use JUnit assertions to verify that the returned list remains consistent with the original additions.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

```java
Scenario 7: Verify that getTopLevelFunctions returns an empty list when the original list is cleared.

Details:
  TestName: getTopLevelFunctionsReturnsEmptyListWhenOriginalListIsCleared
  Description: This test verifies that the getTopLevelFunctions method returns an empty list when the original list is cleared, ensuring that the internal state is correctly reflected.
Execution:
  Arrange: Create an instance of KotlinCompilationUnit and add one or more KotlinFunctionDeclaration instances to it.
  Act: Clear the original list and then invoke the getTopLevelFunctions method.
  Assert: Use JUnit assertions to verify that the returned list is empty.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language.kotlin;

import io.spring.initializr.generator.language.CompilationUnit;
import io.spring.initializr.generator.language.kotlin.KotlinFunctionDeclaration;
import io.spring.initializr.generator.language.kotlin.KotlinTypeDeclaration;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;

public class KotlinCompilationUnitGetTopLevelFunctionsTest extends CompilationUnit<KotlinTypeDeclaration> {

	private KotlinCompilationUnit kotlinCompilationUnit;

	@BeforeEach
	public void setUp() {
		kotlinCompilationUnit = new KotlinCompilationUnit("io.spring.initializr.generator.language.kotlin",
				"TestCompilationUnit");
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsEmptyListWhenNoFunctionsAdded() {
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertTrue(topLevelFunctions.isEmpty(), "The list should be empty when no functions are added.");
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsListWithOneFunction() {
		KotlinFunctionDeclaration function = new KotlinFunctionDeclaration.Builder("testFunction").build();
		kotlinCompilationUnit.addTopLevelFunction(function);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertEquals(1, topLevelFunctions.size(), "The list should contain exactly one function.");
		assertEquals("testFunction", topLevelFunctions.get(0).getName());
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsListWithMultipleFunctions() {
		KotlinFunctionDeclaration function1 = new KotlinFunctionDeclaration.Builder("testFunction1").build();
		KotlinFunctionDeclaration function2 = new KotlinFunctionDeclaration.Builder("testFunction2").build();
		kotlinCompilationUnit.addTopLevelFunction(function1);
		kotlinCompilationUnit.addTopLevelFunction(function2);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertEquals(2, topLevelFunctions.size(), "The list should contain exactly two functions.");
		assertEquals("testFunction1", topLevelFunctions.get(0).getName());
		assertEquals("testFunction2", topLevelFunctions.get(1).getName());
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsSameListInstanceAfterAddingFunctions() {
		KotlinFunctionDeclaration function1 = new KotlinFunctionDeclaration.Builder("testFunction1").build();
		kotlinCompilationUnit.addTopLevelFunction(function1);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		KotlinFunctionDeclaration function2 = new KotlinFunctionDeclaration.Builder("testFunction2").build();
		topLevelFunctions.add(function2);
		assertEquals(2, topLevelFunctions.size(), "The list should contain exactly two functions after adding one.");
		assertEquals("testFunction1", topLevelFunctions.get(0).getName());
		assertEquals("testFunction2", topLevelFunctions.get(1).getName());
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsEmptyListAfterAddingAndRemovingAllFunctions() {
		KotlinFunctionDeclaration function1 = new KotlinFunctionDeclaration.Builder("testFunction1").build();
		kotlinCompilationUnit.addTopLevelFunction(function1);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		topLevelFunctions.clear();
		List<KotlinFunctionDeclaration> updatedTopLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertTrue(updatedTopLevelFunctions.isEmpty(), "The list should be empty after clearing all functions.");
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsCorrectListAfterModifyingOriginalList() {
		KotlinFunctionDeclaration function1 = new KotlinFunctionDeclaration.Builder("testFunction1").build();
		kotlinCompilationUnit.addTopLevelFunction(function1);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		KotlinFunctionDeclaration function2 = new KotlinFunctionDeclaration.Builder("testFunction2").build();
		topLevelFunctions.add(function2);
		List<KotlinFunctionDeclaration> updatedTopLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertEquals(2, updatedTopLevelFunctions.size(),
				"The list should contain exactly two functions after adding one.");
		assertEquals("testFunction1", updatedTopLevelFunctions.get(0).getName());
		assertEquals("testFunction2", updatedTopLevelFunctions.get(1).getName());
	}

	@Test
	@Tag("valid")
	public void getTopLevelFunctionsReturnsEmptyListWhenOriginalListIsCleared() {
		KotlinFunctionDeclaration function1 = new KotlinFunctionDeclaration.Builder("testFunction1").build();
		kotlinCompilationUnit.addTopLevelFunction(function1);
		List<KotlinFunctionDeclaration> topLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		topLevelFunctions.clear();
		List<KotlinFunctionDeclaration> updatedTopLevelFunctions = kotlinCompilationUnit.getTopLevelFunctions();
		assertTrue(updatedTopLevelFunctions.isEmpty(), "The list should be empty after clearing the original list.");
	}

}