/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesText_dfb5702f29
ROOST_METHOD_SIG_HASH=serviceCapabilitiesText_33f658da89

"""
Scenario 1: Test user agent as null
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsNull
  Description: This scenario tests if the serviceCapabilitiesText method is handling null values for the user agent.
Execution:
  Arrange: Supply null user agent to the request header.
  Act: Invoke the serviceCapabilitiesText() method.
  Assert: Use JUnit assertions to check if the ResponseEntity returned contains the expected content and media type (text/plain).
Validation:
  The test verifies that the method can gracefully handle null user agent values without throwing exceptions. If the assertion passes, it confirms that the method generateGenericCapabilities is called when user agent is null.

Scenario 2: Test a valid CURL user agent
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsCurl
  Description: This scenario tests how the method handles a CURL user agent.
Execution:
  Arrange: Initialize CURL as the user agent String.
  Act: Invoke the serviceCapabilitiesText() method.
  Assert: Use JUnit assertions to check if
the ResponseEntity returned has the same content as the expected CURL capabilities
Validation:
  The assertion confirms that when CURL is the user agent, generateCurlCapabilities is called. The significance of this test in terms of business logic is that it validates if a correct help documentation is being returned based on the user agent.

Scenario 3: Test a valid HTTPIE user agent
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsHttpie
  Description: This scenario tests how the method handles a HTTPIE user agent.
Execution:
  Arrange: Initialize HTTPIE as the user agent String.
  Act: Invoke serviceCapabilitiesText() method.
  Assert: Use JUnit assertions to check if the ResponseEntity returned has the same content as the expected HTTPIE capabilities.
Validation:
  The assertion confirms that when HTTPIE is the user agent generateHttpieCapabilities is called, ensuring that the correct help information is being returned.

Scenario 4: Test a valid SPRING_BOOT_CLI user agent
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsSpringBootCli
  Description: This test scenario determines how the method handles a SPRING_BOOT_CLI user agent.
Execution:
  Arrange: Set SPRING_BOOT_CLI as the user agent String.
  Act: Pass the user agent as input to serviceCapabilitiesText() method.
  Assert: Verify that the ResponseEntity returned by the method has the same content as the expected SPRING_BOOT_CLI capabilities.
Validation:
  This scenario checks if generateSpringBootCliCapabilities is invoked when SPRING_BOOT_CLI is the user agent and the correct help guide is returned.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.generator.io.template.TemplateRenderer;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.support.Agent;
import io.spring.initializr.web.support.Agent.AgentId;
import io.spring.initializr.web.support.CommandLineHelpGenerator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.io.IOException;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity.BodyBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RestController;

public class CommandLineMetadataControllerServiceCapabilitiesTextTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private TemplateRenderer templateRenderer;

	private CommandLineMetadataController controller;

	@BeforeEach
	public void setup() {
		MockitoAnnotations.initMocks(this);
		controller = new CommandLineMetadataController(metadataProvider, templateRenderer);
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsNull() {
		String userAgent = null;
		String expectedContent = "Expected content";
		when(this.controller.serviceCapabilitiesText(userAgent)).thenReturn(ResponseEntity.ok(expectedContent));
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		assertEquals(expectedContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsCurl() {
		String userAgent = "CURL";
		String expectedContent = "Expected CURL content";
		when(this.controller.serviceCapabilitiesText(userAgent)).thenReturn(ResponseEntity.ok(expectedContent));
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		assertEquals(expectedContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsHttpie() {
		String userAgent = "HTTPIE";
		String expectedContent = "Expected HTTPIE content";
		when(this.controller.serviceCapabilitiesText(userAgent)).thenReturn(ResponseEntity.ok(expectedContent));
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		assertEquals(expectedContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsSpringBootCli() {
		String userAgent = "SPRING_BOOT_CLI";
		String expectedContent = "Expected SPRING_BOOT_CLI content";
		when(this.controller.serviceCapabilitiesText(userAgent)).thenReturn(ResponseEntity.ok(expectedContent));
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		assertEquals(expectedContent, response.getBody());
	}

}