/*
 * Copyright 2012-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=cleanInputValue_efd1bb8911
ROOST_METHOD_SIG_HASH=cleanInputValue_fb87ee802c

"""
Scenario 1: Testing cleanInputValue with Normal String.
Details:
  TestName: testCleanInputWithNormalString
  Description: The test is meant to check if the method is correctly cleaning a normal string and it does not modify it.
Execution:
  Arrange: Create a simple string "inputValue = 'TextString' ".
  Act: Call method cleanInputValue(inputValue)
  Assert: Assert that the result is the same as the input, 'TextString'.
Validation:
  Verify that the method properly keeps the initial string without modifying it if it does not have any special characters.
  It validates the functionality of the method in cleaning the normal string inputs.

Scenario 2: Testing cleanInputValue with String containing Diacritic marks.
Details:
  TestName: testCleanInputWithDiacriticString.
  Description: The test is meant to check if the method is correctly cleaning a string that contains diacritic marks by removing them.
Execution:
  Arrange: Create a string "inputValue = 'Tèxt Strîng' ".
  Act: Call method cleanInputValue(inputValue).
  Assert: Assert that the result is "Text String" without diacritics.
Validation:
  Verify that the method removes the diacritic marks from the string.
  It validates the functionality of the method in cleaning the string inputs which contain diacritic marks.

Scenario 3: Testing cleanInputValue with null.
Details:
  TestName: testCleanInputWithNullValue.
  Description: The test is meant to check if the method can handle null inputs.
Execution:
  Arrange: Pass null as an argument "inputValue = null".
  Act: Call method cleanInputValue(inputValue).
  Assert: Assert that the result is null as well.
Validation:
  Verify if the method returns null when the input is null.
  It validates the functionality of the method in handling null inputs.

Scenario 4: Testing cleanInputValue with Empty String.
Details:
  TestName: testCleanInputWithEmptyString.
  Description: The test is designed to validate that the method is correctly handling empty string inputs.
Execution:
  Arrange: Pass an empty string as argument "inputValue = '' ".
  Act: Call method cleanInputValue(inputValue).
  Assert: Assert that the result is also an empty string.
Validation:

  Verify that the method returns an empty string if the input was an empty string.
  This ensures the functionality of the method in dealing with empty strings.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import io.spring.initializr.web.project.DefaultProjectRequestToDescriptionConverter;
import org.junit.jupiter.api.*;
import java.text.Normalizer;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import io.spring.initializr.generator.buildsystem.BuildSystem;
import io.spring.initializr.generator.language.Language;
import io.spring.initializr.generator.packaging.Packaging;
import io.spring.initializr.generator.project.MutableProjectDescription;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DefaultMetadataElement;
import io.spring.initializr.metadata.Dependency;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.Type;
import io.spring.initializr.metadata.support.MetadataBuildItemMapper;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

public class DefaultProjectRequestToDescriptionConverterCleanInputValueTest {

	private DefaultProjectRequestToDescriptionConverter converter;

	@BeforeEach
	public void setup() {
		converter = new DefaultProjectRequestToDescriptionConverter();
	}

	@Test
	@Tag("valid")
	public void testCleanInputWithNormalString() {
		String inputValue = "TextString";
		String outputValue = converter.cleanInputValue(inputValue);
		assertEquals(inputValue, outputValue);
	}

	@Test
	@Tag("valid")
	public void testCleanInputWithDiacriticString() {
		String inputValue = "Tèxt Strîng";
		String outputValue = converter.cleanInputValue(inputValue);
		assertEquals("Text String", outputValue);
	}

	@Test
	@Tag("valid")
	public void testCleanInputWithNullValue() {
		String inputValue = null;
		String outputValue = converter.cleanInputValue(inputValue);
		assertNull(outputValue);
	}

	@Test
	@Tag("valid")
	public void testCleanInputWithEmptyString() {
		String inputValue = "";
		String outputValue = converter.cleanInputValue(inputValue);
		assertEquals("", outputValue);
	}

}