/*
 * Copyright 2012-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=convert_1f28a6c7be
ROOST_METHOD_SIG_HASH=convert_7307f7e5a4

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/DefaultProjectRequestToDescriptionConverterTests.java
Tests:
    "@Test
@Test
void convertWhenArtifactIdHasAccentCleanValue() {
    ProjectRequest request = createProjectRequest();
    request.setArtifactId("tëst-âpp");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getArtifactId()).isEqualTo("test-app");
}
"
    "@Test
@Test
void convertWhenGroupIdHasAccentCleanValue() {
    ProjectRequest request = createProjectRequest();
    request.setGroupId("com.êxample.äpp");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getGroupId()).isEqualTo("com.example.app");
}
"
    "@Test
@Test
void convertWhenNameHasAccentCleanValue() {
    ProjectRequest request = createProjectRequest();
    request.setName("My Demö");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getName()).isEqualTo("My Demo");
}
"
    "@Test
@Test
void convertWhenPackageNameHasAccentCleanValue() {
    ProjectRequest request = createProjectRequest();
    request.setPackageName("com.êxample.äpp");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getPackageName()).isEqualTo("com.example.app");
}
"
    "@Test
@Test
void convertWhenTypeIsInvalidShouldThrowException() {
    ProjectRequest request = createProjectRequest();
    request.setType("foo-build");
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, this.metadata)).withMessage("Unknown type 'foo-build' check project metadata");
}
"
    "@Test
@Test
void convertWhenTypeDoesNotDefineBuildTagShouldThrowException() {
    Type type = new Type();
    type.setId("example-project");
    InitializrMetadata testMetadata = InitializrMetadataTestBuilder.withDefaults().addType(type).build();
    ProjectRequest request = createProjectRequest();
    request.setType("example-project");
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, testMetadata)).withMessage("Invalid type 'example-project' (missing build tag) check project metadata");
}
"
    "@Test
@Test
void convertWhenTypeDoesNotDefineDialectTagShouldUseDefaultDialect() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addType("foo", true, "/foo.zip", GradleBuildSystem.ID, null, "test").build();
    ProjectRequest request = createProjectRequest();
    request.setType("foo");
    assertThat(this.converter.convert(request, metadata).getBuildSystem().dialect()).isEqualTo(GradleBuildSystem.DIALECT_GROOVY);
}
"
    "@Test
@Test
void convertWhenTypeDefinesDialectTagShouldUseDialect() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addType("foo", true, "/foo.zip", GradleBuildSystem.ID, GradleBuildSystem.DIALECT_KOTLIN, "test").build();
    ProjectRequest request = createProjectRequest();
    request.setType("foo");
    assertThat(this.converter.convert(request, metadata).getBuildSystem().dialect()).isEqualTo(GradleBuildSystem.DIALECT_KOTLIN);
}
"
    "@Test
@Test
void convertWhenPlatformCompatibilityRangeIsNotSetShouldNotThrowException() {
    this.metadata = InitializrMetadataTestBuilder.withDefaults().setPlatformCompatibilityRange(null).build();
    ProjectRequest request = createProjectRequest();
    request.setBootVersion("1.5.9.RELEASE");
    assertThat(this.converter.convert(request, this.metadata).getPlatformVersion()).isEqualTo(Version.parse("1.5.9.RELEASE"));
}
"
    "@Test
@Test
void convertShouldCallProjectRequestVersionTransformer() {
    ProjectRequestPlatformVersionTransformer transformer = mock(ProjectRequestPlatformVersionTransformer.class);
    Version v1Format = Version.parse("2.4.0.RELEASE");
    given(transformer.transform(v1Format, this.metadata)).willReturn(Version.parse("2.4.0"));
    ProjectRequest request = createProjectRequest();
    request.setBootVersion("2.4.0.RELEASE");
    ProjectDescription description = new DefaultProjectRequestToDescriptionConverter(transformer).convert(request, this.metadata);
    assertThat(description.getPlatformVersion()).hasToString("2.4.0");
    verify(transformer).transform(v1Format, this.metadata);
}
"
    "@Test
@Test
void convertWhenSpringBootVersionInvalidShouldThrowException() {
    this.metadata = InitializrMetadataTestBuilder.withDefaults().setPlatformCompatibilityRange("[2.0.0.RELEASE,2.3.0.M1)").build();
    ProjectRequest request = createProjectRequest();
    request.setBootVersion("1.5.9.RELEASE");
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, this.metadata)).withMessage("Invalid Spring Boot version '1.5.9.RELEASE', Spring Boot compatibility range is >=2.0.0.RELEASE and <2.3.0.M1");
}
"
    "@Test
@Test
void convertWhenPackagingIsInvalidShouldThrowException() {
    ProjectRequest request = createProjectRequest();
    request.setPackaging("star");
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, this.metadata)).withMessage("Unknown packaging 'star' check project metadata");
}
"
    "@Test
@Test
void convertWhenLanguageIsInvalidShouldThrowException() {
    ProjectRequest request = createProjectRequest();
    request.setLanguage("english");
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, this.metadata)).withMessage("Unknown language 'english' check project metadata");
}
"
    "@Test
@Test
void convertWhenDependencyNotPresentShouldThrowException() {
    ProjectRequest request = createProjectRequest();
    request.setDependencies(Collections.singletonList("invalid"));
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, this.metadata)).withMessage("Unknown dependency 'invalid' check project metadata");
}
"
    "@Test
@Test
void convertWhenDependencyOutOfRangeShouldThrowException() {
    Dependency dependency = Dependency.withId("foo");
    dependency.setRange(new VersionRange(Version.parse("2.5.0.M1")));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("foo", dependency).build();
    ProjectRequest request = createProjectRequest();
    request.setDependencies(Collections.singletonList("foo"));
    assertThatExceptionOfType(InvalidProjectRequestException.class).isThrownBy(() -> this.converter.convert(request, metadata)).withMessage("Dependency 'foo' is not compatible " + "with Spring Boot 2.4.1");
}
"
    "@Test
@Test
void convertShouldSetApplicationNameForProjectDescriptionFromRequestWhenPresent() {
    ProjectRequest request = createProjectRequest();
    request.setApplicationName("MyApplication");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getApplicationName()).isEqualTo("MyApplication");
}
"
    "@Test
@Test
void convertShouldSetGroupIdAndArtifactIdFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setArtifactId("foo");
    request.setGroupId("com.example");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getGroupId()).isEqualTo("com.example");
    assertThat(description.getArtifactId()).isEqualTo("foo");
}
"
    "@Test
@Test
void convertShouldSetVersionFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setVersion("1.0.2-SNAPSHOT");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getVersion()).isEqualTo("1.0.2-SNAPSHOT");
}
"
    "@Test
@Test
void convertShouldSetBaseDirectoryFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setBaseDir("my-path");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getBaseDirectory()).isEqualTo("my-path");
}
"
    "@Test
@Test
void convertShouldSetBuildSystemFromRequestTypeAndBuildTag() {
    Type type = new Type();
    type.setId("example-type");
    type.getTags().put("build", "gradle");
    InitializrMetadata testMetadata = InitializrMetadataTestBuilder.withDefaults().addType(type).build();
    ProjectRequest request = createProjectRequest();
    request.setType("example-type");
    ProjectDescription description = this.converter.convert(request, testMetadata);
    assertThat(description.getBuildSystem()).isInstanceOf(GradleBuildSystem.class);
}
"
    "@Test
@Test
void convertShouldSetDescriptionFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setDescription("This is my demo project");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getDescription()).isEqualTo("This is my demo project");
}
"
    "@Test
@Test
void convertShouldSetPackagingFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setPackaging("war");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getPackaging().id()).isEqualTo("war");
}
"
    "@Test
@Test
void convertShouldSetPlatformVersionFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setBootVersion("2.0.3");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getPlatformVersion()).isEqualTo(Version.parse("2.0.3"));
}
"
    "@Test
@Test
void convertShouldSetLanguageForProjectDescriptionFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setJavaVersion("1.8");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getLanguage().id()).isEqualTo("java");
    assertThat(description.getLanguage().jvmVersion()).isEqualTo("1.8");
}
"Scenario 1: Verifying conversion when ProjectRequest and Initializer Metadata are valid

Details:
  TestName: validateConversionWhenDataIsValid.
  Description: This test scenario checks if the convert method correctly converts ProjectRequest to ProjectDescription when supplied with valid metadata.
Execution:
  Arrange: Create a valid ProjectRequest and InitializerMetadata objects.
  Act: Call the 'convert' method with requet and metadata as parameters.
  Assert: Validate if the result is of type ProjectDescription and has expected properties from ProjectRequest object.
Validation:
  This test ensures that the 'convert' method doesn't throw any unwanted exceptions and generates a valid ProjectDescription object when supplied with valid inputs. This is significant for ensuring correct data conversion.

Scenario 2: Verifying conversion when ProjectRequest is null

Details:
  TestName: validateConversionWhenRequestIsNull.
  Description: This test scenario checks how the convert method handles null ProjectRequest.
Execution:
  Arrange: Create an InitializerMetadata object and set ProjectRequest as null.
  Act: Call the 'convert' method with null ProjectRequest and metadata as parameters.
  Assert: Expect an IllegalArgumentException or NullPointer Exception.
Validation:
  This test ensures that the 'convert' method throws appropriate exception when ProjectRequest is null. This confirms the method's safety against null inputs.

Scenario 3: Verifying conversion when InitializrMetadata is null

Details:
  TestName: validateConversionWhenMetaDataIsNull.
  Description: This test scenario checks how the convert method handles null InitializrMetadata.
Execution:
  Arrange: Create a ProjectRequest object and set InitializrMetadata as null.
  Act: Call the 'convert' method with request and null metadata as parameters.
  Assert: Expect an IllegalArgumentException or NullPointer Exception.
Validation:
  This test ensures that the 'convert' method throws appropriate exception when InitializrMetadata is null. This confirms the method's safety against null inputs.

Scenario 4: Verifying conversion when both ProjectRequest and InitializrMetadata are null

Details:
  TestName: validateConversionWhenBothParametersAreNull.
  Description: This test scenario checks how the convert method handles null parameters.
Execution:
  Arrange: Set both ProjectRequest and InitializrMetadata as null.
  Act: Call the 'convert' method with both parameters as null.
  Assert: Expect an IllegalArgumentException or NullPointer Exception.
Validation:
  This test ensures that the 'convert' method throws appropriate exception when both inputs are null. This confirms the method's safety against null inputs.
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import java.text.Normalizer;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import io.spring.initializr.generator.buildsystem.BuildSystem;
import io.spring.initializr.generator.language.Language;
import io.spring.initializr.generator.packaging.Packaging;
import io.spring.initializr.generator.project.MutableProjectDescription;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DefaultMetadataElement;
import io.spring.initializr.metadata.Dependency;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.Type;
import io.spring.initializr.metadata.support.MetadataBuildItemMapper;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

@ExtendWith(MockitoExtension.class)
class DefaultProjectRequestToDescriptionConverterConvertTest {

	@Mock
	private ProjectRequest request;

	@Mock
	private InitializrMetadata metadata;

	private DefaultProjectRequestToDescriptionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new DefaultProjectRequestToDescriptionConverter();
	}

	@Test
	@Tag("valid")
	void validateConversionWhenDataIsValid() {
		// Arrange
		Mockito.when(request.getName()).thenReturn("test");
		Mockito.when(metadata.getTypes()).thenReturn(new HashMap<>());
		// Act
		ProjectDescription description = converter.convert(request, metadata);
		// Assert
		assertNotNull(description);
		assertEquals(request.getName(), description.getName());
	}

	@Test
	@Tag("invalid")
	void validateConversionWhenRequestIsNull() {
		// Assert
		assertThrows(IllegalArgumentException.class, () -> converter.convert(null, metadata));
	}

	@Test
	@Tag("invalid")
	void validateConversionWhenMetaDataIsNull() {
		// Assert
		assertThrows(IllegalArgumentException.class, () -> converter.convert(request, null));
	}

	@Test
	@Tag("invalid")
	void validateConversionWhenBothParametersAreNull() {
		// Assert
		assertThrows(IllegalArgumentException.class, () -> converter.convert(null, null));
	}

}