/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getMetadata_1206d36e1f
ROOST_METHOD_SIG_HASH=getMetadata_204504630d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/controller/custom/CustomProjectGenerationController.java
Tests:
    "@Test
@Override
public CustomProjectRequest projectRequest(Map<String, String> headers) {
    CustomProjectRequest request = new CustomProjectRequest();
    request.getParameters().putAll(headers);
    request.initialize(getMetadata());
    return request;
}
""""
Scenario 1: Valid metadata retrieval

Details:
  TestName: testGetValidMetadata
  Description: This test checks that the getMetadata method correctly returns metadata for a properly initialized ProjectRequestEvent.

Execution:
  Arrange: Instantiate a ProjectRequestEvent object with valid metadata.
  Act: Invoke the getMetadata() method on the prepared ProjectRequestEvent object.
  Assert: Assert that the returned metadata object matches the metadata that was set when instantiating the ProjectRequestEvent object.

Validation:
  This scenario tests the primary function of the getMetadata() method — returning the metadata of the ProjectRequestEvent.
  This validation step confirms that the getMetadata method accurately returns the correct object and ensures that other methods using this data will behave as expected.


Scenario 2: Retrieval of metadata when none is set

Details:
  TestName: testGetMetadataWhenNoneIsSet
  Description: This test case checks the behavior of the getMetadata method when no metadata has been set.

Execution:
  Arrange: Create a ProjectRequestEvent object without setting any metadata.
  Act: Invoke the getMetadata() method on the newly created ProjectRequestEvent object.
  Assert: Assert that the method returns a null.

Validation:
  This scenario verifies that the getMetadata() method handles the absence of metadata correctly by returning null.
  The validation step ensures that further operations using this method do not lead to unexpected exceptions due to the nonexistence of the metadata.


Scenario 3: Confirmation that the returned metadata instance is the exact one set

Details:
  TestName: testConfirmExactMetadataInstance
  Description: This test verifies that the metadata returned by getMetadata is not just a copy but rather, the exact instance of the metadata that was set.

Execution:
  Arrange: Initialize a ProjectRequestEvent object with valid metadata.
  Act: Invoke the getMetadata() method on the prepared ProjectRequestEvent object.
  Assert: Assert using the '==' operator that the returned object is exactly the same instance that was set.

Validation:
  This scenario validates that the getMetadata() method doesn't return a new instance or a copy of the metadata but the exact original Instance.
  This validation step ensures that changes made to the metadata after retrieval will affect the original metadata object in the ProjectRequestEvent instance.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import io.spring.initializr.metadata.InitializrMetadata;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

public class ProjectRequestEventGetMetadataTest {

	@Test
	@Tag("valid")
	public void testGetValidMetadata() {
		ProjectRequest request = new ProjectRequest();
		InitializrMetadata metadata = new InitializrMetadata();
		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(request, metadata);
		assertEquals(metadata, projectRequestEvent.getMetadata());
	}

	@Test
	@Tag("invalid")
	public void testGetMetadataWhenNoneIsSet() {
		ProjectRequest request = new ProjectRequest();
		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(request, null);
		assertNull(projectRequestEvent.getMetadata());
	}

	@Test
	@Tag("valid")
	public void testConfirmExactMetadataInstance() {
		ProjectRequest request = new ProjectRequest();
		InitializrMetadata metadata = new InitializrMetadata();
		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(request, metadata);
		assertTrue(metadata == projectRequestEvent.getMetadata());
	}

}