/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getProjectAssetGenerator_2b7eb3a312
ROOST_METHOD_SIG_HASH=getProjectAssetGenerator_4d07575527

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void invokeProjectStructureGenerationWithCustomAssetGenerator(@TempDir Path directory) {
    WebProjectRequest webRequest = new WebProjectRequest();
    webRequest.initialize(metadata);
    webRequest.setGroupId("org.acme.test");
    webRequest.setType("maven-project");
    ProjectGenerationResult result = new ProjectGenerationInvoker<ProjectRequest>(this.context, this.eventPublisher, new DefaultProjectRequestToDescriptionConverter()) {

        @Override
        protected ProjectAssetGenerator<Path> getProjectAssetGenerator(ProjectDescription description) {
            assertThat(description.getBuildSystem()).isInstanceOf(MavenBuildSystem.class);
            assertThat(description.getGroupId()).isEqualTo("org.acme.test");
            return (context) -> directory;
        }
    }.invokeProjectStructureGeneration(webRequest);
    assertThat(result.getRootDirectory()).isSameAs(directory);
    assertThat(result.getRootDirectory()).isEmptyDirectory();
    verifyProjectSuccessfulEventFor(webRequest);
}
"Scenario 1: Verify getProjectAssetGenerator returns non-null Project Asset Generator

Details:
    TestName: verifyGetProjectAssetGeneratorReturnsNonNull
    Description: This test checks that the getProjectAssetGenerator method assures the non-nullability of the returned ProjectAssetGenerator object.

  Execution:
    Arrange: Create a ProjectDescription object.
    Act: Invoke the getProjectAssetGenerator method with the created ProjectDescription object.
    Assert: Use JUnit assertions to check that the returned ProjectAssetGenerator object is not null.

  Validation:
    The assertion verifies that the getProjectAssetGenerator method returns a non-null instance of ProjectAssetGenerator.
    This test is important as it validates the null safety of the method, ensuring that utilizing the result of this method won't result in null pointer exceptions in further execution.

Scenario 2: Verify the same instance of ProjectAssetGenerator is returned by getProjectAssetGenerator

Details:
    TestName: verifySameInstanceReturnedByGetProjectAssetGenerator
    Description: This test checks if the method getProjectAssetGenerator returns the same instance of ProjectAssetGenerator every time it's invoked.

  Execution:
    Arrange: Prepare a ProjectDescription object.
    Act: Invoke the getProjectAssetGenerator method twice, each time passing the created ProjectDescription object.
    Assert: Use JUnit assertions to check that both returned ProjectAssetGenerator objects are identical.

  Validation:
    The assertion validates that the getProjectAssetGenerator method always returns the reference to the same instance.
    This test ensures the consistency and predictability of the method's behavior, which is crucial for maintaining the same state across multiple invocations.


Scenario 3: Check that getProjectAssetGenerator does not consider input ProjectDescription object

Details:
    TestName: checkProjectDescriptionIgnoredInGetProjectAssetGenerator
    Description: This test verifies that the method getProjectAssetGenerator does not depend on the passed ProjectDescription object.

  Execution:
    Arrange: Create two different ProjectDescription objects.
    Act: Invoke the getProjectAssetGenerator method for both ProjectDescription objects.
    Assert: Use JUnit assertions to verify that both returned ProjectAssetGenerator objects are the same.

  Validation:
    The assertion verifies that the getProjectAssetGenerator method does not consider the ProjectDescription object in its processing.
    This test is significant as it clarifies the role of inputs on method outcomes, which helps identify the method's effect on system state and maintain consistency in the system behavior.


*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import io.spring.initializr.generator.project.ProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import io.spring.initializr.web.project.ProjectRequestToDescriptionConverter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEventPublisher;
import java.nio.file.Path;
import java.util.Random;
import static org.junit.jupiter.api.Assertions.assertSame;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import io.spring.initializr.generator.buildsystem.BuildItemResolver;
import io.spring.initializr.generator.buildsystem.BuildWriter;
import io.spring.initializr.generator.project.DefaultProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectGenerationContext;
import io.spring.initializr.generator.project.ProjectGenerationException;
import io.spring.initializr.generator.project.ProjectGenerator;
import io.spring.initializr.metadata.support.MetadataBuildItemResolver;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.util.FileSystemUtils;

class ProjectGenerationInvokerGetProjectAssetGeneratorTest {

	private ProjectGenerationInvoker<ProjectRequestToDescriptionConverter> projectGenerationInvoker;

	@Mock
	private ApplicationContext parentApplicationContext;

	@Mock
	private ApplicationEventPublisher eventPublisher;

	@Mock
	private ProjectRequestToDescriptionConverter requestConverter;

	@Mock
	private ProjectAssetGenerator<Path> projectAssetGenerator;

	@BeforeEach
	void setUp() {
		projectGenerationInvoker = new ProjectGenerationInvoker<>(parentApplicationContext, eventPublisher,
				requestConverter);
		projectGenerationInvoker.projectAssetGenerator = projectAssetGenerator;
	}

	@Test
	@Tag("valid")
	void verifyGetProjectAssetGeneratorReturnsNonNull() {
		ProjectDescription description = new ProjectDescription();
		ProjectAssetGenerator<Path> result = projectGenerationInvoker.getProjectAssetGenerator(description);
		assertSame(projectAssetGenerator, result);
	}

	@Test
	@Tag("valid")
	void verifySameInstanceReturnedByGetProjectAssetGenerator() {
		ProjectDescription description = new ProjectDescription();
		ProjectAssetGenerator<Path> result1 = projectGenerationInvoker.getProjectAssetGenerator(description);
		ProjectAssetGenerator<Path> result2 = projectGenerationInvoker.getProjectAssetGenerator(description);
		assertSame(result1, result2);
	}

	@Test
	@Tag("boundary")
	void checkProjectDescriptionIgnoredInGetProjectAssetGenerator() {
		ProjectDescription description1 = new ProjectDescription();
		description1.setApplicationName("Application " + new Random().nextInt());
		ProjectAssetGenerator<Path> result1 = projectGenerationInvoker.getProjectAssetGenerator(description1);
		ProjectDescription description2 = new ProjectDescription();
		description2.setApplicationName("Application " + new Random().nextInt());
		ProjectAssetGenerator<Path> result2 = projectGenerationInvoker.getProjectAssetGenerator(description2);
		assertSame(result1, result2);
	}

}