/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=invokeBuildGeneration_5bd7613099
ROOST_METHOD_SIG_HASH=invokeBuildGeneration_078c4c9bac

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void invokeBuildGenerationForMavenBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new MavenBuildAssert(content).hasGroupId(request.getGroupId()).hasArtifactId(request.getArtifactId()).hasVersion(request.getVersion()).doesNotHaveNode("/project/packaging").hasName(request.getName()).hasDescription(request.getDescription()).hasProperty("java.version", request.getJavaVersion()).hasParent("org.springframework.boot", "spring-boot-starter-parent", request.getBootVersion());
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationForGradleBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    request.setJavaVersion("17");
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new GroovyDslGradleBuildAssert(content).hasVersion(request.getVersion()).hasPlugin("org.springframework.boot", request.getBootVersion()).hasToolchainForJava("17");
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationFailureShouldPublishFailureEvent() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("foo-bar");
    try {
        this.invoker.invokeBuildGeneration(request);
    } catch (Exception ex) {
        verifyProjectFailedEventFor(request, ex);
    }
}
""""
  Scenario 1: Verifying invokeBuildGeneration method with valid request input

  Details:
    TestName: testInvokeBuildGenerationWithValidRequest.
    Description: This test aims to check the functionality of the invokeBuildGeneration method when provided with a valid request parameter.

  Execution:
    Arrange: Create a new ProjectRequest and initialize it with appropriate details.
    Act: Call the invokeBuildGeneration method with the initialized ProjectRequest instance.
    Assert: Verify that the method returns the expected byte array and the events are properly published in case of a successful invocation.
  Validation:
    This assertion verifies that the invokeBuildGeneration method correctly generates a byte array when provided with a valid request. If the method fails this test, it indicates a malfunction in processing successful/valid project requests.


  ----------------------------------------------------------------------------------------------------------------------------------

  Scenario 2: Testing invokeBuildGeneration method with invalid request input

  Details:
    TestName: testInvokeBuildGenerationWithInvalidRequest.
    Description: This test aims to check the functionality of invokeBuildGeneration method when provided with an invalid request parameter.

  Execution:
    Arrange: Create a new ProjectRequest and initialize it with inappropriate details.
    Act: Call the invokeBuildGeneration method with the faulty ProjectRequest instance.
    Assert: Verify that the method throws an exception of type ProjectGenerationException and the failure event is properly published.
  Validation:
    This assertion confirms that the invokeBuildGeneration method throws the correct exception and proper failure events are triggered when an invalid request is processed. This is an important test to ensure correct error handling in the application.


  ----------------------------------------------------------------------------------------------------------------------------------

  Scenario 3: Verifying invokeBuildGeneration method when ProjectGenerator returns null

  Details:
    TestName: testInvokeBuildGenerationWithNullProjectGenerator.
    Description: This test aims to check the functionality of the invokeBuildGeneration method when the ProjectGenerator instance created by createProjectGenerator method returns null.

  Execution:
    Arrange: Mock createProjectGenerator method to return null when called. Create a valid ProjectRequest and initialize it.
    Act: Call invokeBuildGeneration method with the valid ProjectRequest instance.
    Assert: Verify that the method throws a ProjectGenerationException and the failure event is properly published.
  Validation:
    This assertion verifies that invokeBuildGeneration method can handle null return value from createProjectGenerator method gracefully by throwing a proper exception and triggering the correct event. If the method fails this test, it indicates a malfunction in error handling.


  ----------------------------------------------------------------------------------------------------------------------------------

  Scenario 4: Verifying invokeBuildGeneration method when requestConverter fails to convert the request

  Details:
    TestName: testInvokeBuildGenerationWithRequestConversionFailure.
    Description: This test aims to check the functionality of the invokeBuildGeneration method when the requestConverter fails to convert the given request.

  Execution:
    Arrange: Mock requestConverter's convert method to throw a ProjectGenerationException and initialize a valid ProjectRequest.
    Act: Call invokeBuildGeneration method with the valid ProjectRequest instance.
    Assert: Verify that the method throws a ProjectGenerationException.
  Validation:
    This assertion validates that the method can handle exceptions from the requestConverter's convert method, hence ensuring correct error handling in the application.

"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.nio.file.Path;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import io.spring.initializr.generator.buildsystem.BuildItemResolver;
import io.spring.initializr.generator.buildsystem.BuildWriter;
import io.spring.initializr.generator.project.DefaultProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationContext;
import io.spring.initializr.generator.project.ProjectGenerationException;
import io.spring.initializr.generator.project.ProjectGenerator;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.support.MetadataBuildItemResolver;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.util.FileSystemUtils;

@ExtendWith(MockitoExtension.class)
public class ProjectGenerationInvokerInvokeBuildGenerationTest {

	@InjectMocks
	private ProjectGenerationInvoker projectGenerationInvoker;

	@Mock
	private InitializrMetadata initializrMetadata;

	@Mock
	private ProjectDescription projectDescription;

	@Mock
	private ProjectGenerator projectGenerator;

	@Mock
	private ApplicationContext parentApplicationContext;

	@Mock
	private ProjectRequestToDescriptionConverter<ProjectRequest> requestConverter;

	@Test
	@Tag("valid")
	public void testInvokeBuildGenerationWithValidRequest() {
		// Arrange
		ProjectRequest projectRequest = new ProjectRequest();
		ProjectDescription projectDescription = new ProjectDescription();
		when(parentApplicationContext.getBean(InitializrMetadataProvider.class)).thenReturn(initializrMetadata);
		when(requestConverter.convert(projectRequest, initializrMetadata)).thenReturn(projectDescription);
		when(createProjectGenerator(initializrMetadata)).thenReturn(projectGenerator);
		// Act
		byte[] result = projectGenerationInvoker.invokeBuildGeneration(projectRequest);
		// Assert
		Assertions.assertNotNull(result, "The result should not be null.");
		Assertions.assertTrue(result.length > 0, "The generated byte array should not be empty.");
	}

	@Test
	@Tag("invalid")
	public void testInvokeBuildGenerationWithInvalidRequest() {
		// Arrange
		ProjectRequest invalidRequest = new ProjectRequest();
		when(parentApplicationContext.getBean(InitializrMetadataProvider.class))
			.thenThrow(new ProjectGenerationException());
		// Act and Assert
		Assertions.assertThrows(ProjectGenerationException.class,
				() -> projectGenerationInvoker.invokeBuildGeneration(invalidRequest));
	}

	@Test
	@Tag("invalid")
	public void testInvokeBuildGenerationWithNullProjectGenerator() {
		// Arrange
		ProjectRequest validRequest = new ProjectRequest();
		when(parentApplicationContext.getBean(InitializrMetadataProvider.class)).thenReturn(initializrMetadata);
		when(requestConverter.convert(validRequest, initializrMetadata)).thenReturn(null);
		// Act and Assert
		Assertions.assertThrows(ProjectGenerationException.class,
				() -> projectGenerationInvoker.invokeBuildGeneration(validRequest));
	}

	@Test
	@Tag("invalid")
	public void testInvokeBuildGenerationWithRequestConversionFailure() {
		// Arrange
		ProjectRequest validRequest = new ProjectRequest();
		when(parentApplicationContext.getBean(InitializrMetadataProvider.class)).thenReturn(initializrMetadata);
		when(requestConverter.convert(validRequest, initializrMetadata)).thenThrow(new ProjectGenerationException());
		// Act and Assert
		Assertions.assertThrows(ProjectGenerationException.class,
				() -> projectGenerationInvoker.invokeBuildGeneration(validRequest));
	}

}