/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getApplicationName_ed17308b5a
ROOST_METHOD_SIG_HASH=getApplicationName_7379f4bf27

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/DefaultProjectRequestToDescriptionConverterTests.java
Tests:
    "@Test
@Test
void convertShouldSetApplicationNameForProjectDescriptionFromRequestWhenPresent() {
    ProjectRequest request = createProjectRequest();
    request.setApplicationName("MyApplication");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getApplicationName()).isEqualTo("MyApplication");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/MetadataProjectDescriptionCustomizerTests.java
Tests:
    "@Test
@Test
void customizeShouldUseDefaultApplicationNameFromMetadata() {
    assertThat(customize(new MutableProjectDescription()).getApplicationName()).isEqualTo("Application");
}
"
    "@Test
@Test
void customizeShouldSetApplicationNameUsingNameWhenAbsent() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setName("MyTest");
    assertThat(customize(description).getApplicationName()).isEqualTo("MyTestApplication");
}
"Scenario 1: Validate if getApplicationName returns valid application name when set.

Details:
TestName: shouldReturnValidApplicationNameWhenSet
Description: This test is meant to check that the method getApplicationName returns a valid application name when it has been set.

Execution:
Arrange: Set up a ProjectRequest instance. Set an application name using setApplicationName().
Act: Invoke the getApplicationName method.
Assert: Assert that the returned application name matches the one set.

Validation:
The assertion aims to verify that the getApplicationName should return the exact string that was set using setApplicationName. It tests the basic getter functionality and ensures the application name is correctly set and retrieved.

Scenario 2: Validate if getApplicationName returns null if no application name is set.

Details:
TestName: shouldReturnNullWhenApplicationNameNotSet
Description: This test is meant to check that the method getApplicationName returns null when the application name has not been set.

Execution:
Arrange: Set up a ProjectRequest instance without setting an application name.
Act: Invoke the getApplicationName method.
Assert: Assert that the returned application name is null.

Validation:
This assertion aims to verify that if no application name has been explicitly set, getApplicationName should return null. This covers the edge case scenario where an application name has not been provided.

Scenario 3: Verify getApplicationName returns updated application name after it is reset.

Details:
TestName: shouldReturnUpdatedApplicationNameWhenReset
Description: This test is meant to validate that the getApplicationName method returns the updated application name if the application name was reset using setApplicationName.

Execution:
Arrange: Create a ProjectRequest instance and set a initial application name using setApplicationName(). Later, update this application name by setting a new name.
Act: Invoke the getApplicationName method.
Assert: Assert that the application name returned is the updated one, not the initial name which was set.

Validation:
This assertion verifies that when the application name is reset, getApplicationName should be able to retrieve the updated name. It is important in scenarios where application name needs to be updated.
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.StringUtils;

public class ProjectRequestGetApplicationNameTest {

	private ProjectRequest projectRequest;

	@BeforeEach
	public void setup() {
		projectRequest = new ProjectRequest();
	}

	@Test
	@Tag("valid")
	public void shouldReturnValidApplicationNameWhenSet() {
		String applicationName = "SpringApp";
		projectRequest.setApplicationName(applicationName);
		String returnedApplicationName = projectRequest.getApplicationName();

		assertEquals(applicationName, returnedApplicationName,
				"getApplicationName must return the correct application name that was set");
	}

	@Test
	@Tag("invalid")
	public void shouldReturnNullWhenApplicationNameNotSet() {
		String returnedApplicationName = projectRequest.getApplicationName();

		assertNull(returnedApplicationName,
				"getApplicationName must return null when application name has not been set");
	}

	@Test
	@Tag("boundary")
	public void shouldReturnUpdatedApplicationNameWhenReset() {
		String initialApplicationName = "SpringApp";
		projectRequest.setApplicationName(initialApplicationName);

		String updatedApplicationName = "UpdatedSpringApp";
		projectRequest.setApplicationName(updatedApplicationName);

		String returnedApplicationName = projectRequest.getApplicationName();

		assertEquals(updatedApplicationName, returnedApplicationName,
				"getApplicationName must return the updated application name when it's reset");
	}

}
