/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createDistributionFile_82e954b859
ROOST_METHOD_SIG_HASH=createDistributionFile_8fc3142b95

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
@SuppressWarnings("unchecked")
void createDistributionDirectory(@TempDir Path tempDir) {
    ProjectRequest request = new ProjectRequest();
    request.setType("gradle-project");
    Path distributionFile = this.invoker.createDistributionFile(tempDir, ".zip");
    assertThat(distributionFile.toString()).isEqualTo(tempDir + ".zip");
    Map<Path, List<Path>> tempFiles = (Map<Path, List<Path>>) ReflectionTestUtils.getField(this.invoker, "temporaryFiles");
    assertThat(tempFiles.get(tempDir)).contains(distributionFile);
}
"Scenario 1: Test to validate the successful creation of distribution file
Details:
TestName: createDistributionFileSuccess()
Description: Test is meant to check if the method successfully creates a distribution file with provided extension and stores it to a temporary map.
Execution:
Arrange: Define a temp directory and an extension for the distribution file.
Act: Call the createDistributionFile() method with the directory and extension as parameters.
Assert: The returned path should match the expected file path. Check if the distribution file path is stored in the temporaryFiles map.
Validation:
Verify if the distribution file initial creation is successful and the file path is stored in the temporaryFiles map with the provided directory as key. This ensures generation of distribution files is working fine.

Scenario 2: Test the case when NULL provided for the extension
Details:
TestName: createDistributionFileWithNullExtension()
Description: The test will validate the behavior when the distribution file extension is not provided (null).
Execution:
Arrange: Define a temp directory and assign NULL to the extension.
Act: Call the createDistributionFile() method with the directory and the null extension as parameters.
Assert: Verify an NPE or a custom exception for the scenario.
Validation:
This tests the application's error handling when the extension is not provided. Application should either throw NPE or a custom exception to maintain the robust nature.

Scenario 3: Test the case when NULL string is provided as directory
Details:
TestName: createDistributionFileWithNullDirectory()
Description: The test will check the behavior of the method when NULL directory is provided.
Execution:
Arrange: Assign NULL to the directory and define an extension for the distribution file.
Act: Call the createDistributionFile() method with the NULL directory and the extension as parameters.
Assert: Verify an NPE or a custom exception for the scenario.
Validation:
Verifying this will check the NULL handling mechanism in the method when the directory parameter is not provided. The application should throw an NPE or a custom exception in order to not proceed with invalid data.

Scenario 4: Test when an empty string is provided as an extension
Details:
TestName: createDistributionFileWithEmptyExtension()
Description: The test will check how the method behaves when the extension is an empty string.
Execution:
Arrange: Define a temp directory and assign an empty string to the extension.
Act: Call the createDistributionFile() method with the directory and the empty extension as parameters.
Assert: Verify an IllegalArgumentException or a custom exception.
Validation:
This tests the application's error handling when the extension is empty. Application should throw an IllegalArgumentException or a custom exception to maintain its robust nature.

Scenario 5: Test when the directory path is not available or inaccessible
Details:
TestName: createDistributionFileDirectoryNotFound()
Description: The test will assess the application's behavior when the directory path does not exist or is inaccessible.
Execution:
Arrange: Pass an invalid directory Path and define an extension for the distribution file.
Act: Call the createDistributionFile() method with the invalid directory and the extension as parameters.
Assert: Verify a FileSystemNotFoundException or a custom exception.
Validation:
This test will validate the application's responsiveness to a situation where the directory does not exist or is unavailable. It should throw an error rather than proceeding with invalid data.
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import java.nio.file.Paths;
import java.nio.file.InvalidPathException;
import java.util.List;
import java.util.Map;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.concurrent.ConcurrentHashMap;
import io.spring.initializr.generator.buildsystem.BuildItemResolver;
import io.spring.initializr.generator.buildsystem.BuildWriter;
import io.spring.initializr.generator.project.DefaultProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationContext;
import io.spring.initializr.generator.project.ProjectGenerationException;
import io.spring.initializr.generator.project.ProjectGenerator;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.support.MetadataBuildItemResolver;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.util.FileSystemUtils;

public class ProjectGenerationInvokerCreateDistributionFileTest {

	private ProjectGenerationInvoker projectGenerationInvoker;

	private Map<Path, List<Path>> tempFiles;

	@BeforeEach
	public void setup() {
		projectGenerationInvoker = Mockito.spy(ProjectGenerationInvoker.class);
		tempFiles = Mockito.mock(Map.class);
		Mockito.doReturn(tempFiles).when(projectGenerationInvoker).getTemporaryFiles();
	}

	@Test
	@Tag("valid")
	public void createDistributionFileSuccess() {
		String extension = ".txt";
		Path dir = Paths.get("tempDir");
		Path expectedFilePath = Paths.get("tempDir" + extension);
		Path actualFilePath = projectGenerationInvoker.createDistributionFile(dir, extension);
		Assertions.assertEquals(expectedFilePath, actualFilePath);
		Mockito.verify(tempFiles).put(Mockito.eq(dir), Mockito.any());
	}

	@Test
	@Tag("invalid")
	public void createDistributionFileWithNullExtension() {
		Path dir = Paths.get("tempDir");
		Assertions.assertThrows(NullPointerException.class, () -> {
			projectGenerationInvoker.createDistributionFile(dir, null);
		});
	}

	@Test
	@Tag("invalid")
	public void createDistributionFileWithNullDirectory() {
		String extension = ".txt";
		Assertions.assertThrows(NullPointerException.class, () -> {
			projectGenerationInvoker.createDistributionFile(null, extension);
		});
	}

	@Test
	@Tag("boundary")
	public void createDistributionFileWithEmptyExtension() {
		String extension = "";
		Path dir = Paths.get("tempDir");
		Assertions.assertThrows(IllegalArgumentException.class, () -> {
			projectGenerationInvoker.createDistributionFile(dir, extension);
		});
	}

	@Test
	@Tag("invalid")
	public void createDistributionFileDirectoryNotFound() {
		String extension = ".txt";
		Path dir = Paths.get("/not/a/valid/dir");
		Assertions.assertThrows(InvalidPathException.class, () -> {
			projectGenerationInvoker.createDistributionFile(dir, extension);
		});
	}

}