/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getArtifactId_526e52f9cf
ROOST_METHOD_SIG_HASH=getArtifactId_9c6601d59c

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/InitializrMetadataBuilderTests.java
Tests:
    "@Test
@Test
void mergeConfig() {
    InitializrProperties config = load(new ClassPathResource("application-test-default.yml"));
    InitializrProperties customDefaultsConfig = load(new ClassPathResource("application-test-custom-defaults.yml"));
    InitializrMetadata metadata = InitializrMetadataBuilder.fromInitializrProperties(config).withInitializrProperties(customDefaultsConfig).build();
    assertDefaultConfig(metadata);
    assertThat(metadata.getGroupId().getContent()).isEqualTo("org.foo");
    assertThat(metadata.getArtifactId().getContent()).isEqualTo("foo-bar");
    assertThat(metadata.getVersion().getContent()).isEqualTo("1.2.4-SNAPSHOT");
    assertThat(metadata.getName().getContent()).isEqualTo("FooBar");
    assertThat(metadata.getDescription().getContent()).isEqualTo("FooBar Project");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.foo.demo");
}
"
    "@Test
@Test
void mergeMetadata() {
    InitializrMetadata metadata = InitializrMetadataBuilder.create().withInitializrMetadata(new ClassPathResource("metadata/config/test-min.json")).build();
    assertThat(metadata.getConfiguration().getEnv().isForceSsl()).isEqualTo(true);
    assertThat(metadata.getDependencies().getContent()).hasSize(1);
    Dependency dependency = metadata.getDependencies().get("test");
    assertThat(dependency).isNotNull();
    assertThat(dependency.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(metadata.getTypes().getContent()).hasSize(1);
    assertThat(metadata.getBootVersions().getContent()).hasSize(2);
    assertThat(metadata.getPackagings().getContent()).hasSize(2);
    assertThat(metadata.getJavaVersions().getContent()).hasSize(1);
    assertThat(metadata.getLanguages().getContent()).hasSize(3);
    assertThat(metadata.getName().getContent()).isEqualTo("metadata-merge");
    assertThat(metadata.getDescription().getContent()).isEqualTo("Demo project for metadata merge");
    assertThat(metadata.getGroupId().getContent()).isEqualTo("org.acme");
    assertThat(metadata.getArtifactId().getContent()).isEqualTo("metadata");
    assertThat(metadata.getVersion().getContent()).isEqualTo("1.0.0-SNAPSHOT");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.acme.demo");
}
"
    "@Test
@Test
void mergeMetadataWithBom() {
    InitializrMetadata metadata = InitializrMetadataBuilder.create().withInitializrMetadata(new ClassPathResource("metadata/config/test-bom.json")).build();
    Map<String, BillOfMaterials> boms = metadata.getConfiguration().getEnv().getBoms();
    assertThat(boms).hasSize(2);
    BillOfMaterials myBom = boms.get("my-bom");
    assertThat(myBom).isNotNull();
    assertThat(myBom.getGroupId()).isEqualTo("org.acme");
    assertThat(myBom.getArtifactId()).isEqualTo("my-bom");
    assertThat(myBom.getVersion()).isEqualTo("2.4.1");
    BillOfMaterials anotherBom = boms.get("another-bom");
    assertThat(anotherBom).isNotNull();
    assertThat(anotherBom.getGroupId()).isEqualTo("org.acme");
    assertThat(anotherBom.getArtifactId()).isEqualTo("another-bom");
    assertThat(anotherBom.getVersion()).isEqualTo("4.5.6.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/DependencyTests.java
Tests:
    "@Test
@Test
void createRootSpringBootStarter() {
    Dependency d = Dependency.createSpringBootStarter("");
    assertThat(d.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(d.getArtifactId()).isEqualTo("spring-boot-starter");
}
"
    "@Test
@Test
void setCoordinatesFromId() {
    Dependency dependency = Dependency.withId("org.foo:bar:1.2.3");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.foo");
    assertThat(dependency.getArtifactId()).isEqualTo("bar");
    assertThat(dependency.getVersion()).isEqualTo("1.2.3");
    assertThat(dependency.getId()).isEqualTo("org.foo:bar:1.2.3");
}
"
    "@Test
@Test
void setCoordinatesFromIdNoVersion() {
    Dependency dependency = Dependency.withId("org.foo:bar");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.foo");
    assertThat(dependency.getArtifactId()).isEqualTo("bar");
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getId()).isEqualTo("org.foo:bar");
}
"
    "@Test
@Test
void setIdFromSimpleName() {
    Dependency dependency = Dependency.withId("web");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(dependency.getArtifactId()).isEqualTo("spring-boot-starter-web");
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getId()).isEqualTo("web");
}
"
    "@Test
private static void validateResolvedDependency(Dependency dependency, String id, String expectedGroupId, String expectedArtifactId, String expectedVersion, boolean expectedStarter, String expectedBom, String expectedRepository) {
    assertThat(dependency.getId()).isEqualTo(id);
    assertThat(dependency.getGroupId()).isEqualTo(expectedGroupId);
    assertThat(dependency.getArtifactId()).isEqualTo(expectedArtifactId);
    assertThat(dependency.getVersion()).isEqualTo(expectedVersion);
    assertThat(dependency.isStarter()).isEqualTo(expectedStarter);
    assertThat(dependency.getBom()).isEqualTo(expectedBom);
    assertThat(dependency.getRepository()).isEqualTo(expectedRepository);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/BillOfMaterialsTests.java
Tests:
    "@Test
@Test
void resolveSimpleRange() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("bom.version");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    bom.getMappings().add(Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0"));
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("bom.version");
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-main");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-main");
}
"
    "@Test
@Test
void resolveSimpleRangeWithGroupIdArtifactId() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("bom.version");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    Mapping mapping = Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0");
    mapping.setGroupId("com.example.override");
    mapping.setArtifactId("bom-override");
    bom.getMappings().add(mapping);
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example.override");
    assertThat(resolved.getArtifactId()).isEqualTo("bom-override");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("bom.version");
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-main");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-main");
}
"
    "@Test
@Test
void resolveRangeOverride() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    Mapping mapping = Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0", "repo-foo");
    mapping.getAdditionalBoms().add("bom-foo");
    bom.getMappings().add(mapping);
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty()).isNull();
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-foo");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-foo");
}
"
    "@Test
@Test
void resolveRangeOverrideAndMapping() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("example.version");
    bom.getMappings().add(Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0"));
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("example.version");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinDependenciesConfigurerTests.java
Tests:
    "@Test
@Test
void configuresDependenciesForGradleBuild() {
    GradleBuild build = new GradleBuild();
    new KotlinDependenciesConfigurer().customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-reflect", "kotlin-test-junit5");
    Dependency kotlinReflect = build.dependencies().get("kotlin-reflect");
    assertThat(kotlinReflect.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinReflect.getArtifactId()).isEqualTo("kotlin-reflect");
    assertThat(kotlinReflect.getVersion()).isNull();
    Dependency kotlinTest = build.dependencies().get("kotlin-test-junit5");
    assertThat(kotlinTest.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinTest.getArtifactId()).isEqualTo("kotlin-test-junit5");
    assertThat(kotlinTest.getScope()).isEqualTo(DependencyScope.TEST_COMPILE);
    assertThat(kotlinTest.getVersion()).isNull();
}
"
    "@Test
@Test
void configuresDependenciesForMavenBuild() {
    MavenBuild build = new MavenBuild();
    new KotlinDependenciesConfigurer().customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-reflect", "kotlin-test-junit5");
    Dependency kotlinReflect = build.dependencies().get("kotlin-reflect");
    assertThat(kotlinReflect.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinReflect.getArtifactId()).isEqualTo("kotlin-reflect");
    assertThat(kotlinReflect.getVersion()).isNull();
    Dependency kotlinTest = build.dependencies().get("kotlin-test-junit5");
    assertThat(kotlinTest.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinTest.getArtifactId()).isEqualTo("kotlin-test-junit5");
    assertThat(kotlinTest.getScope()).isEqualTo(DependencyScope.TEST_COMPILE);
    assertThat(kotlinTest.getVersion()).isNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/MetadataProjectDescriptionCustomizerTests.java
Tests:
    "@Test
@Test
void customizeShouldUseDefaultFromMetadataOnEmptyArtifact() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setArtifactId("");
    assertThat(customize(description).getArtifactId()).isEqualTo("demo");
}
"
    "@Test
@Test
void customizeShouldNotCleanArtifactIdWithValidChars() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setArtifactId("correct_test");
    assertThat(customize(description).getArtifactId()).isEqualTo("correct_test");
}
"
    "@Test
@Test
void customizeShouldCleanInvalidArtifactIdWithHyphenSeparator() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setArtifactId("correct ! ID @");
    assertThat(customize(description).getArtifactId()).isEqualTo("correct-ID");
}
"
    "@Test
@Test
void customizeWithCleanedArtifactIdShouldNotContainHyphenBeforeOrAfterValidSpecialCharacter() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setArtifactId("correct !_!ID @");
    assertThat(customize(description).getArtifactId()).isEqualTo("correct_ID");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void invokeBuildGenerationForMavenBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new MavenBuildAssert(content).hasGroupId(request.getGroupId()).hasArtifactId(request.getArtifactId()).hasVersion(request.getVersion()).doesNotHaveNode("/project/packaging").hasName(request.getName()).hasDescription(request.getDescription()).hasProperty("java.version", request.getJavaVersion()).hasParent("org.springframework.boot", "spring-boot-starter-parent", request.getBootVersion());
    verifyProjectSuccessfulEventFor(request);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenPluginContainerTests.java
Tests:
    "@Test
@Test
void addPlugin() {
    MavenPluginContainer pluginContainer = new MavenPluginContainer();
    pluginContainer.add("com.example", "test-plugin");
    assertThat(pluginContainer.values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getGroupId()).isEqualTo("com.example");
        assertThat(plugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(plugin.getVersionReference()).isNull();
    });
}
"
    "@Test
@Test
void addPluginWithConsumer() {
    MavenPluginContainer pluginContainer = new MavenPluginContainer();
    pluginContainer.add("com.example", "test-plugin", (plugin) -> plugin.version("1.0").execution("first", (first) -> first.goal("run-this")));
    assertThat(pluginContainer.values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getGroupId()).isEqualTo("com.example");
        assertThat(plugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(plugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.0"));
        assertThat(plugin.getExecutions()).hasSize(1);
        assertThat(plugin.getExecutions().get(0).getId()).isEqualTo("first");
        assertThat(plugin.getExecutions().get(0).getGoals()).containsExactly("run-this");
    });
}
"
    "@Test
@Test
void addPluginSeveralTimeReuseConfiguration() {
    MavenPluginContainer pluginContainer = new MavenPluginContainer();
    pluginContainer.add("com.example", "test-plugin", (plugin) -> plugin.version("1.0"));
    pluginContainer.add("com.example", "test-plugin", (plugin) -> plugin.version("2.0"));
    assertThat(pluginContainer.values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getGroupId()).isEqualTo("com.example");
        assertThat(plugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(plugin.getVersionReference()).isEqualTo(VersionReference.ofValue("2.0"));
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/ProjectGeneratorTests.java
Tests:
    "@Test
@Test
void generateCanBeExtendedToFilterProjectContributors(@TempDir Path projectDir) {
    ProjectDescription description = mock(ProjectDescription.class);
    given(description.getArtifactId()).willReturn("test-custom-contributor");
    given(description.getBuildSystem()).willReturn(new MavenBuildSystem());
    ProjectGenerator generator = new ProjectGenerator(mockContextInitializr()) {

        @Override
        protected List<String> getCandidateProjectGenerationConfigurations(ProjectDescription generatorDescription) {
            assertThat(description).isSameAs(generatorDescription);
            return Collections.singletonList(TestProjectGenerationConfiguration.class.getName());
        }
    };
    DefaultProjectAssetGenerator assetGenerator = new DefaultProjectAssetGenerator((desc) -> projectDir);
    Path outputDir = generator.generate(description, assetGenerator);
    Path expectedFile = outputDir.resolve("artifact-id.txt");
    assertThat(expectedFile).isRegularFile();
    assertThat(expectedFile).hasContent("test-custom-contributor");
    verify(description).getArtifactId();
    verify(description).getBuildSystem();
}
"
    "@Test
@Test
void filterProjectContributorsCorrectly() {
    ProjectDescription description = mock(ProjectDescription.class);
    given(description.getArtifactId()).willReturn("test-custom-contributor");
    given(description.getBuildSystem()).willReturn(new MavenBuildSystem());
    ProjectGenerator generator = new ProjectGenerator(mockContextInitializr()) {

        @Override
        List<String> getProjectGenerationConfigurationFactoryNames() {
            return Lists.list(TestProjectGenerationConfiguration.class.getName(), TestProjectGenerationConfiguration2.class.getName());
        }

        @Override
        ProjectGenerationConfigurationTypeFilter getProjectGenerationConfigurationExclusionFilter() {
            return (clazz) -> !TestProjectGenerationConfiguration2.class.equals(clazz);
        }
    };
    List<String> candidates = generator.getCandidateProjectGenerationConfigurations(description);
    assertThat(candidates).containsOnly(TestProjectGenerationConfiguration.class.getCanonicalName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/support/MetadataBuildItemResolverTests.java
Tests:
    "@Test
@Test
void resoleDependencyWithMatchingEntry() {
    InitializrMetadata metadata = new InitializrMetadata();
    DependencyGroup group = DependencyGroup.create("test");
    Dependency target = Dependency.withId("test-dep", "com.example", "test", "1.0.0", "runtime");
    target.setClassifier("test-jar");
    group.getContent().add(target);
    metadata.getDependencies().getContent().add(group);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.Dependency dependency = resolver.resolveDependency("test-dep");
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).hasToString("1.0.0");
    assertThat(dependency.getClassifier()).hasToString("test-jar");
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
}
"
    "@Test
@Test
void resoleDependencyWithMatchingEntryAndCompatibilityRange() {
    InitializrMetadata metadata = new InitializrMetadata();
    DependencyGroup group = DependencyGroup.create("test");
    Dependency dependency = Dependency.withId("test-dep", "com.example", "test");
    dependency.getMappings().add(Mapping.create("[1.0.0.RELEASE, 2.0.0.RELEASE)", null, null, "1.0.0.RELEASE", null, null, null));
    dependency.getMappings().add(Mapping.create("2.0.0.RELEASE", "com.example.override", "test-override", null, null, null, null));
    group.getContent().add(dependency);
    metadata.getDependencies().getContent().add(group);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.Dependency resolveDependency = resolver.resolveDependency("test-dep");
    assertThat(resolveDependency.getGroupId()).isEqualTo("com.example.override");
    assertThat(resolveDependency.getArtifactId()).isEqualTo("test-override");
    assertThat(resolveDependency.getVersion()).isNull();
    assertThat(resolveDependency.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void resoleBomWithMatchingEntry() {
    InitializrMetadata metadata = new InitializrMetadata();
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "2.0.0");
    metadata.getConfiguration().getEnv().getBoms().put("test-bom", bom);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.BillOfMaterials resolvedBom = resolver.resolveBom("test-bom");
    assertThat(resolvedBom.getGroupId()).isEqualTo("com.example");
    assertThat(resolvedBom.getArtifactId()).isEqualTo("bom");
    assertThat(resolvedBom.getVersion()).hasToString("2.0.0");
}
"
    "@Test
@Test
void resoleBomWithMatchingEntryAndCompatibilityRange() throws MalformedURLException {
    InitializrMetadata metadata = new InitializrMetadata();
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "0.0.1");
    bom.getMappings().add(BillOfMaterials.Mapping.create("[1.0.0.RELEASE, 2.0.0.RELEASE)", "1.0.0"));
    bom.getMappings().add(BillOfMaterials.Mapping.create("2.0.0.RELEASE", "1.1.0"));
    metadata.getConfiguration().getEnv().getBoms().put("test-bom", bom);
    metadata.getConfiguration().getEnv().getRepositories().put("test-repo", new Repository("test", new URL("https:
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.BillOfMaterials resolvedBom = resolver.resolveBom("test-bom");
    assertThat(resolvedBom.getGroupId()).isEqualTo("com.example");
    assertThat(resolvedBom.getArtifactId()).isEqualTo("bom");
    assertThat(resolvedBom.getVersion()).hasToString("1.1.0");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/contributor/TestProjectGenerationConfiguration.java
Tests:
    "@Test
@Bean
@ConditionalOnBuildSystem(MavenBuildSystem.ID)
public ProjectContributor testArtifactIdContributor(ProjectDescription description) {
    return (projectRoot) -> {
        Path testFile = projectRoot.resolve("artifact-id.txt");
        Files.createFile(testFile);
        FileCopyUtils.copy(description.getArtifactId(), Files.newBufferedWriter(testFile));
    };
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/DefaultMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeRegisterSpringBootPlugin() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().build();
    MavenBuild build = customizeBuild(metadata);
    assertThat(build.plugins().values()).singleElement().satisfies((mavenPlugin) -> {
        assertThat(mavenPlugin.getGroupId()).isEqualTo("org.springframework.boot");
        assertThat(mavenPlugin.getArtifactId()).isEqualTo("spring-boot-maven-plugin");
        assertThat(mavenPlugin.getVersionReference()).isNull();
    });
}
"
    "@Test
@Test
void customizeWhenNoParentShouldUseSpringBootParent() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().build();
    MavenBuild build = customizeBuild(metadata);
    MavenParent parent = build.getSettings().getParent();
    assertThat(parent.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(parent.getArtifactId()).isEqualTo("spring-boot-starter-parent");
    assertThat(parent.getVersion()).isEqualTo("2.0.0");
    assertThat(parent.getRelativePath()).isEmpty();
}
"
    "@Test
@Test
void customizeWithCustomParentAndSpringBootBomShouldAddBom() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().setMavenParent("com.foo", "foo-parent", "1.0.0-SNAPSHOT", "../pom.xml", true).build();
    MavenBuild build = customizeBuild(metadata);
    MavenParent parent = build.getSettings().getParent();
    assertThat(parent.getGroupId()).isEqualTo("com.foo");
    assertThat(parent.getArtifactId()).isEqualTo("foo-parent");
    assertThat(parent.getVersion()).isEqualTo("1.0.0-SNAPSHOT");
    assertThat(parent.getRelativePath()).isEqualTo("../pom.xml");
    BomContainer boms = build.boms();
    assertThat(boms.items()).hasSize(1);
    assertThat(boms.ids()).contains("spring-boot");
    assertThat(build.properties().versions(VersionProperty::toStandardFormat)).contains(entry("spring-boot.version", "2.0.0"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/DependencyTests.java
Tests:
    "@Test
@Test
void dependencyWithCoordinatesOnly() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithScopeAndVersionValue() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").scope(DependencyScope.RUNTIME).version(VersionReference.ofValue("1.0.0")).build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getVersion().getValue()).isEqualTo("1.0.0");
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithClassifier() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").classifier("test").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isEqualTo("test");
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithType() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").type("test-zip").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isEqualTo("test-zip");
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithExclusions() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").exclusions(new Exclusion("com.example", "exclude1"), new Exclusion("com.example", "exclude2")).build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).containsExactly(new Exclusion("com.example", "exclude1"), new Exclusion("com.example", "exclude2"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenBuildTests.java
Tests:
    "@Test
@Test
void mavenPluginManagementCanBeConfigured() {
    MavenBuild build = new MavenBuild();
    build.pluginManagementPlugins().add("com.example", "test-plugin", (plugin) -> plugin.version("1.2.3"));
    assertThat(build.pluginManagementPlugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.2.3"));
    });
}
"
    "@Test
@Test
void mavenPluginCanBeConfigured() {
    MavenBuild build = new MavenBuild();
    build.plugins().add("com.example", "test-plugin", (plugin) -> plugin.execution("first", (first) -> first.goal("run-this")));
    assertThat(build.plugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isNull();
        assertThat(testPlugin.getExecutions()).hasSize(1);
        assertThat(testPlugin.getExecutions().get(0).getId()).isEqualTo("first");
        assertThat(testPlugin.getExecutions().get(0).getGoals()).containsExactly("run-this");
    });
}
"
    "@Test
@Test
void mavenPluginVersionCanBeAmended() {
    MavenBuild build = new MavenBuild();
    build.plugins().add("com.example", "test-plugin");
    build.plugins().add("com.example", "test-plugin", (plugin) -> plugin.version("1.0.0"));
    assertThat(build.plugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.0.0"));
    });
}
"
    "@Test
@Test
void mavenPluginVersionCanBeAmendedWithCustomizer() {
    MavenBuild build = new MavenBuild();
    build.plugins().add("com.example", "test-plugin", (plugin) -> plugin.version("1.0.0"));
    build.plugins().add("com.example", "test-plugin", (plugin) -> plugin.version(null));
    assertThat(build.plugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isNull();
    });
}
"
    "@Test
@Test
void mavenPluginVersionIsNotLostOnAmend() {
    MavenBuild build = new MavenBuild();
    build.plugins().add("com.example", "test-plugin", (plugin) -> plugin.version("1.0.0"));
    build.plugins().add("com.example", "test-plugin");
    assertThat(build.plugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.0.0"));
    });
}
"
    "@Test
@Test
void mavenPluginManagementInProfileCanBeConfigured() {
    MavenBuild build = new MavenBuild();
    build.profiles().id("test").pluginManagementPlugins().add("com.example", "test-plugin", (plugin) -> plugin.version("1.2.3"));
    assertThat(build.profiles().values()).singleElement().satisfies((profile) -> assertThat(profile.pluginManagementPlugins().values()).singleElement().satisfies((testPlugin) -> {
        assertThat(testPlugin.getGroupId()).isEqualTo("com.example");
        assertThat(testPlugin.getArtifactId()).isEqualTo("test-plugin");
        assertThat(testPlugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.2.3"));
    }));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/support/DefaultDependencyMetadataProviderTests.java
Tests:
    "@Test
@Test
void resolveDependencies() {
    Dependency first = Dependency.withId("first", "org.foo", "first");
    first.getMappings().add(Dependency.Mapping.create("[1.0.0.RELEASE, 1.1.0.RELEASE)", "org.bar", "second", "0.1.0.RELEASE", null, null, null));
    first.getMappings().add(Dependency.Mapping.create("1.1.0.RELEASE", "org.biz", "third", "0.2.0.RELEASE", null, null, null));
    Dependency second = Dependency.withId("second", "org.foo", "second");
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", first, second).build();
    DependencyMetadata dependencyMetadata = this.provider.get(metadata, Version.parse("1.0.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(2);
    assertThat(dependencyMetadata.getDependencies().get("first").getGroupId()).isEqualTo("org.bar");
    assertThat(dependencyMetadata.getDependencies().get("first").getArtifactId()).isEqualTo("second");
    assertThat(dependencyMetadata.getDependencies().get("first").getVersion()).isEqualTo("0.1.0.RELEASE");
    DependencyMetadata anotherDependencyMetadata = this.provider.get(metadata, Version.parse("1.1.0.RELEASE"));
    assertThat(anotherDependencyMetadata.getDependencies()).hasSize(2);
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getGroupId()).isEqualTo("org.biz");
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getArtifactId()).isEqualTo("third");
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getVersion()).isEqualTo("0.2.0.RELEASE");
}
"
    "@Test
@Test
void addBomAndRemoveDuplicates() {
    Dependency first = Dependency.withId("first", "org.foo", "first");
    first.setBom("bom-foo");
    Dependency second = Dependency.withId("second", "org.foo", "second");
    Dependency third = Dependency.withId("third", "org.foo", "third");
    third.setBom("bom-foo");
    BillOfMaterials bom = BillOfMaterials.create("org.foo", "bom");
    bom.getMappings().add(BillOfMaterials.Mapping.create("[1.0.0.RELEASE, 1.1.8.RELEASE)", "1.0.0.RELEASE"));
    bom.getMappings().add(BillOfMaterials.Mapping.create("1.1.8.RELEASE", "2.0.0.RELEASE"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addBom("bom-foo", bom).addDependencyGroup("test", first, second, third).build();
    DependencyMetadata dependencyMetadata = this.provider.get(metadata, Version.parse("1.1.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).isEmpty();
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("1.0.0.RELEASE");
}
"
    "@Test
@Test
void repoFromBomAccordingToVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.0.9.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.0.9.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-bar").getName()).isEqualTo("bar");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("2.0.0.RELEASE");
}
"
    "@Test
@Test
void repoFromBomAccordingToAnotherVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.1.5.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.1.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-biz").getName()).isEqualTo("biz");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("3.0.0.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinMavenFullBuildCustomizerTests.java
Tests:
    "@Test
@Test
void kotlinMavenPluginIsConfigured() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenFullBuildCustomizer(new SimpleKotlinProjectSettings("1.2.70", "1.6")).customize(build);
    assertThat(build.plugins().values()).singleElement().satisfies((kotlinPlugin) -> {
        assertThat(kotlinPlugin.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(kotlinPlugin.getArtifactId()).isEqualTo("kotlin-maven-plugin");
        assertThat(kotlinPlugin.getVersionReference()).isEqualTo(VersionReference.ofProperty("kotlin.version"));
        Configuration configuration = kotlinPlugin.getConfiguration();
        assertThat(configuration).isNotNull();
        assertThat(configuration.getSettings()).hasSize(3);
        Setting args = configuration.getSettings().get(0);
        assertThat(args.getName()).isEqualTo("args");
        assertThat(args.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).hasSize(1);
        assertThat(args.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).element(0).hasFieldOrPropertyWithValue("name", "arg").hasFieldOrPropertyWithValue("value", "-Xjsr305=strict");
        Setting compilerPlugins = configuration.getSettings().get(1);
        assertThat(compilerPlugins.getName()).isEqualTo("compilerPlugins");
        assertThat(compilerPlugins.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).hasSize(1);
        assertThat(compilerPlugins.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).element(0).hasFieldOrPropertyWithValue("name", "plugin").hasFieldOrPropertyWithValue("value", "spring");
        Setting jvmTarget = configuration.getSettings().get(2);
        assertThat(jvmTarget.getName()).isEqualTo("jvmTarget");
        assertThat(jvmTarget.getValue()).isEqualTo("1.6");
        assertThat(kotlinPlugin.getExecutions()).hasSize(2);
        Execution compile = kotlinPlugin.getExecutions().get(0);
        assertThat(compile.getId()).isEqualTo("compile");
        assertThat(compile.getGoals()).containsExactly("compile");
        assertThat(compile.getPhase()).isEqualTo("compile");
        assertThat(compile.getConfiguration()).isNull();
        Execution testCompile = kotlinPlugin.getExecutions().get(1);
        assertThat(testCompile.getId()).isEqualTo("test-compile");
        assertThat(testCompile.getGoals()).containsExactly("test-compile");
        assertThat(testCompile.getPhase()).isEqualTo("test-compile");
        assertThat(testCompile.getConfiguration()).isNull();
        assertThat(kotlinPlugin.getDependencies()).hasSize(1);
        Dependency allOpen = kotlinPlugin.getDependencies().get(0);
        assertThat(allOpen.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(allOpen.getArtifactId()).isEqualTo("kotlin-maven-allopen");
        assertThat(allOpen.getVersionReference()).isEqualTo(VersionReference.ofProperty("kotlin.version"));
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinJpaMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeWhenJpaFacetPresentShouldAddKotlinJpaPlugin() {
    Dependency dependency = Dependency.withId("foo");
    dependency.setFacets(Collections.singletonList("jpa"));
    MavenBuild build = getCustomizedBuild(dependency);
    assertThat(build.plugins().values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(plugin.getArtifactId()).isEqualTo("kotlin-maven-plugin");
        MavenPlugin.Setting settings = plugin.getConfiguration().getSettings().get(0);
        assertThat(settings.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).element(0).hasFieldOrPropertyWithValue("name", "plugin").hasFieldOrPropertyWithValue("value", "jpa");
        assertThat(plugin.getDependencies()).hasSize(1);
        MavenPlugin.Dependency pluginDependency = plugin.getDependencies().get(0);
        assertThat(pluginDependency.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(pluginDependency.getArtifactId()).isEqualTo("kotlin-maven-noarg");
        assertThat(pluginDependency.getVersionReference()).isEqualTo(VersionReference.ofProperty("kotlin.version"));
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDependencyTests.java
Tests:
    "@Test
@Test
void initializeFromStandardDependency() {
    Dependency original = Dependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).classifier("test-jar").type("zip").build();
    MavenDependency dependency = MavenDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getClassifier()).isEqualTo("test-jar");
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.isOptional()).isFalse();
}
"
    "@Test
@Test
void initializeFromMavenDependency() {
    Dependency original = MavenDependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).classifier("test-jar").type("zip").optional(true).build();
    MavenDependency dependency = MavenDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getClassifier()).isEqualTo("test-jar");
    assertThat(dependency.isOptional()).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleDependencyTests.java
Tests:
    "@Test
@Test
void initializeFromStandardDependency() {
    Dependency original = Dependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).type("zip").build();
    GradleDependency dependency = GradleDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getConfiguration()).isNull();
}
"
    "@Test
@Test
void initializeFromMavenDependency() {
    Dependency original = GradleDependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).type("zip").configuration("myConfiguration").build();
    GradleDependency dependency = GradleDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getConfiguration()).isEqualTo("myConfiguration");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void kotlinMavenPluginIsConfigured() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenBuildCustomizer(new SimpleKotlinProjectSettings("1.2.70")).customize(build);
    assertThat(build.plugins().values()).singleElement().satisfies((kotlinPlugin) -> {
        assertThat(kotlinPlugin.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(kotlinPlugin.getArtifactId()).isEqualTo("kotlin-maven-plugin");
        assertThat(kotlinPlugin.getVersionReference()).isNull();
        Configuration configuration = kotlinPlugin.getConfiguration();
        assertThat(configuration).isNotNull();
        assertThat(configuration.getSettings()).hasSize(2);
        Setting args = configuration.getSettings().get(0);
        assertThat(args.getName()).isEqualTo("args");
        assertThat(args.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).hasSize(1);
        assertThat(args.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).element(0).hasFieldOrPropertyWithValue("name", "arg").hasFieldOrPropertyWithValue("value", "-Xjsr305=strict");
        Setting compilerPlugins = configuration.getSettings().get(1);
        assertThat(compilerPlugins.getName()).isEqualTo("compilerPlugins");
        assertThat(compilerPlugins.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).hasSize(1);
        assertThat(compilerPlugins.getValue()).asInstanceOf(InstanceOfAssertFactories.LIST).element(0).hasFieldOrPropertyWithValue("name", "plugin").hasFieldOrPropertyWithValue("value", "spring");
        assertThat(kotlinPlugin.getExecutions()).isEmpty();
        assertThat(kotlinPlugin.getDependencies()).hasSize(1);
        Dependency allOpen = kotlinPlugin.getDependencies().get(0);
        assertThat(allOpen.getGroupId()).isEqualTo("org.jetbrains.kotlin");
        assertThat(allOpen.getArtifactId()).isEqualTo("kotlin-maven-allopen");
        assertThat(allOpen.getVersionReference()).isEqualTo(VersionReference.ofProperty("kotlin.version"));
    });
}
"
    "@Test
@Test
void kotlinMavenKotlinStdlibIsConfiguredWithKotlinOneEight() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenBuildCustomizer(new KotlinOneEightProjectSettings()).customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-stdlib");
    io.spring.initializr.generator.buildsystem.Dependency kotlinStdlib = build.dependencies().get("kotlin-stdlib");
    assertThat(kotlinStdlib.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinStdlib.getArtifactId()).isEqualTo("kotlin-stdlib");
    assertThat(kotlinStdlib.getVersion()).isNull();
    assertThat(kotlinStdlib.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void kotlinMavenKotlinStdlibJdk8IsConfiguredWithKotlinOneSeven() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenBuildCustomizer(new KotlinOneSevenProjectSettings()).customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-stdlib");
    io.spring.initializr.generator.buildsystem.Dependency kotlinStdlib = build.dependencies().get("kotlin-stdlib");
    assertThat(kotlinStdlib.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinStdlib.getArtifactId()).isEqualTo("kotlin-stdlib-jdk8");
    assertThat(kotlinStdlib.getVersion()).isNull();
    assertThat(kotlinStdlib.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/DependencyContainerTests.java
Tests:
    "@Test
@Test
void addDependency() {
    DependencyContainer container = createTestContainer();
    container.add("web", "org.springframework.boot", "spring-boot-starter-web", DependencyScope.COMPILE);
    assertThat(container.ids()).containsOnly("web");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("web")).isTrue();
    Dependency web = container.get("web");
    assertThat(web).isNotNull();
    assertThat(web.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(web.getArtifactId()).isEqualTo("spring-boot-starter-web");
    assertThat(web.getVersion()).isNull();
    assertThat(web.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void addDependencyWithVersion() {
    DependencyContainer container = createTestContainer();
    container.add("custom", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.COMPILE));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    Dependency custom = container.get("custom");
    assertThat(custom).isNotNull();
    assertThat(custom.getGroupId()).isEqualTo("com.example");
    assertThat(custom.getArtifactId()).isEqualTo("acme");
    assertThat(custom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(custom.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/DefaultProjectRequestToDescriptionConverterTests.java
Tests:
    "@Test
@Test
void convertWhenArtifactIdHasAccentCleanValue() {
    ProjectRequest request = createProjectRequest();
    request.setArtifactId("tëst-âpp");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getArtifactId()).isEqualTo("test-app");
}
"
    "@Test
@Test
void convertShouldSetGroupIdAndArtifactIdFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setArtifactId("foo");
    request.setGroupId("com.example");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getGroupId()).isEqualTo("com.example");
    assertThat(description.getArtifactId()).isEqualTo("foo");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/stat/ProjectRequestDocumentFactoryTests.java
Tests:
    "@Test
@Test
void createDocumentForSimpleProject() {
    ProjectRequest request = createProjectRequest();
    ProjectGeneratedEvent event = createProjectGeneratedEvent(request);
    ProjectRequestDocument document = this.factory.createDocument(event);
    assertThat(document.getArtifactId()).isEqualTo("demo");
    assertThat(document.getBuildSystem()).isEqualTo("maven");
    assertThat(document.getClient()).isNull();
    assertThat(document.getDependencies().getValues()).isEmpty();
    assertThat(document.getDependencies().getId()).isEqualTo("_none");
    assertThat(document.getDependencies().getCount()).isEqualTo(0);
    assertThat(document.getErrorState()).isNull();
    assertThat(document.getGenerationTimestamp()).isEqualTo(event.getTimestamp());
    assertThat(document.getGroupId()).isEqualTo("com.example");
    assertThat(document.getJavaVersion()).isEqualTo("1.8");
    assertThat(document.getLanguage()).isEqualTo("java");
    assertThat(document.getPackageName()).isEqualTo("com.example.demo");
    assertThat(document.getPackaging()).isEqualTo("jar");
    assertThat(document.getType()).isEqualTo("maven-project");
    assertThat(document.getVersion().getId()).isEqualTo("2.4.1");
    assertThat(document.getVersion().getMajor()).isEqualTo("2");
    assertThat(document.getVersion().getMinor()).isEqualTo("2.4");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/groovy/GroovyMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void groovyMavenPluginIsConfigured() {
    MavenBuild build = new MavenBuild();
    new GroovyMavenBuildCustomizer().customize(build);
    assertThat(build.plugins().values()).singleElement().satisfies((groovyPlugin) -> {
        assertThat(groovyPlugin.getGroupId()).isEqualTo("org.codehaus.gmavenplus");
        assertThat(groovyPlugin.getArtifactId()).isEqualTo("gmavenplus-plugin");
        assertThat(groovyPlugin.getVersionReference()).isEqualTo(VersionReference.ofValue("1.13.1"));
        Configuration configuration = groovyPlugin.getConfiguration();
        assertThat(configuration).isNull();
        assertThat(groovyPlugin.getExecutions()).hasSize(1);
        Execution execution = groovyPlugin.getExecutions().get(0);
        assertThat(execution.getId()).isNull();
        assertThat(execution.getGoals()).containsExactly("addSources", "addTestSources", "generateStubs", "compile", "generateTestStubs", "compileTests", "removeStubs", "removeTestStubs");
        assertThat(execution.getPhase()).isNull();
        assertThat(execution.getConfiguration()).isNull();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BomContainerTests.java
Tests:
    "@Test
@Test
void addBom() {
    BomContainer container = createTestContainer();
    container.add("root", BillOfMaterials.withCoordinates("org.springframework.boot", "spring-boot-dependencies").version(VersionReference.ofProperty("spring-boot.version")));
    assertThat(container.ids()).containsOnly("root");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("root")).isTrue();
    BillOfMaterials bom = container.get("root");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(bom.getArtifactId()).isEqualTo("spring-boot-dependencies");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofProperty("spring-boot.version"));
    assertThat(bom.getOrder()).isEqualTo(Integer.MAX_VALUE);
}
"
    "@Test
@Test
void addBomWithOrder() {
    BomContainer container = createTestContainer();
    container.add("custom", BillOfMaterials.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).order(42));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    BillOfMaterials bom = container.get("custom");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("com.example");
    assertThat(bom.getArtifactId()).isEqualTo("acme");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(bom.getOrder()).isEqualTo(42);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinJacksonBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeWhenJsonFacetPresentShouldAddJacksonKotlinModule() {
    Dependency dependency = Dependency.withId("foo");
    dependency.setFacets(Collections.singletonList("json"));
    MutableProjectDescription description = new MutableProjectDescription();
    description.setLanguage(new KotlinLanguage());
    MavenBuild build = getCustomizedBuild(dependency, description);
    io.spring.initializr.generator.buildsystem.Dependency jacksonKotlin = build.dependencies().get("jackson-module-kotlin");
    assertThat(jacksonKotlin.getArtifactId()).isEqualTo("jackson-module-kotlin");
    assertThat(jacksonKotlin.getGroupId()).isEqualTo("com.fasterxml.jackson.module");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDistributionManagementTests.java
Tests:
    "@Test
@Test
void distributionManagementWithRelocation() {
    MavenDistributionManagement mdm = builder().relocation((relocation) -> relocation.groupId("com.example.new").artifactId("project").version("1.0.0")).relocation((relocation) -> relocation.message("Moved to com.example.new")).build();
    assertThat(mdm.getRelocation().getGroupId()).isEqualTo("com.example.new");
    assertThat(mdm.getRelocation().getArtifactId()).isEqualTo("project");
    assertThat(mdm.getRelocation().getVersion()).isEqualTo("1.0.0");
    assertThat(mdm.getRelocation().getMessage()).isEqualTo("Moved to com.example.new");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/InitializrMetadataTests.java
Tests:
    "@Test
@Test
void stripInvalidCharsFromPackage() {
    InitializrMetadata metadata = initializeMetadata();
    metadata.getGroupId().setContent("org.acme");
    metadata.getArtifactId().setContent("2foo.bar");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.acme._foo.bar");
    metadata = initializeMetadata();
    metadata.getGroupId().setContent("org.ac-me");
    metadata.getArtifactId().setContent("foo-bar");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.ac_me.foo_bar");
}
"Scenario 1: Test getArtifactId when artifactId is null

Details:
  TestName: getArtifactIdWhenIsNull
  Description: The test is designed to validate the case when artifactId is null.

Execution:
  Arrange: A ProjectRequest instance is created and no value is set for the artifactId field.
  Act: The method getArtifactId is invoked on the ProjectRequest instance.
  Assert: Assert that the returned value is null.

Validation:
  This test is meant to verify that the getArtifactId method returns null when artifactId has not been previously set. This is important to ensure the method correctly handles the condition where artifactId has not been initialized.

Scenario 2: Test getArtifactId when artifactId is an empty string

Details:
  TestName: getArtifactIdWhenIsEmpty
  Description: The test is designed to validate the case when artifactId is an empty string.

Execution:
  Arrange: A ProjectRequest instance is created and an empty string is set as the artifactId.
  Act: The method getArtifactId is invoked on the ProjectRequest instance.
  Assert: Assert that the returned value is an empty string.

Validation:
  This test is meant to verify that the getArtifactId method returns an empty string when artifactId has been set as such. This is important to ensure the method correctly handles the condition where artifactId is empty.

Scenario 3: Test getArtifactId under normal conditions

Details:
  TestName: getArtifactIdNormally
  Description: The test is designed to validate the normal operation of the getArtifactId method.

Execution:
  Arrange: A ProjectRequest instance is created and a non-empty string is set as the artifactId.
  Act: The method getArtifactId is invoked on the ProjectRequest instance.
  Assert: Assert that the returned value is the non-empty string that was set.

Validation:
  This test is meant to verify that the getArtifactId method returns the correct value that was set previously under normal operating conditions. This ensures that the method functions correctly when retrieving the artifactId.
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.StringUtils;

public class ProjectRequestGetArtifactIdTest {

	@Test
	@Tag("valid")
	public void getArtifactIdWhenIsNull() {
		// Arrange
		ProjectRequest projectRequest = new ProjectRequest();
		// Act
		String actual = projectRequest.getArtifactId();
		// Assert
		Assertions.assertNull(actual);
	}

	@Test
	@Tag("valid")
	public void getArtifactIdWhenIsEmpty() {
		// Arrange
		ProjectRequest projectRequest = new ProjectRequest();
		projectRequest.setArtifactId("");
		// Act
		String actual = projectRequest.getArtifactId();
		// Assert
		Assertions.assertEquals("", actual);
	}

	@Test
	@Tag("valid")
	public void getArtifactIdNormally() {
		// Arrange
		ProjectRequest projectRequest = new ProjectRequest();
		String expected = "com.example.demo";
		projectRequest.setArtifactId(expected);
		// Act
		String actual = projectRequest.getArtifactId();
		// Assert
		Assertions.assertEquals(expected, actual);
	}

}