/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createProjectGenerator_a47c7b7d31
ROOST_METHOD_SIG_HASH=createProjectGenerator_a7f17e7a2b

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-docs/src/test/java/io/spring/initializr/doc/generator/project/ProjectGeneratorSetupExampleTests.java
Tests:
    "@Test
@Test
void generateSimpleProjectStructure(@TempDir Path tempDir) {
    StaticApplicationContext context = new StaticApplicationContext();
    context.registerBean(InitializrMetadata.class, () -> InitializrMetadataTestBuilder.withDefaults().build());
    context.registerBean(IndentingWriterFactory.class, IndentingWriterFactory::withDefaultSettings);
    context.registerBean(MustacheTemplateRenderer.class, () -> new MustacheTemplateRenderer("classpath:/templates"));
    context.refresh();
    DefaultProjectAssetGenerator assetGenerator = new DefaultProjectAssetGenerator((description) -> tempDir);
    ProjectGenerator projectGenerator = new ProjectGeneratorSetupExample().createProjectGenerator(context);
    Path directory = projectGenerator.generate(createProjectDescription(), assetGenerator);
    assertThat(directory).isSameAs(tempDir);
    Path helloFile = directory.resolve("hello.txt");
    assertThat(helloFile).exists().isRegularFile().hasContent("Test");
}
""""
  Scenario 1: Test To Check If The ProjectGenerator with null Parameter Creates a ProjectGenerator Object

  Details:
    TestName: testCreateProjectGeneratorWithNullParameter.
    Description: This test is meant to check the correct functioning of the 'createProjectGenerator' method by passing a null parameter as 'metadata'.
  Execution:
    Arrange: Create a null instance for the 'InitializrMetadata' type, which would act as the argument.
    Act: Execute the 'createProjectGenerator' method with the null argument created in the arrange step.
    Assert: Check if the returned 'ProjectGenerator' object is also null as the method parameters were null.
  Validation:
    This assertion verifies whether the 'createProjectGenerator' method correctly handles the null values provided as an argument and if it accordingly returns a null object. This test is significant as handling null values is critical for preventing runtime errors related to the null object reference.

  Scenario 2: Test To Check If The ProjectGenerator with proper Parameter Creates a ProjectGenerator Object

  Details:
    TestName: testCreateProjectGeneratorWithProperParameter.
    Description: This test is meant to check that the 'createProjectGenerator' method creates the 'ProjectGenerator' object correctly when given valid 'InitializrMetadata'.
  Execution:
    Arrange: Create a 'InitializrMetadata' object with valid data to pass as an argument to the 'createProjectGenerator' method.
    Act: Execute the 'createProjectGenerator' method with the mock 'InitializrMetadata' object created in the Arrange step.
    Assert: Check that the returned 'ProjectGenerator' object is not null.
  Validation:
    This assertion verifies whether the 'createProjectGenerator' method on given valid parameters, creates a 'ProjectGenerator' object correctly. This is crucial to verify that the 'createProjectGenerator' method behaves as expected when given valid data.

  Scenario 3: Test the Exception Handling of createProjectGenerator Method

  Details:
    TestName: testCreateProjectGeneratorExceptionHandling.
    Description: This test is intended to check if the 'createProjectGenerator' method handles possible thrown exceptions correctly.
  Execution:
    Arrange: Work with a mock 'InitializrMetadata' object prepared in such a way that it will cause the 'createProjectGenerator' method to throw an exception.
    Act: Call the 'createProjectGenerator' method with the mock 'InitializrMetadata' object created in the Arrange step.
    Assert: Use JUnit's assertThrows to verify whether the 'createProjectGenerator' method throws an appropriate exception.
  Validation:
    The aim of this assertion is to verify the correct exception is thrown by the 'createProjectGenerator' method under special circumstances. It's imperative to ensure exception handling in order to prevent the application from breaking in error situations.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.generator.project.ProjectGenerator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import io.spring.initializr.generator.buildsystem.BuildItemResolver;
import io.spring.initializr.generator.buildsystem.BuildWriter;
import io.spring.initializr.generator.project.DefaultProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationContext;
import io.spring.initializr.generator.project.ProjectGenerationException;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.support.MetadataBuildItemResolver;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.util.FileSystemUtils;

public class ProjectGenerationInvokerCreateProjectGeneratorTest {

	private final ProjectGenerationInvoker testProjectGenerationInvoker = new ProjectGenerationInvoker();

	@Test
	@Tag("invalid")
	public void testCreateProjectGeneratorWithNullParameter() {
		Assertions.assertNull(testProjectGenerationInvoker.createProjectGenerator(null),
				"Test failed - Expected null when called with null argument");
	}

	@Test
	@Tag("valid")
	public void testCreateProjectGeneratorWithProperParameter() {
		InitializrMetadata mockInitializrMetadata = Mockito.mock(InitializrMetadata.class);
		ProjectGenerator resultProjectGenerator = testProjectGenerationInvoker
			.createProjectGenerator(mockInitializrMetadata);
		Assertions.assertNotNull(resultProjectGenerator,
				"Test failed - createProjectGenerator method did not create ProjectGenerator object with valid metadata");
	}

	@Test
	@Tag("valid")
	@Tag("boundary")
	public void testCreateProjectGeneratorExceptionHandling() {
		InitializrMetadata mockInitializrMetadata = Mockito.mock(InitializrMetadata.class);
		Mockito.when(mockInitializrMetadata.someMethodThatThrowsException()).thenThrow(new RuntimeException());
		Assertions.assertThrows(RuntimeException.class,
				() -> testProjectGenerationInvoker.createProjectGenerator(mockInitializrMetadata),
				"Test failed - Expected RuntimeException to be thrown with invalid metadata");
	}

}