/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getBootVersion_ab83ecc646
ROOST_METHOD_SIG_HASH=getBootVersion_2c72ad7d51

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/support/DefaultDependencyMetadataProviderTests.java
Tests:
    "@Test
@Test
void repoFromBomAccordingToVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.0.9.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.0.9.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-bar").getName()).isEqualTo("bar");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("2.0.0.RELEASE");
}
"
    "@Test
@Test
void repoFromBomAccordingToAnotherVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.1.5.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.1.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-biz").getName()).isEqualTo("biz");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("3.0.0.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void invokeBuildGenerationForMavenBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new MavenBuildAssert(content).hasGroupId(request.getGroupId()).hasArtifactId(request.getArtifactId()).hasVersion(request.getVersion()).doesNotHaveNode("/project/packaging").hasName(request.getName()).hasDescription(request.getDescription()).hasProperty("java.version", request.getJavaVersion()).hasParent("org.springframework.boot", "spring-boot-starter-parent", request.getBootVersion());
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationForGradleBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    request.setJavaVersion("17");
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new GroovyDslGradleBuildAssert(content).hasVersion(request.getVersion()).hasPlugin("org.springframework.boot", request.getBootVersion()).hasToolchainForJava("17");
    verifyProjectSuccessfulEventFor(request);
}
"Scenario 1: Test to Check if the Boot Version is Returned Correctly

Details:
    TestName: testGetBootVersionCorrectly
    Description: This test is to validate that the method getBootVersion() returns the correct boot version - that has been previously set using the setBootVersion() method.
Execution:
    Arrange: Create a new ProjectRequest object and set the boot version to "2.3.1" using setBootVersion().
    Act: Call the getBootVersion() method.
    Assert: Assert that the returned string equals "2.3.1".
Validation:
    The assertion verifies that the getBootVersion() method accurately retrieves the boot version set by setBootVersion(). Successful passing of this test ensures the method is retrieving the appropriate return value from the object instance.

Scenario 2: Test to Check if the Boot Version Returns Null when Nothing is Set

Details:
    TestName: testGetBootVersionNotSet
    Description: This test is to validate that the method getBootVersion() returns null if no boot version has been set.
Execution:
    Arrange: Create a new ProjectRequest object without setting the boot version.
    Act: Call the getBootVersion() method.
    Assert: Assert that the returned string is null.
Validation:
    The assertion verifies that the getBootVersion() correctly returns null when no boot version has been set. This test ensures that the getBootVersion() method responds as expected in scenarios where setBootVersion() has not been invoked.

Scenario 3: Test to Check if the Boot Version is Returned Correctly after Changing the Value

Details:
    TestName: testGetBootVersionAfterChange
    Description: This test is to validate that the method getBootVersion() returns the latest set boot version after its value has been modified.
Execution:
    Arrange: Create a new ProjectRequest object and set the boot version to "2.3.1" using setBootVersion(). Change the boot version to "2.4.0" using setBootVersion().
    Act: Call the getBootVersion() method.
    Assert: Assert that the returned string equals "2.4.0".
Validation:
    The assertion verifies that the getBootVersion() method retrieves the latest attribute value even after multiple invocations of its corresponding setter. This test supports the logic that the method always retrieves the latest state of the object instance.

*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.StringUtils;

public class ProjectRequestGetBootVersionTest {

	@Tag("valid")
	@Test
	public void testGetBootVersionCorrectly() {
		ProjectRequest projectRequest = new ProjectRequest();
		projectRequest.setBootVersion("2.3.1");

		String actualBootVersion = projectRequest.getBootVersion();
		assertEquals("2.3.1", actualBootVersion, "Boot version should be 2.3.1");
	}

	@Tag("boundary")
	@Test
	public void testGetBootVersionNotSet() {
		ProjectRequest projectRequest = new ProjectRequest();

		String actualBootVersion = projectRequest.getBootVersion();
		assertNull(actualBootVersion, "Boot version should be null when not set");
	}

	@Tag("valid")
	@Test
	public void testGetBootVersionAfterChange() {
		ProjectRequest projectRequest = new ProjectRequest();
		projectRequest.setBootVersion("2.3.1");
		projectRequest.setBootVersion("2.4.0");

		String actualBootVersion = projectRequest.getBootVersion();
		assertEquals("2.4.0", actualBootVersion, "Boot version should be updated to 2.4.0");
	}

}