/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getProjectRequest_4deadfa269
ROOST_METHOD_SIG_HASH=getProjectRequest_42c43c1c93

"""
Scenario 1: Test to validate the getProjectRequest method with a non-null request object

Details:
  TestName: validateNonNullProjectRequest.
  Description: This test will check if getProjectRequest method is correctly returning a non-null request object.
Execution:
  Arrange: Instantiate ProjectRequest and populate the request object.
  Act: Invoke getProjectRequest method.
  Assert: Verify that the return value matches the expected (non-null) request object.
Validation:
  The assertion verifies that the request object returned by getProjectRequest method is correct and not null. It verifies that the getter method is correctly retrieving the stored request.


Scenario 2: Test to check the getProjectRequest method with a null request object

Details:
  TestName: validateNullProjectRequest.
  Description: This test is meant to check the behavior of getProjectRequest method when the request object is null.
Execution:
  Arrange: Instantiate ProjectRequest without setting up the request object, thus making it null.
  Act: Invoke getProjectRequest method.
  Assert: Verify that the return value is null.
Validation:
  The assertion verifies that getProjectRequest method returns null when the request object is null. This ensures that the getter method handles null values appropriately.


Scenario 3: Test to assert the immutability of getProjectRequest

Details:
  TestName: validateImmutabilityOfProjectRequest.
  Description: This test is meant to ensure that getProjectRequest returns a copy of the request object and not the original one to achieve immutability.
Execution:
  Arrange: Instantiate ProjectRequest and populate the request object. Keep a copy of original request object for comparison.
  Act: Invoke getProjectRequest method. Modify the returned object.
  Assert: Verify that the original request object has not been altered.
Validation:
  The assertion validates that the getProjectRequest method is designed for immutability, thus allowing the request object to be read but not modified.

"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.spring.initializr.metadata.InitializrMetadata;
import java.util.ArrayList;
import org.junit.jupiter.api.*;

public class ProjectRequestEventGetProjectRequestTest {

	@Test
	@Tag("valid")
	public void validateNonNullProjectRequest() {
		ProjectRequest projectRequest = new ProjectRequest();
		projectRequest.setDependencies(new ArrayList<>());
		projectRequest.setName("Non-null request");
		InitializrMetadata metadata = new InitializrMetadata();

		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(projectRequest, metadata);

		ProjectRequest retrievedRequest = projectRequestEvent.getProjectRequest();

		assertNotNull(retrievedRequest);
		assertSame(projectRequest, retrievedRequest);
	}

	@Test
	@Tag("invalid")
	public void validateNullProjectRequest() {
		ProjectRequest projectRequest = null;
		InitializrMetadata metadata = new InitializrMetadata();

		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(projectRequest, metadata);

		ProjectRequest retrievedRequest = projectRequestEvent.getProjectRequest();

		assertNull(retrievedRequest);
	}

	@Test
	@Tag("boundary")
	public void validateImmutabilityOfProjectRequest() {
		ProjectRequest projectRequest = new ProjectRequest();
		projectRequest.setDependencies(new ArrayList<>());
		projectRequest.setName("Test request");

		InitializrMetadata metadata = new InitializrMetadata();
		ProjectRequestEvent projectRequestEvent = new ProjectRequestEvent(projectRequest, metadata);

		ProjectRequest retrievedRequest = projectRequestEvent.getProjectRequest();

		assertNotSame(projectRequest, retrievedRequest);

		// Change value in retrieved request
		retrievedRequest.setName("Changed value");

		// Assert original value has not changed
		assertEquals("Test request", projectRequest.getName());
	}

}