/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getVersion_6fe22325c9
ROOST_METHOD_SIG_HASH=getVersion_a44ba39179

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/InitializrMetadataBuilderTests.java
Tests:
    "@Test
@Test
void mergeConfig() {
    InitializrProperties config = load(new ClassPathResource("application-test-default.yml"));
    InitializrProperties customDefaultsConfig = load(new ClassPathResource("application-test-custom-defaults.yml"));
    InitializrMetadata metadata = InitializrMetadataBuilder.fromInitializrProperties(config).withInitializrProperties(customDefaultsConfig).build();
    assertDefaultConfig(metadata);
    assertThat(metadata.getGroupId().getContent()).isEqualTo("org.foo");
    assertThat(metadata.getArtifactId().getContent()).isEqualTo("foo-bar");
    assertThat(metadata.getVersion().getContent()).isEqualTo("1.2.4-SNAPSHOT");
    assertThat(metadata.getName().getContent()).isEqualTo("FooBar");
    assertThat(metadata.getDescription().getContent()).isEqualTo("FooBar Project");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.foo.demo");
}
"
    "@Test
@Test
void mergeMetadata() {
    InitializrMetadata metadata = InitializrMetadataBuilder.create().withInitializrMetadata(new ClassPathResource("metadata/config/test-min.json")).build();
    assertThat(metadata.getConfiguration().getEnv().isForceSsl()).isEqualTo(true);
    assertThat(metadata.getDependencies().getContent()).hasSize(1);
    Dependency dependency = metadata.getDependencies().get("test");
    assertThat(dependency).isNotNull();
    assertThat(dependency.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(metadata.getTypes().getContent()).hasSize(1);
    assertThat(metadata.getBootVersions().getContent()).hasSize(2);
    assertThat(metadata.getPackagings().getContent()).hasSize(2);
    assertThat(metadata.getJavaVersions().getContent()).hasSize(1);
    assertThat(metadata.getLanguages().getContent()).hasSize(3);
    assertThat(metadata.getName().getContent()).isEqualTo("metadata-merge");
    assertThat(metadata.getDescription().getContent()).isEqualTo("Demo project for metadata merge");
    assertThat(metadata.getGroupId().getContent()).isEqualTo("org.acme");
    assertThat(metadata.getArtifactId().getContent()).isEqualTo("metadata");
    assertThat(metadata.getVersion().getContent()).isEqualTo("1.0.0-SNAPSHOT");
    assertThat(metadata.getPackageName().getContent()).isEqualTo("org.acme.demo");
}
"
    "@Test
@Test
void mergeMetadataWithBom() {
    InitializrMetadata metadata = InitializrMetadataBuilder.create().withInitializrMetadata(new ClassPathResource("metadata/config/test-bom.json")).build();
    Map<String, BillOfMaterials> boms = metadata.getConfiguration().getEnv().getBoms();
    assertThat(boms).hasSize(2);
    BillOfMaterials myBom = boms.get("my-bom");
    assertThat(myBom).isNotNull();
    assertThat(myBom.getGroupId()).isEqualTo("org.acme");
    assertThat(myBom.getArtifactId()).isEqualTo("my-bom");
    assertThat(myBom.getVersion()).isEqualTo("2.4.1");
    BillOfMaterials anotherBom = boms.get("another-bom");
    assertThat(anotherBom).isNotNull();
    assertThat(anotherBom.getGroupId()).isEqualTo("org.acme");
    assertThat(anotherBom.getArtifactId()).isEqualTo("another-bom");
    assertThat(anotherBom.getVersion()).isEqualTo("4.5.6.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/ProjectGeneratorIntegrationTests.java
Tests:
    "@Test
private MutableProjectDescription initProjectDescription() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setApplicationName("DemoApplication");
    description.setPlatformVersion(Version.parse(SpringBootVersion.getVersion()));
    description.setLanguage(new JavaLanguage(JAVA_VERSION));
    description.setGroupId("com.example");
    return description;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/support/AgentTests.java
Tests:
    "@Test
@Test
void checkCurl() {
    Agent agent = Agent.fromUserAgent("curl/1.2.4");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.CURL);
    assertThat(agent.getVersion()).isEqualTo("1.2.4");
}
"
    "@Test
@Test
void checkHttpie() {
    Agent agent = Agent.fromUserAgent("HTTPie/0.8.0");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.HTTPIE);
    assertThat(agent.getVersion()).isEqualTo("0.8.0");
}
"
    "@Test
@Test
void checkJBossForge() {
    Agent agent = Agent.fromUserAgent("SpringBootForgeCli/1.0.0.Alpha4");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.JBOSS_FORGE);
    assertThat(agent.getVersion()).isEqualTo("1.0.0.Alpha4");
}
"
    "@Test
@Test
void checkSpringBootCli() {
    Agent agent = Agent.fromUserAgent("SpringBootCli/1.3.1.RELEASE");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.SPRING_BOOT_CLI);
    assertThat(agent.getVersion()).isEqualTo("1.3.1.RELEASE");
}
"
    "@Test
@Test
void checkSts() {
    Agent agent = Agent.fromUserAgent("STS 3.7.0.201506251244-RELEASE");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.STS);
    assertThat(agent.getVersion()).isEqualTo("3.7.0.201506251244-RELEASE");
}
"
    "@Test
@Test
void checkIntelliJIDEA() {
    Agent agent = Agent.fromUserAgent("IntelliJ IDEA");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.INTELLIJ_IDEA);
    assertThat(agent.getVersion()).isNull();
}
"
    "@Test
@Test
void checkIntelliJIDEAWithVersion() {
    Agent agent = Agent.fromUserAgent("IntelliJ IDEA/144.2 (Community edition; en-us)");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.INTELLIJ_IDEA);
    assertThat(agent.getVersion()).isEqualTo("144.2");
}
"
    "@Test
@Test
void checkNetBeans() {
    Agent agent = Agent.fromUserAgent("nb-springboot-plugin/0.1");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.NETBEANS);
    assertThat(agent.getVersion()).isEqualTo("0.1");
}
"
    "@Test
@Test
void checkVsCode() {
    Agent agent = Agent.fromUserAgent("vscode/0.2.0");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.VSCODE);
    assertThat(agent.getVersion()).isEqualTo("0.2.0");
}
"
    "@Test
@Test
void checkJenkinsX() {
    Agent agent = Agent.fromUserAgent("jx/1.1.71");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.JENKINSX);
    assertThat(agent.getVersion()).isEqualTo("1.1.71");
}
"
    "@Test
@Test
void checkNx() {
    Agent agent = Agent.fromUserAgent("@nxrocks_nx-spring-boot/1.0.0");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.NX);
    assertThat(agent.getVersion()).isEqualTo("1.0.0");
}
"
    "@Test
@Test
void checkGenericBrowser() {
    Agent agent = Agent.fromUserAgent("Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MMB29K) ");
    assertThat(agent.getId()).isEqualTo(Agent.AgentId.BROWSER);
    assertThat(agent.getVersion()).isNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/DependencyTests.java
Tests:
    "@Test
@Test
void setCoordinatesFromId() {
    Dependency dependency = Dependency.withId("org.foo:bar:1.2.3");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.foo");
    assertThat(dependency.getArtifactId()).isEqualTo("bar");
    assertThat(dependency.getVersion()).isEqualTo("1.2.3");
    assertThat(dependency.getId()).isEqualTo("org.foo:bar:1.2.3");
}
"
    "@Test
@Test
void setCoordinatesFromIdNoVersion() {
    Dependency dependency = Dependency.withId("org.foo:bar");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.foo");
    assertThat(dependency.getArtifactId()).isEqualTo("bar");
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getId()).isEqualTo("org.foo:bar");
}
"
    "@Test
@Test
void setIdFromSimpleName() {
    Dependency dependency = Dependency.withId("web");
    dependency.resolve();
    assertThat(dependency.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(dependency.getArtifactId()).isEqualTo("spring-boot-starter-web");
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getId()).isEqualTo("web");
}
"
    "@Test
private static void validateResolvedDependency(Dependency dependency, String id, String expectedGroupId, String expectedArtifactId, String expectedVersion, boolean expectedStarter, String expectedBom, String expectedRepository) {
    assertThat(dependency.getId()).isEqualTo(id);
    assertThat(dependency.getGroupId()).isEqualTo(expectedGroupId);
    assertThat(dependency.getArtifactId()).isEqualTo(expectedArtifactId);
    assertThat(dependency.getVersion()).isEqualTo(expectedVersion);
    assertThat(dependency.isStarter()).isEqualTo(expectedStarter);
    assertThat(dependency.getBom()).isEqualTo(expectedBom);
    assertThat(dependency.getRepository()).isEqualTo(expectedRepository);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/BillOfMaterialsTests.java
Tests:
    "@Test
@Test
void resolveSimpleRange() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("bom.version");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    bom.getMappings().add(Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0"));
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("bom.version");
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-main");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-main");
}
"
    "@Test
@Test
void resolveSimpleRangeWithGroupIdArtifactId() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("bom.version");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    Mapping mapping = Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0");
    mapping.setGroupId("com.example.override");
    mapping.setArtifactId("bom-override");
    bom.getMappings().add(mapping);
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example.override");
    assertThat(resolved.getArtifactId()).isEqualTo("bom-override");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("bom.version");
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-main");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-main");
}
"
    "@Test
@Test
void resolveRangeOverride() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.getRepositories().add("repo-main");
    bom.getAdditionalBoms().add("bom-main");
    Mapping mapping = Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0", "repo-foo");
    mapping.getAdditionalBoms().add("bom-foo");
    bom.getMappings().add(mapping);
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty()).isNull();
    assertThat(resolved.getRepositories()).hasSize(1);
    assertThat(resolved.getRepositories().get(0)).isEqualTo("repo-foo");
    assertThat(resolved.getAdditionalBoms()).hasSize(1);
    assertThat(resolved.getAdditionalBoms().get(0)).isEqualTo("bom-foo");
}
"
    "@Test
@Test
void resolveRangeOverrideAndMapping() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.setVersionProperty("example.version");
    bom.getMappings().add(Mapping.create("[1.2.0.RELEASE,1.3.0.M1)", "1.1.0"));
    bom.validate();
    BillOfMaterials resolved = bom.resolve(Version.parse("1.2.3.RELEASE"));
    assertThat(resolved.getGroupId()).isEqualTo("com.example");
    assertThat(resolved.getArtifactId()).isEqualTo("bom");
    assertThat(resolved.getVersion()).isEqualTo("1.1.0");
    assertThat(resolved.getVersionProperty().toStandardFormat()).isEqualTo("example.version");
}
"
    "@Test
@Test
void resolveRangeWithVariablePatch() {
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "1.0.0");
    bom.getMappings().add(Mapping.create("[1.3.0.RELEASE,1.3.x.RELEASE]", "1.1.0"));
    bom.getMappings().add(BillOfMaterials.Mapping.create("[1.3.x.BUILD-SNAPSHOT,1.4.0.RELEASE)", "1.1.1-SNAPSHOT"));
    bom.validate();
    bom.updateCompatibilityRange(new VersionParser(Arrays.asList(Version.parse("1.3.8.RELEASE"), Version.parse("1.3.9.BUILD-SNAPSHOT"))));
    assertThat(bom.resolve(Version.parse("1.3.8.RELEASE")).getVersion()).isEqualTo("1.1.0");
    assertThat(bom.resolve(Version.parse("1.3.9.RELEASE")).getVersion()).isEqualTo("1.1.1-SNAPSHOT");
    bom.updateCompatibilityRange(new VersionParser(Arrays.asList(Version.parse("1.3.9.RELEASE"), Version.parse("1.3.10.BUILD-SNAPSHOT"))));
    assertThat(bom.resolve(Version.parse("1.3.8.RELEASE")).getVersion()).isEqualTo("1.1.0");
    assertThat(bom.resolve(Version.parse("1.3.9.RELEASE")).getVersion()).isEqualTo("1.1.0");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinJpaGradleBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeWhenJpaFacetPresentShouldAddKotlinJpaPlugin() {
    Dependency dependency = Dependency.withId("foo");
    dependency.setFacets(Collections.singletonList("jpa"));
    GradleBuild build = getCustomizedBuild(dependency);
    assertThat(build.plugins().values().filter(GradlePlugin::isApply)).isEmpty();
    assertThat(build.plugins().values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getId()).isEqualTo("org.jetbrains.kotlin.plugin.jpa");
        assertThat(((StandardGradlePlugin) plugin).getVersion()).isEqualTo("1.2.70");
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinDependenciesConfigurerTests.java
Tests:
    "@Test
@Test
void configuresDependenciesForGradleBuild() {
    GradleBuild build = new GradleBuild();
    new KotlinDependenciesConfigurer().customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-reflect", "kotlin-test-junit5");
    Dependency kotlinReflect = build.dependencies().get("kotlin-reflect");
    assertThat(kotlinReflect.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinReflect.getArtifactId()).isEqualTo("kotlin-reflect");
    assertThat(kotlinReflect.getVersion()).isNull();
    Dependency kotlinTest = build.dependencies().get("kotlin-test-junit5");
    assertThat(kotlinTest.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinTest.getArtifactId()).isEqualTo("kotlin-test-junit5");
    assertThat(kotlinTest.getScope()).isEqualTo(DependencyScope.TEST_COMPILE);
    assertThat(kotlinTest.getVersion()).isNull();
}
"
    "@Test
@Test
void configuresDependenciesForMavenBuild() {
    MavenBuild build = new MavenBuild();
    new KotlinDependenciesConfigurer().customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-reflect", "kotlin-test-junit5");
    Dependency kotlinReflect = build.dependencies().get("kotlin-reflect");
    assertThat(kotlinReflect.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinReflect.getArtifactId()).isEqualTo("kotlin-reflect");
    assertThat(kotlinReflect.getVersion()).isNull();
    Dependency kotlinTest = build.dependencies().get("kotlin-test-junit5");
    assertThat(kotlinTest.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinTest.getArtifactId()).isEqualTo("kotlin-test-junit5");
    assertThat(kotlinTest.getScope()).isEqualTo(DependencyScope.TEST_COMPILE);
    assertThat(kotlinTest.getVersion()).isNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/MetadataProjectDescriptionCustomizerTests.java
Tests:
    "@Test
@Test
void customizeShouldUseDefaultFromMetadataOnEmptyVersion() {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setVersion("  ");
    assertThat(customize(description).getVersion()).isEqualTo("0.0.1-SNAPSHOT");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void invokeBuildGenerationForMavenBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new MavenBuildAssert(content).hasGroupId(request.getGroupId()).hasArtifactId(request.getArtifactId()).hasVersion(request.getVersion()).doesNotHaveNode("/project/packaging").hasName(request.getName()).hasDescription(request.getDescription()).hasProperty("java.version", request.getJavaVersion()).hasParent("org.springframework.boot", "spring-boot-starter-parent", request.getBootVersion());
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationForGradleBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    request.setJavaVersion("17");
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new GroovyDslGradleBuildAssert(content).hasVersion(request.getVersion()).hasPlugin("org.springframework.boot", request.getBootVersion()).hasToolchainForJava("17");
    verifyProjectSuccessfulEventFor(request);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/support/MetadataBuildItemResolverTests.java
Tests:
    "@Test
@Test
void resoleDependencyWithMatchingEntry() {
    InitializrMetadata metadata = new InitializrMetadata();
    DependencyGroup group = DependencyGroup.create("test");
    Dependency target = Dependency.withId("test-dep", "com.example", "test", "1.0.0", "runtime");
    target.setClassifier("test-jar");
    group.getContent().add(target);
    metadata.getDependencies().getContent().add(group);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.Dependency dependency = resolver.resolveDependency("test-dep");
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).hasToString("1.0.0");
    assertThat(dependency.getClassifier()).hasToString("test-jar");
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
}
"
    "@Test
@Test
void resoleDependencyWithMatchingEntryAndCompatibilityRange() {
    InitializrMetadata metadata = new InitializrMetadata();
    DependencyGroup group = DependencyGroup.create("test");
    Dependency dependency = Dependency.withId("test-dep", "com.example", "test");
    dependency.getMappings().add(Mapping.create("[1.0.0.RELEASE, 2.0.0.RELEASE)", null, null, "1.0.0.RELEASE", null, null, null));
    dependency.getMappings().add(Mapping.create("2.0.0.RELEASE", "com.example.override", "test-override", null, null, null, null));
    group.getContent().add(dependency);
    metadata.getDependencies().getContent().add(group);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.Dependency resolveDependency = resolver.resolveDependency("test-dep");
    assertThat(resolveDependency.getGroupId()).isEqualTo("com.example.override");
    assertThat(resolveDependency.getArtifactId()).isEqualTo("test-override");
    assertThat(resolveDependency.getVersion()).isNull();
    assertThat(resolveDependency.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void resoleBomWithMatchingEntry() {
    InitializrMetadata metadata = new InitializrMetadata();
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "2.0.0");
    metadata.getConfiguration().getEnv().getBoms().put("test-bom", bom);
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.BillOfMaterials resolvedBom = resolver.resolveBom("test-bom");
    assertThat(resolvedBom.getGroupId()).isEqualTo("com.example");
    assertThat(resolvedBom.getArtifactId()).isEqualTo("bom");
    assertThat(resolvedBom.getVersion()).hasToString("2.0.0");
}
"
    "@Test
@Test
void resoleBomWithMatchingEntryAndCompatibilityRange() throws MalformedURLException {
    InitializrMetadata metadata = new InitializrMetadata();
    BillOfMaterials bom = BillOfMaterials.create("com.example", "bom", "0.0.1");
    bom.getMappings().add(BillOfMaterials.Mapping.create("[1.0.0.RELEASE, 2.0.0.RELEASE)", "1.0.0"));
    bom.getMappings().add(BillOfMaterials.Mapping.create("2.0.0.RELEASE", "1.1.0"));
    metadata.getConfiguration().getEnv().getBoms().put("test-bom", bom);
    metadata.getConfiguration().getEnv().getRepositories().put("test-repo", new Repository("test", new URL("https:
    metadata.validate();
    MetadataBuildItemResolver resolver = new MetadataBuildItemResolver(metadata, VERSION_2_0_0);
    io.spring.initializr.generator.buildsystem.BillOfMaterials resolvedBom = resolver.resolveBom("test-bom");
    assertThat(resolvedBom.getGroupId()).isEqualTo("com.example");
    assertThat(resolvedBom.getArtifactId()).isEqualTo("bom");
    assertThat(resolvedBom.getVersion()).hasToString("1.1.0");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinProjectGenerationConfigurationTests.java
Tests:
    "@Test
@Test
void kotlinVersionFallbacksToMetadataIfNotPresent() {
    this.projectTester.configure(new MutableProjectDescription(), (context) -> assertThat(context.getBean(KotlinProjectSettings.class).getVersion()).isEqualTo("1.1.1"));
}
"
    "@Test
@Test
void kotlinVersionResolverIsUsedIfPresent() {
    this.projectTester.withBean(KotlinVersionResolver.class, () -> (description) -> "0.9.12").configure(new MutableProjectDescription(), (context) -> assertThat(context.getBean(KotlinProjectSettings.class).getVersion()).isEqualTo("0.9.12"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenProfileActivationTests.java
Tests:
    "@Test
@Test
void profileActivationOs() {
    Os os = createProfileActivation().os("test-name", null, "arm64", null).build().getOs();
    assertThat(os).isNotNull();
    assertThat(os.getName()).isEqualTo("test-name");
    assertThat(os.getFamily()).isNull();
    assertThat(os.getArch()).isEqualTo("arm64");
    assertThat(os.getVersion()).isNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/DefaultMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeWhenNoParentShouldUseSpringBootParent() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().build();
    MavenBuild build = customizeBuild(metadata);
    MavenParent parent = build.getSettings().getParent();
    assertThat(parent.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(parent.getArtifactId()).isEqualTo("spring-boot-starter-parent");
    assertThat(parent.getVersion()).isEqualTo("2.0.0");
    assertThat(parent.getRelativePath()).isEmpty();
}
"
    "@Test
@Test
void customizeWithCustomParentAndSpringBootBomShouldAddBom() {
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().setMavenParent("com.foo", "foo-parent", "1.0.0-SNAPSHOT", "../pom.xml", true).build();
    MavenBuild build = customizeBuild(metadata);
    MavenParent parent = build.getSettings().getParent();
    assertThat(parent.getGroupId()).isEqualTo("com.foo");
    assertThat(parent.getArtifactId()).isEqualTo("foo-parent");
    assertThat(parent.getVersion()).isEqualTo("1.0.0-SNAPSHOT");
    assertThat(parent.getRelativePath()).isEqualTo("../pom.xml");
    BomContainer boms = build.boms();
    assertThat(boms.items()).hasSize(1);
    assertThat(boms.ids()).contains("spring-boot");
    assertThat(build.properties().versions(VersionProperty::toStandardFormat)).contains(entry("spring-boot.version", "2.0.0"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/DependencyTests.java
Tests:
    "@Test
@Test
void dependencyWithCoordinatesOnly() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithScopeAndVersionValue() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").scope(DependencyScope.RUNTIME).version(VersionReference.ofValue("1.0.0")).build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getVersion().getValue()).isEqualTo("1.0.0");
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithClassifier() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").classifier("test").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isEqualTo("test");
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithType() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").type("test-zip").build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isEqualTo("test-zip");
    assertThat(dependency.getExclusions()).isEmpty();
}
"
    "@Test
@Test
void dependencyWithExclusions() {
    Dependency dependency = Dependency.withCoordinates("com.example", "acme").exclusions(new Exclusion("com.example", "exclude1"), new Exclusion("com.example", "exclude2")).build();
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("acme");
    assertThat(dependency.getScope()).isNull();
    assertThat(dependency.getVersion()).isNull();
    assertThat(dependency.getClassifier()).isNull();
    assertThat(dependency.getType()).isNull();
    assertThat(dependency.getExclusions()).containsExactly(new Exclusion("com.example", "exclude1"), new Exclusion("com.example", "exclude2"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/BuildMetadataResolverTests.java
Tests:
    "@Test
@Test
void shouldResolveDependenciesAgainstMapping() {
    Dependency web = Dependency.withId("web", "group", "artifact");
    web.setMappings(List.of(Dependency.Mapping.create("[1.0.0,2.0.0)", null, null, "1.0.0", null, null, null), Dependency.Mapping.create("[2.0.0,3.0.0)", null, null, "2.0.0", null, null, null)));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("web", web).build();
    Build build = createBuild(metadata);
    build.dependencies().add("web");
    BuildMetadataResolver resolver = new BuildMetadataResolver(metadata, Version.parse("1.0.0"));
    assertThat(resolver.dependencies(build)).singleElement().satisfies((dependency) -> assertThat(dependency.getVersion()).isEqualTo("1.0.0"));
    resolver = new BuildMetadataResolver(metadata, Version.parse("2.0.0"));
    assertThat(resolver.dependencies(build)).singleElement().satisfies((dependency) -> assertThat(dependency.getVersion()).isEqualTo("2.0.0"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/support/DefaultDependencyMetadataProviderTests.java
Tests:
    "@Test
@Test
void resolveDependencies() {
    Dependency first = Dependency.withId("first", "org.foo", "first");
    first.getMappings().add(Dependency.Mapping.create("[1.0.0.RELEASE, 1.1.0.RELEASE)", "org.bar", "second", "0.1.0.RELEASE", null, null, null));
    first.getMappings().add(Dependency.Mapping.create("1.1.0.RELEASE", "org.biz", "third", "0.2.0.RELEASE", null, null, null));
    Dependency second = Dependency.withId("second", "org.foo", "second");
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", first, second).build();
    DependencyMetadata dependencyMetadata = this.provider.get(metadata, Version.parse("1.0.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(2);
    assertThat(dependencyMetadata.getDependencies().get("first").getGroupId()).isEqualTo("org.bar");
    assertThat(dependencyMetadata.getDependencies().get("first").getArtifactId()).isEqualTo("second");
    assertThat(dependencyMetadata.getDependencies().get("first").getVersion()).isEqualTo("0.1.0.RELEASE");
    DependencyMetadata anotherDependencyMetadata = this.provider.get(metadata, Version.parse("1.1.0.RELEASE"));
    assertThat(anotherDependencyMetadata.getDependencies()).hasSize(2);
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getGroupId()).isEqualTo("org.biz");
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getArtifactId()).isEqualTo("third");
    assertThat(anotherDependencyMetadata.getDependencies().get("first").getVersion()).isEqualTo("0.2.0.RELEASE");
}
"
    "@Test
@Test
void addBomAndRemoveDuplicates() {
    Dependency first = Dependency.withId("first", "org.foo", "first");
    first.setBom("bom-foo");
    Dependency second = Dependency.withId("second", "org.foo", "second");
    Dependency third = Dependency.withId("third", "org.foo", "third");
    third.setBom("bom-foo");
    BillOfMaterials bom = BillOfMaterials.create("org.foo", "bom");
    bom.getMappings().add(BillOfMaterials.Mapping.create("[1.0.0.RELEASE, 1.1.8.RELEASE)", "1.0.0.RELEASE"));
    bom.getMappings().add(BillOfMaterials.Mapping.create("1.1.8.RELEASE", "2.0.0.RELEASE"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addBom("bom-foo", bom).addDependencyGroup("test", first, second, third).build();
    DependencyMetadata dependencyMetadata = this.provider.get(metadata, Version.parse("1.1.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).isEmpty();
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("1.0.0.RELEASE");
}
"
    "@Test
@Test
void repoFromBomAccordingToVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.0.9.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.0.9.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-bar").getName()).isEqualTo("bar");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("2.0.0.RELEASE");
}
"
    "@Test
@Test
void repoFromBomAccordingToAnotherVersion() {
    DependencyMetadata dependencyMetadata = testRepoFromBomAccordingToVersion("1.1.5.RELEASE");
    assertThat(dependencyMetadata.getBootVersion()).isEqualTo(Version.parse("1.1.5.RELEASE"));
    assertThat(dependencyMetadata.getDependencies()).hasSize(3);
    assertThat(dependencyMetadata.getRepositories()).hasSize(2);
    assertThat(dependencyMetadata.getBoms()).hasSize(1);
    assertThat(dependencyMetadata.getRepositories().get("repo-foo").getName()).isEqualTo("foo");
    assertThat(dependencyMetadata.getRepositories().get("repo-biz").getName()).isEqualTo("biz");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getGroupId()).isEqualTo("org.foo");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getArtifactId()).isEqualTo("bom");
    assertThat(dependencyMetadata.getBoms().get("bom-foo").getVersion()).isEqualTo("3.0.0.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDependencyTests.java
Tests:
    "@Test
@Test
void initializeFromStandardDependency() {
    Dependency original = Dependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).classifier("test-jar").type("zip").build();
    MavenDependency dependency = MavenDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getClassifier()).isEqualTo("test-jar");
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.isOptional()).isFalse();
}
"
    "@Test
@Test
void initializeFromMavenDependency() {
    Dependency original = MavenDependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).classifier("test-jar").type("zip").optional(true).build();
    MavenDependency dependency = MavenDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getClassifier()).isEqualTo("test-jar");
    assertThat(dependency.isOptional()).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/SimpleBuildCustomizerTests.java
Tests:
    "@Test
@Test
void customizeVersion() {
    MutableProjectDescription description = initializeDescription();
    description.setVersion("2.4.0");
    MavenBuild build = customizeBuild(description);
    assertThat(build.getSettings().getVersion()).isEqualTo("2.4.0");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleDependencyTests.java
Tests:
    "@Test
@Test
void initializeFromStandardDependency() {
    Dependency original = Dependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).type("zip").build();
    GradleDependency dependency = GradleDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getConfiguration()).isNull();
}
"
    "@Test
@Test
void initializeFromMavenDependency() {
    Dependency original = GradleDependency.withCoordinates("com.example", "test").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME).type("zip").configuration("myConfiguration").build();
    GradleDependency dependency = GradleDependency.from(original).build();
    assertThat(original).isNotSameAs(dependency);
    assertThat(dependency.getGroupId()).isEqualTo("com.example");
    assertThat(dependency.getArtifactId()).isEqualTo("test");
    assertThat(dependency.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(dependency.getScope()).isEqualTo(DependencyScope.RUNTIME);
    assertThat(dependency.getType()).isEqualTo("zip");
    assertThat(dependency.getConfiguration()).isEqualTo("myConfiguration");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradlePluginContainerTests.java
Tests:
    "@Test
@Test
void addPluginWithConsumer() {
    GradlePluginContainer pluginContainer = new GradlePluginContainer();
    pluginContainer.add("com.example", (plugin) -> plugin.setVersion("1.0"));
    assertThat(pluginContainer.values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getId()).isEqualTo("com.example");
        assertThat(plugin).isInstanceOf(StandardGradlePlugin.class);
        assertThat(((StandardGradlePlugin) plugin).getVersion()).isEqualTo("1.0");
        assertThat(plugin.isApply()).isFalse();
    });
}
"
    "@Test
@Test
void addPluginSeveralTimeReuseConfiguration() {
    GradlePluginContainer pluginContainer = new GradlePluginContainer();
    pluginContainer.add("com.example", (plugin) -> {
        assertThat(plugin.getVersion()).isNull();
        plugin.setVersion("1.0");
    });
    pluginContainer.add("com.example", (plugin) -> {
        assertThat(plugin.getVersion()).isEqualTo("1.0");
        plugin.setVersion("2.0");
    });
    assertThat(pluginContainer.values()).singleElement().satisfies((plugin) -> {
        assertThat(plugin.getId()).isEqualTo("com.example");
        assertThat(plugin).isInstanceOf(StandardGradlePlugin.class);
        assertThat(((StandardGradlePlugin) plugin).getVersion()).isEqualTo("2.0");
        assertThat(plugin.isApply()).isFalse();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/code/kotlin/KotlinMavenBuildCustomizerTests.java
Tests:
    "@Test
@Test
void kotlinMavenKotlinStdlibIsConfiguredWithKotlinOneEight() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenBuildCustomizer(new KotlinOneEightProjectSettings()).customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-stdlib");
    io.spring.initializr.generator.buildsystem.Dependency kotlinStdlib = build.dependencies().get("kotlin-stdlib");
    assertThat(kotlinStdlib.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinStdlib.getArtifactId()).isEqualTo("kotlin-stdlib");
    assertThat(kotlinStdlib.getVersion()).isNull();
    assertThat(kotlinStdlib.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void kotlinMavenKotlinStdlibJdk8IsConfiguredWithKotlinOneSeven() {
    MavenBuild build = new MavenBuild();
    new KotlinMavenBuildCustomizer(new KotlinOneSevenProjectSettings()).customize(build);
    assertThat(build.dependencies().ids()).containsOnly("kotlin-stdlib");
    io.spring.initializr.generator.buildsystem.Dependency kotlinStdlib = build.dependencies().get("kotlin-stdlib");
    assertThat(kotlinStdlib.getGroupId()).isEqualTo("org.jetbrains.kotlin");
    assertThat(kotlinStdlib.getArtifactId()).isEqualTo("kotlin-stdlib-jdk8");
    assertThat(kotlinStdlib.getVersion()).isNull();
    assertThat(kotlinStdlib.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/DependencyContainerTests.java
Tests:
    "@Test
@Test
void addDependency() {
    DependencyContainer container = createTestContainer();
    container.add("web", "org.springframework.boot", "spring-boot-starter-web", DependencyScope.COMPILE);
    assertThat(container.ids()).containsOnly("web");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("web")).isTrue();
    Dependency web = container.get("web");
    assertThat(web).isNotNull();
    assertThat(web.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(web.getArtifactId()).isEqualTo("spring-boot-starter-web");
    assertThat(web.getVersion()).isNull();
    assertThat(web.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void addDependencyWithVersion() {
    DependencyContainer container = createTestContainer();
    container.add("custom", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.COMPILE));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    Dependency custom = container.get("custom");
    assertThat(custom).isNotNull();
    assertThat(custom.getGroupId()).isEqualTo("com.example");
    assertThat(custom.getArtifactId()).isEqualTo("acme");
    assertThat(custom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(custom.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/DefaultProjectRequestToDescriptionConverterTests.java
Tests:
    "@Test
@Test
void convertShouldSetVersionFromRequest() {
    ProjectRequest request = createProjectRequest();
    request.setVersion("1.0.2-SNAPSHOT");
    ProjectDescription description = this.converter.convert(request, this.metadata);
    assertThat(description.getVersion()).isEqualTo("1.0.2-SNAPSHOT");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/stat/ProjectRequestDocumentFactoryTests.java
Tests:
    "@Test
@Test
void createDocumentForSimpleProject() {
    ProjectRequest request = createProjectRequest();
    ProjectGeneratedEvent event = createProjectGeneratedEvent(request);
    ProjectRequestDocument document = this.factory.createDocument(event);
    assertThat(document.getArtifactId()).isEqualTo("demo");
    assertThat(document.getBuildSystem()).isEqualTo("maven");
    assertThat(document.getClient()).isNull();
    assertThat(document.getDependencies().getValues()).isEmpty();
    assertThat(document.getDependencies().getId()).isEqualTo("_none");
    assertThat(document.getDependencies().getCount()).isEqualTo(0);
    assertThat(document.getErrorState()).isNull();
    assertThat(document.getGenerationTimestamp()).isEqualTo(event.getTimestamp());
    assertThat(document.getGroupId()).isEqualTo("com.example");
    assertThat(document.getJavaVersion()).isEqualTo("1.8");
    assertThat(document.getLanguage()).isEqualTo("java");
    assertThat(document.getPackageName()).isEqualTo("com.example.demo");
    assertThat(document.getPackaging()).isEqualTo("jar");
    assertThat(document.getType()).isEqualTo("maven-project");
    assertThat(document.getVersion().getId()).isEqualTo("2.4.1");
    assertThat(document.getVersion().getMajor()).isEqualTo("2");
    assertThat(document.getVersion().getMinor()).isEqualTo("2.4");
}
"
    "@Test
@Test
void createDocumentWithUserAgent() {
    WebProjectRequest request = createProjectRequest();
    request.getParameters().put("user-agent", "HTTPie/0.8.0");
    ProjectGeneratedEvent event = createProjectGeneratedEvent(request);
    ProjectRequestDocument document = this.factory.createDocument(event);
    assertThat(document.getClient().getId()).isEqualTo("httpie");
    assertThat(document.getClient().getVersion()).isEqualTo("0.8.0");
}
"
    "@Test
@Test
void createDocumentWithUserAgentNoVersion() {
    WebProjectRequest request = createProjectRequest();
    request.getParameters().put("user-agent", "IntelliJ IDEA");
    ProjectGeneratedEvent event = createProjectGeneratedEvent(request);
    ProjectRequestDocument document = this.factory.createDocument(event);
    assertThat(document.getClient().getId()).isEqualTo("intellijidea");
    assertThat(document.getClient().getVersion()).isNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BomContainerTests.java
Tests:
    "@Test
@Test
void addBom() {
    BomContainer container = createTestContainer();
    container.add("root", BillOfMaterials.withCoordinates("org.springframework.boot", "spring-boot-dependencies").version(VersionReference.ofProperty("spring-boot.version")));
    assertThat(container.ids()).containsOnly("root");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("root")).isTrue();
    BillOfMaterials bom = container.get("root");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(bom.getArtifactId()).isEqualTo("spring-boot-dependencies");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofProperty("spring-boot.version"));
    assertThat(bom.getOrder()).isEqualTo(Integer.MAX_VALUE);
}
"
    "@Test
@Test
void addBomWithOrder() {
    BomContainer container = createTestContainer();
    container.add("custom", BillOfMaterials.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).order(42));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    BillOfMaterials bom = container.get("custom");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("com.example");
    assertThat(bom.getArtifactId()).isEqualTo("acme");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(bom.getOrder()).isEqualTo(42);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDistributionManagementTests.java
Tests:
    "@Test
@Test
void distributionManagementWithRelocation() {
    MavenDistributionManagement mdm = builder().relocation((relocation) -> relocation.groupId("com.example.new").artifactId("project").version("1.0.0")).relocation((relocation) -> relocation.message("Moved to com.example.new")).build();
    assertThat(mdm.getRelocation().getGroupId()).isEqualTo("com.example.new");
    assertThat(mdm.getRelocation().getArtifactId()).isEqualTo("project");
    assertThat(mdm.getRelocation().getVersion()).isEqualTo("1.0.0");
    assertThat(mdm.getRelocation().getMessage()).isEqualTo("Moved to com.example.new");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-metadata/src/test/java/io/spring/initializr/metadata/InitializrMetadataTests.java
Tests:
    "@Test
@Test
void updateSpringBootVersions() {
    InitializrMetadata metadata = initializeMetadata();
    BillOfMaterials bom = BillOfMaterials.create("org.acme", "foo-bom");
    bom.getMappings().add(Mapping.create("[1.2.0.RELEASE,1.3.x.RELEASE]", "1.0.0"));
    bom.getMappings().add(Mapping.create("1.3.x.BUILD-SNAPSHOT", "1.1.0-BUILD-SNAPSHOT"));
    Dependency dependency = Dependency.withId("bar");
    dependency.getMappings().add(Dependency.Mapping.create("[1.3.0.RELEASE, 1.3.x.RELEASE]", null, null, "0.1.0.RELEASE", null, null, null));
    dependency.getMappings().add(Dependency.Mapping.create("1.3.x.BUILD-SNAPSHOT", null, null, "0.2.0.RELEASE", null, null, null));
    addTestDependencyGroup(metadata, dependency);
    metadata.getConfiguration().getEnv().getBoms().put("foo-bom", bom);
    Kotlin kotlin = metadata.getConfiguration().getEnv().getKotlin();
    kotlin.setDefaultVersion("1.3");
    kotlin.getMappings().add(createKotlinVersionMapping("[1.2.0.RELEASE,1.3.x.RELEASE]", "1.1"));
    kotlin.getMappings().add(createKotlinVersionMapping("1.3.x.BUILD-SNAPSHOT", "1.2"));
    metadata.validate();
    List<DefaultMetadataElement> bootVersions = Arrays.asList(DefaultMetadataElement.create("1.3.6.RELEASE", "1.3.6", false), DefaultMetadataElement.create("1.3.7.BUILD-SNAPSHOT", "1.3.7", false));
    metadata.updateSpringBootVersions(bootVersions);
    assertThat(metadata.getConfiguration().getEnv().getBoms().get("foo-bom").resolve(Version.parse("1.3.6.RELEASE")).getVersion()).isEqualTo("1.0.0");
    assertThat(metadata.getConfiguration().getEnv().getBoms().get("foo-bom").resolve(Version.parse("1.3.7.BUILD-SNAPSHOT")).getVersion()).isEqualTo("1.1.0-BUILD-SNAPSHOT");
    assertThat(metadata.getDependencies().get("bar").resolve(Version.parse("1.3.6.RELEASE")).getVersion()).isEqualTo("0.1.0.RELEASE");
    assertThat(metadata.getDependencies().get("bar").resolve(Version.parse("1.3.7.BUILD-SNAPSHOT")).getVersion()).isEqualTo("0.2.0.RELEASE");
    assertThat(metadata.getConfiguration().getEnv().getKotlin().resolveKotlinVersion(Version.parse("1.3.7.BUILD-SNAPSHOT"))).isEqualTo("1.2");
}
"Scenarios:

Scenario 1: Checking for correct version retrieval
Details:
  TestName: testVersionRetrievedCorrectly
  Description: This test is intended to verify if the getVersion() method correctly returns the previously set version.
Execution:
  Arrange: Create a new ProjectRequest object and call its setVersion method with a given version string.
  Act: Call the getVersion method on this ProjectRequest object.
  Assert: Check if the returned version matches the previously set version.
Validation:
  We expect the getVersion method to return the version that was previously set. This test verifies the correct working of the version getter method. Proper version fetching is important in various project-related operations like version comparisons, database entries, version-based selections, etc.

Scenario 2: Confirming functionality when version is null
Details:
  TestName: testReturnsNullForUnsetVersion
  Description: This test aims to ensure that the getVersion() method returns null when there is no value set for the version attribute.
Execution:
  Arrange: Generate a new ProjectRequest object without calling the setVersion method.
  Act: Invoke the getVersion method on the ProjectRequest object.
  Assert: Confirm that the getVersion method call returns null.
Validation:
  If there is no defined value for the version, the getVersion method should return null. This is the expected behavior because the version attribute is initialized to null during object generation.

Scenario 3: Confirming proper handling of empty String input
Details:
  TestName: testHandleEmptyVersion
  Description: Test if the getVersion() method correctly handles an empty string as the version.
Execution:
  Arrange: Build a new ProjectRequest object. Invoke its setVersion method with an empty string as an argument.
  Act: Invoke the getVersion method on the ProjectRequest object.
  Assert: Confirm that the getVersion call returns an empty string.
Validation:
  The application should handle empty String inputs without any exceptions. This test verifies such functionality. It makes sure that even when a version is not properly set (like an empty string), there is no unexpected behavior or exceptions.

Scenario 4: Checking returned version for multiple invocations
Details:
  TestName: testReturnedVersionPersistence
  Description: This test is for confirming that multiple invocations of getVersion() method returns the same value every time.
Execution:
  Arrange: Generate a new ProjectRequest object. Invoke its setVersion method with a predefined version string.
  Act: Invoke the getVersion method on this object multiple times.
  Assert: Confirm that all calls to getVersion return the same value.
Validation:
  This test confirms that getVersion maintains the same output across multiple invocations. This is important because the version should remain consistent once it's set.

Scenario 5: Ensuring non-interference of other methods on getVersion
Details:
  TestName: testNoInterferenceFromOtherMethods
  Description: Test if calling other setter methods after setting the version does not change the version's value.
Execution:
  Arrange: Create a new ProjectRequest object. Call its setVersion method with a certain version string. Then, call some other setter methods with their respective arguments.
  Act: Invoke the getVersion method on the ProjectRequest object.
  Assert: Confirm getVersion's output equals the earlier defined version string, and not the values given to the other setters.
Validation:
  Other setters should not affect the version of the ProjectRequest object. This test ensures such isolation of variable setting in different methods. This binding prevents bugs and unexpected behavior during program execution.

*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.StringUtils;

public class ProjectRequestGetVersionTest {

	@Test
	@Tag("valid")
	void testVersionRetrievedCorrectly() {
		ProjectRequest request = new ProjectRequest();
		request.setVersion("1.0");
		assertEquals("1.0", request.getVersion());
	}

	@Test
	@Tag("valid")
	void testReturnsNullForUnsetVersion() {
		ProjectRequest request = new ProjectRequest();
		assertNull(request.getVersion());
	}

	@Test
	@Tag("valid")
	void testHandleEmptyVersion() {
		ProjectRequest request = new ProjectRequest();
		request.setVersion("");
		assertEquals("", request.getVersion());
	}

	@Test
	@Tag("valid")
	void testReturnedVersionPersistence() {
		ProjectRequest request = new ProjectRequest();
		request.setVersion("1.0");
		assertEquals("1.0", request.getVersion());
		assertEquals("1.0", request.getVersion());
	}

	@Test
	@Tag("valid")
	void testNoInterferenceFromOtherMethods() {
		ProjectRequest request = new ProjectRequest();
		request.setVersion("1.0");
		request.setArtifactId("test");
		request.setGroupId("com.example");
		assertEquals("1.0", request.getVersion());
	}

}