/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getBaseDir_e572396175
ROOST_METHOD_SIG_HASH=getBaseDir_a044e12403

Scenario 1: Validate the base directory Retrieve action when no base directory is set

Details:
TestName: getBaseDirWithoutSetting
Description: This test case aims to check the getBaseDir() functionality when no base directory is set. It's expected to return null since no value was ever set.
Execution:
Arrange: Instantiate a ProjectRequest and do not set a base directory.
Act: Invoke the getBaseDir() method.
Assert: Assert that the resulting base directory is null.
Validation:
This check ensures that the getBaseDir() method appropriately handles the scenario where no base directory has been set and ensures the method can handle null values.

Scenario 2: Validate the base directory Retrieve action after setting the base directory.

Details:
TestName: getBaseDirAfterSetting
Description: This test case aims to check the getBaseDir() functionality after the base directory is set using setBaseDir(). It is designed to confirm the method is retrieving the correct base directory set earlier.
Execution:
Arrange: Instantiate a ProjectRequest and set a base directory.
Act: Invoke the getBaseDir() method.
Assert: Assert that the resulting base directory is as set earlier.
Validation:
This checks if the getBaseDir() method can correctly retrieve the set base path value, ensuring that the method is working as it is intended.


Scenario 3: Validate the base directory retrieve action when baseDir value is reset to null

Details:
TestName: getBaseDirAfterReset
Description: This test case aims to check how the getBaseDir() method respond when baseDir value is reset to null after setting a base directory.
Execution:
Arrange: Instantiate a ProjectRequest, set a base directory and, reset base directory to null.
Act: Invoke the getBaseDir() method.
Assert: Assert that the resulting base directory is null.
Validation:
This validates that the getBaseDir() method is capable of retrieving the most recent value of the base directory, even when it's set to null. It exposes how the method handles situations where a previously set value is reset.
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.StringUtils;

public class ProjectRequestGetBaseDirTest {

	@Test
	@Tag("valid")
	public void getBaseDirWithoutSettingTest() {
		ProjectRequest projectRequest = new ProjectRequest();
		// This test case expects that getBaseDir() will return null if it has not been
		// set
		Assertions.assertNull(projectRequest.getBaseDir());
	}

	@Test
	@Tag("valid")
	public void getBaseDirAfterSettingTest() {
		ProjectRequest projectRequest = new ProjectRequest();
		String baseDir = "TestBaseDir";
		projectRequest.setBaseDir(baseDir);
		// This test case expects that getBaseDir() will return the value set through
		// setBaseDir()
		Assertions.assertEquals(baseDir, projectRequest.getBaseDir());
	}

	@Test
	@Tag("boundary")
	public void getBaseDirAfterResetTest() {
		ProjectRequest projectRequest = new ProjectRequest();
		String baseDir = "TestBaseDir";
		projectRequest.setBaseDir(baseDir);
		projectRequest.setBaseDir(null);
		// This test case expects that getBaseDir() will return null if it has been reset
		Assertions.assertNull(projectRequest.getBaseDir());
	}

}