/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=cleanTempFiles_c6aa981e2a
ROOST_METHOD_SIG_HASH=cleanTempFiles_d130d5e1bc

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
void cleanupTempFilesShouldOnlyCleanupSpecifiedDir() throws IOException {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    ProjectGenerationResult result = this.invoker.invokeProjectStructureGeneration(request);
    this.invoker.cleanTempFiles(result.getRootDirectory());
    assertThat(result.getRootDirectory()).doesNotExist();
}
""""
  Scenario 1: Testing removal of temporary files for a valid directory path

  Details:
    TestName: removeTempFilesValidPath.
    Description: This test cases explores a scenario where the directory path to be cleaned up exists and contains temporary files. The validation of temporary files removal using FileSystemUtils is expected to be successful.
  Execution:
    Arrange: Instantiate the directory path with a valid temporary files directory.
    Act: Invoke the 'cleanTempFiles' with the valid directory path.
    Assert: Validate that the temporary files in the directory are deleted and the ConcurrentHashMap does not contain the directory key.
  Validation:
    This tests validates the correct cleanup functionality of the 'cleanTempFiles' method when provided with a valid directory path. This scenario ensures that the temporary files cleanup function works as expected when invoked with a valid directory in usual use-cases.

  Scenario 2: Testing removal of temporary files for a directory path with no temporary files

  Details:
    TestName: removeTempFilesEmptyDirectory.
    Description: This test scenario is meant to check the functionality of 'cleanTempFiles' method when the provided directory path does not contain any temporary files, but exists in the ConcurrentHashMap.
  Execution:
    Arrange: Instantiate the directory to an existing path but one that does not have any temporary files.
    Act: Invoke the 'cleanTempFiles' method with this directory path.
    Assert: Validate that the directory is no longer available in the ConcurrentHashMap.
  Validation:
    This scenario validates that even if a directory does not contain any temporary files, the 'cleanTempFiles' method removes the directory from the ConcurrentHashMap, ensuring the cleanup of empty directories as well.

  Scenario 3: Testing cleanTempFiles with a non-existent directory path

  Details:
    TestName: cleanTempFilesWithNonExistentPath.
    Description: This test is to assert the method behavior when provided with a directory path that does not exist. The cleanTempFiles method should handle such scenarios gracefully.
  Execution:
    Arrange: Instantiate the directory path to a non-existent directory.
    Act: Invoke 'cleanTempFiles' method with this non-existent directory path.
    Assert: Validate that the ConcurrentHashMap does not contain the non-existent directory path.
  Validation:
    The test case is to ensure that the 'cleanTempFiles' method omits non-existent directories without throwing an exception and correctly validates the existence of directories before attempting cleanup.

  Scenario 4: Testing removeTempFiles handling of IOException

  Details:
    TestName: removeTempFilesIOExceptionHandling.
    Description: This test is to assert how the cleanTempFiles method handles any exceptions that occur while attempting to clean temporary files.
  Execution:
    Arrange: Mock the FileSystemUtils.deleteRecursively(path) method to throw an IOException.
    Act: Invoke 'cleanTempFiles' method.
    Assert: The method should gracefully handle the IOException and should not cause the test to fail.
  Validation:
    This test case ensures that any exceptions that occur while removing temporary files are properly handled and do not cause the method to break.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import static org.junit.jupiter.api.Assertions.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.*;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import io.spring.initializr.generator.buildsystem.BuildItemResolver;
import io.spring.initializr.generator.buildsystem.BuildWriter;
import io.spring.initializr.generator.project.DefaultProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectAssetGenerator;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationContext;
import io.spring.initializr.generator.project.ProjectGenerationException;
import io.spring.initializr.generator.project.ProjectGenerator;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.support.MetadataBuildItemResolver;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.util.FileSystemUtils;

public class ProjectGenerationInvokerCleanTempFilesTest {

	private ProjectGenerationInvoker projectGenerationInvoker;

	@Mock
	private Path directoryPath;

	@BeforeEach
	public void setUp() {
		projectGenerationInvoker = new ProjectGenerationInvoker();
	}

	@Test
	@Tag("valid")
	public void removeTempFilesValidPath() {
		directoryPath = Files.createTempDirectory("TempDir");
		projectGenerationInvoker.cleanTempFiles(directoryPath);
		assertFalse(projectGenerationInvoker.temporaryFiles.containsKey(directoryPath),
				"Directory path should not exist in the map.");
		assertFalse(Files.exists(directoryPath), "Directory should not exist.");
	}

	@Test
	@Tag("valid")
	public void removeTempFilesEmptyDirectory() {
		directoryPath = Files.createTempDirectory("EmptyDir");
		projectGenerationInvoker.cleanTempFiles(directoryPath);
		assertFalse(projectGenerationInvoker.temporaryFiles.containsKey(directoryPath),
				"Empty directory should be removed from the map.");
	}

	@Test
	@Tag("invalid")
	public void cleanTempFilesWithNonExistentPath() {
		directoryPath = Path.of("/nonexistent/path/dir");
		projectGenerationInvoker.cleanTempFiles(directoryPath);
		assertFalse(projectGenerationInvoker.temporaryFiles.containsKey(directoryPath),
				"Non-existent directory should not be in map.");
	}

	@Test
    @Tag("integration")
    public void removeTempFilesIOExceptionHandling() {
        directoryPath = Files.createTempDirectory("DirWithIOException");
        FileSystemUtils.deleteRecursively(path) {
            throw new IOException("IOException occurred.");
        }
        projectGenerationInvoker.cleanTempFiles(directoryPath);
        assertTrue(projectGenerationInvoker.temporaryFiles.containsKey(directoryPath), "Directory with IOException should still be in map.");
    }

}