/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=initialize_cc4dc0e25f
ROOST_METHOD_SIG_HASH=initialize_ad8ab78bc9

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/DefaultProjectRequestToDescriptionConverterTests.java
Tests:
    "@Test
private ProjectRequest createProjectRequest() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(this.metadata);
    return request;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/stat/ProjectRequestDocumentFactoryTests.java
Tests:
    "@Test
private WebProjectRequest createProjectRequest() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(this.metadata);
    return request;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/controller/custom/CustomProjectGenerationController.java
Tests:
    "@Test
@Override
public CustomProjectRequest projectRequest(Map<String, String> headers) {
    CustomProjectRequest request = new CustomProjectRequest();
    request.getParameters().putAll(headers);
    request.initialize(getMetadata());
    return request;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/stat/ProjectGenerationStatPublisherTests.java
Tests:
    "@Test
private WebProjectRequest createProjectRequest() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(this.metadata);
    return request;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/d7e2a4c8-535f-48fd-a4f6-b950f88805c3/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/project/ProjectGenerationInvokerTests.java
Tests:
    "@Test
@Test
@SuppressWarnings("unchecked")
void invokeProjectStructureGeneration() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    ProjectGenerationResult result = this.invoker.invokeProjectStructureGeneration(request);
    assertThat(new ProjectStructure(result.getRootDirectory())).hasMavenBuild();
    Map<Path, List<Path>> tempFiles = (Map<Path, List<Path>>) ReflectionTestUtils.getField(this.invoker, "temporaryFiles");
    assertThat(tempFiles.get(result.getRootDirectory())).contains(result.getRootDirectory());
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeProjectStructureGenerationFailureShouldPublishFailureEvent() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("foo-bar");
    try {
        this.invoker.invokeProjectStructureGeneration(request);
    } catch (Exception ex) {
        verifyProjectFailedEventFor(request, ex);
    }
}
"
    "@Test
@Test
void invokeBuildGenerationForMavenBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.setType("maven-project");
    request.initialize(metadata);
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new MavenBuildAssert(content).hasGroupId(request.getGroupId()).hasArtifactId(request.getArtifactId()).hasVersion(request.getVersion()).doesNotHaveNode("/project/packaging").hasName(request.getName()).hasDescription(request.getDescription()).hasProperty("java.version", request.getJavaVersion()).hasParent("org.springframework.boot", "spring-boot-starter-parent", request.getBootVersion());
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationForGradleBuild() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    request.setJavaVersion("17");
    byte[] bytes = this.invoker.invokeBuildGeneration(request);
    String content = new String(bytes);
    new GroovyDslGradleBuildAssert(content).hasVersion(request.getVersion()).hasPlugin("org.springframework.boot", request.getBootVersion()).hasToolchainForJava("17");
    verifyProjectSuccessfulEventFor(request);
}
"
    "@Test
@Test
void invokeBuildGenerationFailureShouldPublishFailureEvent() {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("foo-bar");
    try {
        this.invoker.invokeBuildGeneration(request);
    } catch (Exception ex) {
        verifyProjectFailedEventFor(request, ex);
    }
}
"
    "@Test
@Test
void cleanupTempFilesShouldOnlyCleanupSpecifiedDir() throws IOException {
    WebProjectRequest request = new WebProjectRequest();
    request.initialize(metadata);
    request.setType("gradle-project");
    ProjectGenerationResult result = this.invoker.invokeProjectStructureGeneration(request);
    this.invoker.cleanTempFiles(result.getRootDirectory());
    assertThat(result.getRootDirectory()).doesNotExist();
}
"
    "@Test
@Test
void invokeProjectStructureGenerationWithCustomAssetGenerator(@TempDir Path directory) {
    WebProjectRequest webRequest = new WebProjectRequest();
    webRequest.initialize(metadata);
    webRequest.setGroupId("org.acme.test");
    webRequest.setType("maven-project");
    ProjectGenerationResult result = new ProjectGenerationInvoker<ProjectRequest>(this.context, this.eventPublisher, new DefaultProjectRequestToDescriptionConverter()) {

        @Override
        protected ProjectAssetGenerator<Path> getProjectAssetGenerator(ProjectDescription description) {
            assertThat(description.getBuildSystem()).isInstanceOf(MavenBuildSystem.class);
            assertThat(description.getGroupId()).isEqualTo("org.acme.test");
            return (context) -> directory;
        }
    }.invokeProjectStructureGeneration(webRequest);
    assertThat(result.getRootDirectory()).isSameAs(directory);
    assertThat(result.getRootDirectory()).isEmptyDirectory();
    verifyProjectSuccessfulEventFor(webRequest);
}
""""
Scenario 1: Test If Metadata Defaults are Returned Successfully

Details:
  TestName: testIfMetadataDefaultsAreReturnedSuccessfully
  Description: This test scenario mainly checks whether the metadata defaults are initialized and returned correctly without any error.
Execution:
  Arrange: Mock InitializrMetadata.class to provide mock metadata defaults.
           Create an instance of WebProjectRequest and initialize it with mock metadata.
  Act: Invoke initialize() method with the mock InitializrMetadata object.
  Assert: Use JUnit assertions to compare actual bean properties set against expected properties.
Validation:
  The assertion aims to verify if the set bean properties match the expected properties. The expected results are based on the mock InitializrMetadata object that provides the metadata defaults. If there's a match, it points out that the initialize() method is functional.


Scenario 2: Test If a Property Not Being Writable Is Skipped

Details:
  TestName: testIfNonWritablePropertyIsSkipped
  Description: The test is meant to check that a non-writable property from the metadata defaults is skipped during initialization.
Execution:
  Arrange: Arrange mock InitializrMetadata.class to provide metadata defaults with a non-writable property.
           Create an instance of WebProjectRequest and initialize it with the mock metadata.
  Act: Invoke the initialize() method with the mock InitializrMetadata object.
  Assert: Check if the non-writable property wasn't set.
Validation:
  This test verifies if the initialize() method correctly identifies and skips a non-writable property. The successful execution of this test ensures the robustness of the initialization process.


Scenario 3: Test If "packageName" Property Is Skipped

Details:
  TestName: testIfPackageNamePropertyIsSkipped
  Description: This test scenario aims to verify that the 'packageName' property from the metadata defaults is skipped during initialization.
Execution:
  Arrange: Arrange mock InitializrMetadata.class to provide metadata defaults with 'packageName' property.
           Create an instance of WebProjectRequest and initialize it with the mock metadata.
  Act: Invoke the initialize() method with the mock metadata.
  Assert: Use JUnit assertions to check if 'packageName' property wasn't set.
Validation:
  This test aims to check if the initialize() method correctly identifies and skips setting the 'packageName' property. This indicates the correct execution of conditional logic in the method.

Scenario 4: Testing Exception Handling During Initialization

Details:
  TestName: testExceptionHandlingDuringInitialization
  Description: This test aims to check if the initialize method handles exceptions when there is a problem accessing metadata defaults.
Execution:
  Arrange: Mock InitializrMetadata.class and let defaults() method throw a RuntimeException.
           Create an instance of WebProjectRequest and initialize it with the mock metadata.
  Act: Invoke the initialize() method with the mock InitializrMetadata object.
  Assert: Expect a RuntimeException using AssertThrows in JUnit.
Validation:
  The test verifies that the initialize() method can gracefully handle exceptions that may arise during initialization. The expected result is a RuntimeException, signifying a fault while accessing metadata defaults.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.project;

import io.spring.initializr.metadata.InitializrMetadata;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.HashMap;
import java.util.Map;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.springframework.beans.BeanWrapperImpl;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class WebProjectRequestInitializeTest {

	private InitializrMetadata mockMetadata;

	private WebProjectRequest webProjectRequest;

	@BeforeEach
	public void setup() {
		mockMetadata = mock(InitializrMetadata.class);
		webProjectRequest = new WebProjectRequest();
	}

	@Tag("Valid")
	@Test
	public void testIfMetadataDefaultsAreReturnedSuccessfully() {
		Map<String, Object> defaults = new HashMap<>();
		defaults.put("groupId", "com.test");
		defaults.put("artifactId", "sample");
		when(mockMetadata.defaults()).thenReturn(defaults);
		webProjectRequest.initialize(mockMetadata);
		BeanWrapperImpl bean = new BeanWrapperImpl(webProjectRequest);
		assertEquals("com.test", bean.getPropertyValue("groupId"));
		assertEquals("sample", bean.getPropertyValue("artifactId"));
	}

	@Tag("Boundary")
	@Test
	public void testIfNonWritablePropertyIsSkipped() {
		Map<String, Object> defaults = new HashMap<>();
		defaults.put("invalidProperty", "invalidValue");
		when(mockMetadata.defaults()).thenReturn(defaults);
		webProjectRequest.initialize(mockMetadata);
		BeanWrapperImpl bean = new BeanWrapperImpl(webProjectRequest);
		assertNull(bean.getPropertyValue("invalidProperty"));
	}

	@Tag("Boundary")
    @Test
    public void testIfPackageNamePropertyIsSkipped() {
        Map<String, Object> defaults = new HashMap<>();
        defaults.put("package io.spring.initializr.web.project;
import io.spring.initializr.metadata.InitializrMetadata;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.HashMap;
import java.util.Map;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.springframework.beans.BeanWrapperImpl;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

        when(mockMetadata.defaults()).thenReturn(defaults);
        webProjectRequest.initialize(mockMetadata);
        BeanWrapperImpl bean = new BeanWrapperImpl(webProjectRequest);
        assertNull(bean.getPropertyValue("package io.spring.initializr.web.project;
import io.spring.initializr.metadata.InitializrMetadata;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.HashMap;
import java.util.Map;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.springframework.beans.BeanWrapperImpl;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

    }

	@Tag("Invalid")
	@Test
	public void testExceptionHandlingDuringInitialization() {
		when(mockMetadata.defaults()).thenThrow(RuntimeException.class);
		assertThrows(RuntimeException.class, () -> {
			webProjectRequest.initialize(mockMetadata);
		});
	}

}