/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createUniqueId_8fa91d0557
ROOST_METHOD_SIG_HASH=createUniqueId_30c760a911

"""
Scenario 1: Test Unique ID Creation with Non-Null Content
Details:
  TestName: testUniqueIDCreationWithNonNullContent
  Description: This test is to check if the method 'createUniqueId' returns a unique ID of type String when given a non-null content.
Execution:
  Arrange: Set up a non-null content string variable.
  Act: Invoke the createUniqueId method with the non-null content string.
  Assert: Assert that the returned value is not null and a type of String.
Validation:
  Asserts that the method is generating a unique ID for non-null content hence proving that the functionality to create a unique ID works effectively when non-null content is provided.

Scenario 2: Test Unique ID Creation with Null Content
Details:
  TestName: testUniqueIDCreationWithNullContent
  Description: This test is to check if the method 'createUniqueId' can handle null content and how it behaves when provided with it.
Execution:
  Arrange: Set up a null content string variable.
  Act: Invoke the createUniqueId method with the null content string.
  Assert: Assert that IllegalArgumentException is thrown or handle the null scenario appropriately based on method functionality.
Validation:
  Asserts that the method creates unique ID is behaving as expected when provided with null content. This is important to understand how the method works under exceptional circumstances.

Scenario 3: Different Contents Produce Different IDs
Details:
  TestName: testDifferentContentsProduceDifferentIDs
  Description: This test is to check if different inputs or contents to the 'createUniqueId' method generates different IDs.
Execution:
  Arrange: Set up two different content string variables.
  Act: Invoke the createUniqueId method with the two different content strings.
  Assert: Assert that the returned string from both cases are not equal.
Validation:
  Asserts that the method properly creates unique IDs, as different content should produce non-identical IDs, hence validating the functionality of creating unique IDs.

Scenario 4: Same content yields the same ID
Details:
  TestName: testSameContentYieldsSameID
  Description: This test is to verify if the method 'createUniqueId' produces the same ID when invoked with the same content string.
Execution:
  Arrange: Set up the same content string variable twice.
  Act: Invoke the createUniqueId method with the same content string twice.
  Assert: Assert that the two returned ID strings are equal.
Validation:
  Asserting that the method properly generates IDs, as the same content should yield the same Unique ID, validating the uniqueness and consistency of ID generation.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.InitializrMetadataProvider;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.util.DigestUtils;
import org.junit.jupiter.api.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

public class AbstractMetadataControllerCreateUniqueIdTest {

	@Tag("valid")
	@Test
	public void testUniqueIDCreationWithNonNullContent() {
		InitializrMetadataProvider metadataProvider = Mockito.mock(InitializrMetadataProvider.class);
		AbstractMetadataController controller = new AbstractMetadataController(metadataProvider);
		String nonNullContent = "Testing content";
		String result = controller.createUniqueId(nonNullContent);
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.getClass().equals(String.class));
	}

	@Tag("invalid")
	@Test
	public void testUniqueIDCreationWithNullContent() {
		InitializrMetadataProvider metadataProvider = Mockito.mock(InitializrMetadataProvider.class);
		AbstractMetadataController controller = new AbstractMetadataController(metadataProvider);
		Assertions.assertThrows(IllegalArgumentException.class, () -> {
			controller.createUniqueId(null);
		});
	}

	@Tag("valid")
	@Test
	public void testDifferentContentsProduceDifferentIDs() {
		InitializrMetadataProvider metadataProvider = Mockito.mock(InitializrMetadataProvider.class);
		AbstractMetadataController controller = new AbstractMetadataController(metadataProvider);
		String firstContent = "First Content";
		String secondContent = "Second Content";

		String firstResult = controller.createUniqueId(firstContent);
		String secondResult = controller.createUniqueId(secondContent);
		Assertions.assertNotEquals(firstResult, secondResult);
	}

	@Tag("valid")
	@Test
	public void testSameContentYieldsSameID() {
		InitializrMetadataProvider metadataProvider = Mockito.mock(InitializrMetadataProvider.class);
		AbstractMetadataController controller = new AbstractMetadataController(metadataProvider);
		String sameContent = "Same Content";

		String firstResult = controller.createUniqueId(sameContent);
		String secondResult = controller.createUniqueId(sameContent);
		Assertions.assertEquals(firstResult, secondResult);
	}

}