/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=generateAppUrl_c0bd08f76a
ROOST_METHOD_SIG_HASH=generateAppUrl_952bf58219

"""
  Scenario 1: Test if method generates HTTPS URL when forceSsl is enabled.

  Details:
    TestName: testGenerateHttpsUrl
    Description: This test is designed to confirm that the method correctly generates an HTTPS URL when the forceSsl flag is set to true.
  Execution:
    Arrange: Set up a mock ServletUriComponentsBuilder with a specified scheme (say, "http"). Enable forceSsl to return true when invoked.
    Act: Invoke the generateAppUrl method.
    Assert: Use JUnit assertions to validate if the returned URL uses the HTTPS scheme.
  Validation:
    The assertion verifies that the method correctly switches to "https" when forceSsl is enabled. This test ensures that the forceSsl functionality is working as intended and upholds the application's security.

  Scenario 2: Test if method generates HTTP URL when forceSsl is disabled.

  Details:
    TestName: testGenerateHttpUrl
    Description: This test checks the functionality of generateAppUrl when the forceSsl flag is not enabled.
  Execution:
    Arrange: Set up a mock ServletUriComponentsBuilder with a specified scheme (say, "http"). Make sure that forceSsl returns false when invoked.
    Act: Invoke the generateAppUrl method.
    Assert: Use JUnit assertions to validate if the returned URL uses the HTTP scheme.
  Validation:
    The assertion checks that the method doesn't switch to "https" when forceSsl is not enabled. This test verifies the correct behavior of the method under standard operation without forced SSL.

  Scenario 3: Test if method throws NullPointerException when ServletUriComponentsBuilder and forceSsl are null.

  Details:
    TestName: testNullPointerScenario
    Description: This test is meant to check the exception handling of the system when null values are passed to the generateAppUrl method.
  Execution:
    Arrange: Set forceSsl and ServletUriComponentsBuilder to return null.
    Act: Invoke the generateAppUrl method.
    Assert: Use JUnit assertions to verify if a NullPointerException is thrown.
  Validation:
    This assertion ensures that the method has appropriate exception handling mechanism and doesn't fail unexpectedly when provided with null values. It signifies solid and well-rounded coding practices.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;
import org.junit.jupiter.api.*;
import java.nio.charset.StandardCharsets;
import org.springframework.util.DigestUtils;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

public class AbstractMetadataControllerGenerateAppUrlTest {

	private AbstractMetadataController controller;

	private InitializrMetadataProvider metadataProvider;

	@BeforeEach
	public void setUp() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		when(metadataProvider.get()).thenReturn(new InitializrMetadata());
		controller = new AbstractMetadataController(metadataProvider);
	}

	@Test
	@Tag("valid")
	public void testGenerateHttpsUrl() {
		MockHttpServletRequest request = new MockHttpServletRequest();
		RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(request));
		when(metadataProvider.get().getConfiguration().getEnv().isForceSsl()).thenReturn(true);
		String expectedUrl = "https://localhost";
		assertEquals(expectedUrl, controller.generateAppUrl());
	}

	@Test
	@Tag("valid")
	public void testGenerateHttpUrl() {
		MockHttpServletRequest request = new MockHttpServletRequest();
		RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(request));
		when(metadataProvider.get().getConfiguration().getEnv().isForceSsl()).thenReturn(false);
		String expectedUrl = "http://localhost";
		assertEquals(expectedUrl, controller.generateAppUrl());
	}

	@Test
	@Tag("invalid")
	public void testNullPointerScenario() {
		assertThrows(NullPointerException.class, () -> controller.generateAppUrl());
		when(metadataProvider.get().getConfiguration().getEnv().isForceSsl()).thenReturn(null);
		RequestContextHolder.setRequestAttributes(null);
	}

}