/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesText_dfb5702f29
ROOST_METHOD_SIG_HASH=serviceCapabilitiesText_33f658da89

"""
Scenario 1: Test the condition when userAgent header is Null
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsNull
  Description: This test checks the scenario when the userAgent header is not provided. It should return the result of the generateGenericCapabilities method.
Execution:
  Arrange: Create mock objects for the InitializrMetadata and CommandLineHelpGenerator. Set the metadataProvider to return mocked InitializrMetadata. Also, mock the generateGenericCapabilities method to return a dummy response.
  Act: Call the serviceCapabilitiesText method with null userAgent.
  Assert: Verify that the generateGenericCapabilities method called and assert that the return body is the expected response.
Validation:
  The assertion verifies that the system can handle requests without the userAgent header and provide the default functionality. This is significant as it shows the system can handle requests even in case if userAgent header is missing.

Scenario 2: Test the condition when userAgent is "CURL"
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsCurl
  Description: This test case checks if the system correctly identifies the CURL userAgent and calls the respective method for CURL capabilities.
Execution:
  Arrange: Mock agent for the userAgent "CURL" and also mock the generateCurlCapabilities method to return a dummy response.
  Act: Call the serviceCapabilitiesText method with "CURL" userAgent.
  Assert: Verify that the generateCurlCapabilities method called and assert returned body as the expected response.
Validation:
  This test verifies if the system correctly identifies the CURL userAgent and gets the CURL capabilities. This functionality is key as it tailors the response based on the user's environment.

Scenario 3: Test the condition when userAgent is "HTTPIE"
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsHttpie
  Description: This test case checks if the system correctly identifies the HTTPIE userAgent and calls the respective method for HTTPIE capabilities.
Execution:
  Arrange: Mock agent for the userAgent "HTTPIE" and also mock the generateHttpieCapabilities method to return a dummy response.
  Act: Call the serviceCapabilitiesText method with "HTTPIE" userAgent.
  Assert: Verify that the generateHttpieCapabilities method is called and assert returned body as the expected response.
Validation:
  This scenario verifies that the method accurately identifies the HTTPIE userAgent and uses the respective method to get the capabilities. This approach personalizes the response based on the client's environment.

Scenario 4: Test the condition when userAgent is "SPRING_BOOT_CLI"
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsSpringBootCli
  Description: This test case checks if the system correctly identifies the SPRING_BOOT_CLI userAgent and calls the respective method for SPRING_BOOT_CLI capabilities.
Execution:
  Arrange: Mock agent for the userAgent "SPRING_BOOT_CLI". Also, mock the generateSpringBootCliCapabilities method to return a dummy response.
  Act: Call the serviceCapabilitiesText method with "SPRING_BOOT_CLI" userAgent.
  Assert: Verify that the generateSpringBootCliCapabilities method called and assert returned body as expected response.
Validation:
  The test validates that the system correctly identifies the SPRING_BOOT_CLI userAgent and provides the SPRING_BOOT_CLI capabilities. This test ensures the system can provide personalized content based on the user environment.

Scenario 5: Test when userAgent value is not recognized
Details:
  TestName: testServiceCapabilitiesTextWhenUserAgentIsUnrecognized
  Description: This test checks the scenario when the userAgent is unrecognized or unsupported. The system should fallback to generateGenericCapabilities method in such cases.
Execution:
  Arrange: Set an unrecognized userAgent value and mock generateGenericCapabilities method to return a dummy response.
  Act: Invoke serviceCapabilitiesText method with the unrecognized userAgent.
  Assert: Verify that generateGenericCapabilities method called and assert that the return body is as expected.
Validation:
  This scenario ensures that the system can handle unrecognized or unsupported userAgents gracefully by providing generic capabilities. This functionality is crucial for maintaining robustness against varied client environments.
"""
Note: Replace "dummy response" and "expected response" with actual values in real-world testing situations. Also, add the necessary error handling and edge cases based on the specific business requirements.
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.http.ResponseEntity;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.support.Agent;
import io.spring.initializr.web.support.Agent.AgentId;
import io.spring.initializr.generator.io.template.TemplateRenderer;
import io.spring.initializr.web.support.CommandLineHelpGenerator;
import org.springframework.http.HttpHeaders;
import java.io.IOException;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity.BodyBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RestController;

public class CommandLineMetadataControllerServiceCapabilitiesTextTest {

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsNull() throws IOException {
		String testContent = "testContent";
		String testUrl = "http://test.com";
		CommandLineHelpGenerator commandLineHelpGenerator = mock(CommandLineHelpGenerator.class);
		when(commandLineHelpGenerator.generateGenericCapabilities(any(), eq(testUrl))).thenReturn(testContent);
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		when(metadataProvider.get()).thenReturn(mock(InitializrMetadata.class));
		CommandLineMetadataController controller = new CommandLineMetadataController(metadataProvider,
				mock(TemplateRenderer.class));
		controller.commandLineHelpGenerator = commandLineHelpGenerator;
		ResponseEntity<String> response = controller.serviceCapabilitiesText(null);
		assertEquals(testContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsCurl() throws IOException {
		String testContent = "curlTestContent";
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		CommandLineHelpGenerator commandLineHelpGenerator = mock(CommandLineHelpGenerator.class);
		when(commandLineHelpGenerator.generateCurlCapabilities(any(), any())).thenReturn(testContent);
		CommandLineMetadataController controller = new CommandLineMetadataController(metadataProvider,
				mock(TemplateRenderer.class));
		controller.commandLineHelpGenerator = commandLineHelpGenerator;
		ResponseEntity<String> response = controller.serviceCapabilitiesText(AgentId.CURL.getName());
		assertEquals(testContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsHttpie() throws IOException {
		String testContent = "httpieTestContent";
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		CommandLineHelpGenerator commandLineHelpGenerator = mock(CommandLineHelpGenerator.class);
		when(commandLineHelpGenerator.generateHttpieCapabilities(any(), any())).thenReturn(testContent);
		CommandLineMetadataController controller = new CommandLineMetadataController(metadataProvider,
				mock(TemplateRenderer.class));
		controller.commandLineHelpGenerator = commandLineHelpGenerator;
		ResponseEntity<String> response = controller.serviceCapabilitiesText(AgentId.HTTPIE.getName());
		assertEquals(testContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesTextWhenUserAgentIsSpringBootCli() throws IOException {
		String testContent = "springBootCliTestContent";
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		CommandLineHelpGenerator commandLineHelpGenerator = mock(CommandLineHelpGenerator.class);
		when(commandLineHelpGenerator.generateSpringBootCliCapabilities(any(), any())).thenReturn(testContent);
		CommandLineMetadataController controller = new CommandLineMetadataController(metadataProvider,
				mock(TemplateRenderer.class));
		controller.commandLineHelpGenerator = commandLineHelpGenerator;
		ResponseEntity<String> response = controller.serviceCapabilitiesText(AgentId.SPRING_BOOT_CLI.getName());
		assertEquals(testContent, response.getBody());
	}

	@Test
	@Tag("invalid")
	public void testServiceCapabilitiesTextWhenUserAgentIsUnrecognized() throws IOException {
		String testContent = "unrecognizedTestContent";
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		CommandLineHelpGenerator commandLineHelpGenerator = mock(CommandLineHelpGenerator.class);
		when(commandLineHelpGenerator.generateGenericCapabilities(any(), any())).thenReturn(testContent);
		CommandLineMetadataController controller = new CommandLineMetadataController(metadataProvider,
				mock(TemplateRenderer.class));
		controller.commandLineHelpGenerator = commandLineHelpGenerator;
		ResponseEntity<String> response = controller.serviceCapabilitiesText("unrecognized");
		assertEquals(testContent, response.getBody());
	}

}