/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesText_6ba8701e1b
ROOST_METHOD_SIG_HASH=serviceCapabilitiesText_dce8efd552


Scenario 1: Verify response when 'User-Agent' is null

Details:
  TestName: nullUserAgentResponse
  Description: This test checks the behavior of the method when the `User-Agent` header is not provided (null). It ensures the method generates generic capabilities in this case.

Execution:
  Arrange: Set up an instance of the `CommandLineMetadataController` with a mock `metadataProvider` and `commandLineHelpGenerator`. Pass `null` as the `userAgent` parameter.
  Act: Invoke the `serviceCapabilitiesText` method with a null `User-Agent`.
  Assert: Assert that the response body contains the generic capabilities text and the response has the correct `eTag`.

Validation:
  Validate that the application falls back to the generic capabilities when no `User-Agent` is provided. This ensures consistent behavior in cases where the client does not identify themselves explicitly.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import io.spring.initializr.generator.io.template.TemplateRenderer;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.support.Agent;
import io.spring.initializr.web.support.Agent.AgentId;
import io.spring.initializr.web.support.CommandLineHelpGenerator;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import java.io.IOException;
import org.junit.jupiter.api.*;
import org.springframework.http.ResponseEntity.BodyBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RestController;

class CommandLineMetadataControllerServiceCapabilitiesTextTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private CommandLineHelpGenerator commandLineHelpGenerator;

	@InjectMocks
	private CommandLineMetadataController controller;

	CommandLineMetadataControllerServiceCapabilitiesTextTest() {
		TemplateRenderer templateRenderer = mock(TemplateRenderer.class);
		MockitoAnnotations.openMocks(this);
		this.controller = new CommandLineMetadataController(metadataProvider, templateRenderer);
	}

	@Test
	@Tag("valid")
	public void nullUserAgentResponse() throws IOException {
		// Arrange
		String appUrl = "http://dummy-url.test"; // TODO replace with dynamic URL in
													// integration tests
		String content = "Generic capabilities content"; // TODO replace with actual
															// expected content
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		when(controller.generateAppUrl()).thenReturn(appUrl);
		when(commandLineHelpGenerator.generateGenericCapabilities(metadataMock, appUrl)).thenReturn(content);
		when(controller.createUniqueId(content)).thenReturn("dummy-etag");
		// Act
		ResponseEntity<String> response = controller.serviceCapabilitiesText(null);
		// Assert
		assertEquals(MediaType.TEXT_PLAIN, response.getHeaders().getContentType());
		assertEquals("dummy-etag", response.getHeaders().getETag());
		assertEquals(content, response.getBody());
	}

	@Test
	@Tag("valid")
	public void curlUserAgentResponse() throws IOException {
		// Arrange
		String userAgent = "curl/7.64.1"; // TODO replace with simulated agent inputs
		String appUrl = "http://dummy-url.test"; // TODO replace with dynamic URL in
													// integration tests
		String content = "Curl capabilities content"; // TODO replace with actual expected
														// content
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		Agent agentMock = mock(Agent.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		when(controller.generateAppUrl()).thenReturn(appUrl);
		when(commandLineHelpGenerator.generateCurlCapabilities(metadataMock, appUrl)).thenReturn(content);
		when(controller.createUniqueId(content)).thenReturn("dummy-etag");
		when(Agent.fromUserAgent(userAgent)).thenReturn(agentMock);
		when(agentMock.getId()).thenReturn(AgentId.CURL);
		// Act
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		// Assert
		assertEquals(MediaType.TEXT_PLAIN, response.getHeaders().getContentType());
		assertEquals("dummy-etag", response.getHeaders().getETag());
		assertEquals(content, response.getBody());
	}

	@Test
	@Tag("invalid")
	public void unknownUserAgentResponse() throws IOException {
		// Arrange
		String userAgent = "unknown-agent"; // TODO replace with simulated agent inputs
		String appUrl = "http://dummy-url.test"; // TODO replace with dynamic URL in
													// integration tests
		String content = "Generic capabilities content"; // TODO replace with actual
															// expected content
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		when(controller.generateAppUrl()).thenReturn(appUrl);
		when(commandLineHelpGenerator.generateGenericCapabilities(metadataMock, appUrl)).thenReturn(content);
		when(controller.createUniqueId(content)).thenReturn("dummy-etag");
		when(Agent.fromUserAgent(userAgent)).thenReturn(null);
		// Act
		ResponseEntity<String> response = controller.serviceCapabilitiesText(userAgent);
		// Assert
		assertEquals(MediaType.TEXT_PLAIN, response.getHeaders().getContentType());
		assertEquals("dummy-etag", response.getHeaders().getETag());
		assertEquals(content, response.getBody());
	}

}