/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesFor_4bd823958e
ROOST_METHOD_SIG_HASH=serviceCapabilitiesFor_28dfd3d1a3

Scenario 1: Test to verify correct MediaType is used in ResponseEntity
Details:
  TestName: verifyCorrectMediaTypeInResponse
  Description: This test is meant to check whether the correct MediaType set based on the 'contentType' parameter is used in the ResponseEntity when the serviceCapabilitiesFor() method is called.
Execution:
  Arrange: Create mock for InitializrMetadataProvider and InitializrMetadata. Set the metadataProvider to return the mock InitializrMetadata. Create an instance of MediaType.
  Act: Call the serviceCapabilitiesFor() method with InitializrMetadataVersion and MediaType as parameters.
  Assert: Check if the MediaType of the ResponseEntity returned is as expected.
Validation:
  The assertion aims to verify if the serviceCapabilitiesFor() method correctly assigns the MediaType in the ResponseEntity it returns. Ensuring this is critical as it defines the format of the data included in the ResponseEntity's body.

Scenario 2: Test when createUniqueId(content) throws exception
Details:
  TestName: handleExceptionWhenCreateUniqueIdFails
  Description: This test is meant to check the serviceCapabilitiesFor() method's behavior when createUniqueId(content) operation throws an exception.
Execution:
  Arrange: Create mock for InitializrMetadataProvider and InitializrMetadata. Set the metadataProvider to return the mock InitializrMetadata. Create an instance of MediaType. Make createUniqueId(content) operation throw an exception.
  Act: Call the serviceCapabilitiesFor() method with InitializrMetadataVersion and MediaType as parameters.
  Assert: Check if the appropriate exception is thrown.
Validation:
  With this test, we ensure that the serviceCapabilitiesFor() method correctly handles exceptions that may be thrown when generateAppUrl() or createUniqueId(content) operations fail. Ensuring proper error handling strategies prevents unmanaged exceptions that lead to an application crash.

Scenario 3: Test to validate CacheControl in the ResponseEntity
Details:
  TestName: validateCacheControlInResponse
  Description: This test is meant to check if the CacheControl set in the ResponseEntity returned by serviceCapabilitiesFor() method is as expected.
Execution:
  Arrange: Create mock for InitializrMetadataProvider and InitializrMetadata. Set the metadataProvider to return the mock InitializrMetadata. Create an instance of MediaType.
  Act: Call the serviceCapabilitiesFor() method with InitializrMetadataVersion and MediaType as parameters.
  Assert: Check if the CacheControl of the ResponseEntity returned is as expected.
Validation:
  This test ensures that the serviceCapabilitiesFor() method sets the appropriate CacheControl values in the ResponseEntity it returns. A correct CacheControl is vital for managing data cache effectively, which is critical for performance.

Scenario 4: Test to ensure correct content is present in the ResponseEntity
Details:
  TestName: verifyResponseBodyContent
  Description: This test checks that the expected content is present in the ResponseEntity's body when the serviceCapabilitiesFor() method is called.
Execution:
  Arrange: Create mock for InitializrMetadataProvider and InitializrMetadata. Set the metadataProvider to return the mock InitializrMetadata. Create an instance of MediaType.
  Act: Call the serviceCapabilitiesFor() method with InitializrMetadataVersion and MediaType as parameters.
  Assert: Check if the content in the ResponseEntity's body is as expected.
Validation:
  This test aims to verify the correctness of data present in the ResponseEntity's body. This is crucial as accurate data must be returned for the correct functioning of the caller's method.
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.*;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import org.junit.jupiter.api.*;
import java.io.IOException;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@ExtendWith(MockitoExtension.class)
class ProjectMetadataControllerServiceCapabilitiesForTest {

	private InitializrMetadataProvider metadataProvider;

	private ProjectMetadataController controller;

	@BeforeEach
	public void setUp() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		controller = new ProjectMetadataController(metadataProvider);
	}

	@AfterEach
	public void tearDown() {
		metadataProvider = null;
		controller = null;
	}

	@Test
	@Tag("valid")
	void verifyCorrectMediaTypeInResponse() {
		MediaType mt = MediaType.APPLICATION_JSON;
		InitializrMetadata returnedMetadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(returnedMetadata);
		ResponseEntity<String> response = controller.serviceCapabilitiesFor(InitializrMetadataVersion.V2_2, mt);
		assertEquals(mt, response.getHeaders().getContentType());
	}

	@Test
	@Tag("invalid")
	void handleExceptionWhenCreateUniqueIdFails() {
		MediaType mt = MediaType.APPLICATION_JSON;
		when(metadataProvider.get()).thenThrow(new RuntimeException());
		Exception exception = assertThrows(RuntimeException.class, () -> {
			controller.serviceCapabilitiesFor(InitializrMetadataVersion.V2_2, mt);
		});
		assertTrue(exception.getMessage().contains("Failed to create unique id"));
	}

	@Test
	@Tag("valid")
	void validateCacheControlInResponse() {
		MediaType mt = MediaType.APPLICATION_JSON;
		InitializrMetadata returnedMetadata = mock(InitializrMetadata.class);
		CacheControl cc = CacheControl.maxAge(2, TimeUnit.HOURS);
		when(metadataProvider.get()).thenReturn(returnedMetadata);
		ResponseEntity<String> response = controller.serviceCapabilitiesFor(InitializrMetadataVersion.V2_2, mt);
		assertTrue(response.getHeaders().getCacheControl().contains(cc.getHeaderValue()));
	}

	@Test
	@Tag("valid")
	void verifyResponseBodyContent() {
		MediaType mt = MediaType.APPLICATION_JSON;
		InitializrMetadata returnedMetadata = mock(InitializrMetadata.class);
		String expectedContent = "";
		when(metadataProvider.get()).thenReturn(returnedMetadata);
		when(returnedMetadata.write()).thenReturn(expectedContent);
		ResponseEntity<String> response = controller.serviceCapabilitiesFor(InitializrMetadataVersion.V2_2, mt);
		assertEquals(expectedContent, response.getBody());
	}

}