/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=config_9959740393
ROOST_METHOD_SIG_HASH=config_becbf164d9

"""
Scenario 1: Test when "config" returns InitializedMetadata successfully.

  Details:
    TestName: testConfigReturnInitializedMetadataSuccessfully.
    Description: This test is meant to check normal behavior on calling the endpoint "/metadata/config".
  Execution:
    Arrange: Mock the metadataProvider and configure it to return a valid InitializrMetadata object.
    Act: Invoke the config() method.
    Assert: Assert that the returned InitializrMetadata object is not null and matches the expected metadata.
  Validation:
    The outcome verifies that the config() method correctly returns the metadata provided by the metadataProvider. This test is crucial for validating normal execution and ensuring that the controller function is operating properly.

Scenario 2: Test when "config" Returns null output.

  Details:
    TestName: testConfigReturnNullOutput.
    Description: The test is meant to check the scenario when the "metadataProvider.get()" method is configured to return null.
  Execution:
    Arrange: Mock the metadataProvider and configure it to return null.
    Act: Invoke the 'config' function.
    Assert: Assert that the returned InitializrMetadata object is null.
  Validation:
    The outcome validates that the 'config' function appropriately handles and returns null when the 'metadataProvider.get()' method does not provide any metadata.

Scenario 3: Test "config" method when "metadataProvider.get()" method throws an exception.

  Details:
    TestName: testConfigWhenMetadataProviderThrowsException.
    Description: This test is meant to check the error handling of the "config" method when the metadata provider throws an unexpected exception.
  Execution:
    Arrange: Mock the metadataProvider and configure it to throw a RuntimeException.
    Act: Invoke the 'config' function.
    Assert: Assert that a RuntimeException is thrown.
  Validation:
    This test validates that the 'config' method appropriately propagates exceptions thrown by the metadataProvider. It is crucial for ensuring proper error handling in the application.

Please note that the number and type of tests can change significantly depending on the exact business and execution logic of the 'metadataProvider' component and other parts of your application.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.any;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@ExtendWith(MockitoExtension.class)
class ProjectMetadataControllerConfigTest {

	private ProjectMetadataController projectMetadataController;

	private InitializrMetadataProvider metadataProvider;

	@BeforeEach
	void init() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		projectMetadataController = new ProjectMetadataController(metadataProvider);
	}

	@Test
	@Tag("valid")
	void testConfigReturnInitializedMetadataSuccessfully() {
		InitializrMetadata expectedMetadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(expectedMetadata);
		InitializrMetadata actualMetadata = projectMetadataController.config();
		assertEquals(expectedMetadata, actualMetadata);
	}

	@Test
	@Tag("invalid")
	void testConfigReturnNullOutput() {
		when(metadataProvider.get()).thenReturn(null);
		InitializrMetadata actualMetadata = projectMetadataController.config();
		assertNull(actualMetadata);
	}

	@Test
	@Tag("boundary")
	void testConfigWhenMetadataProviderThrowsException() {
		when(metadataProvider.get()).thenThrow(RuntimeException.class);
		assertThrows(RuntimeException.class, () -> {
			projectMetadataController.config();
		});
	}

}