/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesV21_bfa2b5a6e7
ROOST_METHOD_SIG_HASH=dependenciesV21_bfa2b5a6e7

"""
  Scenario 1: Test with a valid bootVersion parameter

  Details:
    TestName: testDependenciesV21WithValidBootVersion
    Description: This test scenario is expected to invoke the dependenciesV21 method with a valid bootVersion parameter and check if it indeed returns the expected ResponseEntity.
  Execution:
    Arrange: Mock the InitializrMetadataProvider and DependencyMetadataProvider to return desired stub data upon invocation. Set up a mock bootVersion that is within the valid range.
    Act: Invoke the dependenciesV21 method with aforementioned mock bootVersion.
    Assert: Assert that ResponseEntity returned has the expected HTTP status and body.
  Validation:
    The assertion verifies that the method behaves as expected with valid bootVersion. This is crucial as it confirms the application's ability to fetch dependencies with specified boot versions.


  Scenario 2: Test with null bootVersion parameter

  Details:
    TestName: testDependenciesV21WithNullBootVersion
    Description: This scenario is meant to test dependenciesV21 method when invoked with null bootVersion. If no bootVersion is given, the default boot version should be used.
  Execution:
    Arrange: Mock the InitializrMetadataProvider to return a predefined InitializrMetadata with appropriate default bootVersion.
    Act: Call the dependenciesV21 method with bootVersion as null.
    Assert: Assert that the ResponseEntity returned has the body contents matching the default bootVersion.
  Validation:
    This assertion verifies that if bootVersion is not specifically given, the application correctly uses the default bootVersion. It validates the software's response when parameter value is not provided.


  Scenario 3: Test the behavior with invalid bootVersion parameter

  Details:
    TestName: testDependenciesV21WithInvalidBootVersion
    Description: This scenario checks the behavior of dependenciesV21 method when invoked with an invalid, out-of-range bootVersion, to ensure the method throws the appropriate exception.
  Execution:
    Arrange: Mock the InitializrMetadataProvider to return a desired InitializrMetadata. Also, define an invalid bootVersion that's out of the defined range.
    Act: Invoke the dependenciesV21 method with the aforementioned invalid bootVersion.
    Assert: Use JUnit to assert that the expected InvalidProjectRequestException is thrown.
  Validation:
    Validating that an expected exception is thrown for an invalid bootVersion verifies that the application handles errors thereby maintaining code execution integrity.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidProjectRequestException;
import io.spring.initializr.web.project.ProjectRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import static io.spring.initializr.web.mapper.InitializrMetadataVersion.V2_2;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerDependenciesV21Test {

	@Mock
	private InitializrMetadataProvider initializrMetadataProvider;

	@Mock
	private DependencyMetadataProvider dependencyMetadataProvider;

	private ProjectMetadataController controller;

	@BeforeEach
	public void setUp() {
		MockitoAnnotations.initMocks(this);
		this.controller = new ProjectMetadataController(this.initializrMetadataProvider,
				this.dependencyMetadataProvider);
	}

	@Test
	@Tag("valid")
	public void testDependenciesV21WithValidBootVersion() {
		String bootVersion = "2.1.8";
		when(initializrMetadataProvider.get()).thenReturn(new ProjectRequest(bootVersion));
		ResponseEntity<String> response = this.controller.dependenciesV21(bootVersion);
		assertEquals(HttpStatus.OK, response.getStatusCode());
		verify(initializrMetadataProvider, times(1)).get();
		verify(initializrMetadataProvider, times(1)).get(metadata, effectiveBootVersion);
		assertEquals(bootVersion, response.getBody());
	}

	@Test
	@Tag("boundary")
	public void testDependenciesV21WithNullBootVersion() {
		String defaultBootVersion = "2.1.4";
		when(initializrMetadataProvider.get()).thenReturn(new ProjectRequest(defaultBootVersion));
		ResponseEntity<String> response = this.controller.dependenciesV21(null);
		assertEquals(HttpStatus.OK, response.getStatusCode());
		verify(initializrMetadataProvider, times(1)).get();
		verify(initializrMetadataProvider, times(1)).get(metadata, effectiveBootVersion);
		assertEquals(defaultBootVersion, response.getBody());
	}

	@Test
	@Tag("invalid")
	public void testDependenciesV21WithInvalidBootVersion() {
		String invalidBootVersion = "1.1.1";
		when(initializrMetadataProvider.get()).thenReturn(new ProjectRequest(invalidBootVersion));
		InvalidProjectRequestException ex = assertThrows(InvalidProjectRequestException.class,
				() -> this.controller.dependenciesV21(invalidBootVersion));
		assertEquals("Invalid Spring Boot version", ex.getMessage());
		verify(initializrMetadataProvider, times(1)).get();
		verify(initializrMetadataProvider, times(1)).get(metadata, effectiveBootVersion);
	}

}