/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=determineCacheControlFor_9483f8f769
ROOST_METHOD_SIG_HASH=determineCacheControlFor_f23ff5dce3

"""
Scenario 1: Validate that correct CacheControl set for valid InitializrMetadata.
Details:
  TestName: validateCorrectCacheControlSetForValidMetadata.
  Description: This test is meant to verify that when valid InitializrMetadata is provided, the expected CacheControl is set correctly.
Execution:
  Arrange: Mock an object of type InitializrMetadata.
  Act: Invoke determineCacheControlFor(metadata).
  Assert: Use JUnit assertions to ensure that "CacheControl.maxAge(2, TimeUnit.HOURS)" is returned.
Validation:
  The assertion verifies that the method correctly sets up CacheControl parameters based on given metadata. It is crucial for ensuring that the calculated cache control is correct and will ensure that the metadata will be stored in the cache for the right amount of time.

Scenario 2: Test behaviour when null InitializrMetadata is provided.
Details:
  TestName: handleNullMetadata.
  Description: The test aims to validate how the determineCacheControlFor method reacts when null metadata is passed.
Execution:
  Arrange: Pass a null value as the method's parameter.
  Act: Invoke determineCacheControlFor(null).
  Assert: If no exception handling exists in the method for null values, use JUnit assertions to expect a NullPointerException to be thrown, else if it handles null values, assert the expected behaviour in response to null metadata.
Validation:
  The assertion aims to verify how the method handles a null object. As metadata is essential for cache control determination, handling a null object must either throw an exception or fallback to some default cache control.

Scenario 3: Validate the determineCacheControlFor method in conjunction with other methods like dependenciesFor.
Details:
  TestName: validateCacheControlInDependenciesForMethod.
  Description: The test verifies the role of the determineCacheControlFor method in other methods within the same class, particularly the dependenciesFor method.
Execution:
  Arrange: Mock InitializrMetadata and other needed parameters for dependenciesFor method.
  Act: Invoke dependenciesFor(metadataVersion, bootVersion).
  Assert: Assert that the returned ResponseEntity object has the cache control returned by 'determineCacheControlFor(metadata)'.
Validation:
  This test proves the correct integration and usage of the 'determineCacheControlFor' method with other functions within the same class, ensuring that the cache set by this method is correctly attached to the HTTP response.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import java.time.Duration;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.springframework.http.CacheControl;
import org.springframework.http.ResponseEntity;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadataVersion;
import org.junit.jupiter.api.*;
import java.io.IOException;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerDetermineCacheControlForTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private DependencyMetadataProvider dependencyMetadataProvider;

	private AutoCloseable mockAnnotationsCloseable;

	@InjectMocks
	private ProjectMetadataController controller;

	@BeforeEach
	void setUp() {
		mockAnnotationsCloseable = MockitoAnnotations.openMocks(this);
	}

	@AfterEach
	void tearDown() throws Exception {
		mockAnnotationsCloseable.close();
	}

	@Test
	@Tag("valid")
	void validateCorrectCacheControlSetForValidMetadata() {
		var metadata = Mockito.mock(InitializrMetadata.class);
		var expectedCacheControl = CacheControl.maxAge(2, TimeUnit.HOURS);

		var result = controller.determineCacheControlFor(metadata);

		assertEquals(expectedCacheControl.toHeaderValue(), result.toHeaderValue());
	}

	@Test
	@Tag("invalid")
	void handleNullMetadata() {
		assertThrows(NullPointerException.class, () -> controller.determineCacheControlFor(null));
	}

	@Test
	@Tag("integration")
	void validateCacheControlInDependenciesForMethod() {
		var metadataVersion = InitializrMetadataVersion.V2_1;
		var bootVersion = "2.1.0";
		var metadata = Mockito.mock(InitializrMetadata.class);
		Mockito.when(metadataProvider.get()).thenReturn(metadata);

		var responseEntity = controller.dependenciesFor(metadataVersion, bootVersion);
		assertEquals(CacheControl.maxAge(2, TimeUnit.HOURS).toHeaderValue(),
				responseEntity.getHeaders().getCacheControl());
	}

}