/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesV2_3743e6cc05
ROOST_METHOD_SIG_HASH=serviceCapabilitiesV2_3743e6cc05

"""
Scenario 1 : Validate normal execution of serviceCapabilitiesV2 method
TestName: serviceCapabilitiesV2NormalExecution
Description: This test scenario validates the normal retrieval of service capabilities version 2.
Execution:
- Arrange: None. The test does not require any setup.
- Act: Invoke the method serviceCapabilitiesV2() without any parameters.
- Assert: Assert that the obtained ResponseEntity<String> is not null.
Validation:
- The test verifies that the serviceCapabilitiesV2 method is executing without errors and returning a valid ResponseEntity<String>.
- This test is important to ensure that service capabilities for version 2 are always retrievable.

Scenario 2: Verify MediaType returned by serviceCapabilitiesV2 method
TestName: verifyMediaTypeOfServiceCapabilitiesV2
Description: This test scenario checks that the MediaType returned by the serviceCapabilitiesV2() method is as expected.
Execution:
- Arrange: None. The test does not require any setup.
- Act: Invoke the method serviceCapabilitiesV2() without any parameters.
- Assert: Assert that the MediaType of the obtained ResponseEntity<String> equals "application/vnd.initializr.v2+json".
Validation:
- The test verifies that the serviceCapabilitiesV2 method returns the correct MediaType.
- This check is important to ensure that clients consuming the service are able to handle the returned data format correctly.

Scenario 3: Verify Content (Body) of ResponseEntity returned by serviceCapabilitiesV2 method
TestName: verifyContentOfServiceCapabilitiesV2
Description: This test scenario checks that the content (body) of the ResponseEntity<String> returned by serviceCapabilitiesV2() is not empty.
Execution:
- Arrange: None. The test does not require any setup.
- Act: Invoke the method serviceCapabilitiesV2() without any parameters.
- Assert: Assert that the body of the obtained ResponseEntity<String> is not empty.
Validation:
- The test verifies that the serviceCapabilitiesV2 method returns a non-empty body.
- It is important that we return valid content about the service capabilities for clients that have requested information in version 2.

Scenario 4: Verify HTTP Status OK (200) returned by serviceCapabilitiesV2 method
TestName: verifyHttpStatusOkForServiceCapabilitiesV2
Description: This test scenario checks that the HTTP Status of the ResponseEntity<String> returned by serviceCapabilitiesV2() is OK (200).
Execution:
- Arrange: None. The test does not require any setup.
- Act: Invoke the method serviceCapabilitiesV2() without any parameters.
- Assert: Assert that the HttpStatus of the obtained ResponseEntity<String> is OK (200).
Validation:
- This test verifies that the serviceCapabilitiesV2 method responds with HTTP status 200, meaning that the request was successful.
- This check is critical for monitoring the health and status of the service endpoint.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerServiceCapabilitiesV2Test {

	private final InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);

	private final DependencyMetadataProvider dependencyMetadataProvider = mock(DependencyMetadataProvider.class);

	private final ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
			dependencyMetadataProvider);

	@Test
	@Tag("valid")
	public void serviceCapabilitiesV2NormalExecution() {
		ResponseEntity<String> response = controller.serviceCapabilitiesV2();
		Assertions.assertNotNull(response, "ResponseEntity should not be null");
	}

	@Test
	@Tag("valid")
	public void verifyMediaTypeOfServiceCapabilitiesV2() {
		ResponseEntity<String> response = controller.serviceCapabilitiesV2();
		Assertions.assertEquals("application/vnd.initializr.v2+json", response.getHeaders().getContentType().toString(),
				"MediaType should be 'application/vnd.initializr.v2+json'");
	}

	@Test
	@Tag("valid")
	public void verifyContentOfServiceCapabilitiesV2() {
		ResponseEntity<String> response = controller.serviceCapabilitiesV2();
		Assertions.assertTrue(response.hasBody(), "ResponseEntity body should not be empty");
	}

	@Test
	@Tag("valid")
	public void verifyHttpStatusOkForServiceCapabilitiesV2() {
		ResponseEntity<String> response = controller.serviceCapabilitiesV2();
		Assertions.assertEquals(HttpStatus.OK, response.getStatusCode(), "HttpStatus should be OK (200)");
	}

}