/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=invalidMetadataRequest_5918172e4a
ROOST_METHOD_SIG_HASH=invalidMetadataRequest_6e32ba98b3

"""
Scenario 1: Test the method when InvalidInitializrMetadataException is thrown
Details:
  TestName: invalidMetadataRequestException.
  Description: This test is meant to check whether the 'invalidMetadataRequest' method correctly returns a BAD_REQUEST HTTP status when an InvalidInitializrMetadataException is thrown.
Execution:
  Arrange: Mock the HttpServletResponse and the InvalidInitializrMetadataException with an appropriate message.
  Act: Invoke the 'invalidMetadataRequest' method with the mocked HttpServletResponse and InvalidInitializrMetadataException.
  Assert: Check that the sendError method of the HttpServletResponse object has been called with the appropriate BAD_REQUEST status and the exception message.
Validation:
  The assertion verifies that the correct HTTP status and error message are set in the response when an InvalidInitializrMetadataException is thrown. This is significant in ensuring the right error response structure.

Scenario 2: Test the method when a blank error message is provided in the exception
Details:
  TestName: invalidMetadataRequestBlankMessageException.
  Description: This test is meant to check the behavior of 'invalidMetadataRequest' method when the exception has no/blank message.
Execution:
  Arrange: Mock the HttpServletResponse and the InvalidInitializrMetadataException with a blank message.
  Act: Invoke the 'invalidMetadataRequest' method with the mocked HttpServletResponse and InvalidInitializrMetadataException.
  Assert: Check that the sendError method of the HttpServletResponse object has been called with the appropriate BAD_REQUEST status and the blank message.
Validation:
  This assertion verifies that the method can handle situations where the exception message is blank and set the appropriate HTTP status in the response. This helps ensure that uninformative error messages do not break the application's error handling mechanism.

Scenario 3: Test the method when the method throws an IOException
Details:
  TestName: invalidMetadataRequestThrowsIOException.
  Description: This test is meant to check the behavior of 'invalidMetadataRequest' when the method fails to send the error response and throws an IOException.
Execution:
  Arrange: Arrange the HttpServletResponse mock to throw an IOException when the sendError method is invoked.
  Act: Invoke the 'invalidMetadataRequest' method with the mocked HttpServletResponse and InvalidInitializrMetadataException.
  Assert: Assert that an IOException is thrown.
Validation:
  This assertion verifies that the method throws an IOException when it fails to send the error. This is a crucial part of the error propagation mechanism, ensuring that upper layers are notified when the method fails to execute properly.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.doThrow;
import java.io.IOException;
import jakarta.servlet.http.HttpServletResponse;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@ExtendWith(MockitoExtension.class)
public class ProjectMetadataControllerInvalidMetadataRequestTest {

	@Mock
	private HttpServletResponse mockResponse;

	@Mock
	private InvalidInitializrMetadataException mockException;

	public ProjectMetadataControllerInvalidMetadataRequestTest() {
		MockitoAnnotations.initMocks(this);
	}

	@Test
	@Tag("invalid")
	public void invalidMetadataRequestException() throws IOException {
		ProjectMetadataController controller = new ProjectMetadataController(null, null);
		String errorMessage = "Mock error message";
		Mockito.doReturn(errorMessage).when(mockException).getMessage();

		controller.invalidMetadataRequest(mockResponse, mockException);
		verify(mockResponse).sendError(HttpStatus.BAD_REQUEST.value(), errorMessage);
	}

	@Test
	@Tag("boundary")
	public void invalidMetadataRequestBlankMessageException() throws IOException {
		ProjectMetadataController controller = new ProjectMetadataController(null, null);
		Mockito.doReturn("").when(mockException).getMessage();
		controller.invalidMetadataRequest(mockResponse, mockException);
		verify(mockResponse).sendError(HttpStatus.BAD_REQUEST.value(), "");
	}

	@Test
	@Tag("invalid")
	public void invalidMetadataRequestThrowsIOException() {
		ProjectMetadataController controller = new ProjectMetadataController(null, null);
		Mockito.doReturn("Mock error message").when(mockException).getMessage();
		doThrow(new IOException()).when(mockResponse).sendError(HttpStatus.BAD_REQUEST.value(), "Mock error message");
		Assertions.assertThrows(IOException.class, () -> {
			controller.invalidMetadataRequest(mockResponse, mockException);
		});
	}

}