/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=invalidMetadataRequest_2735e59d53
ROOST_METHOD_SIG_HASH=invalidMetadataRequest_1d1fa56ff4


Scenario [1]: Invalid Metadata Request with Valid Exception Message

Details:
  TestName: invalidMetadataRequestWithValidMessage.
  Description: This test checks if the `invalidMetadataRequest` method properly handles a valid `InvalidInitializrMetadataException` and sends an error response with HttpStatus.BAD_REQUEST and the correct exception message.

Execution:
  Arrange: Initialize `HttpServletResponse` mock and create an `InvalidInitializrMetadataException` with a valid message.
  Act: Call the `invalidMetadataRequest` method with the initialized `response` mock and exception object.
  Assert: Verify that the `response.sendError` method is invoked with `HttpStatus.BAD_REQUEST.value()` and the valid exception message.
Validation:
  This test ensures that the method correctly maps the exception scenario to the expected error HTTP response, proving proper integration between exception handling and response management.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.http.HttpStatus;
import org.junit.jupiter.api.*;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerInvalidMetadataRequestTest {

	@Test
	@Tag("invalid")
	public void invalidMetadataRequestWithValidMessage() throws IOException {
		// Arrange
		HttpServletResponse responseMock = Mockito.mock(HttpServletResponse.class);
		String validMessage = "Invalid Metadata Provided.";
		InvalidInitializrMetadataException exception = new InvalidInitializrMetadataException(validMessage);
		ProjectMetadataController controller = new ProjectMetadataController(
				Mockito.mock(InitializrMetadataProvider.class), Mockito.mock(DependencyMetadataProvider.class));

		// Act
		controller.invalidMetadataRequest(responseMock, exception);

		// Assert
		Mockito.verify(responseMock).sendError(HttpStatus.BAD_REQUEST.value(), validMessage);
	}

}