/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesV21_14260ffd96
ROOST_METHOD_SIG_HASH=serviceCapabilitiesV21_14260ffd96

"""
Scenario 1: Test to verify service capabilities of V2.1 version while expecting successful response

Details:
  TestName: testServiceCapabilitiesV21Response
  Description: This test is designed to check if the serviceCapabilitiesV21 method is returning the expected response entity which matches the metadata for the V2.1 version.
Execution:
  Arrange: Mock the InitializrMetadata and ResponseEntity objects.
  Act: Call the serviceCapabilitiesV21 method.
  Assert: Assert that the returned ResponseEntity matches the mock one.
Validation:
  The assertion will verify if the correct entity response is given for the V2.1 version. This test ensures that the appropriate metadata is returned by the method when given the specified version.

Scenario 2: Test to verify whether the correct content-type is set in the response header

Details:
  TestName: testContentTypeInServiceCapabilitiesV21Response
  Description: This test is meant to check if the set content type in the response header of serviceCapabilitiesV21 method matches the type assigned to the V2.1 version.
Execution:
  Arrange: Mock ResponseEntity and set its content type to the one corresponding to V2.1 version.
  Act: Call the serviceCapabilitiesV21 method.
  Assert: Assert that the content type in response header equals the mock content type.
Validation:
  The assertion confirms if the correct content type is set in the response header. This test ensures that the serviceCapabilitiesV21 method does not err in setting the header with the appropriate content type.

Scenario 3: Test to confirm successful caching for service capabilities of V2.1 version

Details:
  TestName: testCachingInServiceCapabilitiesV21
  Description: The test is designed to confirm that the appropriate caching controls are set in the response header when calling serviceCapabilitiesV21 method.
Execution:
  Arrange: Mock CacheControl and ResponseEntity objects and set the cache control to that of the V2.1 version.
  Act: Call the serviceCapabilitiesV21 method.
  Assert: Assert if CacheControl in the response header equals the mock one.
Validation:
  This assertion will validate the correctness of the caching controls for this specific version (V2.1). This is crucial for verifying that caching for the service capabilities of V2.1 version is properly controlled.

Scenario 4: Test to verify handling of invalid metadata

Details:
  TestName: testInvalidMetadataHandlingInServiceCapabilitiesV21
  Description: This test is to ensure that serviceCapabilitiesV21 method throws an exception when provided with invalid metadata.
Execution:
  Arrange: Mock InitializrMetadata with invalid values.
  Act: Call the serviceCapabilitiesV21 method.
  Assert: Expect an InvalidInitializrMetadataException to be thrown.
Validation:
  This test ensures that the serviceCapabilitiesV21 method has the appropriate exception handling logic in place for invalid metadata. It ensures that any issues with the metadata will not go unnoticed.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import java.io.IOException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import org.junit.jupiter.api.*;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerServiceCapabilitiesV21Test {

	private ProjectMetadataController projectMetadataController;

	private InitializrMetadataProvider initializrMetadataProvider = mock(InitializrMetadataProvider.class);

	private DependencyMetadataProvider dependencyMetadataProvider = mock(DependencyMetadataProvider.class);

	private HttpHeaders responseHeaders = new HttpHeaders();

	@BeforeEach
	public void setUp() {
		projectMetadataController = new ProjectMetadataController(initializrMetadataProvider,
				dependencyMetadataProvider);
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesV21Response() {
		ResponseEntity<String> mockResponseEntity = mock(ResponseEntity.class);
		when(initializrMetadataProvider.get()).thenReturn(mock(InitializrMetadata.class));
		when(mockResponseEntity.getBody()).thenReturn("testMetadata");

		ResponseEntity<String> responseEntity = projectMetadataController.serviceCapabilitiesV21();
		assertEquals(mockResponseEntity.getBody(), responseEntity.getBody());
	}

	@Test
	@Tag("valid")
	public void testContentTypeInServiceCapabilitiesV21Response() {
		responseHeaders.setContentType(InitializrMetadataVersion.V2_1.getMediaType());
		ResponseEntity<String> responseEntity = projectMetadataController.serviceCapabilitiesV21();
		assertEquals(responseHeaders.getContentType(), responseEntity.getHeaders().getContentType());
	}

	@Test
	@Tag("valid")
	public void testCachingInServiceCapabilitiesV21() {
		String cache = CacheControl.noCache().getHeaderValue();
		responseHeaders.add(HttpHeaders.CACHE_CONTROL, cache);
		ResponseEntity<String> responseEntity = projectMetadataController.serviceCapabilitiesV21();

		assertEquals(responseHeaders.getCacheControl(), responseEntity.getHeaders().getCacheControl());
	}

	@Test
	@Tag("invalid")
	public void testInvalidMetadataHandlingInServiceCapabilitiesV21() {
		when(initializrMetadataProvider.get()).thenThrow(new InvalidProjectRequestException("Invalid metadata"));
		assertThrows(InvalidProjectRequestException.class, () -> {
			projectMetadataController.serviceCapabilitiesV21();
		});
	}

}