/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesV22_76bdf67242
ROOST_METHOD_SIG_HASH=serviceCapabilitiesV22_76bdf67242

"""
Scenario 1: Validate Service Capabilities V2.2 Normal Flow
  Details:
    TestName: validateServiceCapabilitiesV22NormalFlow
    Description: This test checks if the serviceCapabilitiesV22() method will return the desired service capabilities for the specified initializr metadata version (V2.2) under normal conditions.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_2 and pass it to the serviceCapabilitiesV22() method.
    Act: Invoke the serviceCapabilitiesV22() method.
    Assert: Assert that the returned ResponseEntity object's body is not null and the content-type is "application/vnd.initializr.v2.2+json"
  Validation:
    The assertion checks that the appropriate ResponseEntity is returned from the serviceCapabilitiesV22 method. The expected result is based on passing a valid Initializr Metadata Version.

Scenario 2: Validate Service Capabilities V2.2 Return MediaType
  Details:
    TestName: validateServiceCapabilitiesV22MediaType
    Description: This test is designed to validate that the MediaType returned from the serviceCapabilitiesV22() method is the one expected for V2.2.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_2 and pass that as an argument of the serviceCapabilitiesV22() method.
    Act: Invoke the serviceCapabilitiesV22() method.
    Assert: Assert that the MediaType in the returned ResponseEntity object is "application/vnd.initializr.v2.2+json"
  Validation:
    The test verifies if the MediaType produced by the method serviceCapabilitiesV22 is "application/vnd.initializr.v2.2+json", thus confirming that the expected MediaType is being used.

Scenario 3: Validate Service Capabilities V2.2 Body Type
  Details:
    TestName: validateServiceCapabilitiesV22BodyType
    Description: This test verifies if the body of the ResponseEntity returned by the serviceCapabilitiesV22() method is of String type.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_2 and pass that as an argument of the serviceCapabilitiesV22() method.
    Act: Invoke the serviceCapabilitiesV22() method.
    Assert: Assert that the body of the returned ResponseEntity object is of String type.
  Validation:
    This test ensures that the serviceCapabilitiesV22 method returns a ResponseEntity with a body of string type as expected in function's signature.

Scenario 4: Validate Service Capabilities V2.2 Response Code
  Details:
    TestName: validateServiceCapabilitiesV22ResponseCode
    Description: This test aims to validate that the ResponseEntity returned from the serviceCapabilitiesV22() method has a HTTP status code of OK (200).
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_2 and pass that as an argument of the serviceCapabilitiesV22() method.
    Act: Invoke the serviceCapabilitiesV22() method.
    Assert: Assert that the HttpStatus in the returned ResponseEntity object is HttpStatus.OK.
  Validation:
    The assertion confirms that the ResponseEntity returned by the serviceCapabilitiesV22 method has a HTTP status code of OK (200). The expected result is ensured by passing a valid Initializr Metadata Version.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@Tag("integration")
class ProjectMetadataControllerServiceCapabilitiesV22Test {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	private ResponseEntity<String> responseEntity;

	@Test
	@Tag("valid")
	void validateServiceCapabilitiesV22NormalFlow() {
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider, null);
		responseEntity = controller.serviceCapabilitiesV22();

		assertNotNull(responseEntity.getBody());
		assertEquals("application/vnd.initializr.v2.2+json", responseEntity.getHeaders().getContentType().toString());
	}

	@Test
	@Tag("valid")
	void validateServiceCapabilitiesV22MediaType() {
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider, null);
		responseEntity = controller.serviceCapabilitiesV22();
		MediaType mediaType = responseEntity.getHeaders().getContentType();

		assertEquals("application/vnd.initializr.v2.2+json", mediaType.toString());
	}

	@Test
	@Tag("valid")
	void validateServiceCapabilitiesV22BodyType() {
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider, null);
		responseEntity = controller.serviceCapabilitiesV22();
		assertTrue(responseEntity.getBody() instanceof String);
	}

	@Test
	@Tag("valid")
	void validateServiceCapabilitiesV22ResponseCode() {
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider, null);
		responseEntity = controller.serviceCapabilitiesV22();
		assertEquals(200, responseEntity.getStatusCodeValue());
	}

}