/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createMetadataJsonMapper_e410ddcb67
ROOST_METHOD_SIG_HASH=createMetadataJsonMapper_d32646c50a

Scenario 1: Create metadata Json mapper v2 for given metadataVersion

  Details:
    TestName: createMetadataJsonMapperForV2.
    Description: The test is meant to check how the createMetadataJsonMapper method reacts when provided with metadataVersion = V2. It is expected to return InitializrMetadataV2JsonMapper.
  Execution:
    Arrange: Initialize the metadataVersion as V2.
    Act: Invoke the createMetadataJsonMapper with V2 as parameter.
    Assert: Assert that the returned object is an instance of InitializrMetadataV2JsonMapper.
  Validation:
    The test validates if the correct mapper object is created when metadata version V2 is passed to the method. If assertion passes, it indicates that the method behaves as expected when provided with V2 metadataVersion.


Scenario 2: Create metadata Json mapper v2_1 for given metadataVersion

  Details:
    TestName: createMetadataJsonMapperForV2_1.
    Description: The test is meant to check how the createMetadataJsonMapper method behaves when provided with metadataVersion = V2_1. It is expected to return InitializrMetadataV21JsonMapper.
  Execution:
    Arrange: Initialize the metadataVersion as V2_1.
    Act: Invoke the createMetadataJsonMapper with V2_1 as parameter.
    Assert: Assert that the returned object is an instance of InitializrMetadataV21JsonMapper.
  Validation:
    The test validates if the correct mapper object is created when metadata version V2_1 is passed to the method. If assertion passes, it indicates that the method behaves as expected when provided with V2_1 metadataVersion.


Scenario 3: Create metadata Json mapper for unsupported metadataVersion

  Details:
    TestName: createMetadataJsonMapperForUnsupportedVersion.
    Description: The test is meant to check how the createMetadataJsonMapper method behaves when provided with unsupported metadataVersion. It is expected to return InitializrMetadataV22JsonMapper as a fallback.
  Execution:
    Arrange: Initialize the metadataVersion with an unsupported version.
    Act: Invoke the createMetadataJsonMapper with unsupported version as parameter.
    Assert: Assert that the returned object is an instance of InitializrMetadataV22JsonMapper.
  Validation:
    The test verifies whether the method adheres to the condition of returning an instance of InitializrMetadataV22JsonMapper when provided with unsupported metadataVersion. If the assertion passes, it means the method follows the fallback condition as expected.
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.InitializrMetadataVersion;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.web.controller.ProjectMetadataController;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrMetadata;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerCreateMetadataJsonMapperTest {

	private ProjectMetadataController controller;

	private DependencyMetadataProvider dependencyMetadataProvider;

	private InitializrMetadataProvider metadataProvider;

	@BeforeEach
	public void setup() {
		metadataProvider = Mockito.mock(InitializrMetadataProvider.class);
		dependencyMetadataProvider = Mockito.mock(DependencyMetadataProvider.class);
		controller = new ProjectMetadataController(metadataProvider, dependencyMetadataProvider);
		Mockito.when(metadataProvider.get()).thenReturn(Mockito.mock(InitializrMetadata.class));
	}

	@Test
	@Tag("valid")
	public void createMetadataJsonMapperForV2() {
		InitializrMetadataJsonMapper result = controller.createMetadataJsonMapper(InitializrMetadataVersion.V2);
		Assertions.assertTrue(result instanceof InitializrMetadataV2JsonMapper);
	}

	@Test
	@Tag("valid")
	public void createMetadataJsonMapperForV2_1() {
		InitializrMetadataJsonMapper result = controller.createMetadataJsonMapper(InitializrMetadataVersion.V2_1);
		Assertions.assertTrue(result instanceof InitializrMetadataV21JsonMapper);
	}

	@Test
	@Tag("valid")
	public void createMetadataJsonMapperForUnsupportedVersion() {
		InitializrMetadataJsonMapper result = controller.createMetadataJsonMapper(InitializrMetadataVersion.V2_2);
		Assertions.assertTrue(result instanceof InitializrMetadataV22JsonMapper);
	}

}