/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesV21_ff95b5882c
ROOST_METHOD_SIG_HASH=dependenciesV21_dfcabe432b

Scenario 1: Validate Response When bootVersion Parameter Is Provided and Valid

Details:
  TestName: responseForValidBootVersion
  Description: This test validates that when a valid bootVersion parameter is provided, the correct response with expected data is returned successfully. It aims to test the application behavior for valid input scenarios.

Execution:
  Arrange: Mock the InitializrMetadataProvider to return appropriate metadata with a given compatibility range. Mock the DependencyMetadataProvider to provide dependency metadata for the valid bootVersion.
  Act: Invoke the `dependenciesV21` method with a valid bootVersion (e.g., "2.5.4").
  Assert: Compare the returned ResponseEntity's content, headers, and HTTP status against expected values.
Validation:
  Verify that the response contains dependency metadata and has the correct content type and HTTP status (200 OK). This test ensures compatibility of bootVersion with the platform's requirements.

---

Scenario 2: Validate Response When No bootVersion Parameter Is Provided

Details:
  TestName: responseWhenBootVersionNotProvided
  Description: This test checks the behavior of the method when no bootVersion parameter is supplied. It validates that the default Spring Boot version is used appropriately.

Execution:
  Arrange: Mock the InitializrMetadataProvider to return metadata with a default bootVersion (e.g., "2.6.3"). Mock the DependencyMetadataProvider to provide dependency metadata for the default bootVersion.
  Act: Invoke the `dependenciesV21` method with a null value for bootVersion.
  Assert: Use assertions to ensure that the response contains dependency metadata for the default bootVersion and has the correct HTTP status.
Validation:
  Validate that the method handles the absence of bootVersion correctly and defaults to the proper bootVersion specified in metadata.

---

Scenario 3: Validate Response When bootVersion Is Incompatible with the Platform

Details:
  TestName: responseForIncompatibleBootVersion
  Description: This test ensures that the method throws an InvalidProjectRequestException when the provided bootVersion is incompatible with the platform's requirements.

Execution:
  Arrange: Mock the InitializrMetadataProvider to return metadata with a defined compatibility range (e.g., "2.4.x - 2.6.x"). Mock the DependencyMetadataProvider but set the compatibility check to fail for the provided bootVersion (e.g., "3.0.0").
  Act: Invoke the `dependenciesV21` method with an incompatible bootVersion.
  Assert: Verify that an InvalidProjectRequestException is thrown with the expected error message.
Validation:
  Confirm that the method correctly identifies incompatible bootVersion and throws an exception, ensuring robust error handling for invalid input.

---

Scenario 4: Validate Media Type of Response

Details:
  TestName: responseHasCorrectMediaType
  Description: Validate that the response returned by the method carries the correct media type associated with version V2_1 ("application/hal+json").

Execution:
  Arrange: Mock the InitializrMetadataProvider to return valid metadata. Mock the DependencyMetadataProvider to provide appropriate dependency metadata.
  Act: Invoke the `dependenciesV21` method with a valid bootVersion or null.
  Assert: Validate that the response has a Content-Type header set to "application/hal+json".
Validation:
  Ensure that the method assigns the correct media type for responses generated with InitializrMetadataVersion.V2_1.

---

Scenario 5: Validate Cache-Control Header in Response

Details:
  TestName: responseIncludesCacheControlHeader
  Description: Ensure that the response returned by the method includes a maximum cache age of 2 hours as specified in the `determineCacheControlFor` method.

Execution:
  Arrange: Mock the InitializrMetadataProvider to return valid metadata with appropriate settings. Mock the DependencyMetadataProvider to provide dependency metadata.
  Act: Invoke the `dependenciesV21` method with any valid bootVersion or null.
  Assert: Check that the Cache-Control header in the response specifies "max-age=7200".
Validation:
  Confirm that caching behavior for the response is configured correctly, optimizing API performance and reducing redundant calls.

---

Scenario 6: Validate ETag Header in Response

Details:
  TestName: responseIncludesETagHeader
  Description: Verify that the response includes the appropriate ETag header to support response validation and caching.

Execution:
  Arrange: Mock the InitializrMetadataProvider and DependencyMetadataProvider to generate dependency metadata. Ensure that the generated content has a unique identifier for the ETag header.
  Act: Invoke the `dependenciesV21` method with any valid bootVersion or null.
  Assert: Validate that the ETag header in the response matches the expected unique ID derived from the content.
Validation:
  Confirm that the ETag header is included to optimize caching and response validation.

---

Scenario 7: Validate Error Handling When MetadataProvider Fails

Details:
  TestName: responseWhenMetadataProviderFails
  Description: Ensure that the method handles errors gracefully when InitializrMetadataProvider fails to provide metadata.

Execution:
  Arrange: Mock the InitializrMetadataProvider to throw an exception when invoked. Do not set up DependencyMetadataProvider.
  Act: Invoke the `dependenciesV21` method and capture the thrown exception.
  Assert: Validate that the correct exception is thrown and the response's status code signifies an internal server error (500).
Validation:
  Confirm that the method responds gracefully to unexpected errors in service dependencies, adhering to robustness principles.

---

Scenario 8: Validate JSON Structure of Dependency Metadata in Response

Details:
  TestName: responseContainsCorrectDependencyJsonStructure
  Description: Ensure that the response payload contains valid JSON representing dependency metadata generated by DependencyMetadataV21JsonMapper.

Execution:
  Arrange: Mock InitializrMetadataProvider and DependencyMetadataProvider to produce valid dependency metadata. Mock the DependencyMetadataV21JsonMapper to generate expected JSON.
  Act: Invoke the `dependenciesV21` method with a valid bootVersion or null.
  Assert: Validate that the JSON structure of the response matches the expected dependency metadata format.
Validation:
  Verify that the response data complies with the expected schema, ensuring compatibility and predictability of the API output.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.*;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import jakarta.servlet.http.HttpServletResponse;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.http.ResponseEntity;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerDependenciesV21Test {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private DependencyMetadataProvider dependencyMetadataProvider;

	@Test
	@Tag("valid")
	public void responseForValidBootVersion() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Platform platform = mock(Platform.class);
		Version version = Version.parse("2.5.4");
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(version)).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, version)).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act
		ResponseEntity<String> response = controller.dependenciesV21("2.5.4");
		// Assert
		assertNotNull(response);
		assertEquals("application/hal+json", response.getHeaders().getContentType().toString());
		assertEquals(200, response.getStatusCodeValue());
	}

	@Test
	@Tag("valid")
	public void responseWhenBootVersionNotProvided() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Version defaultVersion = Version.parse("2.6.3");
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getBootVersions().getDefault().getId()).thenReturn("2.6.3");
		when(dependencyMetadataProvider.get(metadata, defaultVersion)).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act
		ResponseEntity<String> response = controller.dependenciesV21(null);
		// Assert
		assertNotNull(response);
		assertEquals(200, response.getStatusCodeValue());
	}

	@Test
	@Tag("invalid")
	public void responseForIncompatibleBootVersion() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		Platform platform = mock(Platform.class);
		Version incompatibleVersion = Version.parse("3.0.0");
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(incompatibleVersion)).thenReturn(false);
		when(platform.determineCompatibilityRangeRequirement()).thenReturn("2.4.x - 2.6.x");
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act & Assert
		InvalidProjectRequestException exception = assertThrows(InvalidProjectRequestException.class, () -> {
			controller.dependenciesV21("3.0.0");
		});
		assertEquals("Invalid Spring Boot version '3.0.0', Spring Boot compatibility range is 2.4.x - 2.6.x",
				exception.getMessage());
	}

	@Test
	@Tag("valid")
	public void responseHasCorrectMediaType() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(dependencyMetadataProvider.get(metadata, Version.parse("2.5.4"))).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act
		ResponseEntity<String> response = controller.dependenciesV21("2.5.4");
		// Assert
		assertEquals("application/hal+json", response.getHeaders().getContentType().toString());
	}

	@Test
	@Tag("boundary")
	public void responseIncludesCacheControlHeader() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(dependencyMetadataProvider.get(metadata, Version.parse("2.5.4"))).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act
		ResponseEntity<String> response = controller.dependenciesV21("2.5.4");
		// Assert
		assertTrue(response.getHeaders().getCacheControl().contains("max-age=7200"));
	}

	@Test
	@Tag("boundary")
	public void responseIncludesETagHeader() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(dependencyMetadataProvider.get(metadata, Version.parse("2.5.4"))).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act
		ResponseEntity<String> response = controller.dependenciesV21("2.5.4");
		// Assert
		assertNotNull(response.getHeaders().getETag());
	}

	@Test
	@Tag("invalid")
	public void responseWhenMetadataProviderFails() {
		// Arrange
		when(metadataProvider.get()).thenThrow(new RuntimeException("Metadata provider error"));
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			controller.dependenciesV21("2.5.4");
		});
		assertEquals("Metadata provider error", exception.getMessage());
	}

	@Test
	@Tag("valid")
	public void responseContainsCorrectDependencyJsonStructure() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(dependencyMetadataProvider.get(metadata, Version.parse("2.5.4"))).thenReturn(dependencyMetadata);
		ProjectMetadataController controller = new ProjectMetadataController(metadataProvider,
				dependencyMetadataProvider);
		DependencyMetadataV21JsonMapper mapper = mock(DependencyMetadataV21JsonMapper.class);
		when(mapper.write(dependencyMetadata))
			.thenReturn("{\"dependencies\":[{\"id\":\"spring-boot\",\"name\":\"Spring Boot\"}]}");
		// Act
		ResponseEntity<String> response = controller.dependenciesV21("2.5.4");
		// Assert
		assertTrue(response.getBody().contains("\"dependencies\""));
	}

}