/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesV22_5591217b85
ROOST_METHOD_SIG_HASH=dependenciesV22_2abc1e8737

Scenario 1: Test to check if the method correctly handles a null boot version
Details:
  TestName: shouldHandleNullBootVersion
  Description: This test examines if the dependenciesV22 method can handle a null boot version. This would typically represent a scenario where a boot version is not provided upon the method invocation.
Execution:
  Arrange: A null argument for bootVersion should be initialized.
  Act: Call the dependenciesV22 method with this null argument.
  Assert: The result should be checked for any unexpected exceptions or states that should not exist when the boot version is not provided.
Validation:
  Assertion aims to verify if the method can handle a situation where bootVersion is not provided. This depicts the flexibility of the method to default to a setting when input is not provided.

Scenario 2: Test to check the method's response with a valid bootVersion string
Details:
  TestName: shouldReturnResponsEntityForValidBootVersion
  Description: This test checks if the dependenciesV22 method returns the correct ResponseEntity when a valid bootVersion string is provided.
Execution:
  Arrange: A valid bootVersion string that conforms to the expected format.
  Act: Call the method with this bootVersion string as an argument.
  Assert: Checks whether the returned ResponseEntity contains the correct and expected information.
Validation:
  Ensure that the ResponseEntity returned matches expectations by asserting that the body, HttpStatus and headers are as expected. This is vital to the method’s functionality as it's the main API response returned to the client.

Scenario 3: Test to check the method's response with an invalid bootVersion string
Details:
  TestName: shouldThrowExceptionForInvalidBootVersion
  Description: This test verifies if the dependenciesV22 method throws an InvalidProjectRequestException when an invalid bootVersion string is provided.
Execution:
  Arrange: An invalid bootVersion string that does not conform to the expected format.
  Act: Call the method with this bootVersion string as an argument.
  Assert: An InvalidProjectRequestException is expected to be thrown.
Validation:
  Verifies the method's ability to handle and respond appropriately to invalid inputs. It's fundamental to validating bootVersion inputs before processing.

Scenario 4: Test to check if the method respects the cache control settings
Details:
  TestName: shouldRespectCacheControlSettings
  Description: This test ensures that the cacheControl settings indicated by the dependenciesV22 method in the ResponseEntity headers are acknowledged and used.
Execution:
  Arrange: A valid bootVersion string.
  Act: Call the dependenciesV22 method with the bootVersion string as an argument.
  Assert: The ResponseEntity returned should have headers that designate a cacheControl with max age set to 2 hours.
Validation:
  Validate if the method correctly sets cache control configurations in the HTTP response, which could be crucial for efficient resource usage and response management in a real-world enterprise application.
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@ExtendWith(MockitoExtension.class)
public class ProjectMetadataControllerDependenciesV22Test {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	private ProjectMetadataController controller;

	@BeforeEach
	public void setup() {
		controller = new ProjectMetadataController(metadataProvider, null);
	}

	@Test
	@DisplayName("Handle null boot version")
	@Tag("valid")
	public void shouldHandleNullBootVersion() {
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		assertDoesNotThrow(() -> controller.dependenciesV22(null));
	}

	@Test
	@DisplayName("Returns correct ResponseEntity when provided a valid bootVersion")
	@Tag("valid")
	public void shouldReturnResponsEntityForValidBootVersion() {
		String bootVersion = "2.2.1.RELEASE";
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		ResponseEntity<String> response = controller.dependenciesV22(bootVersion);
		assertNotNull(response);
		assertEquals(HttpStatus.OK, response.getStatusCode());
		assertTrue(response.hasBody());
	}

	@Test
	@DisplayName("Throws InvalidProjectRequestException when provided an invalid bootVersion")
	@Tag("invalid")
	public void shouldThrowExceptionForInvalidBootVersion() {
		String bootVersion = "3.0.0.M2";
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		assertThrows(InvalidProjectRequestException.class, () -> controller.dependenciesV22(bootVersion));
	}

	@Test
	@DisplayName("Respects CacheControl settings")
	@Tag("integration")
	public void shouldRespectCacheControlSettings() {
		String bootVersion = "2.2.1.RELEASE";
		InitializrMetadata metadataMock = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadataMock);
		ResponseEntity<String> responseEntity = controller.dependenciesV22(bootVersion);
		assertNotNull(responseEntity);
		assertTrue(responseEntity.getHeaders().containsKey("Cache-Control"));
		assertEquals("max-age=7200", responseEntity.getHeaders().getFirst("Cache-Control"));
	}

}