/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesFor_bfb710c364
ROOST_METHOD_SIG_HASH=dependenciesFor_b87841a204

"""
  Scenario 1: Test for Allowed BootVersion

  Details:
    TestName: checkAllowedBootVersion
    Description: This test case is created to check that the method returns a response with the expected properties if we supply a bootVersion that is compatible with the platform.
  Execution:
    Arrange: Pass an allowed bootVersion and set up the objects to reflect this configuration.
    Act: Invoke dependenciesFor with the platform-compatible bootVersion.
    Assert: Check that the returned ResponseEntity contains OK status, the expected MediaType, CacheControl with the expected time, unique ETag, and content matching dependency metadata.
  Validation:
    The assertion verifies that if a compatible bootVersion is provided, then the function should return a successful response with a match to the expected values. This is important because it validates the expected successful operation of this function when an allowed bootVersion is supplied.

  Scenario 2: Test for Disallowed BootVersion

  Details:
    TestName: checkDisallowedBootVersion
    Description: This test case is created to check that the function throws an exception when we supply a bootVersion that is not compatible with the platform.
  Execution:
    Arrange: Pass a disallowed bootVersion and set up the objects to reflect this configuration.
    Act: Invoke dependenciesFor with the non-compatible bootVersion.
    Assert: Use junit asserts to verify whether an invalid project request exception is thrown.
  Validation:
    The test confirms that the function rejects an incompatible bootVersion specifier and raises the correct exception. This helps to ensure that incompatible Spring Boot versions are correctly handled and prevented.

  Scenario 3: Empty BootVersion String Test

  Details:
    TestName: checkEmptyBootVersion
    Description: This test case is to verify whether the function behaves correctly when an empty bootVersion string is supplied.
  Execution:
    Arrange: Set up to simulate a condition where bootVersion might be an empty string.
    Act: Invoke dependenciesFor with an empty bootVersion string.
    Assert: Check whether the function works properly, and doesn't raise any exception.
  Validation:
    The assertion checks if the function can handle an empty bootVersion string by using the default bootVersion from the metadata. It is necessary to ensure that the function can handle and automatically resolve unspecified or empty inputs.

  Scenario 4: Null BootVersion String Test

  Details:
    TestName: checkNullBootVersion
    Description: This test case is meant to check whether the function behaves correctly when null is passed for bootVersion.
  Execution:
    Arrange: Set up to reflect a condition where bootVersion is null.
    Act: Call dependenciesFor with null as the bootVersion.
    Assert: Verify whether the function executes without throwing an exception, and returns the expected result.
  Validation:
    The purpose of this validation is to verify that the function handles a null bootVersion by using the default bootVersion from the metadata, and doesn’t produce an error. This ensures that the function is able to handle and resolve null input cases properly.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.ResponseEntity;
import org.springframework.util.Assert;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerDependenciesForTest {

	private InitializrMetadataProvider metadataProvider;

	private DependencyMetadata.Provider dependencyMetadataProvider;

	private ProjectMetadataController controller;

	private InitializrMetadata metadata;

	@BeforeEach
	void setUp() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		dependencyMetadataProvider = mock(DependencyMetadata.Provider.class);
		controller = new ProjectMetadataController(metadataProvider, dependencyMetadataProvider);
		metadata = new InitializrMetadata();
		when(metadataProvider.get()).thenReturn(metadata);
	}

	@Test
	@Tag("valid")
	void checkAllowedBootVersion() {
		String bootVersion = Version.parse("2.1.1").toString();
		Platform platform = new Platform("", Version.parse(bootVersion).getId(), "", "");
		metadata.getConfiguration().getEnv().setPlatform(platform);

		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_2, bootVersion);
		Assert.notNull(response, "Response must not be null");
		Assertions.assertEquals(200, response.getStatusCodeValue(), "HttpStatus code should be 200");
	}

	@Test
	@Tag("invalid")
	void checkDisallowedBootVersion() {
		String bootVersion = Version.parse("2.3.1").toString();
		Platform platform = new Platform("", Version.parse("2.1.1").getId(), "", "");
		metadata.getConfiguration().getEnv().setPlatform(platform);
		Assertions.assertThrows(InvalidProjectRequestException.class,
				() -> controller.dependenciesFor(InitializrMetadataVersion.V2_2, bootVersion));
	}

	@Test
	@Tag("boundary")
	void checkEmptyBootVersion() {
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_2, "");
		Assert.notNull(response, "Response must not be null");
		Assertions.assertEquals(200, response.getStatusCodeValue(), "HttpStatus code should be 200");
	}

	@Test
	@Tag("boundary")
	void checkNullBootVersion() {
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_1, null);
		Assert.notNull(response, "Response must not be null");
		Assertions.assertEquals(200, response.getStatusCodeValue(), "HttpStatus code should be 200");
	}

}