/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createMetadataJsonMapper_e410ddcb67
ROOST_METHOD_SIG_HASH=createMetadataJsonMapper_d32646c50a


Scenario 1: Validate mapper creation for InitializrMetadataVersion.V2

Details:
  TestName: validateMapperForV2
  Description: Ensure that the method `createMetadataJsonMapper` returns an instance of `InitializrMetadataV2JsonMapper` when the parameter `metadataVersion` is set to `InitializrMetadataVersion.V2`.

Execution:
  Arrange: Create an instance of `InitializrMetadataVersion.V2`.
  Act: Invoke the method `createMetadataJsonMapper` with `InitializrMetadataVersion.V2` as the argument.
  Assert: Check that the returned object is an instance of `InitializrMetadataV2JsonMapper`.

Validation:
  Verify that the correct implementation of the mapper for version V2 is created. This ensures the method follows the business logic for handling version-specific operations for InitializrMetadata.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerCreateMetadataJsonMapperTest {

	private final ProjectMetadataController projectMetadataController = new ProjectMetadataController(null, null);

	@Test
	@Tag("valid")
	public void validateMapperForV2() {
		InitializrMetadataJsonMapper result = projectMetadataController
			.createMetadataJsonMapper(InitializrMetadataVersion.V2);
		assertTrue(result instanceof InitializrMetadataV2JsonMapper,
				"Mapper for V2 should be an instance of InitializrMetadataV2JsonMapper");
	}

	@Test
	@Tag("valid")
	public void validateMapperForV21() {
		InitializrMetadataJsonMapper result = projectMetadataController
			.createMetadataJsonMapper(InitializrMetadataVersion.V2_1);
		assertTrue(result instanceof InitializrMetadataV21JsonMapper,
				"Mapper for V2_1 should be an instance of InitializrMetadataV21JsonMapper");
	}

	@Test
	@Tag("valid")
	public void validateMapperForDefaultCaseV22() {
		InitializrMetadataJsonMapper result = projectMetadataController
			.createMetadataJsonMapper(InitializrMetadataVersion.V2_2);
		assertTrue(result instanceof InitializrMetadataV22JsonMapper,
				"Mapper for V2_2 should be an instance of InitializrMetadataV22JsonMapper");
	}

	@Test
	@Tag("boundary")
	public void validateMapperForNullMetadataVersion() {
		// Null case scenario (boundary)
		try {
			InitializrMetadataJsonMapper result = projectMetadataController.createMetadataJsonMapper(null);
			assertTrue(result instanceof InitializrMetadataV22JsonMapper,
					"Default mapper should be of InitializrMetadataV22JsonMapper in null version case");
		}
		catch (Exception e) {
			fail("Exception should not be thrown for null metadata version.");
		}
	}

}