/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesFor_4bd823958e
ROOST_METHOD_SIG_HASH=serviceCapabilitiesFor_28dfd3d1a3


Scenario [1]: Test with valid metadata version and content type

Details:
  TestName: serviceCapabilitiesForValidInput
  Description: This test verifies if the method correctly generates a ResponseEntity when provided with valid `InitializrMetadataVersion` and `MediaType`. It validates proper handling of metadata and response properties including body, content type, ETag, and cache control.

Execution:
  Arrange: Initialize mocks or stubs for `metadataProvider` to return valid `InitializrMetadata`. Prepare valid `metadataVersion` and `contentType` arguments. Ensure auxiliary methods (`createMetadataJsonMapper`, `generateAppUrl`, etc.) return expected values.
  Act: Invoke the `serviceCapabilitiesFor` method using the valid initialized values.
  Assert: Confirm that the returned response body contains the correct metadata. Validate that the content type matches the `MediaType` provided. Verify ETag generation and cache control configuration.

Validation:
  This test ensures the correctness and integrity of the mapping and processing mechanisms for a valid use case. It guarantees that valid inputs produce a consistent and expected `ResponseEntity`.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.mockito.Mock;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.metadata.InitializrMetadataVersion;
import java.util.concurrent.TimeUnit;
import java.io.IOException;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerServiceCapabilitiesForTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private InitializrMetadata metadata;

	@Mock
	private InitializrMetadataJsonMapper metadataJsonMapper;

	private ProjectMetadataController controller;

	@BeforeEach
	public void setUp() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		metadata = mock(InitializrMetadata.class);
		metadataJsonMapper = mock(InitializrMetadataJsonMapper.class);
		controller = new ProjectMetadataController(metadataProvider, null);
	}

	@Test
	@Tag("valid")
	public void serviceCapabilitiesForValidInput() {
		// Arrange
		InitializrMetadataVersion metadataVersion = InitializrMetadataVersion.V2_1; // TODO:
																					// Replace
																					// with
																					// correct
																					// metadata
																					// version
																					// if
																					// needed
		MediaType contentType = MediaType.APPLICATION_JSON; // TODO: Change media type if
															// required
		String appUrl = "http://example.com"; // TODO: Replace with test URL as necessary
		String expectedContent = "{\"key\":\"value\"}";
		when(controller.generateAppUrl()).thenReturn(appUrl);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadataJsonMapper.write(metadata, appUrl)).thenReturn(expectedContent);
		// Act
		ResponseEntity<String> response = controller.serviceCapabilitiesFor(metadataVersion, contentType);
		// Assert
		assertNotNull(response);
		assertEquals(expectedContent, response.getBody());
		assertEquals(contentType, response.getHeaders().getContentType());
		assertNotNull(response.getHeaders().get(HttpHeaders.ETAG));
		assertEquals(TimeUnit.HOURS.toSeconds(2),
				response.getHeaders()
					.getCacheControl()
					.stream()
					.mapToLong(policy -> Integer.parseInt(policy.split("=")[1]))
					.sum());
	}

}