/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesV22_6834be80a5
ROOST_METHOD_SIG_HASH=dependenciesV22_b6a4439c3a


Scenario 1: Valid Spring Boot version provided

Details:
  TestName: validSpringBootVersionProvided
  Description: This test verifies the behavior when a valid `bootVersion` is provided as a parameter to the `dependenciesV22` method. It ensures that the method correctly generates dependency metadata and returns a successful response.
Execution:
  Arrange: Mock the `metadataProvider` and `dependencyMetadataProvider` to provide valid metadata and dependency details. Set up a valid `bootVersion` compatible with the platform.
  Act: Call the `dependenciesV22` method, passing the valid `bootVersion`.
  Assert: Assert that the response is a `ResponseEntity` with status 200, valid content type, and expected body.
Validation:
  The assertion confirms the correct functioning of the method when a valid `bootVersion` is provided. Ensures that dependency metadata is generated accurately and the response is correctly formatted.

Scenario 2: Default Spring Boot version used when `bootVersion` is null

Details:
  TestName: defaultSpringBootVersionUsed
  Description: This test checks the behavior of `dependenciesV22` when `bootVersion` parameter is not provided. It ensures that the default boot version from metadata is used.
Execution:
  Arrange: Mock the `metadataProvider` to return metadata containing a default boot version. Configure the `dependencyMetadataProvider` to return dependency details compatible with the default version.
  Act: Call the `dependenciesV22` method with `bootVersion` set to null.
  Assert: Verify that the response is a `ResponseEntity` with status 200 and contains dependency metadata corresponding to the default boot version.
Validation:
  This test validates that the method correctly handles the absence of `bootVersion` and defaults to the metadata-defined version.

Scenario 3: Invalid Spring Boot version provided

Details:
  TestName: invalidSpringBootVersionProvided
  Description: This test ensures that the `dependenciesV22` method throws an `InvalidProjectRequestException` when an unsupported `bootVersion` is provided.
Execution:
  Arrange: Mock the `metadataProvider` to provide platform configuration with specific compatibility requirements. Set the `bootVersion` to an incompatible version.
  Act: Invoke the `dependenciesV22` method with the invalid `bootVersion`.
  Assert: Use `assertThrows` to verify that `InvalidProjectRequestException` is thrown with the appropriate error message.
Validation:
  The test ensures proper error handling and exception throwing when an unsupported `bootVersion` is passed.

Scenario 4: Media type validation for response

Details:
  TestName: mediaTypeValidationForResponse
  Description: This test validates that the response from `dependenciesV22` has the correct media type as defined by `InitializrMetadataVersion.V2_2`.
Execution:
  Arrange: Mock the `metadataProvider` and `dependencyMetadataProvider` to return valid metadata and dependency details. Define a valid `bootVersion`.
  Act: Call the `dependenciesV22` method with the valid `bootVersion`.
  Assert: Assert that the response's content type matches `InitializrMetadataVersion.V2_2.getMediaType()`.
Validation:
  The test ensures that the media type of the response aligns with the expected version-specific media type.

Scenario 5: Validate eTag generation for response

Details:
  TestName: validateETagGeneration
  Description: This test checks if the response from `dependenciesV22` includes a correct and unique eTag for caching.
Execution:
  Arrange: Mock dependencies to provide metadata and dependency details. Configure a valid `bootVersion` for the test.
  Act: Invoke the `dependenciesV22` method with the valid `bootVersion`.
  Assert: Verify that the response includes a properly generated eTag header.
Validation:
  Ensures that the response is optimized for caching by including a unique identifier in the eTag header.

Scenario 6: Verify cache-control settings

Details:
  TestName: verifyCacheControlSettings
  Description: This test ensures that the `CacheControl` settings in the response from `dependenciesV22` are correctly applied based on metadata configurations.
Execution:
  Arrange: Mock metadata and dependency details for the method. Provide a valid `bootVersion`.
  Act: Call the `dependenciesV22` method with the valid `bootVersion`.
  Assert: Check that the response includes a `Cache-Control` header with `max-age` settings as defined by the `determineCacheControlFor` method.
Validation:
  The test verifies proper caching behavior by ensuring the `CacheControl` settings are applied correctly in the response.

Scenario 7: Generate dependency metadata content validation

Details:
  TestName: generateDependencyMetadataContentValidation
  Description: This test validates that the JSON content generated by the method matches the expected dependency metadata structure and fields.
Execution:
  Arrange: Mock metadata and dependency providers to produce consistent and predefined content. Define a valid `bootVersion`.
  Act: Call the `dependenciesV22` method and retrieve the response body.
  Assert: Compare the response content against the expected JSON structure for dependency metadata.
Validation:
  Ensures that the generated dependency metadata is correctly formatted and includes all expected fields in the JSON output.

Scenario 8: Validate response for large dependency metadata

Details:
  TestName: validateResponseForLargeDependencyMetadata
  Description: This test checks the performance and correctness of the `dependenciesV22` method when the dependency metadata contains a large number of entries.
Execution:
  Arrange: Mock the dependency metadata provider to return a large data set. Provide a valid `bootVersion`.
  Act: Invoke the method with the valid `bootVersion`.
  Assert: Verify that the response status is 200 and the body contains all expected metadata entries correctly.
Validation:
  Ensures the method can handle large dependency metadata sets and produce accurate responses without performance degradation.

Scenario 9: Exception handling for null metadata from provider

Details:
  TestName: handleNullMetadataFromProvider
  Description: This test validates that the `dependenciesV22` method correctly throws an exception when the `metadataProvider` returns null.
Execution:
  Arrange: Mock the `metadataProvider` to return null. Prepare a valid `bootVersion`.
  Act: Call the `dependenciesV22` method.
  Assert: Assert that an appropriate exception is thrown because the metadata is null.
Validation:
  Confirms robust error handling when the `metadataProvider` returns invalid or null data.

Scenario 10: Validate compatibility check logic of platform

Details:
  TestName: validateCompatibilityCheckLogic
  Description: This test ensures that the compatibility check logic for the platform correctly determines whether a `bootVersion` is supported.
Execution:
  Arrange: Mock the platform configuration in the metadata to include specific compatible versions. Provide `bootVersion` as a supported version.
  Act: Invoke the `dependenciesV22` method with the compatible `bootVersion`.
  Assert: Assert that the response is successful and contains metadata for the valid `bootVersion`.
Validation:
  This test ensures that the compatibility check for the platform works as intended and correctly validates `bootVersion`.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.http.CacheControl;
import org.springframework.http.ResponseEntity;
import org.springframework.http.MediaType;
import java.util.concurrent.TimeUnit;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import org.junit.jupiter.api.*;
import java.io.IOException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerDependenciesV22Test {

	private final InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);

	private final DependencyMetadataProvider dependencyMetadataProvider = mock(DependencyMetadataProvider.class);

	private final ProjectMetadataController projectMetadataController = new ProjectMetadataController(metadataProvider,
			dependencyMetadataProvider);

	@Test
	@Tag("valid")
	public void validSpringBootVersionProvided() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version validVersion = Version.parse("2.5.4"); // TODO: Change to a valid version
														// based on the actual setup
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(validVersion)).thenReturn(true);
		when(dependencyMetadataProvider.get(any(), eq(validVersion))).thenReturn(dependencyMetadata);
		String expectedContent = "{\"dependencies\":[]}"; // TODO: Adjust based on actual
															// content generation
		DependencyMetadataJsonMapper mapper = new DependencyMetadataV21JsonMapper();
		when(metadataProvider.get()).thenReturn(metadata);
		// Act
		ResponseEntity<String> response = projectMetadataController.dependenciesV22(validVersion.toString());
		// Assert
		assertEquals(200, response.getStatusCodeValue());
		assertEquals(MediaType.APPLICATION_JSON, response.getHeaders().getContentType());
		assertNotNull(response.getBody());
		assertEquals(expectedContent, response.getBody());
	}

	@Test
	@Tag("valid")
	public void defaultSpringBootVersionUsed() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version defaultVersion = Version.parse("2.5.4"); // TODO: Change to a valid
															// default version based on
															// the metadata configuration
		when(metadata.getBootVersions().getDefault().getId()).thenReturn(defaultVersion.toString());
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(dependencyMetadataProvider.get(metadata, defaultVersion)).thenReturn(dependencyMetadata);
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(defaultVersion)).thenReturn(true);
		String expectedContent = "{\"dependencies\":[]}"; // TODO: Adjust based on actual
															// content generation
		// Act
		ResponseEntity<String> response = projectMetadataController.dependenciesV22(null);
		// Assert
		assertEquals(200, response.getStatusCodeValue());
		assertNotNull(response.getBody());
		assertEquals(expectedContent, response.getBody());
	}

	@Test
	@Tag("invalid")
	public void invalidSpringBootVersionProvided() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version invalidVersion = Version.parse("0.0.0"); // TODO: Adjust to an invalid
															// version based on metadata
															// configuration
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(invalidVersion)).thenReturn(false);
		// Act & Assert
		assertThrows(InvalidProjectRequestException.class,
				() -> projectMetadataController.dependenciesV22(invalidVersion.toString()),
				"Invalid Spring Boot version '0.0.0'");
	}

	@Test
	@Tag("valid")
	public void mediaTypeValidationForResponse() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version validVersion = Version.parse("2.5.4"); // TODO: Change to a valid version
														// based on the actual metadata
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(validVersion)).thenReturn(true);
		when(dependencyMetadataProvider.get(any(), eq(validVersion))).thenReturn(dependencyMetadata);
		// Act
		ResponseEntity<String> response = projectMetadataController.dependenciesV22(validVersion.toString());
		// Assert
		assertEquals(InitializrMetadataVersion.V2_2.getMediaType(), response.getHeaders().getContentType());
	}

	@Test
	@Tag("valid")
	public void validateETagGeneration() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version validVersion = Version.parse("2.3.6.RELEASE"); // TODO: Use valid version
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(validVersion)).thenReturn(true);
		when(dependencyMetadataProvider.get(any(), eq(validVersion))).thenReturn(dependencyMetadata);
		String expectedContent = "{\"dependencies\":[]}"; // TODO: Replace with real
															// expected content
		// Act
		ResponseEntity<String> response = projectMetadataController.dependenciesV22(validVersion.toString());
		// Assert
		assertNotNull(response.getHeaders().getETag());
	}

	@Test
	@Tag("boundary")
	public void verifyCacheControlSettings() {
		// Arrange
		InitializrMetadata metadata = mock(InitializrMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		Version validVersion = Version.parse("2.1.3.RELEASE"); // TODO: Valid version
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		Platform platform = mock(Platform.class);
		when(metadata.getConfiguration().getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(validVersion)).thenReturn(true);
		when(dependencyMetadataProvider.get(any(), eq(validVersion))).thenReturn(dependencyMetadata);
		CacheControl expectedCacheControl = CacheControl.maxAge(2, TimeUnit.HOURS);
		// Act
		ResponseEntity<String> response = projectMetadataController.dependenciesV22(validVersion.toString());
		// Assert
		assertThat(response.getHeaders().getCacheControl()).isEqualTo(expectedCacheControl.getHeaderValue());
	}

}