/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=dependenciesFor_bfb710c364
ROOST_METHOD_SIG_HASH=dependenciesFor_b87841a204


Scenario 1: Validate successful response when valid Spring Boot version is provided

Details:
  TestName: validateSuccessfulResponseWithValidBootVersion
  Description: This test verifies the behavior of the method when a valid Spring Boot version is provided. It checks if the correct dependency metadata is returned in the response with proper HTTP headers.

Execution:
  Arrange: Set up mocks for `InitializrMetadataProvider` to return valid metadata and `DependencyMetadataProvider` to return valid dependency metadata. Provide a compatible Spring Boot version as input to the method.
  Act: Invoke the `dependenciesFor` method with a valid boot version and appropriate `InitializrMetadataVersion`.
  Assert: Assert that the response contains dependency metadata content, the content-type matches the expected media type, and cache-control is correctly set.
Validation:
  Verify that the method correctly processes a valid Spring Boot version and produces a successful HTTP response with metadata and headers, ensuring compatibility checks are bypassed and appropriate data is returned.

---

Scenario 2: Validate default version selection when boot version is null

Details:
  TestName: validateDefaultBootVersionSelection
  Description: This test verifies the behavior of the method when a null boot version is provided. It checks if the default Spring Boot version from the metadata is used successfully.

Execution:
  Arrange: Mock `InitializrMetadataProvider` to return metadata containing a default boot version. Do not pass a boot version to the method (null value).
  Act: Invoke the `dependenciesFor` method with a null boot version and appropriate `InitializrMetadataVersion`.
  Assert: Assert that the response contains dependency metadata content generated using the default boot version, with headers correctly set.
Validation:
  Verify that the default Spring Boot version is used seamlessly when no explicit boot version is provided. This ensures proper fallback handling in cases of null input values.

---

Scenario 3: Validate exception when Spring Boot version is incompatible

Details:
  TestName: handleIncompatibleBootVersionException
  Description: This test verifies that an `InvalidProjectRequestException` is thrown when the provided Spring Boot version is incompatible with the platform.

Execution:
  Arrange: Mock `InitializrMetadataProvider` to return metadata with defined compatibility constraints. Pass an incompatible boot version to the method.
  Act: Invoke the `dependenciesFor` method with an incompatible boot version.
  Assert: Assert that the method throws an `InvalidProjectRequestException` with the correct error message.
Validation:
  Verify correct exception handling when an invalid boot version is encountered, ensuring that invalid project requests are intercepted with meaningful error information.

---

Scenario 4: Validate response with the correct media type based on metadata version

Details:
  TestName: validateResponseMediaType
  Description: This test verifies that the response media type matches the expected media type defined by the `InitializrMetadataVersion` provided in the method parameters.

Execution:
  Arrange: Mock `InitializrMetadataProvider` and `DependencyMetadataProvider` to return valid data. Provide any valid boot version along with a specific `InitializrMetadataVersion`.
  Act: Invoke the `dependenciesFor` method with the specific metadata version and boot version.
  Assert: Assert that the media type in the response matches the expected value for the given `InitializrMetadataVersion`.
Validation:
  Verify that the method correctly establishes the media type of the response based on the metadata version, ensuring compliance with API standards and compatibility.

---

Scenario 5: Validate response caching behavior based on metadata

Details:
  TestName: validateCacheControlHeaders
  Description: This test verifies that the response includes the correct cache control headers defined by the metadata.

Execution:
  Arrange: Mock `InitializrMetadataProvider` to return metadata. Provide valid inputs to the method.
  Act: Invoke the `dependenciesFor` method with any valid metadata version and boot version.
  Assert: Assert that the cache control headers in the response match the expected values (max-age set to 2 hours).
Validation:
  Verify that the cache control behavior in the response is correctly determined based on the metadata, ensuring optimal caching strategy for API consumers.

---

Scenario 6: Validate correct eTag generation for response content

Details:
  TestName: validateUniqueETagGeneration
  Description: This test ensures that the response includes a correctly generated unique eTag for the dependency metadata content.

Execution:
  Arrange: Mock `InitializrMetadataProvider` and `DependencyMetadataProvider` to return valid data. Pass compatible inputs.
  Act: Invoke the `dependenciesFor` method with a valid boot version and metadata version.
  Assert: Assert that the eTag in the response corresponds to the unique hash of the content provided.
Validation:
  Verify the uniqueness and correctness of the eTag in the response, ensuring efficient client-side caching and consistency.

---

Scenario 7: Validate behavior when dependency metadata provider fails

Details:
  TestName: handleDependencyMetadataProviderFailure
  Description: This test verifies that the method handles failures in the `DependencyMetadataProvider` gracefully without crashing.

Execution:
  Arrange: Mock `DependencyMetadataProvider` to throw an exception. Pass valid inputs to the method.
  Act: Invoke the `dependenciesFor` method with a valid boot version and metadata version.
  Assert: Assert that the method handles the exception appropriately without returning a response.
Validation:
  Verify robust error handling within the method when the dependency metadata provider encounters issues, ensuring resilience in API operations.

---

Scenario 8: Validate response when metadata provider fails

Details:
  TestName: handleMetadataProviderFailure
  Description: This test ensures that the method handles failures in the `InitializrMetadataProvider` gracefully without crashing.

Execution:
  Arrange: Mock `InitializrMetadataProvider` to throw an exception. Pass valid inputs to the method.
  Act: Invoke the `dependenciesFor` method with valid metadata version and boot version.
  Assert: Assert that the method handles the exception appropriately without returning a response.
Validation:
  Verify robust error handling within the method when the metadata provider encounters issues, ensuring resilience and application stability.

---

Scenario 9: Validate correct content generation with metadata mapper

Details:
  TestName: validateDependencyJsonMapperContentGeneration
  Description: This test verifies that the `createDependencyJsonMapper` generates correct dependency metadata JSON content for the response.

Execution:
  Arrange: Mock `InitializrMetadataProvider`, `DependencyMetadataProvider`, and the JSON mapper to return valid data. Provide compatible inputs.
  Act: Invoke the `dependenciesFor` method with a valid metadata version and boot version.
  Assert: Assert that the JSON content in the response matches the expected metadata structure generated by the mapper.
Validation:
  Verify that the dependency metadata is correctly serialized into JSON content using the `createDependencyJsonMapper`, ensuring accurate data representation in API responses.

*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.http.ResponseEntity;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrConfiguration;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidProjectRequestException;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ProjectMetadataControllerDependenciesForTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private DependencyMetadataProvider dependencyMetadataProvider;

	@Mock
	private InitializrMetadata metadata;

	@Mock
	private InitializrConfiguration configuration;

	@Mock
	private Platform platform;

	private ProjectMetadataController controller;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		controller = new ProjectMetadataController(metadataProvider, dependencyMetadataProvider);
	}

	@Test
	@Tag("valid")
	public void validateSuccessfulResponseWithValidBootVersion() {
		String bootVersion = "2.5.0";
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(bootVersion))).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, Version.parse(bootVersion))).thenReturn(dependencyMetadata);
		when(new DependencyMetadataV21JsonMapper().write(dependencyMetadata)).thenReturn("dependencyContent");
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_1, bootVersion);
		assertEquals("dependencyContent", response.getBody());
		assertEquals(InitializrMetadataVersion.V2_1.getMediaType(), response.getHeaders().getContentType());
		assertNotNull(response.getHeaders().getCacheControl());
	}

	@Test
	@Tag("boundary")
	public void validateDefaultBootVersionSelection() {
		String defaultBootVersion = "2.5.0";
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getBootVersions().getDefault().getId()).thenReturn(defaultBootVersion);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(defaultBootVersion))).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, Version.parse(defaultBootVersion)))
			.thenReturn(dependencyMetadata);
		when(new DependencyMetadataV21JsonMapper().write(dependencyMetadata)).thenReturn("dependencyContent");
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_1, null);
		assertEquals("dependencyContent", response.getBody());
		assertEquals(InitializrMetadataVersion.V2_1.getMediaType(), response.getHeaders().getContentType());
		assertNotNull(response.getHeaders().getCacheControl());
	}

	@Test
	@Tag("invalid")
	public void handleIncompatibleBootVersionException() {
		String incompatibleBootVersion = "1.0.0";
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(incompatibleBootVersion))).thenReturn(false);
		when(platform.determineCompatibilityRangeRequirement()).thenReturn("2.x");
		InvalidProjectRequestException exception = assertThrows(InvalidProjectRequestException.class, () -> {
			controller.dependenciesFor(InitializrMetadataVersion.V2_1, incompatibleBootVersion);
		});
		assertEquals("Invalid Spring Boot version '1.0.0', Spring Boot compatibility range is 2.x",
				exception.getMessage());
	}

	@Test
	@Tag("valid")
	public void validateResponseMediaType() {
		String bootVersion = "2.5.0";
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(bootVersion))).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, Version.parse(bootVersion))).thenReturn(dependencyMetadata);
		when(new DependencyMetadataV21JsonMapper().write(dependencyMetadata)).thenReturn("dependencyContent");
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_2, bootVersion);
		assertEquals(InitializrMetadataVersion.V2_2.getMediaType(), response.getHeaders().getContentType());
	}

	@Test
	@Tag("valid")
	public void validateCacheControlHeaders() {
		String bootVersion = "2.5.0";
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(bootVersion))).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, Version.parse(bootVersion))).thenReturn(dependencyMetadata);
		when(new DependencyMetadataV21JsonMapper().write(dependencyMetadata)).thenReturn("dependencyContent");
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_2, bootVersion);
		assertNotNull(response.getHeaders().getCacheControl());
	}

	@Test
	@Tag("integration")
	public void validateUniqueETagGeneration() {
		String bootVersion = "2.5.0";
		DependencyMetadata dependencyMetadata = mock(DependencyMetadata.class);
		when(metadataProvider.get()).thenReturn(metadata);
		when(metadata.getConfiguration()).thenReturn(configuration);
		when(configuration.getEnv().getPlatform()).thenReturn(platform);
		when(platform.isCompatibleVersion(Version.parse(bootVersion))).thenReturn(true);
		when(dependencyMetadataProvider.get(metadata, Version.parse(bootVersion))).thenReturn(dependencyMetadata);
		when(new DependencyMetadataV21JsonMapper().write(dependencyMetadata)).thenReturn("dependencyContent");
		ResponseEntity<String> response = controller.dependenciesFor(InitializrMetadataVersion.V2_2, bootVersion);
		assertNotNull(response.getHeaders().getETag());
	}

}