/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=serviceCapabilitiesHal_e1be8cb43c
ROOST_METHOD_SIG_HASH=serviceCapabilitiesHal_e1be8cb43c

"""
  Scenario 1: Validate the HTTP GET request with /metadata/client path and "application/hal+json" content type

  Details:
    TestName: testServiceCapabilitiesHal
    Description: This test is meant to validate that when a HTTP GET request is made to /metadata/client endpoint with "application/hal+json" content type, the serviceCapabilitiesHal() method is invoked and it returns a response of type ResponseEntity<String> with the correct content type.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_1 and MediaType.parseMediaType("application/hal+json")
    Act: Invoke the serviceCapabilitiesHal() method.
    Assert: Use JUnit assertions to check if the returned response is of type ResponseEntity and it has the content type "application/hal+json"
  Validation:
    This assertion verifies that the method serviceCapabilitiesHal correctly handles GET requests to /metadata/client endpoint with "application/hal+json" content type and returns the expected ResponseEntity. This is critical to ensure that the server responds correctly to this type of requests.

  Scenario 2: Validate the handling of InvalidInitializrMetadataException

  Details:
    TestName: testServiceCapabilitiesHalMetadataException
    Description: This test is meant to validate that when an InvalidInitializrMetadataException is thrown during the execution of serviceCapabilitiesHal() method, the appropriate HTTP response status and message are returned.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_1 and MediaType.parseMediaType("application/hal+json") and simulate InvalidInitializrMetadataException.
    Act: Invoke the serviceCapabilitiesHal() method.
    Assert: Use JUnit assertions to check if the exception handler method returns an HTTP response with a BAD_REQUEST status and the correct exception error message.
  Validation:
    This assertion verifies that the method serviceCapabilitiesHal correctly handles InvalidInitializrMetadataException. This ensures that when there's an error in processing the metadata, the client receives an appropriate error message.

  Scenario 3: Validate Cache Control in serviceCapabilitiesHal

  Details:
    TestName: testServiceCapabilitiesHalCacheControl
    Description: This test is meant to validate that when a HTTP GET request is made to /metadata/client endpoint with "application/hal+json" content type, the serviceCapabilitiesHal() method sets the cache control correctly in the response header.
  Execution:
    Arrange: Mock the InitializrMetadataVersion.V2_1 and MediaType.parseMediaType("application/hal+json")
    Act: Invoke the serviceCapabilitiesHal() method.
    Assert: Use JUnit assertions to check if the returned ResponseEntity object has the CacheControl set to maxAge(2, TimeUnit.HOURS)
  Validation:
    This assertion verifies that the serviceCapabilitiesHal method sets the CacheControl correctly in the header of HTTP response. This ensures that correct cache-control headers are sent to clients to maintain efficient and accurate data.
"""


*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.mock;
import java.lang.reflect.Method;
import io.spring.initializr.metadata.DependencyMetadataProvider;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.metadata.InvalidInitializrMetadataException;
import io.spring.initializr.web.mapper.InitializrMetadataVersion;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import io.spring.initializr.generator.version.Version;
import io.spring.initializr.metadata.DependencyMetadata;
import io.spring.initializr.metadata.InitializrConfiguration.Platform;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.web.mapper.DependencyMetadataJsonMapper;
import io.spring.initializr.web.mapper.DependencyMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataJsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV21JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV22JsonMapper;
import io.spring.initializr.web.mapper.InitializrMetadataV2JsonMapper;
import io.spring.initializr.web.project.InvalidProjectRequestException;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

public class ProjectMetadataControllerServiceCapabilitiesHalTest {

	private ProjectMetadataController controller;

	private InitializrMetadataProvider metadataProviderMock;

	private DependencyMetadataProvider dependencyMetadataProviderMock;

	@BeforeEach
	public void setUp() {
		metadataProviderMock = mock(InitializrMetadataProvider.class);
		dependencyMetadataProviderMock = mock(DependencyMetadataProvider.class);
		controller = new ProjectMetadataController(metadataProviderMock, dependencyMetadataProviderMock);
	}

	@AfterEach
	public void tearDown() {
		controller = null;
		metadataProviderMock = null;
		dependencyMetadataProviderMock = null;
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesHal() {
		ResponseEntity<String> response = controller.serviceCapabilitiesHal();
		assertNotNull(response);
		assertEquals("application/hal+json", response.getHeaders().getContentType().toString());
	}

	@Test
	@Tag("invalid")
	public void testServiceCapabilitiesHalMetadataException() {
		when(metadataProviderMock.get()).thenThrow(new InvalidInitializrMetadataException("Test Exception"));

		try {
			ResponseEntity<String> response = controller.serviceCapabilitiesHal();
		}
		catch (InvalidInitializrMetadataException ex) {
			assertEquals("Test Exception", ex.getMessage());
		}
	}

	@Test
	@Tag("valid")
	public void testServiceCapabilitiesHalCacheControl() {
		ResponseEntity<String> response = controller.serviceCapabilitiesHal();
		HttpHeaders headers = response.getHeaders();
		CacheControl control = headers.getCacheControl();
		assertNotNull(control);
		assertTrue(control.getHeaderValue().contains("max-age=" + 2 * 60 * 60));
	}

}