/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=spring_61f83c27b6
ROOST_METHOD_SIG_HASH=spring_61f83c27b6

"""
Scenario 1: Test when SpringCliDistributionController's spring method correctly creates a URL and returns it.

Details:
  TestName: testSpringMethodUrlCreation
  Description: This test is meant to check if the spring method in SpringCliDistributionController correctly creates a URL using the InitializrMetadataProvider and returns it prefixed with 'redirect:'.
Execution:
  Arrange: Mock the behavior of metadataProvider to return a specific, known URL for the 'zip' distribution.
  Act: Invoke the spring method.
  Assert: Ensure that the returned URL is the one that was set in our mock, prefixed with 'redirect:'.
Validation:
  The assertion validates if the spring method is correctly creating and returning a URL using 'zip' as the distribution type. A successful test indicates the controller redirects to the correct URL.

Scenario 2: Test when InitializrMetadataProvider get method returns null.

Details:
  TestName: testSpringMethodWithNullMetadata
  Description: This test is meant to check the behavior of the spring method when the InitializrMetadataProvider returns null.
Execution:
  Arrange: Mock the behavior of metadataProvider.get() to return null.
  Act: Invoke the spring method.
  Assert: Ensure that the returned URL should be 'redirect:null'.
Validation:
  The assertion validates that when metadataProvider.get() is null, it should return redirect:null. It ensures the smooth functioning of the spring method in absence of metadata.

Scenario 3: Test when InitializrMetadataProvider createCliDistributionURl method throws an exception.

Details:
  TestName: testSpringMethodWhenExceptionThrown
  Description: This test checks how the spring method handles situations where an exception is thrown during URL creation.
Execution:
  Arrange: Mock the behavior of metadataProvider to throw an exception when attempting to create a distribution URL.
  Act: Invoke the spring method.
  Assert: Expect the exception to propagate, or handle appropriately and return a specific known error message.
Validation:
  The test checks if the spring method catches and handles thrown exceptions properly. A successful test indicates robust error handling in the spring method which is necessary for stability.
  """
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.junit.jupiter.api.*;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

public class SpringCliDistributionControllerSpringTest {

	private InitializrMetadataProvider metadataProvider;

	private SpringCliDistributionController controller;

	@BeforeEach
	public void setup() {
		metadataProvider = mock(InitializrMetadataProvider.class);
		controller = new SpringCliDistributionController(metadataProvider);
	}

	@Test
	@Tag("validScenario")
	public void testSpringMethodUrlCreation() {
		// Arrange
		String testUrl = "testUrl";
		when(metadataProvider.get()).thenReturn(mock(InitializrMetadata.class));
		when(metadataProvider.get().createCliDistributionURl("zip")).thenReturn(testUrl);
		// Act
		String resultUrl = controller.spring();
		// Assert
		assertEquals("redirect:" + testUrl, resultUrl);
	}

	@Test
	@Tag("invalidScenario")
	public void testSpringMethodWithNullMetadata() {
		// Arrange
		when(metadataProvider.get()).thenReturn(null);
		// Act
		String resultUrl = controller.spring();
		// Assert
		assertEquals("redirect:null", resultUrl);
	}

	@Test
	@Tag("boundaryScenario")
	public void testSpringMethodWhenExceptionThrown() {
		// Arrange
		when(metadataProvider.get()).thenThrow(new RuntimeException("Test exception"));
		// Act and Assert
		assertThrows(RuntimeException.class, () -> controller.spring());
	}

}