/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=springTgz_05998713f7
ROOST_METHOD_SIG_HASH=springTgz_05998713f7

"""
Scenario 1: Testing the URL redirection with successful output

TestName: testSuccessfulUrlRedirection
Description: This test validates the URL redirection based on the input provided.
Execution:
  Arrange: Mock the InitializrMetadataProvider to return some predefined URL upon invocation.
  Act: Invoke the method springTgz and capture its return value.
  Assert: Verify that the return value starts with "redirect:" and contains the predefined URL.
Validation:
  This test validates that the method springTgz correctly forms a redirection URL using the InitializrMetadataProvider's URL. The expected result is due to the predefined return value of the mocked InitializrMetadataProvider and the method's logic of prepending "redirect:" to it.

Scenario 2: Testing the URL redirection with empty URL

TestName: testUrlRedirectionWithEmptyUrl
Description: This test checks the URL redirection when an empty URL is provided.
Execution:
  Arrange: Mock the InitializrMetadataProvider to return an empty string upon invocation.
  Act: Invoke the method springTgz and capture its return value.
  Assert: Verify that the return value is "redirect:".
Validation:
  This test ensures that the method springTgz properly handles an empty URL scenario. The method is expected to return "redirect:" in this case, based on its logic.

Scenario 3: Testing the URL redirection handling for NullPointerException

TestName: testHandlingOfNullPointerException
Description: This test checks how the method handles the NullPointerException.
Execution:
  Arrange: Mock the InitializrMetadataProvider to return null upon invocation to mimic a NullPointerException.
  Act: Invoke the method springTgz and capture any exception thrown.
  Assert: Verify that a NullPointerException is captured.
Validation:
  This test assesses the springTgz method's behavior when encountering a NullPointerException. The method should throw this exception in this scenario, because it does not handle null return values from the InitializrMetadataProvider.

Scenario 4: Testing the URL redirection handling for malformed URL

TestName: testHandlingOfMalformedURLException
Description: This test checks how the method handles a malformed URL.
Execution:
  Arrange: Mock the InitializrMetadataProvider to return an invalid URL upon invocation.
  Act: Invoke the method springTgz and capture any exception thrown.
  Assert: Verify that a MalformedURLException is captured.
Validation:
  This test asserts the springTgz method's behavior when provided with a malformed URL. The method should throw a MalformedURLException in this scenario, because it does not validate the URL's format.
"""
*/

// ********RoostGPT********

package io.spring.initializr.web.controller;

import io.spring.initializr.metadata.InitializrMetadataProvider;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@ExtendWith(MockitoExtension.class)
public class SpringCliDistributionControllerSpringTgzTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Test
	@Tag("valid")
	public void testSuccessfulUrlRedirection() {
		String mockUrl = "http://mock-url.com";
		when(metadataProvider.get().createCliDistributionURl("tar.gz")).thenReturn(mockUrl);
		SpringCliDistributionController controller = new SpringCliDistributionController(metadataProvider);
		String result = controller.springTgz();
		assertEquals("redirect:" + mockUrl, result);
	}

	@Test
	@Tag("boundary")
	public void testUrlRedirectionWithEmptyUrl() {
		when(metadataProvider.get().createCliDistributionURl("tar.gz")).thenReturn("");
		SpringCliDistributionController controller = new SpringCliDistributionController(metadataProvider);
		String result = controller.springTgz();
		assertEquals("redirect:", result);
	}

	@Test
	@Tag("invalid")
	public void testHandlingOfNullPointerException() {
		when(metadataProvider.get().createCliDistributionURl("tar.gz")).thenReturn(null);
		SpringCliDistributionController controller = new SpringCliDistributionController(metadataProvider);
		assertThrows(NullPointerException.class, controller::springTgz);
	}

	@Test
	@Tag("invalid")
	public void testHandlingOfMalformedURLException() {
		String mockUrl = "htp:://invalid-url";
		when(metadataProvider.get().createCliDistributionURl("tar.gz")).thenReturn(mockUrl);
		SpringCliDistributionController controller = new SpringCliDistributionController(metadataProvider);
		assertThrows(MalformedURLException.class, controller::springTgz);
	}

}