/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=projectGenerationController_8ab258a4a1
ROOST_METHOD_SIG_HASH=projectGenerationController_dab2b7ce7e

"""
Scenario 1: Test projectGenerationController with a valid metadataProvider and applicationContext

Details:
  TestName: testProjectGenerationControllerWithValidParams
  Description: This test is meant to check that the projectGenerationController method performs correctly when provided with valid InitializrMetadataProvider and ApplicationContext inputs.
Execution:
  Arrange: Mock the InitializrMetadataProvider and ApplicationContext objects.
  Act: Invoke the projectGenerationController method with the mocked objects as parameters.
  Assert: Assert that the returned CustomProjectGenerationController is not null.
Validation:
  This assertion verifies that the method correctly creates a CustomProjectGenerationController when provided with valid inputs. If the method behaves as expected, it should return a non-null object of type CustomProjectGenerationController.

Scenario 2: Test projectGenerationController with a null metadataProvider

Details:
  TestName: testProjectGenerationControllerWithNullMetadataProvider
  Description: This test is intended to validate the method's behavior when the InitializrMetadataProvider input is null.
Execution:
  Arrange: Mock an ApplicationContext. Pass a null value as InitializrMetadataProvider.
  Act: Invoke the projectGenerationController method with null InitializrMetadataProvider, mocking the ApplicationContext.
  Assert: Assert that an exception was thrown.
Validation:
  The assertion checks whether an exception is thrown when a null InitializrMetadataProvider is passed into the projectGenerationController method. This test is significant because it ensures that the method behaves as expected when it receives invalid input.

Scenario 3: Test projectGenerationController with a null applicationContext

Details:
  TestName: testProjectGenerationControllerWithNullApplicationContext
  Description: This test should validate the method's action when the ApplicationContext is null.
Execution:
  Arrange: Mock an InitializrMetadataProvider. Pass a null value as ApplicationContext.
  Act: Invoke the projectGenerationController method with null ApplicationContext, mocking the InitializrMetadataProvider.
  Assert: Assert that an exception was thrown.
Validation:
  To ensure that the projectGenerationController method behaves as expected when it receives invalid input, the assertion will check whether an exception is thrown when a null ApplicationContext is passed.

"""
*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.generator.project.MutableProjectDescription;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.controller.ProjectGenerationController;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import io.spring.initializr.web.project.ProjectRequestToDescriptionConverter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

@ExtendWith(MockitoExtension.class)
public class CustomProjectGenerationConfigurationExampleProjectGenerationControllerTest {

	@Mock
	private InitializrMetadataProvider metadataProvider;

	@Mock
	private ApplicationContext applicationContext;

	@InjectMocks
	private CustomProjectGenerationConfigurationExample customProjectGenerationConfigurationExample;

	@Test
	@Tag("valid")
	public void testProjectGenerationControllerWithValidParams() {
		CustomProjectGenerationController controller = customProjectGenerationConfigurationExample
			.projectGenerationController(metadataProvider, applicationContext);
		assertNotNull(controller);
	}

	@Test
	@Tag("invalid")
	public void testProjectGenerationControllerWithNullMetadataProvider() {
		assertThrows(NullPointerException.class, () -> {
			customProjectGenerationConfigurationExample.projectGenerationController(null, applicationContext);
		});
	}

	@Test
	@Tag("invalid")
	public void testProjectGenerationControllerWithNullApplicationContext() {
		assertThrows(NullPointerException.class, () -> {
			customProjectGenerationConfigurationExample.projectGenerationController(metadataProvider, null);
		});
	}

}