/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=convert_0a01496364
ROOST_METHOD_SIG_HASH=convert_1d5efa1237


Scenario 1: Verify conversion returns instance of MutableProjectDescription

Details:
  TestName: convertReturnsMutableProjectDescription
  Description: Ensure that the `convert` method returns a new instance of `MutableProjectDescription` when given a valid `CustomProjectRequest` and `InitializrMetadata`.
Execution:
  Arrange: Create mock instances of `CustomProjectRequest` and `InitializrMetadata`.
  Act: Call the `convert` method with the mock instances.
  Assert: Use an assertion to verify that the returned object is an instance of `MutableProjectDescription`.
Validation:
  This test validates that the method's responsibility to return the correct type (`MutableProjectDescription`) is fulfilled, ensuring that the conversion logic operates correctly at a foundational level.

*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.generator.project.MutableProjectDescription;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.web.project.CustomProjectRequest;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.assertj.core.api.Assertions.assertThat;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.controller.ProjectGenerationController;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import io.spring.initializr.web.project.ProjectRequestToDescriptionConverter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

class CustomProjectRequestToDescriptionConverterConvertTest {

	@Test
	@Tag("valid")
	void convertReturnsMutableProjectDescription() {
		// Arrange
		CustomProjectGenerationConfigurationExample parent = new CustomProjectGenerationConfigurationExample();
		CustomProjectGenerationConfigurationExample.CustomProjectRequestToDescriptionConverter converter = parent.new CustomProjectRequestToDescriptionConverter();
		CustomProjectRequest mockRequest = Mockito.mock(CustomProjectRequest.class); // Mocking
																						// CustomProjectRequest
		InitializrMetadata mockMetadata = Mockito.mock(InitializrMetadata.class); // Mocking
																					// InitializrMetadata

		// Act
		ProjectDescription result = converter.convert(mockRequest, mockMetadata);

		// Assert
		assertThat(result).isInstanceOf(MutableProjectDescription.class); // Assert using
																			// AssertJ
	}

	@Test
	@Tag("nullRequest")
	void convertWithNullRequestShouldThrowException() {
		// Arrange
		CustomProjectGenerationConfigurationExample parent = new CustomProjectGenerationConfigurationExample();
		CustomProjectGenerationConfigurationExample.CustomProjectRequestToDescriptionConverter converter = parent.new CustomProjectRequestToDescriptionConverter();
		InitializrMetadata mockMetadata = Mockito.mock(InitializrMetadata.class); // Mock
																					// InitializrMetadata

		// Act & Assert
		try {
			converter.convert(null, mockMetadata);
		}
		catch (IllegalArgumentException e) {
			assertThat(e.getMessage()).contains("Request cannot be null");
		}
	}

	@Test
	@Tag("nullMetadata")
	void convertWithNullMetadataShouldThrowException() {
		// Arrange
		CustomProjectGenerationConfigurationExample parent = new CustomProjectGenerationConfigurationExample();
		CustomProjectGenerationConfigurationExample.CustomProjectRequestToDescriptionConverter converter = parent.new CustomProjectRequestToDescriptionConverter();
		CustomProjectRequest mockRequest = Mockito.mock(CustomProjectRequest.class); // Mock
																						// CustomProjectRequest

		// Act & Assert
		try {
			converter.convert(mockRequest, null);
		}
		catch (IllegalArgumentException e) {
			assertThat(e.getMessage()).contains("Metadata cannot be null");
		}
	}
	// TODO: Add more test cases for different valid/invalid combinations

}