/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=convert_b1cb36a8e4
ROOST_METHOD_SIG_HASH=convert_390a89183f

"""
Scenario 1: Successful conversion of CustomProjectRequest to ProjectDescriptio

Details:
  TestName: testSuccessfulConversion.
  Description: This test verifies if the 'convert' method creates a new instance of 'MutableProjectDescription' successfully when given a valid 'CustomProjectRequest' and 'InitializrMetadata'.
  Execution:
    Arrange: A valid instance of 'CustomProjectRequest' and 'InitializrMetadata' are created for testing.
    Act: The 'convert' method is invoked with the created 'CustomProjectRequest' and 'InitializrMetadata'.
    Assert: Assert that the returned 'ProjectDescription' is an instance of 'MutableProjectDescription'.
  Validation:
    The assertion verifies whether the returned 'ProjectDescription' is a 'MutableProjectDescription'. The method under test is expected to always create and return a new 'MutableProjectDescription' regardless of the input parameters. The success of this test ensures the method correctly instantiates the 'MutableProjectDescription' class.

Scenario 2: Conversion with null request parameter

Details:
  TestName: testNullRequestConversion.
  Description: This test checks the 'convert' method behavior when invoked with a null 'CustomProjectRequest' and a valid 'InitializrMetadata'.
  Execution:
    Arrange: A null 'CustomProjectRequest' and a valid 'InitializrMetadata' are used for testing.
    Act: The 'convert' method is invoked with the null 'CustomProjectRequest' and valid 'InitializrMetadata'.
    Assert: Assert that the returned 'ProjectDescription' is an instance of 'MutableProjectDescription'.
  Validation:
    The assertion verifies that the 'convert' method handles null 'CustomProjectRequest' gracefully without throwing null pointer exception but returning a new 'MutableProjectDescription'. This ensures the method's robustness in handling null inputs.

Scenario 3: Conversion with null metadata parameter

Details:
  TestName: testNullMetadataConversion.
  Description: This test checks the 'convert' method behavior when invoked with a valid 'CustomProjectRequest' and a null 'InitializrMetadata'.
  Execution:
    Arrange: A valid 'CustomProjectRequest' and a null 'InitializrMetadata' are used for testing.
    Act: The 'convert' method is invoked with the valid 'CustomProjectRequest' and null 'InitializrMetadata'.
    Assert: Assert that the returned 'ProjectDescription' is an instance of 'MutableProjectDescription'.
  Validation:
    The assertion verifies that the 'convert' method handles null 'InitializrMetadata' gracefully without throwing null pointer exception but returning a new 'MutableProjectDescription'. This ensures that the method can handle different variations of input conditions.
"""
*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.MutableProjectDescription;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.controller.ProjectGenerationController;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import io.spring.initializr.web.project.ProjectRequestToDescriptionConverter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

public class CustomProjectRequestToDescriptionConverterConvertTest {

	CustomProjectGenerationConfigurationExample configExample = new CustomProjectGenerationConfigurationExample();

	CustomProjectGenerationConfigurationExample.CustomProjectRequestToDescriptionConverter converter = configExample.new CustomProjectRequestToDescriptionConverter();

	@Test
	@Tag("valid")
	public void testSuccessfulConversion() {
		// Arrange
		CustomProjectRequest request = new CustomProjectRequest();
		InitializrMetadata metadata = new InitializrMetadata();
		// Act
		ProjectDescription description = converter.convert(request, metadata);
		// Assert
		assertTrue(description instanceof MutableProjectDescription,
				"Returned ProjectDescription should be an instance of MutableProjectDescription");
	}

	@Test
	@Tag("boundary")
	public void testNullRequestConversion() {
		// Arrange
		CustomProjectRequest request = null;
		InitializrMetadata metadata = new InitializrMetadata();
		// Act
		ProjectDescription description = converter.convert(request, metadata);
		// Assert
		assertTrue(description instanceof MutableProjectDescription,
				"Returned ProjectDescription should be an instance of MutableProjectDescription");
	}

	@Test
	@Tag("boundary")
	public void testNullMetadataConversion() {
		// Arrange
		CustomProjectRequest request = new CustomProjectRequest();
		InitializrMetadata metadata = null;
		// Act
		ProjectDescription description = converter.convert(request, metadata);
		// Assert
		assertTrue(description instanceof MutableProjectDescription,
				"Returned ProjectDescription should be an instance of MutableProjectDescription");
	}

}