/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=projectGenerationController_8ab258a4a1
ROOST_METHOD_SIG_HASH=projectGenerationController_dab2b7ce7e

"""
  Scenario 1: Testing the projectGenerationController with a valid metadataProvider and applicationContext.

  Details:
    TestName: testProjectGenerationControllerWithValidArguments.
    Description: This test is intended to verify if the projectGenerationController method can create a new instance of CustomProjectGenerationController with a valid metadataProvider and applicationContext.
  Execution:
    Arrange: Mock the InitializrMetadataProvider and ApplicationContext arguments.
    Act: Invoke the projectGenerationController method with the mocked arguments.
    Assert: Verify that the returned object is an instance of CustomProjectGenerationController.
  Validation:
    The assertion confirms that the method can successfully return a valid instance of the CustomProjectGenerationController, meaning it can properly initialize and create a CustomProjectGenerationController object.

  Scenario 2: Testing the projectGenerationController with a null metadataProvider.

  Details:
    TestName: testProjectGenerationControllerWithNullMetadataProvider.
    Description: This test aims to evaluate the method's handling of the scenario where null is passed as the metadataProvider.
  Execution:
    Arrange: Pass null for the metadataProvider argument, and mock the ApplicationContext.
    Act: Invoke the projectGenerationController method with the null metadataProvider and the mocked ApplicationContext.
    Assert: Expect an exception to be thrown, as we are passing a key parameter as null.
  Validation:
    The test ensures that the method properly handles instance where metadataProvider, which is a non-optional parameter, is null.

  Scenario 3: Testing the projectGenerationController with a null ApplicationContext.

  Details:
    TestName: testProjectGenerationControllerWithNullApplicationContext.
    Description: The test validates the method's ability to handle cases where the ApplicationContext parameter is null.
  Execution:
    Arrange: Mock the metadataProvider, and pass the ApplicationContext as null.
    Act: Call the projectGenerationController with the mocked metadataProvider and null ApplicationContext parameters.
    Assert: An exception should be thrown, as the method cannot function correctly if a crucial dependency, ApplicationContext, is null.
  Validation:
    The test verifies if the method is designed to safeguard against cases where the ApplicationContext, a key dependency, is not provided.

  Scenario 4: Testing the projectGenerationController with null parameters.

  Details:
    TestName: testProjectGenerationControllerWithNullParameters.
    Description: This test examines how the method behaves when both parameters are null.
  Execution:
    Arrange: Set both the InitializrMetadataProvider and ApplicationContext parameters to null.
    Act: Invoke the projectGenerationController method with null parameters.
    Assert: An exception should be thrown, reflecting that either parameter being null causes the method to malfunction.
  Validation:
    The test confirms that the method is equipped to detect and respond to null dependencies.
"""
*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.generator.project.MutableProjectDescription;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.metadata.InitializrMetadata;
import io.spring.initializr.metadata.InitializrMetadataProvider;
import io.spring.initializr.web.controller.ProjectGenerationController;
import io.spring.initializr.web.project.ProjectGenerationInvoker;
import io.spring.initializr.web.project.ProjectRequestToDescriptionConverter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.junit.jupiter.api.*;

@SpringBootTest
class CustomProjectGenerationConfigurationExampleProjectGenerationControllerTest {

	@Test
	@Tag("valid")
	public void testProjectGenerationControllerWithValidArguments() {
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);
		ApplicationContext applicationContext = mock(ApplicationContext.class);

		CustomProjectGenerationConfigurationExample instance = new CustomProjectGenerationConfigurationExample();
		Object result = instance.projectGenerationController(metadataProvider, applicationContext);

		assertTrue(result instanceof CustomProjectGenerationController);
	}

	@Test
	@Tag("invalid")
	public void testProjectGenerationControllerWithNullMetadataProvider() {
		ApplicationContext applicationContext = mock(ApplicationContext.class);

		CustomProjectGenerationConfigurationExample instance = new CustomProjectGenerationConfigurationExample();
		assertThrows(IllegalArgumentException.class, () -> {
			instance.projectGenerationController(null, applicationContext);
		});
	}

	@Test
	@Tag("invalid")
	public void testProjectGenerationControllerWithNullApplicationContext() {
		InitializrMetadataProvider metadataProvider = mock(InitializrMetadataProvider.class);

		CustomProjectGenerationConfigurationExample instance = new CustomProjectGenerationConfigurationExample();
		assertThrows(IllegalArgumentException.class, () -> {
			instance.projectGenerationController(metadataProvider, null);
		});
	}

	@Test
	@Tag("invalid")
	public void testProjectGenerationControllerWithNullParameters() {
		CustomProjectGenerationConfigurationExample instance = new CustomProjectGenerationConfigurationExample();
		assertThrows(IllegalArgumentException.class, () -> {
			instance.projectGenerationController(null, null);
		});
	}

}