/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=warPluginContributor_495dd4fb10
ROOST_METHOD_SIG_HASH=warPluginContributor_6816e9724d

"""
  Scenario 1: Test if 'war' plugin addition function is working correctly

  Details:
    TestName: checkWarPluginAddition.
    Description: This test will check if the method correctly adds the 'war' plugin to the build.
  Execution:
    Arrange: Create a mock GradleBuild object and inject it into warPluginContributor method.
    Act: Invoke the warPluginContributor method.
    Assert: Use JUnit assertions to see if the 'war' plugin has been correctly added to the build.
  Validation:
    The assertion aims to validate that the 'war' plugin is correctly added to the build system. This is important to ensure the correct functioning of the application when it's packaged as 'war'.

  Scenario 2: Test if warPluginContributor handles incorrect build type

  Details:
    TestName: checkForIncorrectBuildType.
    Description: This test will check if the method throws an exception when an incorrect build system type is passed.
  Execution:
    Arrange: Create a mock GradleBuild object with a system type other than GradleBuildSystem.ID and inject it into warPluginContributor method.
    Act: Invoke the warPluginContributor method.
    Assert: Assert that the method throws an exception.
  Validation:
    The assertion aims to confirm that warPluginContributor correctly identifies an incorrect build system type and throws an exception. This prevents the application from building with an incorrect system type.

  Scenario 3: Test if warPluginContributor handles incorrect packaging type

  Details:
    TestName: checkForIncorrectPackagingType.
    Description: This test will check if the method throws an exception when an incorrect packaging type is passed.
  Execution:
    Arrange: Create a mock GradleBuild object with a packaging type other than WarPackaging.ID and inject it into warPluginContributor method.
    Act: Invoke the warPluginContributor method.
    Assert: Assert that the method throws an exception.
  Validation:
    The assertion aims to confirm that warPluginContributor correctly identifies an incorrect packaging type and throws an exception. This prevents the application from building with an incorrect packaging type.
"""
*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import static org.mockito.Mockito.verify;
import static org.junit.jupiter.api.Assertions.assertThrows;
import io.spring.initializr.generator.buildsystem.gradle.GradleBuild;
import io.spring.initializr.generator.buildsystem.gradle.GradleBuildSystem;
import io.spring.initializr.generator.packaging.war.WarPackaging;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.context.annotation.Bean;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;
import io.spring.initializr.generator.condition.ConditionalOnBuildSystem;
import io.spring.initializr.generator.condition.ConditionalOnPackaging;
import io.spring.initializr.generator.spring.build.BuildCustomizer;

public class ProjectCustomizationExamplesWarPluginContributorTest {

	private GradleBuild gradleBuild;

	private ProjectCustomizationExamples projectCustomizationExamples;

	@BeforeEach
	public void setup() {
		gradleBuild = Mockito.mock(GradleBuild.class);
		projectCustomizationExamples = new ProjectCustomizationExamples();
	}

	@Test
	@Tag("valid")
	public void checkWarPluginAddition() {
		projectCustomizationExamples.warPluginContributor().customize(gradleBuild);
		verify(gradleBuild).plugins().add("war");
	}

	@Test
	@Tag("invalid")
	public void checkForIncorrectBuildType() {
		GradleBuild incorrectGradleBuild = Mockito.mock(GradleBuild.class,
				Mockito.withSettings().useConstructor("InvalidBuildSystem"));
		assertThrows(Exception.class,
				() -> projectCustomizationExamples.warPluginContributor().customize(incorrectGradleBuild));
	}

	@Test
	@Tag("invalid")
	public void checkForIncorrectPackagingType() {
		GradleBuild incorrectGradleBuild = Mockito.mock(GradleBuild.class,
				Mockito.withSettings().useConstructor(WarPackaging.ID, "InvalidPackaging"));
		assertThrows(Exception.class,
				() -> projectCustomizationExamples.warPluginContributor().customize(incorrectGradleBuild));
	}

}