/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=warPluginContributor_76fa117380
ROOST_METHOD_SIG_HASH=warPluginContributor_2221b6b54a


Scenario 1: Verify WAR Plugin is Added to Gradle Build Plugins

Details:
  TestName: warPluginAddedToGradleBuild
  Description: This test checks whether the "war" plugin is correctly added to the GradleBuild object when the warPluginContributor method is invoked. It ensures that the method performs its intended functionality of modifying the build configuration by inserting the "war" plugin.

Execution:
  Arrange: Instantiate a GradleBuild object to represent the build configuration and prepare the warPluginContributor method to be tested.
  Act: Use the method warPluginContributor to apply the modification to the GradleBuild object.
  Assert: Verify that the GradleBuild object's plugins list contains the plugin "war".

Validation:
  The assertion confirms that the warPluginContributor method successfully modifies the GradleBuild object. This ensures the core functionality of the method aligns with the expected business logic of adding WAR support to Gradle builds.

---

Scenario 2: Check plugin addition does not interfere with existing plugins

Details:
  TestName: existingPluginsUnchangedAfterWarPluginAddition
  Description: This test ensures that invoking the warPluginContributor method does not remove or modify any existing plugins in the GradleBuild object. It verifies that the functionality only adds the "war" plugin without interfering with any preexisting configurations.

Execution:
  Arrange: Instantiate a GradleBuild object, add a preexisting plugin (e.g., "java"), and prepare the warPluginContributor method to be tested.
  Act: Invoke the warPluginContributor method on the GradleBuild object.
  Assert: Verify that the "java" plugin and any other preexisting plugins remain unchanged while the "war" plugin is added.

Validation:
  The assertion ensures that the method functions without introducing unintended side effects, preserving all existing configurations while adding the "war" plugin.

---

Scenario 3: Ensure WAR Plugin is added only once

Details:
  TestName: preventDuplicateWarPluginAddition
  Description: This test ensures that the warPluginContributor method does not add duplicate entries of the "war" plugin to the GradleBuild object when called multiple times.

Execution:
  Arrange: Instantiate a GradleBuild object and invoke the warPluginContributor method twice.
  Act: Apply the method twice to the same GradleBuild object.
  Assert: Verify that the "war" plugin is only present once in the plugins list.

Validation:
  The test verifies that the method maintains proper idempotent behavior by ensuring duplicate plugin entries are not added to the Gradle configuration.

---

Scenario 4: Verify method behavior on an empty GradleBuild

Details:
  TestName: addWarPluginToEmptyGradleBuild
  Description: This test checks the behavior of the warPluginContributor method when invoked on an empty GradleBuild object without any prior configurations or plugins.

Execution:
  Arrange: Create a new GradleBuild object with no preexisting configurations.
  Act: Use the warPluginContributor method to modify the GradleBuild object.
  Assert: Verify that only the "war" plugin is added to the plugins list.

Validation:
  The test guarantees the method functions correctly under initial configuration scenarios, ensuring it can handle empty build setups effectively.

---

Scenario 5: Confirm WAR Plugin addition for WarPackaging build system

Details:
  TestName: ensureWarPluginAddedForWarPackaging
  Description: This test verifies that the warPluginContributor method correctly adds the "war" plugin when the build system is set to WarPackaging, as per its conditional behavior and intended functionality.

Execution:
  Arrange: Configure a GradleBuild object to use WarPackaging.
  Act: Apply the warPluginContributor method to the GradleBuild object.
  Assert: Confirm that the "war" plugin is successfully added.

Validation:
  The test ensures compatibility and expected behavior when the build system is specifically tailored for WAR packaging.

---

Scenario 6: Validate method behavior with unsupported build systems

Details:
  TestName: noWarPluginForUnsupportedBuildSystem
  Description: This test ensures that the warPluginContributor method does not add the "war" plugin when the build system is incompatible or unsupported.

Execution:
  Arrange: Create a GradleBuild object configured with a non-WarPackaging build system.
  Act: Invoke the warPluginContributor method on the GradleBuild object.
  Assert: Verify that the "war" plugin is not added to the plugins list.

Validation:
  The assertion aims to confirm that the method respects conditional dependencies, ensuring no plugins are added for unsupported build systems.

---

Scenario 7: Verify that plugins list is not null before modification

Details:
  TestName: ensureNonNullPluginsListBeforeAddingWarPlugin
  Description: This test checks that the GradleBuild object's plugins list is properly initialized before attempting to add the "war" plugin.

Execution:
  Arrange: Create a new GradleBuild object and observe its initial state.
  Act: Apply the warPluginContributor method to the GradleBuild object.
  Assert: Confirm that the plugins list is not null and successfully modified.

Validation:
  This test validates that the method handles initialization correctly and ensures no null pointer exceptions or errors arise during execution.

*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.generator.buildsystem.gradle.GradleBuild;
import io.spring.initializr.generator.spring.build.BuildCustomizer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import io.spring.initializr.generator.buildsystem.gradle.GradleBuildSystem;
import io.spring.initializr.generator.condition.ConditionalOnBuildSystem;
import io.spring.initializr.generator.condition.ConditionalOnPackaging;
import io.spring.initializr.generator.packaging.war.WarPackaging;
import org.springframework.context.annotation.Bean;

class ProjectCustomizationExamplesWarPluginContributorTest {

	private final ProjectCustomizationExamples projectCustomizationExamples = new ProjectCustomizationExamples();

	@Test
	@Tag("valid")
	void warPluginAddedToGradleBuild() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertTrue(gradleBuild.plugins().contains("war"), "The plugins list should contain 'war'");
	}

	@Test
	@Tag("valid")
	void existingPluginsUnchangedAfterWarPluginAddition() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		gradleBuild.plugins().add("java");
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertTrue(gradleBuild.plugins().contains("java"), "The plugins list should still contain 'java'");
		assertTrue(gradleBuild.plugins().contains("war"), "The plugins list should contain 'war'");
	}

	@Test
	@Tag("valid")
	void preventDuplicateWarPluginAddition() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		customizer.customize(gradleBuild);
		// Assert
		assertEquals(1, gradleBuild.plugins().stream().filter(plugin -> plugin.equals("war")).count(),
				"There should be only one 'war' plugin in the list");
	}

	@Test
	@Tag("valid")
	void addWarPluginToEmptyGradleBuild() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertEquals(1, gradleBuild.plugins().size(), "Only one plugin should exist in the list");
		assertTrue(gradleBuild.plugins().contains("war"), "The plugins list should contain 'war'");
	}

	@Test
	@Tag("integration")
	void ensureWarPluginAddedForWarPackaging() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertTrue(gradleBuild.plugins().contains("war"),
				"The 'war' plugin should exist for WarPackaging build system");
		// Note: Ensure the build system supports WarPackaging explicitly.
	}

	@Test
	@Tag("invalid")
	void noWarPluginForUnsupportedBuildSystem() {
		// Add a comment if unsupported build system logic is needed
		// In the business logic function 'warPluginContributor', there is no check for
		// unsupported build systems.
		// A check should be added to prevent adding 'war' plugin for unsupported build
		// systems.
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertFalse(gradleBuild.plugins().contains("war"),
				"The 'war' plugin should not be added for unsupported build systems");
	}

	@Test
	@Tag("boundary")
	void ensureNonNullPluginsListBeforeAddingWarPlugin() {
		// Arrange
		GradleBuild gradleBuild = new GradleBuild();
		BuildCustomizer<GradleBuild> customizer = projectCustomizationExamples.warPluginContributor();
		// Act
		customizer.customize(gradleBuild);
		// Assert
		assertNotNull(gradleBuild.plugins(), "The plugins list should not be null");
		assertTrue(gradleBuild.plugins().contains("war"), "The plugins list should contain 'war'");
	}

}