/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=createProjectGenerator_ede895daf0
ROOST_METHOD_SIG_HASH=createProjectGenerator_5191a2029f

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-docs/src/test/java/io/spring/initializr/doc/generator/project/ProjectGeneratorSetupExampleTests.java
Tests:
    "@Test
@Test
void generateSimpleProjectStructure(@TempDir Path tempDir) {
    StaticApplicationContext context = new StaticApplicationContext();
    context.registerBean(InitializrMetadata.class, () -> InitializrMetadataTestBuilder.withDefaults().build());
    context.registerBean(IndentingWriterFactory.class, IndentingWriterFactory::withDefaultSettings);
    context.registerBean(MustacheTemplateRenderer.class, () -> new MustacheTemplateRenderer("classpath:/templates"));
    context.refresh();
    DefaultProjectAssetGenerator assetGenerator = new DefaultProjectAssetGenerator((description) -> tempDir);
    ProjectGenerator projectGenerator = new ProjectGeneratorSetupExample().createProjectGenerator(context);
    Path directory = projectGenerator.generate(createProjectDescription(), assetGenerator);
    assertThat(directory).isSameAs(tempDir);
    Path helloFile = directory.resolve("hello.txt");
    assertThat(helloFile).exists().isRegularFile().hasContent("Test");
}
"Scenario 1: Verifying that createProjectGenerator method initializes ProjectGenerator with correct parent context.

TestName: verifyProjectGeneratorParentContextInitialization
Description: This test is meant to verify that the createProjectGenerator correctly sets the parent context of the ProjectGenerator.

Execution:
  Arrange: Mock the ApplicationContext instance and pass it as parameter to createProjectGenerator.
  Act: Invoke the createProjectGenerator with the mocked ApplicationContext.
  Assert: Use JUnit assertions to assert that the ApplicationContext provided as a parameter is set as a parent context in the ProjectGenerator.
Validation:
  This assertion verifies that createProjectGenerator correctly applies configuration to the ProjectGenerator instance regarding the parent context assignment, which is crucial for processing and contributions in the pipeline.

Scenario 2: Check that createProjectGenerator registers the correct bean.

TestName: validateProjectGeneratorBeanRegistration
Description: This test aims to make sure that the createProjectGenerator successfully registers the SampleContributor bean in the context.

Execution:
  Arrange: Mock the ApplicationContext, then use it as a parameter to call the createProjectGenerator.
  Act: Invoke the createProjectGenerator method with provided ApplicationContext.
  Assert: Assert using JUnit to check if the SampleContributor bean is registered in the ApplicationContext of ProjectGenerator.
Validation:
   The test's goal is to ensure that the required beans are registered in the ApplicationContext. This occurs so that the ProjectGenerator has access to all the necessary beans it needs to function properly.

Scenario 3: Check for null ApplicationContext input.

TestName: validateAgainstNullApplicationContext
Description: This test is to ensure the createProjectGenerator method throws an exception when a null ApplicationContext is passed.

Execution:
  Arrange: Pass a null value as the ApplicationContext to the createProjectGenerator.
  Act: Call createProjectGenerator method with null ApplicationContext.
  Assert: Assert that an exception is thrown when createProjectGenerator is called with a null ApplicationContext.
Validation:
  This test validates the functionality of the createProjectGenerator method when receiving a null parameter. This increases the robustness of the code by checking its behavior when provided with invalid inputs.
*/

// ********RoostGPT********

package io.spring.initializr.doc.generator.project;

import io.spring.initializr.generator.project.ProjectGenerator;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Tag;
import org.springframework.beans.factory.NoSuchBeanDefinitionException;
import org.springframework.context.ApplicationContext;
import org.junit.jupiter.api.*;

public class ProjectGeneratorSetupExampleCreateProjectGeneratorTest {

	@Mock
	private ApplicationContext appContext;

	private ProjectGenerator projectGenerator;

	private ProjectGeneratorSetupExample projectGeneratorSetupExample;

	@BeforeEach
	public void setUp() {
		MockitoAnnotations.initMocks(this);
		projectGeneratorSetupExample = new ProjectGeneratorSetupExample();
	}

	@Test
	@Tag("valid")
	public void verifyProjectGeneratorParentContextInitialization() {
		// Act
		projectGenerator = projectGeneratorSetupExample.createProjectGenerator(appContext);
		// Assert
		assertEquals(appContext, projectGenerator.getApplicationContext().getParent());
	}

	@Test
	@Tag("valid")
	public void validateProjectGeneratorBeanRegistration() {
		// Act
		projectGenerator = projectGeneratorSetupExample.createProjectGenerator(appContext);
		// Assert
		assertDoesNotThrow(() -> projectGenerator.getApplicationContext().getBean(SampleContributor.class));
	}

	@Test
	@Tag("invalid")
	public void validateAgainstNullApplicationContext() {
		// Act and Assert
		assertThrows(InvalidArgumentException.class, () -> projectGeneratorSetupExample.createProjectGenerator(null));
	}

}