/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=toString_2b7d8251af
ROOST_METHOD_SIG_HASH=toString_bbffdadaa2

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeFileWriterTests.java
Tests:
    "@Test
private String write(ComposeFile file) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, "\t"::repeat);
    new ComposeFileWriter().writeTo(writer, file);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/text/MustacheSectionTests.java
Tests:
    "@Test
@Test
void renderSection() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.singletonMap("key", "hello"));
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("hello%n"));
}
"
    "@Test
@Test
void renderSectionWithCustomModelResolution() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.emptyMap()) {

        @Override
        protected Map<String, Object> resolveModel(Map<String, Object> model) {
            return Collections.singletonMap("key", "custom");
        }
    };
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("custom%n"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionParserTests.java
Tests:
    "@Test
@Test
void versionWithNoQualifier() {
    Version version = this.parser.parse("1.2.0");
    assertThat(version.toString()).isEqualTo("1.2.0");
}
"
    "@Test
@Test
void versionWithQualifierAndDotSeparator() {
    Version version = this.parser.parse("1.2.0.RELEASE");
    assertThat(version.toString()).isEqualTo("1.2.0.RELEASE");
}
"
    "@Test
@Test
void versionWithQualifierAndDashSeparator() {
    Version version = this.parser.parse("1.2.0-SNAPSHOT");
    assertThat(version.toString()).isEqualTo("1.2.0-SNAPSHOT");
}
"
    "@Test
@Test
void versionWithQualifierVersionAndDotSeparator() {
    Version version = this.parser.parse("1.2.0.RC2");
    assertThat(version.toString()).isEqualTo("1.2.0.RC2");
}
"
    "@Test
@Test
void versionWithQualifierVersionAndDashSeparator() {
    Version version = this.parser.parse("1.2.0-M3");
    assertThat(version.toString()).isEqualTo("1.2.0-M3");
}
"
    "@Test
@Test
void parseVariableVersionMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.3.x.BUILD-SNAPSHOT").toString()).isEqualTo("1.3.9.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoPatchMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.x.x.RELEASE").toString()).isEqualTo("1.3.8.RELEASE");
}
"
    "@Test
@Test
void parseVariableVersionNoQualifierMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.4.0.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.4.x").toString()).isEqualTo("1.4.0.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.4.x.BUILD-SNAPSHOT").toString()).isEqualTo("1.4.999.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoPatchNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("2.x.x.RELEASE").toString()).isEqualTo("2.999.999.RELEASE");
}
"
    "@Test
@Test
void parseVariableVersionNoQualifierNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.4.0.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.2.x").toString()).isEqualTo("1.2.999");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GroovyDslGradleSettingsWriterTests.java
Tests:
    "@Test
private String generateSettings(GradleBuild build) {
    GradleSettingsWriter writer = new GroovyDslGradleSettingsWriter();
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out, new SimpleIndentStrategy("\t")), build);
    return out.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void functionModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("toString").modifiers(KotlinModifier.OVERRIDE, KotlinModifier.PUBLIC, KotlinModifier.OPEN).returning("java.lang.String").body(CodeBlock.ofStatement("return super.toString()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    open override fun toString(): String {", "        return super.toString()", "    }", "", "}");
}
"
    "@Test
private Path writeSourceCode(KotlinSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(JavaSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/packaging/PackagingTests.java
Tests:
    "@Test
@Test
void jarPackaging() {
    Packaging jar = Packaging.forId("jar");
    assertThat(jar).isInstanceOf(JarPackaging.class);
    assertThat(jar.id()).isEqualTo("jar");
    assertThat(jar.toString()).isEqualTo("jar");
}
"
    "@Test
@Test
void warPackaging() {
    Packaging war = Packaging.forId("war");
    assertThat(war).isInstanceOf(WarPackaging.class);
    assertThat(war.id()).isEqualTo("war");
    assertThat(war.toString()).isEqualTo("war");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenBuildWriterTests.java
Tests:
    "@Test
private String writePom(MavenBuildWriter writer, MavenBuild mavenBuild) {
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out), mavenBuild);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
private String write(CodeBlock code, FormattingOptions options) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, new SimpleIndentStrategy("\t"));
    code.write(writer, options);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BuildSystemTests.java
Tests:
    "@Test
@Test
void gradleBuildSystem() {
    BuildSystem gradle = BuildSystem.forId("gradle");
    assertThat(gradle).isInstanceOf(GradleBuildSystem.class);
    assertThat(gradle.id()).isEqualTo("gradle");
    assertThat(gradle.toString()).isEqualTo("gradle");
}
"
    "@Test
@Test
void mavenBuildSystem() {
    BuildSystem maven = BuildSystem.forId("maven");
    assertThat(maven).isInstanceOf(MavenBuildSystem.class);
    assertThat(maven.id()).isEqualTo("maven");
    assertThat(maven.toString()).isEqualTo("maven");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/LanguageTests.java
Tests:
    "@Test
@Test
void javaLanguage() {
    Language java = Language.forId("java", "11");
    assertThat(java).isInstanceOf(JavaLanguage.class);
    assertThat(java.id()).isEqualTo("java");
    assertThat(java.toString()).isEqualTo("java");
    assertThat(java.jvmVersion()).isEqualTo("11");
}
"
    "@Test
@Test
void kotlinLanguage() {
    Language kotlin = Language.forId("kotlin", null);
    assertThat(kotlin).isInstanceOf(KotlinLanguage.class);
    assertThat(kotlin.id()).isEqualTo("kotlin");
    assertThat(kotlin.toString()).isEqualTo("kotlin");
    assertThat(kotlin.jvmVersion()).isEqualTo("1.8");
}
"
    "@Test
@Test
void groovyLanguage() {
    Language groovy = Language.forId("groovy", "1.8");
    assertThat(groovy).isInstanceOf(GroovyLanguage.class);
    assertThat(groovy.id()).isEqualTo("groovy");
    assertThat(groovy.toString()).isEqualTo("groovy");
    assertThat(groovy.jvmVersion()).isEqualTo("1.8");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/IndentingWriterTests.java
Tests:
    "@Test
private String content() {
    return this.stringWriter.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/KotlinDslGradleSettingsWriterTests.java
Tests:
    "@Test
private String generateSettings(GradleBuild build) {
    GradleSettingsWriter writer = new KotlinDslGradleSettingsWriter();
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out, new SimpleIndentStrategy("\t")), build);
    return out.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionRangeTests.java
Tests:
    "@Test
@Test
void simpleStartingRange() {
    assertThat(new VersionRange(Version.parse("1.3.0.RELEASE")).toString()).isEqualTo(">=1.3.0.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(GroovySourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"```plaintext
Scenario 1: Verify toString() returns id when id is null

Details:
  TestName: toStringReturnsIdWhenIdIsNull
  Description: This test verifies that the toString() method returns the value of id() when id is null.
Execution:
  Arrange: Create an instance of AbstractLanguage with id set to null.
  Act: Invoke the toString() method on the created instance.
  Assert: Verify that the returned value is equal to the value of id().
Validation:
  Clarify that the assertion aims to verify the correct behavior of toString() when id is null, ensuring that it returns the value of id() as expected.
  Elaborate on the significance of this test in ensuring that the toString() method functions correctly in scenarios where id might be uninitialized or null.

Scenario 2: Verify toString() returns id when id is set to a non-null value

Details:
  TestName: toStringReturnsIdWhenIdIsNonNull
  Description: This test verifies that the toString() method returns the value of id() when id is set to a non-null value.
Execution:
  Arrange: Create an instance of AbstractLanguage with id set to a non-null value.
  Act: Invoke the toString() method on the created instance.
  Assert: Verify that the returned value is equal to the value of id().
Validation:
  Clarify that the assertion aims to verify the correct behavior of toString() when id is set to a non-null value, ensuring that it returns the value of id() as expected.
  Elaborate on the significance of this test in ensuring that the toString() method functions correctly in typical use cases.

Scenario 3: Verify toString() returns id when id is an empty string

Details:
  TestName: toStringReturnsIdWhenIdIsEmptyString
  Description: This test verifies that the toString() method returns the value of id() when id is set to an empty string.
Execution:
  Arrange: Create an instance of AbstractLanguage with id set to an empty string.
  Act: Invoke the toString() method on the created instance.
  Assert: Verify that the returned value is equal to the value of id().
Validation:
  Clarify that the assertion aims to verify the correct behavior of toString() when id is set to an empty string, ensuring that it handles this edge case appropriately.
  Elaborate on the significance of this test in ensuring that the toString() method functions correctly when id might be an empty string.

Scenario 4: Verify toString() returns id when id contains special characters

Details:
  TestName: toStringReturnsIdWhenIdContainsSpecialCharacters
  Description: This test verifies that the toString() method returns the value of id() when id contains special characters.
Execution:
  Arrange: Create an instance of AbstractLanguage with id set to a string containing special characters.
  Act: Invoke the toString() method on the created instance.
  Assert: Verify that the returned value is equal to the value of id().
Validation:
  Clarify that the assertion aims to verify the correct behavior of toString() when id contains special characters, ensuring that it handles this case appropriately.
  Elaborate on the significance of this test in ensuring that the toString() method functions correctly when id might contain special characters.

Scenario 5: Verify toString() returns id when id is a long string

Details:
  TestName: toStringReturnsIdWhenIdIsLongString
  Description: This test verifies that the toString() method returns the value of id() when id is set to a long string.
Execution:
  Arrange: Create an instance of AbstractLanguage with id set to a long string.
  Act: Invoke the toString() method on the created instance.
  Assert: Verify that the returned value is equal to the value of id().
Validation:
  Clarify that the assertion aims to verify the correct behavior of toString() when id is set to a long string, ensuring that it handles this case appropriately.
  Elaborate on the significance of this test in ensuring that the toString() method functions correctly when id might be a long string.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.*;

public class AbstractLanguageToStringTest {

	@Test
	@Tag("invalid")
	public void toStringReturnsIdWhenIdIsNull() {
		AbstractLanguage language = new AbstractLanguage(null, "1.8", "java");
		assertNull(language.toString());
	}

	@Test
	@Tag("valid")
	public void toStringReturnsIdWhenIdIsNonNull() {
		AbstractLanguage language = new AbstractLanguage("Java", "1.8", "java");
		assertEquals("Java", language.toString());
	}

	@Test
	@Tag("boundary")
	public void toStringReturnsIdWhenIdIsEmptyString() {
		AbstractLanguage language = new AbstractLanguage("", "1.8", "java");
		assertEquals("", language.toString());
	}

	@Test
	@Tag("valid")
	public void toStringReturnsIdWhenIdContainsSpecialCharacters() {
		AbstractLanguage language = new AbstractLanguage("Java#1.8", "1.8", "java");
		assertEquals("Java#1.8", language.toString());
	}

	@Test
	@Tag("boundary")
	public void toStringReturnsIdWhenIdIsLongString() {
		String longId = "JavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJavaJava";
		AbstractLanguage language = new AbstractLanguage(longId, "1.8", "java");
		assertEquals(longId, language.toString());
	}

}