/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getAttributes_4ee651bad6
ROOST_METHOD_SIG_HASH=getAttributes_905e4ef607

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleTaskContainerTests.java
Tests:
    "@Test
@Test
void customizeTask() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> {
        task.attribute("fork", "true");
        task.append("names", "test");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("test");
        assertThat(task.getType()).isNull();
        assertThat(task.getAttributes()).containsOnly(Attribute.set("fork", "true"), Attribute.append("names", "test"));
        assertThat(task.getInvocations()).isEmpty();
        assertThat(task.getNested()).isEmpty();
    });
}
"
    "@Test
@Test
void customizeTaskWithType() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customizeWithType("com.example.MyTask", (task) -> {
        task.attribute("fork", "true");
        task.invoke("property", "taskDir");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("MyTask");
        assertThat(task.getType()).isEqualTo("com.example.MyTask");
        assertThat(task.getAttributes()).containsOnly(Attribute.set("fork", "true"));
        assertThat(task.getInvocations()).singleElement().satisfies((invocation) -> {
            assertThat(invocation.getTarget()).isEqualTo("property");
            assertThat(invocation.getArguments()).containsOnly("taskDir");
        });
        assertThat(task.getNested()).isEmpty();
    });
}
"
    "@Test
@Test
void customizeTaskSeveralTimeReuseConfiguration() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> {
        task.attribute("ignore", "false");
        task.attribute("fork", "true");
    });
    container.customize("test", (task) -> {
        task.attribute("fork", "false");
        task.invoke("method", "arg1", "arg2");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("test");
        assertThat(task.getType()).isNull();
        assertThat(task.getAttributes()).containsOnly(Attribute.set("ignore", "false"), Attribute.set("fork", "false"));
        assertThat(task.getInvocations()).singleElement().satisfies((invocation) -> {
            assertThat(invocation.getTarget()).isEqualTo("method");
            assertThat(invocation.getArguments()).containsOnly("arg1", "arg2");
        });
        assertThat(task.getNested()).isEmpty();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationContainerTests.java
Tests:
    "@Test
@Test
void valuesWithSimpleAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeReuseConfiguration() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "another"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test", "another");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeCanReplaceAttribute() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 42).build()));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.set("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 24).build()));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test", "com.example.Nested");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).singleElement().isInstanceOfSatisfying(Annotation.class, (nested) -> {
                assertThat(nested.getClassName()).isEqualTo(NESTED_CLASS_NAME);
                assertThat(nested.getAttributes()).singleElement().satisfies((nestedAttribute) -> {
                    assertThat(nestedAttribute.getName()).isEqualTo("counter");
                    assertThat(nestedAttribute.getValues()).containsExactly(24);
                });
            });
        });
    });
}
"```plaintext
Scenario 1: Verify that getAttributes returns an empty list when no attributes are set

Details:
  TestName: getAttributesReturnsEmptyListWhenNoAttributesAreSet
  Description: This test checks that the getAttributes method returns an empty list when no attributes have been added to the Annotation object.

Execution:
  Arrange: Create an instance of the Annotation class without adding any attributes.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list is empty.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 2: Verify that getAttributes returns a list with a single attribute when one attribute is set

Details:
  TestName: getAttributesReturnsListWithSingleAttribute
  Description: This test checks that the getAttributes method returns a list containing a single attribute when one attribute has been added to the Annotation object.

Execution:
  Arrange: Create an instance of the Annotation class and add one attribute using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains exactly one attribute with the expected name and values.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 3: Verify that getAttributes returns a list with multiple attributes when multiple attributes are set

Details:
  TestName: getAttributesReturnsListWithMultipleAttributes
  Description: This test checks that the getAttributes method returns a list containing multiple attributes when multiple attributes have been added to the Annotation object.

Execution:
  Arrange: Create an instance of the Annotation class and add multiple attributes using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains all the expected attributes with the correct names and values.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 4: Verify that getAttributes returns attributes in the order they were added

Details:
  TestName: getAttributesReturnsAttributesInOrder
  Description: This test checks that the getAttributes method returns attributes in the order they were added to the Annotation object.

Execution:
  Arrange: Create an instance of the Annotation class and add multiple attributes using the Builder class in a specific order.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes in the expected order.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 5: Verify that getAttributes handles attributes with different types correctly

Details:
  TestName: getAttributesHandlesAttributesWithDifferentTypes
  Description: This test checks that the getAttributes method correctly handles attributes with different types (e.g., primitives, strings, classes, enums, annotations, and code blocks).

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with different types using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct types and values.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 6: Verify that getAttributes handles attributes with duplicate names correctly

Details:
  TestName: getAttributesHandlesAttributesWithDuplicateNames
  Description: This test checks that the getAttributes method correctly handles attributes with duplicate names by merging their values.

Execution:
  Arrange: Create an instance of the Annotation class and add multiple attributes with the same name using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains a single attribute with the merged values.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 7: Verify that getAttributes handles attributes with mixed types correctly

Details:
  TestName: getAttributesHandlesAttributesWithMixedTypes
  Description: This test checks that the getAttributes method correctly handles attributes with mixed types by throwing an IllegalArgumentException.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with mixed types using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 8: Verify that getAttributes handles attributes with incompatible types correctly

Details:
  TestName: getAttributesHandlesAttributesWithIncompatibleTypes
  Description: This test checks that the getAttributes method correctly handles attributes with incompatible types by throwing an IllegalArgumentException.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with incompatible types using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 9: Verify that getAttributes handles attributes with null values correctly

Details:
  TestName: getAttributesHandlesAttributesWithNullValues
  Description: This test checks that the getAttributes method correctly handles attributes with null values by throwing an IllegalArgumentException.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with null values using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 10: Verify that getAttributes handles attributes with empty values correctly

Details:
  TestName: getAttributesHandlesAttributesWithEmptyValues
  Description: This test checks that the getAttributes method correctly handles attributes with empty values by throwing an IllegalArgumentException.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with empty values using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 11: Verify that getAttributes handles attributes with large values correctly

Details:
  TestName: getAttributesHandlesAttributesWithLargeValues
  Description: This test checks that the getAttributes method correctly handles attributes with large values without performance degradation.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with large values using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct values and the method completes within an acceptable time frame.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 12: Verify that getAttributes handles attributes with special characters correctly

Details:
  TestName: getAttributesHandlesAttributesWithSpecialCharacters
  Description: This test checks that the getAttributes method correctly handles attributes with special characters in their names or values.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with special characters using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct names and values.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 13: Verify that getAttributes handles attributes with nested annotations correctly

Details:
  TestName: getAttributesHandlesAttributesWithNestedAnnotations
  Description: This test checks that the getAttributes method correctly handles attributes with nested annotations.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with nested annotations using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct nested annotations.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 14: Verify that getAttributes handles attributes with code blocks correctly

Details:
  TestName: getAttributesHandlesAttributesWithCodeBlocks
  Description: This test checks that the getAttributes method correctly handles attributes with code blocks.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with code blocks using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct code blocks.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 15: Verify that getAttributes handles attributes with enums correctly

Details:
  TestName: getAttributesHandlesAttributesWithEnums
  Description: This test checks that the getAttributes method correctly handles attributes with enums.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with enums using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct enums.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 16: Verify that getAttributes handles attributes with classes correctly

Details:
  TestName: getAttributesHandlesAttributesWithClasses
  Description: This test checks that the getAttributes method correctly handles attributes with classes.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with classes using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct classes.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 17: Verify that getAttributes handles attributes with strings correctly

Details:
  TestName: getAttributesHandlesAttributesWithStrings
  Description: This test checks that the getAttributes method correctly handles attributes with strings.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with strings using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct strings.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 18: Verify that getAttributes handles attributes with primitives correctly

Details:
  TestName: getAttributesHandlesAttributesWithPrimitives
  Description: This test checks that the getAttributes method correctly handles attributes with primitives.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with primitives using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct primitives.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 19: Verify that getAttributes handles attributes with mixed case names correctly

Details:
  TestName: getAttributesHandlesAttributesWithMixedCaseNames
  Description: This test checks that the getAttributes method correctly handles attributes with mixed case names.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with mixed case names using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct names.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```

```plaintext
Scenario 20: Verify that getAttributes handles attributes with reserved keywords correctly

Details:
  TestName: getAttributesHandlesAttributesWithReservedKeywords
  Description: This test checks that the getAttributes method correctly handles attributes with reserved keywords as names.

Execution:
  Arrange: Create an instance of the Annotation class and add attributes with reserved keywords as names using the Builder class.
  Act: Call the getAttributes method on the Annotation instance.
  Assert: Verify that the returned list contains the attributes with the correct names.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import io.spring.initializr.generator.language.Annotation.Builder;
import io.spring.initializr.generator.language.Annotation.Attribute;
import io.spring.initializr.generator.language.Annotation.AttributeType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import io.spring.initializr.generator.io.IndentingWriter;
import io.spring.initializr.generator.language.CodeBlock.FormattingOptions;
import org.springframework.util.ClassUtils;imports;imports=List.copyOf(builder.imports);imports=new HashSet<>();imports.add(name.getName());imports.addAll(copy.imports);imports.clear();imports.addAll(annotation.imports);imports::addAll);

class AnnotationGetAttributesTest {

	private Builder builder;

	@BeforeEach
	void setUp() {
		builder = new Builder();
	}

	@Test
	@Tag("valid")
	public void getAttributesReturnsEmptyListWhenNoAttributesAreSet() {
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).isEmpty();
	}

	@Test
	@Tag("valid")
	public void getAttributesReturnsListWithSingleAttribute() {
		builder.set("key", "value");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly("value");
	}

	@Test
	@Tag("valid")
	public void getAttributesReturnsListWithMultipleAttributes() {
		builder.set("key1", "value1").set("key2", "value2");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(2);
		assertThat(attributes).extracting(Attribute::getName).containsExactly("key1", "key2");
		assertThat(attributes).extracting(Attribute::getValues).containsExactly(List.of("value1"), List.of("value2"));
	}

	@Test
	@Tag("valid")
	public void getAttributesReturnsAttributesInOrder() {
		builder.set("key1", "value1").set("key2", "value2");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).extracting(Attribute::getName).containsExactly("key1", "key2");
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithDifferentTypes() {
		builder.set("key1", 1).set("key2", "value2").set("key3", Boolean.TRUE);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(3);
		assertThat(attributes).extracting(Attribute::getName).containsExactly("key1", "key2", "key3");
		assertThat(attributes).extracting(Attribute::getValues)
			.containsExactly(List.of(1), List.of("value2"), List.of(Boolean.TRUE));
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithDuplicateNames() {
		builder.add("key", "value1").add("key", "value2");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly("value1", "value2");
	}

	@Test
	@Tag("invalid")
	public void getAttributesHandlesAttributesWithMixedTypes() {
		assertThrows(IllegalArgumentException.class, () -> builder.set("key", 1, "value"));
	}

	@Test
	@Tag("invalid")
	public void getAttributesHandlesAttributesWithIncompatibleTypes() {
		assertThrows(IllegalArgumentException.class, () -> builder.set("key", new Object()));
	}

	@Test
	@Tag("invalid")
	public void getAttributesHandlesAttributesWithNullValues() {
		assertThrows(IllegalArgumentException.class, () -> builder.set("key", (Object) null));
	}

	@Test
	@Tag("invalid")
	public void getAttributesHandlesAttributesWithEmptyValues() {
		assertThrows(IllegalArgumentException.class, () -> builder.set("key"));
	}

	@Test
	@Tag("boundary")
	public void getAttributesHandlesAttributesWithLargeValues() {
		String largeValue = "a".repeat(1000000);
		builder.set("key", largeValue);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(largeValue);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithSpecialCharacters() {
		builder.set("key@1!", "value@1!");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key@1!");
		assertThat(attributes.get(0).getValues()).containsExactly("value@1!");
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithNestedAnnotations() {
		Annotation nestedAnnotation = new Builder().set("nestedKey", "nestedValue").build();
		builder.set("key", nestedAnnotation);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(nestedAnnotation);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithCodeBlocks() {
		CodeBlock codeBlock = CodeBlock.of("System.out.println();");
		builder.set("key", codeBlock);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(codeBlock);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithEnums() {
		builder.set("key", AttributeType.PRIMITIVE);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(AttributeType.PRIMITIVE);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithClasses() {
		builder.set("key", String.class);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(String.class);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithStrings() {
		builder.set("key", "value");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly("value");
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithPrimitives() {
		builder.set("key", 1);
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("key");
		assertThat(attributes.get(0).getValues()).containsExactly(1);
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithMixedCaseNames() {
		builder.set("Key", "value");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("Key");
		assertThat(attributes.get(0).getValues()).containsExactly("value");
	}

	@Test
	@Tag("valid")
	public void getAttributesHandlesAttributesWithReservedKeywords() {
		builder.set("class", "value");
		Annotation annotation = builder.build();
		List<Attribute> attributes = annotation.getAttributes();
		assertThat(attributes).hasSize(1);
		assertThat(attributes.get(0).getName()).isEqualTo("class");
		assertThat(attributes.get(0).getValues()).containsExactly("value");
	}

}