/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=has_237cbfeda2
ROOST_METHOD_SIG_HASH=has_d4ace9ca4e

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradlePluginContainerTests.java
Tests:
    "@Test
@Test
void hasPluginWithMatchingStandardPlugin() {
    GradlePluginContainer pluginContainer = new GradlePluginContainer();
    pluginContainer.add("com.example");
    assertThat(pluginContainer.has("com.example")).isTrue();
}
"
    "@Test
@Test
void hasPluginWithMatchingAppliedPlugin() {
    GradlePluginContainer pluginContainer = new GradlePluginContainer();
    pluginContainer.apply("com.example");
    assertThat(pluginContainer.has("com.example")).isTrue();
}
"
    "@Test
@Test
void hasPluginWithNonMatchingPlugin() {
    GradlePluginContainer pluginContainer = new GradlePluginContainer();
    pluginContainer.apply("com.example");
    assertThat(pluginContainer.has("com.example.another")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/MavenRepositoryContainerTests.java
Tests:
    "@Test
@Test
void addMavenRepository() {
    MavenRepositoryContainer container = createTestContainer();
    container.add(MavenRepository.withIdAndUrl("test", "https:
    assertThat(container.ids()).containsOnly("test");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("test")).isTrue();
    MavenRepository repository = container.get("test");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("my repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isTrue();
    assertThat(repository.isSnapshotsEnabled()).isFalse();
}
"
    "@Test
@Test
void addMavenRepositoryInstance() {
    MavenRepositoryContainer container = createTestContainer();
    MavenRepository instance = MavenRepository.withIdAndUrl("test", "https:
    container.add(instance);
    assertThat(container.ids()).containsOnly("test");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("test")).isTrue();
    MavenRepository repository = container.get("test");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("my repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isTrue();
    assertThat(repository.isSnapshotsEnabled()).isFalse();
}
"
    "@Test
@Test
void addMavenRepositoryWithSnapshotsEnabled() {
    MavenRepositoryContainer container = createTestContainer();
    container.add(MavenRepository.withIdAndUrl("custom", "https:
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    MavenRepository repository = container.get("custom");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("custom-snapshots");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isFalse();
    assertThat(repository.isSnapshotsEnabled()).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleConfigurationContainerTests.java
Tests:
    "@Test
@Test
void hasWithMatchingRegisteredName() {
    GradleConfigurationContainer container = new GradleConfigurationContainer();
    container.add("devOnly");
    assertThat(container.has("devOnly")).isTrue();
}
"
    "@Test
@Test
void hasWithMatchingCustomization() {
    GradleConfigurationContainer container = new GradleConfigurationContainer();
    container.customize("runtime", (configuration) -> configuration.extendsFrom("test"));
    assertThat(container.has("runtime")).isTrue();
}
"
    "@Test
@Test
void hasWithNonMatchingNameOrCustomization() {
    GradleConfigurationContainer container = new GradleConfigurationContainer();
    container.add("devOnly");
    container.customize("runtime", (configuration) -> configuration.extendsFrom("test"));
    assertThat(container.has("test")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BomContainerTests.java
Tests:
    "@Test
@Test
void addBom() {
    BomContainer container = createTestContainer();
    container.add("root", BillOfMaterials.withCoordinates("org.springframework.boot", "spring-boot-dependencies").version(VersionReference.ofProperty("spring-boot.version")));
    assertThat(container.ids()).containsOnly("root");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("root")).isTrue();
    BillOfMaterials bom = container.get("root");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(bom.getArtifactId()).isEqualTo("spring-boot-dependencies");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofProperty("spring-boot.version"));
    assertThat(bom.getOrder()).isEqualTo(Integer.MAX_VALUE);
}
"
    "@Test
@Test
void addBomWithOrder() {
    BomContainer container = createTestContainer();
    container.add("custom", BillOfMaterials.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).order(42));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    BillOfMaterials bom = container.get("custom");
    assertThat(bom).isNotNull();
    assertThat(bom.getGroupId()).isEqualTo("com.example");
    assertThat(bom.getArtifactId()).isEqualTo("acme");
    assertThat(bom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(bom.getOrder()).isEqualTo(42);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BuildItemContainerTests.java
Tests:
    "@Test
@Test
void emptyContainer() {
    BuildItemContainer<String, String> container = createTestContainer(new LinkedHashMap<>());
    assertThat(container.isEmpty()).isTrue();
    assertThat(container.ids()).isEmpty();
    assertThat(container.items()).isEmpty();
    assertThat(container.get("any")).isNull();
    assertThat(container.has("any")).isFalse();
}
"
    "@Test
@Test
void addElement() {
    BuildItemContainer<String, String> container = createTestContainer(new LinkedHashMap<>());
    container.add("test", "value");
    assertThat(container.ids()).containsOnly("test");
    assertThat(container.items()).containsOnly("value");
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.get("test")).isEqualTo("value");
    assertThat(container.has("test")).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/DependencyContainerTests.java
Tests:
    "@Test
@Test
void addDependency() {
    DependencyContainer container = createTestContainer();
    container.add("web", "org.springframework.boot", "spring-boot-starter-web", DependencyScope.COMPILE);
    assertThat(container.ids()).containsOnly("web");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("web")).isTrue();
    Dependency web = container.get("web");
    assertThat(web).isNotNull();
    assertThat(web.getGroupId()).isEqualTo("org.springframework.boot");
    assertThat(web.getArtifactId()).isEqualTo("spring-boot-starter-web");
    assertThat(web.getVersion()).isNull();
    assertThat(web.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"
    "@Test
@Test
void addDependencyWithVersion() {
    DependencyContainer container = createTestContainer();
    container.add("custom", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.COMPILE));
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    Dependency custom = container.get("custom");
    assertThat(custom).isNotNull();
    assertThat(custom.getGroupId()).isEqualTo("com.example");
    assertThat(custom.getArtifactId()).isEqualTo("acme");
    assertThat(custom.getVersion()).isEqualTo(VersionReference.ofValue("1.0.0"));
    assertThat(custom.getScope()).isEqualTo(DependencyScope.COMPILE);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenPluginContainerTests.java
Tests:
    "@Test
@Test
void hasPluginWithMatchingPlugin() {
    MavenPluginContainer pluginContainer = new MavenPluginContainer();
    pluginContainer.add("com.example", "test-plugin");
    assertThat(pluginContainer.has("com.example", "test-plugin")).isTrue();
}
"
    "@Test
@Test
void hasPluginWithNonMatchingPlugin() {
    MavenPluginContainer pluginContainer = new MavenPluginContainer();
    pluginContainer.add("com.example", "test-plugin");
    assertThat(pluginContainer.has("com.example", "another-plugin")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenProfileContainerTests.java
Tests:
    "@Test
@Test
void hasProfileWithMatchingProfile() {
    MavenProfileContainer container = createTestContainer();
    container.id("profile1");
    assertThat(container.has("profile1")).isTrue();
}
"
    "@Test
@Test
void hasProfileWithNonMatchingProfile() {
    MavenProfileContainer container = createTestContainer();
    container.id("profile1");
    assertThat(container.has("profile2")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenResourceContainerTests.java
Tests:
    "@Test
@Test
void mavenResourceCanBeSearched() {
    MavenResourceContainer container = new MavenResourceContainer();
    assertThat(container.has("src/main/test")).isFalse();
    container.add("src/main/test");
    assertThat(container.has("src/main/test")).isTrue();
}
"
    "@Test
@Test
void mavenResourceCanBeRemoved() {
    MavenResourceContainer container = new MavenResourceContainer();
    container.add("src/main/test");
    assertThat(container.has("src/main/test")).isTrue();
    assertThat(container.remove("src/main/test")).isTrue();
    assertThat(container.has("src/main/test")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeServiceContainerTests.java
Tests:
    "@Test
@Test
void hasWithMatchingService() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> service.image("my-image"));
    assertThat(container.has("test")).isTrue();
}
"
    "@Test
@Test
void hasWithNonMatchingName() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> service.image("my-image"));
    assertThat(container.has("another")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleTaskContainerTests.java
Tests:
    "@Test
@Test
void hasWithMatchingTask() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> task.attribute("fork", "true"));
    assertThat(container.has("test")).isTrue();
}
"
    "@Test
@Test
void hasWithMatchingTaskWithType() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customizeWithType("JavaCompile", (task) -> task.attribute("fork", "true"));
    assertThat(container.has("JavaCompile")).isTrue();
}
"
    "@Test
@Test
void hasWithNonMatchingNameOrType() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> task.attribute("fork", "true"));
    container.customizeWithType("JavaCompile", (task) -> task.attribute("fork", "true"));
    assertThat(container.has("another")).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationContainerTests.java
Tests:
    "@Test
@Test
void hasWithMatchingAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.has(TEST_CLASS_NAME)).isTrue();
}
"
    "@Test
@Test
void hasWithNonMatchingAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.has(ClassName.of("com.example.Another"))).isFalse();
}
"Here are the test scenarios for the `has` method in the `AnnotationContainer` class:

### Scenario 1: Check if an annotation exists in the container
```plaintext
Scenario 1: Check if an annotation exists in the container

Details:
  TestName: hasAnnotationWithExistingClassName
  Description: This test checks if the `has` method correctly identifies when an annotation with a given ClassName exists in the container.

Execution:
  Arrange: Create an instance of `AnnotationContainer` and add an annotation with a specific `ClassName`.
  Act: Call the `has` method with the same `ClassName`.
  Assert: Verify that the `has` method returns `true`.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method accurately detects the presence of an annotation associated with a specific `ClassName` in the container.
  This is significant because it ensures that the container correctly manages and retrieves annotations based on their associated class names.
```

### Scenario 2: Check if a non-existent annotation is not found in the container
```plaintext
Scenario 2: Check if a non-existent annotation is not found in the container

Details:
  TestName: hasAnnotationWithNonExistingClassName
  Description: This test checks if the `has` method correctly identifies when an annotation with a given ClassName does not exist in the container.

Execution:
  Arrange: Create an instance of `AnnotationContainer` and do not add any annotations.
  Act: Call the `has` method with a `ClassName` that has not been added to the container.
  Assert: Verify that the `has` method returns `false`.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method accurately identifies the absence of an annotation associated with a specific `ClassName` in the container.
  This is significant because it ensures that the container correctly handles cases where an annotation is not present.
```

### Scenario 3: Check if the `has` method handles null input gracefully
```plaintext
Scenario 3: Check if the `has` method handles null input gracefully

Details:
  TestName: hasAnnotationWithNullClassName
  Description: This test checks if the `has` method handles a null `ClassName` input gracefully without throwing an exception.

Execution:
  Arrange: Create an instance of `AnnotationContainer`.
  Act: Call the `has` method with a null `ClassName`.
  Assert: Verify that the `has` method returns `false` without throwing an exception.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method does not break when provided with a null input and gracefully returns `false`.
  This is significant because it ensures that the method is robust and can handle unexpected null inputs without causing runtime errors.
```

### Scenario 4: Check if the `has` method works correctly after removing an annotation
```plaintext
Scenario 4: Check if the `has` method works correctly after removing an annotation

Details:
  TestName: hasAnnotationAfterRemoval
  Description: This test checks if the `has` method correctly identifies the absence of an annotation after it has been removed from the container.

Execution:
  Arrange: Create an instance of `AnnotationContainer`, add an annotation with a specific `ClassName`, and then remove the annotation.
  Act: Call the `has` method with the `ClassName` of the removed annotation.
  Assert: Verify that the `has` method returns `false`.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method accurately reflects the removal of an annotation and correctly identifies its absence.
  This is significant because it ensures that the container correctly updates its internal state when annotations are removed.
```

### Scenario 5: Check if the `has` method works correctly with a deep copy of the container
```plaintext
Scenario 5: Check if the `has` method works correctly with a deep copy of the container

Details:
  TestName: hasAnnotationInDeepCopyContainer
  Description: This test checks if the `has` method works correctly when called on a deep copy of the `AnnotationContainer`.

Execution:
  Arrange: Create an instance of `AnnotationContainer`, add an annotation with a specific `ClassName`, and create a deep copy of the container.
  Act: Call the `has` method on the deep copy with the `ClassName` of the added annotation.
  Assert: Verify that the `has` method returns `true`.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method works correctly on a deep copy of the container, ensuring that the deep copy maintains the same state as the original container.
  This is significant because it ensures that the `deepCopy` method produces a valid and accurate copy of the container.
```

### Scenario 6: Check if the `has` method works correctly with an empty container
```plaintext
Scenario 6: Check if the `has` method works correctly with an empty container

Details:
  TestName: hasAnnotationInEmptyContainer
  Description: This test checks if the `has` method correctly handles an empty `AnnotationContainer`.

Execution:
  Arrange: Create an instance of `AnnotationContainer` without adding any annotations.
  Act: Call the `has` method with any `ClassName`.
  Assert: Verify that the `has` method returns `false`.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  The assertion aims to confirm that the `has` method returns `false` when called on an empty container, ensuring that the method correctly handles the absence of any annotations.
  This is significant because it ensures that the `has` method does not produce false positives when the container is empty.
```

These scenarios cover various aspects of the `has` method, including normal operation, edge cases, and error handling.,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.function.Consumer;
import java.util.stream.Stream;
import io.spring.initializr.generator.language.Annotation.Builder;

public class AnnotationContainerHasTest {

	private AnnotationContainer annotationContainer;

	@BeforeEach
	public void setUp() {
		annotationContainer = new AnnotationContainer();
	}

	@Test
	@Tag("valid")
	public void testHasAnnotationWithExistingClassName() {
		ClassName className = ClassName.of("com.example.MyAnnotation");
		annotationContainer.add(className, builder -> {
		});
		assertTrue(annotationContainer.has(className));
	}

	@Test
	@Tag("valid")
	public void testHasAnnotationWithNonExistingClassName() {
		ClassName className = ClassName.of("com.example.MyAnnotation");
		assertFalse(annotationContainer.has(className));
	}

	@Test
	@Tag("invalid")
	public void testHasAnnotationWithNullClassName() {
		assertFalse(annotationContainer.has(null));
	}

	@Test
	@Tag("valid")
	public void testHasAnnotationAfterRemoval() {
		ClassName className = ClassName.of("com.example.MyAnnotation");
		annotationContainer.add(className, builder -> {
		});
		annotationContainer.remove(className);
		assertFalse(annotationContainer.has(className));
	}

	@Test
	@Tag("valid")
	public void testHasAnnotationInDeepCopyContainer() {
		ClassName className = ClassName.of("com.example.MyAnnotation");
		annotationContainer.add(className, builder -> {
		});
		AnnotationContainer deepCopy = annotationContainer.deepCopy();
		assertTrue(deepCopy.has(className));
	}

	@Test
	@Tag("valid")
	public void testHasAnnotationInEmptyContainer() {
		ClassName className = ClassName.of("com.example.MyAnnotation");
		assertFalse(annotationContainer.has(className));
	}

}