/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getSimpleName_48f60ecb3f
ROOST_METHOD_SIG_HASH=getSimpleName_a749ddc05b

```java
Scenario 1: Test the basic functionality of getSimpleName

Details:
  TestName: getSimpleName
  Description: This test checks that the getSimpleName method returns the correct simple name for a ClassName instance.

Execution:
  Arrange: Create a ClassName instance with a known simple name.
  Act: Invoke the getSimpleName method on the instance.
  Assert: Verify that the returned simple name matches the expected value.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Test getSimpleName with a nested class

Details:
  TestName: getSimpleNameNestedClass
  Description: This test checks that the getSimpleName method correctly handles nested classes.

Execution:
  Arrange: Create a ClassName instance representing a nested class.
  Act: Invoke the getSimpleName method on the nested class instance.
  Assert: Verify that the returned simple name is correct.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Test getSimpleName with a primitive type

Details:
  TestName: getSimpleNamePrimitiveType
  Description: This test checks that the getSimpleName method correctly handles primitive types.

Execution:
  Arrange: Create a ClassName instance representing a primitive type.
  Act: Invoke the getSimpleName method on the primitive type instance.
  Assert: Verify that the returned simple name is correct.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Test getSimpleName with a class in the default package

Details:
  TestName: getSimpleNameDefaultPackage
  Description: This test checks that the getSimpleName method correctly handles classes in the default package.

Execution:
  Arrange: Create a ClassName instance representing a class in the default package.
  Act: Invoke the getSimpleName method on the instance.
  Assert: Verify that the returned simple name is correct.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Test getSimpleName with a class in the java.lang package

Details:
  TestName: getSimpleNameJavaLangPackage
  Description: This test checks that the getSimpleName method correctly handles classes in the java.lang package.

Execution:
  Arrange: Create a ClassName instance representing a class in the java.lang package.
  Act: Invoke the getSimpleName method on the instance.
  Assert: Verify that the returned simple name is correct.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.List;
import java.util.Objects;
import javax.lang.model.SourceVersion;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;

public class ClassNameGetSimpleNameTest {

	@Tag("valid")
	@Test
	public void getSimpleName() {
		ClassName className = new ClassName("com.example", "TestClass", null);
		assertEquals("TestClass", className.getSimpleName());
	}

	@Tag("valid")
	@Test
	public void getSimpleNameNestedClass() {
		ClassName outerClass = new ClassName("com.example", "OuterClass", null);
		ClassName nestedClass = new ClassName("com.example", "NestedClass", outerClass);
		assertEquals("NestedClass", nestedClass.getSimpleName());
	}

	@Tag("valid")
	@Test
	public void getSimpleNamePrimitiveType() {
		ClassName className = new ClassName("java.lang", "int", null);
		assertEquals("int", className.getSimpleName());
	}

	@Tag("valid")
	@Test
	public void getSimpleNameDefaultPackage() {
		ClassName className = new ClassName("", "DefaultClass", null);
		assertEquals("DefaultClass", className.getSimpleName());
	}

	@Tag("valid")
	@Test
	public void getSimpleNameJavaLangPackage() {
		ClassName className = new ClassName("java.lang", "String", null);
		assertEquals("String", className.getSimpleName());
	}

}