/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=toString_7c98e53e1e
ROOST_METHOD_SIG_HASH=toString_bbffdadaa2

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeFileWriterTests.java
Tests:
    "@Test
private String write(ComposeFile file) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, "\t"::repeat);
    new ComposeFileWriter().writeTo(writer, file);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/text/MustacheSectionTests.java
Tests:
    "@Test
@Test
void renderSection() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.singletonMap("key", "hello"));
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("hello%n"));
}
"
    "@Test
@Test
void renderSectionWithCustomModelResolution() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.emptyMap()) {

        @Override
        protected Map<String, Object> resolveModel(Map<String, Object> model) {
            return Collections.singletonMap("key", "custom");
        }
    };
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("custom%n"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionParserTests.java
Tests:
    "@Test
@Test
void versionWithNoQualifier() {
    Version version = this.parser.parse("1.2.0");
    assertThat(version.toString()).isEqualTo("1.2.0");
}
"
    "@Test
@Test
void versionWithQualifierAndDotSeparator() {
    Version version = this.parser.parse("1.2.0.RELEASE");
    assertThat(version.toString()).isEqualTo("1.2.0.RELEASE");
}
"
    "@Test
@Test
void versionWithQualifierAndDashSeparator() {
    Version version = this.parser.parse("1.2.0-SNAPSHOT");
    assertThat(version.toString()).isEqualTo("1.2.0-SNAPSHOT");
}
"
    "@Test
@Test
void versionWithQualifierVersionAndDotSeparator() {
    Version version = this.parser.parse("1.2.0.RC2");
    assertThat(version.toString()).isEqualTo("1.2.0.RC2");
}
"
    "@Test
@Test
void versionWithQualifierVersionAndDashSeparator() {
    Version version = this.parser.parse("1.2.0-M3");
    assertThat(version.toString()).isEqualTo("1.2.0-M3");
}
"
    "@Test
@Test
void parseVariableVersionMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.3.x.BUILD-SNAPSHOT").toString()).isEqualTo("1.3.9.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoPatchMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.x.x.RELEASE").toString()).isEqualTo("1.3.8.RELEASE");
}
"
    "@Test
@Test
void parseVariableVersionNoQualifierMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.4.0.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.4.x").toString()).isEqualTo("1.4.0.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.4.x.BUILD-SNAPSHOT").toString()).isEqualTo("1.4.999.BUILD-SNAPSHOT");
}
"
    "@Test
@Test
void parseVariableVersionNoPatchNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.3.9.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("2.x.x.RELEASE").toString()).isEqualTo("2.999.999.RELEASE");
}
"
    "@Test
@Test
void parseVariableVersionNoQualifierNoMatch() {
    List<Version> currentVersions = Arrays.asList(this.parser.parse("1.3.8.RELEASE"), this.parser.parse("1.4.0.BUILD-SNAPSHOT"));
    this.parser = new VersionParser(currentVersions);
    assertThat(this.parser.parse("1.2.x").toString()).isEqualTo("1.2.999");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GroovyDslGradleSettingsWriterTests.java
Tests:
    "@Test
private String generateSettings(GradleBuild build) {
    GradleSettingsWriter writer = new GroovyDslGradleSettingsWriter();
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out, new SimpleIndentStrategy("\t")), build);
    return out.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void functionModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("toString").modifiers(KotlinModifier.OVERRIDE, KotlinModifier.PUBLIC, KotlinModifier.OPEN).returning("java.lang.String").body(CodeBlock.ofStatement("return super.toString()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    open override fun toString(): String {", "        return super.toString()", "    }", "", "}");
}
"
    "@Test
private Path writeSourceCode(KotlinSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(JavaSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/packaging/PackagingTests.java
Tests:
    "@Test
@Test
void jarPackaging() {
    Packaging jar = Packaging.forId("jar");
    assertThat(jar).isInstanceOf(JarPackaging.class);
    assertThat(jar.id()).isEqualTo("jar");
    assertThat(jar.toString()).isEqualTo("jar");
}
"
    "@Test
@Test
void warPackaging() {
    Packaging war = Packaging.forId("war");
    assertThat(war).isInstanceOf(WarPackaging.class);
    assertThat(war.id()).isEqualTo("war");
    assertThat(war.toString()).isEqualTo("war");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenBuildWriterTests.java
Tests:
    "@Test
private String writePom(MavenBuildWriter writer, MavenBuild mavenBuild) {
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out), mavenBuild);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
private String write(CodeBlock code, FormattingOptions options) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, new SimpleIndentStrategy("\t"));
    code.write(writer, options);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BuildSystemTests.java
Tests:
    "@Test
@Test
void gradleBuildSystem() {
    BuildSystem gradle = BuildSystem.forId("gradle");
    assertThat(gradle).isInstanceOf(GradleBuildSystem.class);
    assertThat(gradle.id()).isEqualTo("gradle");
    assertThat(gradle.toString()).isEqualTo("gradle");
}
"
    "@Test
@Test
void mavenBuildSystem() {
    BuildSystem maven = BuildSystem.forId("maven");
    assertThat(maven).isInstanceOf(MavenBuildSystem.class);
    assertThat(maven.id()).isEqualTo("maven");
    assertThat(maven.toString()).isEqualTo("maven");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/LanguageTests.java
Tests:
    "@Test
@Test
void javaLanguage() {
    Language java = Language.forId("java", "11");
    assertThat(java).isInstanceOf(JavaLanguage.class);
    assertThat(java.id()).isEqualTo("java");
    assertThat(java.toString()).isEqualTo("java");
    assertThat(java.jvmVersion()).isEqualTo("11");
}
"
    "@Test
@Test
void kotlinLanguage() {
    Language kotlin = Language.forId("kotlin", null);
    assertThat(kotlin).isInstanceOf(KotlinLanguage.class);
    assertThat(kotlin.id()).isEqualTo("kotlin");
    assertThat(kotlin.toString()).isEqualTo("kotlin");
    assertThat(kotlin.jvmVersion()).isEqualTo("1.8");
}
"
    "@Test
@Test
void groovyLanguage() {
    Language groovy = Language.forId("groovy", "1.8");
    assertThat(groovy).isInstanceOf(GroovyLanguage.class);
    assertThat(groovy.id()).isEqualTo("groovy");
    assertThat(groovy.toString()).isEqualTo("groovy");
    assertThat(groovy.jvmVersion()).isEqualTo("1.8");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/IndentingWriterTests.java
Tests:
    "@Test
private String content() {
    return this.stringWriter.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/KotlinDslGradleSettingsWriterTests.java
Tests:
    "@Test
private String generateSettings(GradleBuild build) {
    GradleSettingsWriter writer = new KotlinDslGradleSettingsWriter();
    StringWriter out = new StringWriter();
    writer.writeTo(new IndentingWriter(out, new SimpleIndentStrategy("\t")), build);
    return out.toString().replace("\r\n", "\n");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionRangeTests.java
Tests:
    "@Test
@Test
void simpleStartingRange() {
    assertThat(new VersionRange(Version.parse("1.3.0.RELEASE")).toString()).isEqualTo(">=1.3.0.RELEASE");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(GroovySourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"```plaintext
Scenario 1: Verify toString for a simple class name without package

Details:
  TestName: simpleClassNameToString
  Description: This test checks if the toString method correctly returns the canonical name for a simple class name without a package.

Execution:
  Arrange: Create an instance of ClassName with a simple name and no package.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly handles simple class names without packages.

Scenario 2: Verify toString for a class name with a package

Details:
  TestName: classNameWithPackageToString
  Description: This test checks if the toString method correctly returns the canonical name for a class name with a package.

Execution:
  Arrange: Create an instance of ClassName with a simple name and a package.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly includes the package name in the canonical name.

Scenario 3: Verify toString for a nested class

Details:
  TestName: nestedClassToString
  Description: This test checks if the toString method correctly returns the canonical name for a nested class.

Execution:
  Arrange: Create instances of ClassName representing a nested class and its enclosing class.
  Act: Invoke the toString method on the nested class instance.
  Assert: Verify that the returned string matches the expected canonical name, including both the enclosing and nested class names.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly handles nested class names.

Scenario 4: Verify toString for a primitive type

Details:
  TestName: primitiveTypeToString
  Description: This test checks if the toString method correctly returns the canonical name for a primitive type.

Execution:
  Arrange: Create an instance of ClassName for a primitive type.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name, including the java.lang package for primitive types.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly includes the java.lang package for primitive types.

Scenario 5: Verify toString for a class with an empty package

Details:
  TestName: emptyPackageToString
  Description: This test checks if the toString method correctly returns the canonical name for a class with an empty package.

Execution:
  Arrange: Create an instance of ClassName with a simple name and an empty package.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name, which should be the simple name without any package prefix.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly handles classes with an empty package.

Scenario 6: Verify toString for a class with a complex package structure

Details:
  TestName: complexPackageStructureToString
  Description: This test checks if the toString method correctly returns the canonical name for a class with a complex package structure.

Execution:
  Arrange: Create an instance of ClassName with a simple name and a complex package structure.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name, including the full package structure.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly handles complex package structures.

Scenario 7: Verify toString for a class with special characters in the package name

Details:
  TestName: specialCharactersInPackageToString
  Description: This test checks if the toString method correctly returns the canonical name for a class with special characters in the package name.

Execution:
  Arrange: Create an instance of ClassName with a simple name and a package name containing special characters.
  Act: Invoke the toString method on the created instance.
  Assert: Verify that the returned string matches the expected canonical name, including the special characters in the package name.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  This test ensures that the toString method correctly handles special characters in the package name.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Objects;
import javax.lang.model.SourceVersion;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.List;

class ClassNameToStringTest {

	@Test
	@Tag("valid")
	public void simpleClassNameToString() {
		ClassName className = new ClassName("", "SimpleClass", null);
		assertEquals("SimpleClass", className.toString());
	}

	@Test
	@Tag("valid")
	public void classNameWithPackageToString() {
		ClassName className = new ClassName("com.example", "MyClass", null);
		assertEquals("com.example.MyClass", className.toString());
	}

	@Test
	@Tag("valid")
	public void nestedClassToString() {
		ClassName enclosing = new ClassName("com.example", "Outer", null);
		ClassName nested = new ClassName("com.example", "Inner", enclosing);
		assertEquals("com.example.Outer.Inner", nested.toString());
	}

	@Test
	@Tag("valid")
	public void primitiveTypeToString() {
		ClassName primitive = new ClassName("java.lang", "int", null);
		assertEquals("java.lang.int", primitive.toString());
	}

	@Test
	@Tag("valid")
	public void emptyPackageToString() {
		ClassName className = new ClassName("", "EmptyPackageClass", null);
		assertEquals("EmptyPackageClass", className.toString());
	}

	@Test
    @Tag("valid")
    public void complexPackageStructureToString() {
        ClassName className = new ClassName("com.example.subpackage io.spring.initializr.generator.language;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
import java.util.List;

	assertEquals("com.example.subpackage io.spring.initializr.generator.language;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

}

@Test
    @Tag("valid")
    public void specialCharactersInPackageToString() {
        ClassName className = new ClassName("com.example.package io.spring.initializr.generator.language;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Objects;
import javax.lang.model.SourceVersion;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.List;

assertEquals("com.example.package io.spring.initializr.generator.language;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Objects;
import javax.lang.model.SourceVersion;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.List;

}}

class ClassName {

	private String package io.spring.initializr.generator.language;
import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	private String simpleName;

	private ClassName enclosingType;

	private String canonicalName;

	private ClassName(String packageName, String simpleName, ClassName enclosingType) {
        this.package io.spring.initializr.generator.language;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	this.simpleName=simpleName;this.enclosingType=enclosingType;}

	public static ClassName of(String fqName) {
		Assert.notNull(fqName, "'className' must not be null");
		if (!isValidClassName(fqName)) {
			throw new IllegalStateException("Invalid class name '" + fqName + "'");
		}
		if (!fqName.contains("$")) {
			return createClassName(fqName);
		}
		String[] elements = fqName.split("(?<!\\$)\\$(?!\\$)");
		ClassName className = createClassName(elements[0]);
		for (int i = 1; i < elements.length; i++) {
			className = new ClassName(className.getPackageName(), elements[i], className);
		}
		return className;
	}

	public String getName() {
        ClassName enclosingType = getEnclosingType();
        String simpleName = getSimpleName();
        return (enclosingType != null) ? (enclosingType.getName() + '.' + simpleName) : simpleName;
    }

	public String getPackageName() {
        return this.package io.spring.initializr.generator.language;
import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	}

	public String getSimpleName() {
        return this.simpleName;
    }

	public ClassName getEnclosingType() {
		return this.enclosingType;
	}

	public String getCanonicalName() {
		if (this.canonicalName == null) {
			StringBuilder names = new StringBuilder();
			buildName(this, names);
			this.canonicalName = addPackageIfNecessary(names.toString());
		}
		return this.canonicalName;
	}

	private boolean isPrimitive() {
		return isPrimitive(getSimpleName());
	}

	private String addPackageIfNecessary(String part) {
        if (this.packageName.isEmpty() || this.packageName.equals("java.lang") && isPrimitive()) {
            return part;
        }
        return this.package io.spring.initializr.generator.language;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	}

	private static boolean isValidClassName(String className) {
        for (String s : className.split("\\.", -1)) {
            String candidate = s.replace("[", "").replace("]", "");
            if (!SourceVersion.isIdentifier(candidate)) {
                return false;
            }
        }
        return true;
    }

	private static ClassName createClassName(String className) {
        int i = className.lastIndexOf('.');
        if (i != -1) {
            return new ClassName(className.substring(0, i), className.substring(i + 1), null);
        } else {
            String package io.spring.initializr.generator.language;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	return new ClassName(
	package io.spring.initializr.generator.language;

import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import java.util.Objects;
	import javax.lang.model.SourceVersion;
	import org.springframework.lang.Nullable;
	import org.springframework.util.Assert;
	import static org.junit.jupiter.api.Assertions.assertEquals;
	import org.junit.jupiter.api.*;
	import java.util.List;

	}}

	private static void buildName(ClassName className, StringBuilder sb) {
		if (className == null) {
			return;
		}
		String typeName = (className.getEnclosingType() != null) ? "." + className.getSimpleName()
				: className.getSimpleName();
		sb.insert(0, typeName);
		buildName(className.getEnclosingType(), sb);
	}

	@Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ClassName className)) {
            return false;
        }
        return getCanonicalName().equals(className.getCanonicalName());
    }

	@Override
    public int hashCode() {
        return Objects.hash(getCanonicalName());
    }

	@Override
    public String toString() {
        return getCanonicalName();
    }

}