/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getName_2194eac8d2
ROOST_METHOD_SIG_HASH=getName_8400ac6fb7

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/MavenRepositoryTests.java
Tests:
    "@Test
@Test
void repositoryWithDetails() {
    MavenRepository repo = MavenRepository.withIdAndUrl("test", "https:
    assertThat(repo.getId()).isEqualTo("test");
    assertThat(repo.getUrl()).isEqualTo("https:
    assertThat(repo.getName()).isEqualTo("Test repository");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenPluginTests.java
Tests:
    "@Test
@SuppressWarnings("unchecked")
@Test
void configurationParameterWithNestedValuesCanBeAdded() {
    MavenPlugin plugin = plugin("com.example", "test-plugin").configuration((configuration) -> configuration.configure("items", (items) -> {
        items.add("item", (firstItem) -> firstItem.add("name", "one"));
        items.add("item", (secondItem) -> secondItem.add("name", "two"));
    })).build();
    assertThat(plugin.getConfiguration().getSettings()).hasSize(1);
    Setting setting = plugin.getConfiguration().getSettings().get(0);
    assertThat(setting.getName()).isEqualTo("items");
    assertThat(setting.getValue()).isInstanceOf(List.class);
    List<Setting> values = (List<Setting>) setting.getValue();
    assertThat(values.stream().map(Setting::getName)).containsExactly("item", "item");
    assertThat(values.stream().map(Setting::getValue)).anySatisfy((value) -> {
        assertThat(value).isInstanceOf(List.class);
        List<Setting> itemValues = (List<Setting>) value;
        assertThat(itemValues.stream().map(Setting::getName)).containsExactly("name");
        assertThat(itemValues.stream().map(Setting::getValue)).containsExactly("one");
    });
    assertThat(values.stream().map(Setting::getValue)).anySatisfy((value) -> {
        assertThat(value).isInstanceOf(List.class);
        List<Setting> itemValues = (List<Setting>) value;
        assertThat(itemValues.stream().map(Setting::getName)).containsExactly("name");
        assertThat(itemValues.stream().map(Setting::getValue)).containsExactly("two");
    });
    assertThat(values).hasSize(2);
}
"
    "@Test
@Test
@SuppressWarnings("unchecked")
void configurationParameterWithNestedValuesCanBeCustomized() {
    MavenPlugin plugin = plugin("com.example", "test-plugin").configuration((configuration) -> configuration.configure("items", (items) -> items.add("item", "one"))).configuration((configuration) -> configuration.configure("items", (items) -> items.add("item", "two"))).build();
    assertThat(plugin.getConfiguration().getSettings()).hasSize(1);
    Setting setting = plugin.getConfiguration().getSettings().get(0);
    assertThat(setting.getName()).isEqualTo("items");
    assertThat(setting.getValue()).isInstanceOf(List.class);
    List<Setting> values = (List<Setting>) setting.getValue();
    assertThat(values.stream().map(Setting::getName)).containsExactly("item", "item");
    assertThat(values.stream().map(Setting::getValue)).containsExactly("one", "two");
}
"
    "@Test
@Test
@SuppressWarnings("unchecked")
void configurationParameterWithSeveralLevelOfNestedValuesCanBeCustomized() {
    MavenPlugin plugin = plugin("com.example", "test-plugin").configuration((configuration) -> configuration.configure("items", (items) -> items.configure("item", (subItems) -> subItems.add("subItem", "one")))).configuration((configuration) -> configuration.configure("items", (items) -> items.configure("item", (subItems) -> subItems.add("subItem", "two").add("subItem", "three")))).build();
    assertThat(plugin.getConfiguration().getSettings()).hasSize(1);
    Setting setting = plugin.getConfiguration().getSettings().get(0);
    assertThat(setting.getName()).isEqualTo("items");
    assertThat(setting.getValue()).isInstanceOf(List.class);
    List<Setting> items = (List<Setting>) setting.getValue();
    assertThat(items).hasSize(1);
    Setting item = items.get(0);
    assertThat(item.getName()).isEqualTo("item");
    assertThat(item.getValue()).isInstanceOf(List.class);
    List<Setting> subItems = (List<Setting>) item.getValue();
    assertThat(subItems.stream().map(Setting::getName)).containsExactly("subItem", "subItem", "subItem");
    assertThat(subItems.stream().map(Setting::getValue)).containsExactly("one", "two", "three");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationTests.java
Tests:
    "@Test
@Test
void annotationWithClass() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", Test.class).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithClassName() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ClassName.of(Test.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithTypeReferenceInvokeConfiguredFormattingOptions() {
    ClassName typeReference = ClassName.of("com.example.Another");
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.classReference(typeReference)).willReturn(CodeBlock.of("$T::class", typeReference));
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", typeReference).build();
    assertThat(write(test, options)).isEqualTo("@Test(test = Another::class)");
    verify(options).classReference(typeReference);
    assertThat(test.getImports()).containsOnly("com.example.Test", typeReference.getName());
}
"
    "@Test
@Test
void annotationWithEnum() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ChronoUnit.CENTURIES).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithEnumCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", CodeBlock.of("$T.CENTURIES", ChronoUnit.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithParameterClassAndCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("types", StringWriter.class, CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"
    "@Test
@Test
void annotationWithAmendedValues() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).add("types", StringWriter.class).add("types", CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDistributionManagementTests.java
Tests:
    "@Test
@Test
void distributionManagementWithRepository() {
    MavenDistributionManagement mdm = builder().repository((repository) -> repository.id("released-repo").name("released repo").url("https:
    DeploymentRepository repository = mdm.getRepository();
    assertThat(repository.getId()).isEqualTo("released-repo");
    assertThat(repository.getName()).isEqualTo("released repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.getLayout()).isEqualTo("default");
    assertThat(repository.getUniqueVersion()).isNull();
}
"
    "@Test
@Test
void distributionManagementWithSnapshotRepository() {
    MavenDistributionManagement mdm = builder().snapshotRepository((repository) -> repository.id("snapshot-repo").name("snapshot repo").url("scp:
    DeploymentRepository snapshotRepository = mdm.getSnapshotRepository();
    assertThat(snapshotRepository.getId()).isEqualTo("snapshot-repo");
    assertThat(snapshotRepository.getName()).isEqualTo("snapshot repo");
    assertThat(snapshotRepository.getUrl()).isEqualTo("scp:
    assertThat(snapshotRepository.getLayout()).isNull();
    assertThat(snapshotRepository.getUniqueVersion()).isTrue();
}
"
    "@Test
@Test
void distributionManagementWithSite() {
    MavenDistributionManagement mdm = builder().site((site) -> site.id("website").name("web site")).site((site) -> site.url("scp:
    Site site = mdm.getSite();
    assertThat(site.getId()).isEqualTo("website");
    assertThat(site.getName()).isEqualTo("web site");
    assertThat(site.getUrl()).isEqualTo("scp:
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenLicenseTests.java
Tests:
    "@Test
@Test
void licenseWithNameOnly() {
    MavenLicense license = new MavenLicense.Builder().name("Apache License, Version 2.0").build();
    assertThat(license.getName()).isEqualTo("Apache License, Version 2.0");
    assertThat(license.getUrl()).isNull();
    assertThat(license.getDistribution()).isNull();
    assertThat(license.getComments()).isNull();
}
"
    "@Test
@Test
void licenseWithFullDetails() {
    MavenLicense license = new MavenLicense.Builder().name("Apache License, Version 2.0").url("https:
    assertThat(license.getName()).isEqualTo("Apache License, Version 2.0");
    assertThat(license.getUrl()).isEqualTo("https:
    assertThat(license.getDistribution()).isEqualTo(Distribution.MANUAL);
    assertThat(license.getComments()).isEqualTo("A business-friendly OSS license");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/ProjectGeneratorTests.java
Tests:
    "@Test
@Test
void generateCanBeExtendedToFilterProjectContributors(@TempDir Path projectDir) {
    ProjectDescription description = mock(ProjectDescription.class);
    given(description.getArtifactId()).willReturn("test-custom-contributor");
    given(description.getBuildSystem()).willReturn(new MavenBuildSystem());
    ProjectGenerator generator = new ProjectGenerator(mockContextInitializr()) {

        @Override
        protected List<String> getCandidateProjectGenerationConfigurations(ProjectDescription generatorDescription) {
            assertThat(description).isSameAs(generatorDescription);
            return Collections.singletonList(TestProjectGenerationConfiguration.class.getName());
        }
    };
    DefaultProjectAssetGenerator assetGenerator = new DefaultProjectAssetGenerator((desc) -> projectDir);
    Path outputDir = generator.generate(description, assetGenerator);
    Path expectedFile = outputDir.resolve("artifact-id.txt");
    assertThat(expectedFile).isRegularFile();
    assertThat(expectedFile).hasContent("test-custom-contributor");
    verify(description).getArtifactId();
    verify(description).getBuildSystem();
}
"
    "@Test
@Test
void filterProjectContributorsCorrectly() {
    ProjectDescription description = mock(ProjectDescription.class);
    given(description.getArtifactId()).willReturn("test-custom-contributor");
    given(description.getBuildSystem()).willReturn(new MavenBuildSystem());
    ProjectGenerator generator = new ProjectGenerator(mockContextInitializr()) {

        @Override
        List<String> getProjectGenerationConfigurationFactoryNames() {
            return Lists.list(TestProjectGenerationConfiguration.class.getName(), TestProjectGenerationConfiguration2.class.getName());
        }

        @Override
        ProjectGenerationConfigurationTypeFilter getProjectGenerationConfigurationExclusionFilter() {
            return (clazz) -> !TestProjectGenerationConfiguration2.class.equals(clazz);
        }
    };
    List<String> candidates = generator.getCandidateProjectGenerationConfigurations(description);
    assertThat(candidates).containsOnly(TestProjectGenerationConfiguration.class.getCanonicalName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/ClassNameTests.java
Tests:
    "@Test
@ParameterizedTest
@MethodSource("primitivesAndPrimitivesArray")
void primitivesAreHandledProperly(ClassName className, String expectedName) {
    assertThat(className.getName()).isEqualTo(expectedName);
    assertThat(className.getCanonicalName()).isEqualTo(expectedName);
    assertThat(className.getPackageName()).isEqualTo("java.lang");
}
"
    "@Test
@ParameterizedTest
@MethodSource("arrays")
void arraysHaveSuitableReflectionTargetName(ClassName typeReference, String expectedName) {
    assertThat(typeReference.getName()).isEqualTo(expectedName);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/DefaultProjectAssetGeneratorTests.java
Tests:
    "@Test
@Test
void generationWithoutExplicitFactoryFailIfBeanIsNotPresent() {
    ProjectDescription description = new MutableProjectDescription();
    assertThatThrownBy(() -> {
        try (ProjectGenerationContext context = new ProjectGenerationContext()) {
            context.registerBean(ProjectDescription.class, () -> description);
            context.refresh();
            new DefaultProjectAssetGenerator().generate(context);
        }
    }).isInstanceOf(NoSuchBeanDefinitionException.class).hasMessageContaining(ProjectDirectoryFactory.class.getName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/MavenRepositoryContainerTests.java
Tests:
    "@Test
@Test
void addMavenRepository() {
    MavenRepositoryContainer container = createTestContainer();
    container.add(MavenRepository.withIdAndUrl("test", "https:
    assertThat(container.ids()).containsOnly("test");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("test")).isTrue();
    MavenRepository repository = container.get("test");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("my repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isTrue();
    assertThat(repository.isSnapshotsEnabled()).isFalse();
}
"
    "@Test
@Test
void addMavenRepositoryInstance() {
    MavenRepositoryContainer container = createTestContainer();
    MavenRepository instance = MavenRepository.withIdAndUrl("test", "https:
    container.add(instance);
    assertThat(container.ids()).containsOnly("test");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("test")).isTrue();
    MavenRepository repository = container.get("test");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("my repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isTrue();
    assertThat(repository.isSnapshotsEnabled()).isFalse();
}
"
    "@Test
@Test
void addMavenRepositoryWithSnapshotsEnabled() {
    MavenRepositoryContainer container = createTestContainer();
    container.add(MavenRepository.withIdAndUrl("custom", "https:
    assertThat(container.ids()).containsOnly("custom");
    assertThat(container.items()).hasSize(1);
    assertThat(container.isEmpty()).isFalse();
    assertThat(container.has("custom")).isTrue();
    MavenRepository repository = container.get("custom");
    assertThat(repository).isNotNull();
    assertThat(repository.getName()).isEqualTo("custom-snapshots");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.isReleasesEnabled()).isFalse();
    assertThat(repository.isSnapshotsEnabled()).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenProfileActivationTests.java
Tests:
    "@Test
@Test
void profileActivationOs() {
    Os os = createProfileActivation().os("test-name", null, "arm64", null).build().getOs();
    assertThat(os).isNotNull();
    assertThat(os.getName()).isEqualTo("test-name");
    assertThat(os.getFamily()).isNull();
    assertThat(os.getArch()).isEqualTo("arm64");
    assertThat(os.getVersion()).isNull();
}
"
    "@Test
@Test
void profileActivationProperty() {
    assertThat(createProfileActivation().property("test", "1").build().getProperty()).satisfies((property) -> {
        assertThat(property).isNotNull();
        assertThat(property.getName()).isEqualTo("test");
        assertThat(property.getValue()).isEqualTo("1");
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", StringUtils.class);
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassNameAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", ClassName.of(StringUtils.class));
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithParameterCodeBlockAddsImports() {
    CodeBlock code = CodeBlock.of("$L", CodeBlock.of("$T.truncate(myString)", ClassName.of(StringUtils.class)));
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDeveloperTests.java
Tests:
    "@Test
@Test
void developerWithIdOnly() {
    MavenDeveloper developer = new MavenDeveloper.Builder().id("jsmith").build();
    assertThat(developer.getId()).isEqualTo("jsmith");
    assertThat(developer.getName()).isNull();
    assertThat(developer.getEmail()).isNull();
    assertThat(developer.getUrl()).isNull();
    assertThat(developer.getOrganization()).isNull();
    assertThat(developer.getOrganizationUrl()).isNull();
    assertThat(developer.getRoles()).hasSize(0);
    assertThat(developer.getTimezone()).isNull();
    assertThat(developer.getProperties()).hasSize(0);
}
"
    "@Test
@Test
void developerWithFullDetails() {
    MavenDeveloper developer = new MavenDeveloper.Builder().id("jsmith").name("John Smith").email("john@example.com").url("http:
    assertThat(developer.getId()).isEqualTo("jsmith");
    assertThat(developer.getName()).isEqualTo("John Smith");
    assertThat(developer.getEmail()).isEqualTo("john@example.com");
    assertThat(developer.getUrl()).isEqualTo("http:
    assertThat(developer.getOrganization()).isEqualTo("Acme Corp");
    assertThat(developer.getOrganizationUrl()).isEqualTo("http:
    assertThat(developer.getRoles()).containsExactly("developer", "tester");
    assertThat(developer.getTimezone()).isEqualTo("Asia/Karachi");
    assertThat(developer.getProperties()).containsExactly(entry("prop1", "test1"), entry("prop2", "test2"), entry("prop3", "test3"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeServiceContainerTests.java
Tests:
    "@Test
@Test
void customizeService() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> {
        service.image("my-image");
        service.imageTag("my-image-tag");
        service.imageWebsite("https:
        service.environment("param", "value");
        service.ports(8080);
        service.command("run");
        service.label("foo", "bar");
    });
    assertThat(container.values()).singleElement().satisfies((service) -> {
        assertThat(service.getName()).isEqualTo("test");
        assertThat(service.getImage()).isEqualTo("my-image");
        assertThat(service.getImageTag()).isEqualTo("my-image-tag");
        assertThat(service.getImageWebsite()).isEqualTo("https:
        assertThat(service.getEnvironment()).containsOnly(entry("param", "value"));
        assertThat(service.getPorts()).containsOnly(8080);
        assertThat(service.getCommand()).isEqualTo("run");
        assertThat(service.getLabels()).containsOnly(entry("foo", "bar"));
    });
}
"
    "@Test
@Test
void customizeTaskSeveralTimeReuseConfiguration() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> {
        service.image("my-image");
        service.imageTag("my-image-tag");
        service.imageWebsite("https:
        service.environment("param", "value");
        service.ports(7070);
        service.command("run");
    });
    container.add("test", (service) -> {
        service.image("my-image");
        service.imageTag("my-image-tag");
        service.imageWebsite("https:
        service.environment("param", "value2");
        service.ports(8080);
        service.command("run2");
    });
    assertThat(container.values()).singleElement().satisfies((service) -> {
        assertThat(service.getName()).isEqualTo("test");
        assertThat(service.getImage()).isEqualTo("my-image");
        assertThat(service.getImageTag()).isEqualTo("my-image-tag");
        assertThat(service.getImageWebsite()).isEqualTo("https:
        assertThat(service.getEnvironment()).containsOnly(entry("param", "value2"));
        assertThat(service.getPorts()).containsOnly(7070, 8080);
        assertThat(service.getCommand()).isEqualTo("run2");
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleTaskContainerTests.java
Tests:
    "@Test
@Test
void customizeTask() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> {
        task.attribute("fork", "true");
        task.append("names", "test");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("test");
        assertThat(task.getType()).isNull();
        assertThat(task.getAttributes()).containsOnly(Attribute.set("fork", "true"), Attribute.append("names", "test"));
        assertThat(task.getInvocations()).isEmpty();
        assertThat(task.getNested()).isEmpty();
    });
}
"
    "@Test
@Test
void customizeTaskWithType() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customizeWithType("com.example.MyTask", (task) -> {
        task.attribute("fork", "true");
        task.invoke("property", "taskDir");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("MyTask");
        assertThat(task.getType()).isEqualTo("com.example.MyTask");
        assertThat(task.getAttributes()).containsOnly(Attribute.set("fork", "true"));
        assertThat(task.getInvocations()).singleElement().satisfies((invocation) -> {
            assertThat(invocation.getTarget()).isEqualTo("property");
            assertThat(invocation.getArguments()).containsOnly("taskDir");
        });
        assertThat(task.getNested()).isEmpty();
    });
}
"
    "@Test
@Test
void customizeTaskSeveralTimeReuseConfiguration() {
    GradleTaskContainer container = new GradleTaskContainer();
    container.customize("test", (task) -> {
        task.attribute("ignore", "false");
        task.attribute("fork", "true");
    });
    container.customize("test", (task) -> {
        task.attribute("fork", "false");
        task.invoke("method", "arg1", "arg2");
    });
    assertThat(container.values()).singleElement().satisfies((task) -> {
        assertThat(task.getName()).isEqualTo("test");
        assertThat(task.getType()).isNull();
        assertThat(task.getAttributes()).containsOnly(Attribute.set("ignore", "false"), Attribute.set("fork", "false"));
        assertThat(task.getInvocations()).singleElement().satisfies((invocation) -> {
            assertThat(invocation.getTarget()).isEqualTo("method");
            assertThat(invocation.getArguments()).containsOnly("arg1", "arg2");
        });
        assertThat(task.getNested()).isEmpty();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationContainerTests.java
Tests:
    "@Test
@Test
void valuesWithSimpleAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeReuseConfiguration() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "another"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test", "another");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeCanReplaceAttribute() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 42).build()));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.set("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 24).build()));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test", "com.example.Nested");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).singleElement().isInstanceOfSatisfying(Annotation.class, (nested) -> {
                assertThat(nested.getClassName()).isEqualTo(NESTED_CLASS_NAME);
                assertThat(nested.getAttributes()).singleElement().satisfies((nestedAttribute) -> {
                    assertThat(nestedAttribute.getName()).isEqualTo("counter");
                    assertThat(nestedAttribute.getValues()).containsExactly(24);
                });
            });
        });
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenProfileTests.java
Tests:
    "@Test
@Test
void profileWithActivation() {
    MavenProfile profile = createProfile("test");
    profile.activation().jdk("15").property("test", "value").jdk(null);
    assertThat(profile.getActivation().getProperty()).satisfies((property) -> {
        assertThat(property.getName()).isEqualTo("test");
        assertThat(property.getValue()).isEqualTo("value");
    });
    assertThat(profile.getActivation().getJdk()).isNull();
}
"### Scenario 1: Class with No Enclosing Type

**Details:**
- **TestName:** getNameWithoutEnclosingType
- **Description:** This test checks the behavior of the `getName` method when the class does not have an enclosing type.

**Execution:**
- **Arrange:** Create an instance of `ClassName` with no enclosing type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the simple name of the class.

**Validation:**
- The assertion aims to verify that the method correctly handles classes without enclosing types and returns only the simple name. This is significant for ensuring that the method correctly identifies and concatenates the names of nested classes when there are no enclosing types.

```java
@Test
void getNameWithoutEnclosingType() {
    ClassName className = new ClassName("com.example", "MyClass", null);
    String name = className.getName();
    assertEquals("com.example.MyClass", name);
}
```

### Scenario 2: Class with Enclosing Type

**Details:**
- **TestName:** getNameWithEnclosingType
- **Description:** This test checks the behavior of the `getName` method when the class has an enclosing type.

**Execution:**
- **Arrange:** Create an instance of `ClassName` with an enclosing type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the combined name of the enclosing type and the simple name of the class.

**Validation:**
- The assertion aims to verify that the method correctly concatenates the names of nested classes. This is crucial for ensuring that the method returns the fully qualified name of the class, which is essential for reflection and class loading.

```java
@Test
void getNameWithEnclosingType() {
    ClassName enclosingClass = new ClassName("com.example", "OuterClass", null);
    ClassName className = new ClassName("com.example", "InnerClass", enclosingClass);
    String name = className.getName();
    assertEquals("com.example.OuterClass.InnerClass", name);
}
```

### Scenario 3: Class with Multiple Levels of Enclosing Types

**Details:**
- **TestName:** getNameWithMultipleEnclosingTypes
- **Description:** This test checks the behavior of the `getName` method when the class has multiple levels of enclosing types.

**Execution:**
- **Arrange:** Create an instance of `ClassName` with multiple levels of enclosing types.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the combined name of all enclosing types and the simple name of the class.

**Validation:**
- The assertion aims to verify that the method correctly handles deeply nested classes. This is important for ensuring that the method can accurately reflect the structure of complex class hierarchies, which is crucial for tools that depend on reflection and class loading.

```java
@Test
void getNameWithMultipleEnclosingTypes() {
    ClassName enclosingClass1 = new ClassName("com.example", "OuterClass1", null);
    ClassName enclosingClass2 = new ClassName("com.example", "OuterClass2", enclosingClass1);
    ClassName className = new ClassName("com.example", "InnerClass", enclosingClass2);
    String name = className.getName();
    assertEquals("com.example.OuterClass1.OuterClass2.InnerClass", name);
}
```

### Scenario 4: Primitive Class

**Details:**
- **TestName:** getNameForPrimitiveClass
- **Description:** This test checks the behavior of the `getName` method for primitive classes.

**Execution:**
- **Arrange:** Create an instance of `ClassName` representing a primitive type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the correct name for the primitive type.

**Validation:**
- The assertion aims to verify that the method correctly identifies and returns the names of primitive types. This is important for ensuring that the method can handle primitive types, which have special treatment in Java.

```java
@Test
void getNameForPrimitiveClass() {
    ClassName className = new ClassName("", "int", null);
    String name = className.getName();
    assertEquals("int", name);
}
```

### Scenario 5: Array Class

**Details:**
- **TestName:** getNameForArrayClass
- **Description:** This test checks the behavior of the `getName` method for array classes.

**Execution:**
- **Arrange:** Create an instance of `ClassName` representing an array type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the correct name for the array type.

**Validation:**
- The assertion aims to verify that the method correctly identifies and returns the names of array types. This is important for ensuring that the method can handle array types, which have special syntax in Java.

```java
@Test
void getNameForArrayClass() {
    ClassName className = new ClassName("com.example", "String[]", null);
    String name = className.getName();
    assertEquals("com.example.String[]", name);
}
```

### Scenario 6: Nested Primitive Array Class

**Details:**
- **TestName:** getNameForNestedPrimitiveArrayClass
- **Description:** This test checks the behavior of the `getName` method for nested primitive array classes.

**Execution:**
- **Arrange:** Create an instance of `ClassName` representing a nested primitive array type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the correct name for the nested primitive array type.

**Validation:**
- The assertion aims to verify that the method correctly identifies and returns the names of nested primitive array types. This is important for ensuring that the method can handle complex type structures, which are common in Java.

```java
@Test
void getNameForNestedPrimitiveArrayClass() {
    ClassName className = new ClassName("com.example", "int[][]", null);
    String name = className.getName();
    assertEquals("com.example.int[][]", name);
}
```

### Scenario 7: Nested Class with Primitive Array

**Details:**
- **TestName:** getNameForNestedClassWithPrimitiveArray
- **Description:** This test checks the behavior of the `getName` method for nested classes with primitive array types.

**Execution:**
- **Arrange:** Create an instance of `ClassName` representing a nested class with a primitive array type.
- **Act:** Invoke the `getName` method.
- **Assert:** Verify that the method returns the correct name for the nested class with a primitive array type.

**Validation:**
- The assertion aims to verify that the method correctly identifies and returns the names of nested classes with primitive array types. This is important for ensuring that the method can handle complex type structures, which are common in Java.

```java
@Test
void getNameForNestedClassWithPrimitiveArray() {
    ClassName enclosingClass = new ClassName("com.example", "OuterClass", null);
    ClassName className = new ClassName("com.example", "int[][]", enclosingClass);
    String name = className.getName();
    assertEquals("com.example.OuterClass.int[][]", name);
}
```

These scenarios cover various edge cases and ensure that the `getName` method handles different types of classes and nested structures correctly.,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.Objects;
import org.junit.jupiter.api.*;
import java.util.List;
import javax.lang.model.SourceVersion;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;

@Tag("valid")
class ClassNameGetNameTest {

	@Test
	void getNameWithoutEnclosingType() {
		ClassName className = new ClassName("com.example", "MyClass", null);
		String name = className.getName();
		assertEquals("com.example.MyClass", name);
	}

	@Test
	@Tag("valid")
	void getNameWithEnclosingType() {
		ClassName enclosingClass = new ClassName("com.example", "OuterClass", null);
		ClassName className = new ClassName("com.example", "InnerClass", enclosingClass);
		String name = className.getName();
		assertEquals("com.example.OuterClass with its class name as ClassName.InnerClass", name);
	}

	@Test
	@Tag("valid")
	void getNameWithMultipleEnclosingTypes() {
		ClassName enclosingClass1 = new ClassName("com.example", "OuterClass1", null);
		ClassName enclosingClass2 = new ClassName("com.example", "OuterClass2", enclosingClass1);
		ClassName className = new ClassName("com.example", "InnerClass", enclosingClass2);
		String name = className.getName();
		assertEquals(
				"com.example.OuterClass1 with its class name as ClassName.OuterClass2 with its class name as ClassName.InnerClass",
				name);
	}

	@Test
	@Tag("valid")
	void getNameForPrimitiveClass() {
		ClassName className = new ClassName("", "int", null);
		String name = className.getName();
		assertEquals("int", name);
	}

	@Test
	@Tag("valid")
	void getNameForArrayClass() {
		ClassName className = new ClassName("com.example", "String[]", null);
		String name = className.getName();
		assertEquals("com.example.String[]", name);
	}

	@Test
	@Tag("valid")
	void getNameForNestedPrimitiveArrayClass() {
		ClassName className = new ClassName("com.example", "int[][]", null);
		String name = className.getName();
		assertEquals("com.example.int[][]", name);
	}

	@Test
	@Tag("valid")
	void getNameForNestedClassWithPrimitiveArray() {
		ClassName enclosingClass = new ClassName("com.example", "OuterClass", null);
		ClassName className = new ClassName("com.example", "int[][]", enclosingClass);
		String name = className.getName();
		assertEquals("com.example.OuterClass with its class name as ClassName.int[][]", name);
	}

}