/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDistributionManagementTests.java
Tests:
    "@Test
@Test
void distributionManagementEmpty() {
    MavenDistributionManagement result = builder().build();
    assertThat(result.isEmpty()).isTrue();
    assertThat(result.getRelocation().isEmpty()).isTrue();
    assertThat(result.getRepository().isEmpty()).isTrue();
    assertThat(result.getSite().isEmpty()).isTrue();
    assertThat(result.getSnapshotRepository().isEmpty()).isTrue();
}
"
    "@Test
@Test
void distributionManagementWithDownloadUrl() {
    MavenDistributionManagement mdm = builder().downloadUrl("https:
    assertThat(mdm.getDownloadUrl()).isEqualTo("https:
}
"
    "@Test
@Test
void distributionManagementWithRepository() {
    MavenDistributionManagement mdm = builder().repository((repository) -> repository.id("released-repo").name("released repo").url("https:
    DeploymentRepository repository = mdm.getRepository();
    assertThat(repository.getId()).isEqualTo("released-repo");
    assertThat(repository.getName()).isEqualTo("released repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.getLayout()).isEqualTo("default");
    assertThat(repository.getUniqueVersion()).isNull();
}
"
    "@Test
@Test
void distributionManagementWithSnapshotRepository() {
    MavenDistributionManagement mdm = builder().snapshotRepository((repository) -> repository.id("snapshot-repo").name("snapshot repo").url("scp:
    DeploymentRepository snapshotRepository = mdm.getSnapshotRepository();
    assertThat(snapshotRepository.getId()).isEqualTo("snapshot-repo");
    assertThat(snapshotRepository.getName()).isEqualTo("snapshot repo");
    assertThat(snapshotRepository.getUrl()).isEqualTo("scp:
    assertThat(snapshotRepository.getLayout()).isNull();
    assertThat(snapshotRepository.getUniqueVersion()).isTrue();
}
"
    "@Test
@Test
void distributionManagementWithSite() {
    MavenDistributionManagement mdm = builder().site((site) -> site.id("website").name("web site")).site((site) -> site.url("scp:
    Site site = mdm.getSite();
    assertThat(site.getId()).isEqualTo("website");
    assertThat(site.getName()).isEqualTo("web site");
    assertThat(site.getUrl()).isEqualTo("scp:
}
"
    "@Test
@Test
void distributionManagementWithRelocation() {
    MavenDistributionManagement mdm = builder().relocation((relocation) -> relocation.groupId("com.example.new").artifactId("project").version("1.0.0")).relocation((relocation) -> relocation.message("Moved to com.example.new")).build();
    assertThat(mdm.getRelocation().getGroupId()).isEqualTo("com.example.new");
    assertThat(mdm.getRelocation().getArtifactId()).isEqualTo("project");
    assertThat(mdm.getRelocation().getVersion()).isEqualTo("1.0.0");
    assertThat(mdm.getRelocation().getMessage()).isEqualTo("Moved to com.example.new");
}
"
    "@Test
private MavenDistributionManagement.Builder builder() {
    return new MavenDistributionManagement.Builder();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlocksCanBeAdded() {
    CodeBlock code = CodeBlock.builder().add("(123").add(CodeBlock.of(", 456)")).build();
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithMultipleStatements() {
    CodeBlock code = CodeBlock.builder().addStatement("myInstance.sayHello(123)").addStatement(CodeBlock.of("myInstance.sayHello(456)")).build();
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        myInstance.sayHello(456);
        """);
    assertThat(code.getImports()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void functionWithParameterAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("something").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    fun something(@Service service: MyService) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.another.MyService;", "import com.example.stereotype.Service;", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"```java
Scenario 1: Verify that the builder method initializes a new Builder instance

Details:
  TestName: builderInitializesNewBuilderInstance
  Description: This test ensures that the builder method creates and returns a new instance of the Builder class.

Execution:
  Arrange: None.
  Act: Call the builder() method on the CodeBlock class.
  Assert: Verify that the returned object is an instance of the Builder class.

Validation:
  Clarify what the assertion aims to verify: The assertion aims to verify that the builder method correctly initializes and returns a new Builder instance.
  Elaborate on the significance: This test is crucial to ensure that the builder pattern is correctly implemented and that subsequent methods called on the Builder instance do not affect other instances.

Scenario 2: Verify that multiple calls to the builder method return different Builder instances

Details:
  TestName: builderReturnsDifferentInstances
  Description: This test checks that calling the builder method multiple times returns different instances of the Builder class.

Execution:
  Arrange: None.
  Act:
    1. Call the builder() method and store the result in builder1.
    2. Call the builder() method again and store the result in builder2.
  Assert: Assert that builder1 is not the same instance as builder2.

Validation:
  Clarify what the assertion aims to verify: The assertion ensures that each call to the builder method returns a new instance, ensuring that the builder pattern is correctly implemented.
  Elaborate on the significance: This test is essential to ensure that the Builder instances are independent and do not interfere with each other, which is a key aspect of the builder pattern.

Scenario 3: Verify that the builder method returns a Builder instance with default fields

Details:
  TestName: builderReturnsBuilderWithDefaultFields
  Description: This test verifies that the Builder instance returned by the builder method has the default field values.

Execution:
  Arrange: None.
  Act:
    1. Call the builder() method and store the result in builder.
    2. Access the fields of the Builder instance (parts, args, imports).
  Assert:
    1. Verify that the parts field is initialized as null.
    2. Verify that the args field is initialized as null.
    3. Verify that the imports field is initialized as null.

Validation:
  Clarify what the assertion aims to verify: The assertion ensures that the Builder instance has the default field values, which are null for parts, args, and imports.
  Elaborate on the significance: This test is important to ensure that the Builder instance starts with a clean state, ready for further configuration.

Scenario 4: Verify that the builder method does not affect the static field JAVA_FORMATTING_OPTIONS

Details:
  TestName: builderDoesNotAffectStaticField
  Description: This test ensures that calling the builder method does not modify the static field JAVA_FORMATTING_OPTIONS.

Execution:
  Arrange:
    1. Store the initial value of the JAVA_FORMATTING_OPTIONS field.
  Act:
    1. Call the builder() method.
  Assert: Verify that the value of JAVA_FORMATTING_OPTIONS remains unchanged.

Validation:
  Clarify what the assertion aims to verify: The assertion ensures that the builder method does not alter the static field JAVA_FORMATTING_OPTIONS.
  Elaborate on the significance: This test is important to ensure that the builder method does not have side effects and does not affect other parts of the system, especially static fields.

Scenario 5: Verify that the builder method returns a Builder instance with correct formatting options

Details:
  TestName: builderReturnsBuilderWithCorrectFormattingOptions
  Description: This test verifies that the Builder instance returned by the builder method has the correct formatting options.

Execution:
  Arrange: None.
  Act:
    1. Call the builder() method and store the result in builder.
    2. Access the JAVA_FORMATTING_OPTIONS field of the Builder instance.
  Assert: Verify that the JAVA_FORMATTING_OPTIONS field is initialized with a new instance of JavaFormattingOptions.

Validation:
  Clarify what the assertion aims to verify: The assertion ensures that the Builder instance has the correct formatting options, specifically a new instance of JavaFormattingOptions.
  Elaborate on the significance: This test is important to ensure that the Builder instance is correctly configured with the default formatting options, which are crucial for generating code blocks.

Scenario 6: Verify that the builder method does not throw any exceptions

Details:
  TestName: builderDoesNotThrowExceptions
  Description: This test ensures that calling the builder method does not throw any exceptions.

Execution:
  Arrange: None.
  Act: Call the builder() method.
  Assert: Verify that no exceptions are thrown during the method call.

Validation:
  Clarify what the assertion aims to verify: The assertion ensures that the builder method is robust and does not fail unexpectedly.
  Elaborate on the significance: This test is important to ensure that the builder method is reliable and can be used in various scenarios without fear of unexpected failures.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import io.spring.initializr.generator.language.CodeBlock.Builder;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.StreamSupport;
import io.spring.initializr.generator.io.IndentingWriter;
import org.springframework.util.ClassUtils;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);

public class CodeBlockBuilderTest {

	@Test
	@Tag("valid")
	public void builderInitializesNewBuilderInstance() {
		Builder builder = CodeBlock.builder();
		assertNotNull(builder);
		assertTrue(builder instanceof Builder);
	}

	@Test
	@Tag("valid")
	public void builderReturnsDifferentInstances() {
		Builder builder1 = CodeBlock.builder();
		Builder builder2 = CodeBlock.builder();
		assertNotSame(builder1, builder2);
	}

	// Scenario 3: Verify that the builder method returns a Builder instance with default
	// fields
	// This scenario is not applicable because the Builder instance does not have default
	// fields as per the provided information.
	// Scenario 4: Verify that the builder method does not affect the static field
	// JAVA_FORMATTING_OPTIONS
	// This scenario is not applicable because the Builder instance does not have a static
	// field JAVA_FORMATTING_OPTIONS as per the provided information.
	// Scenario 5: Verify that the builder method returns a Builder instance with correct
	// formatting options
	// This scenario is not applicable because the Builder instance does not have a
	// JAVA_FORMATTING_OPTIONS field as per the provided information.
	@Test
	@Tag("valid")
	public void builderDoesNotThrowExceptions() {
		assertDoesNotThrow(() -> CodeBlock.builder());
	}

}