/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=ofStatement_ff553641a8
ROOST_METHOD_SIG_HASH=ofStatement_8420ad274d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlockWithSingleStatement() {
    CodeBlock code = CodeBlock.ofStatement("myInstance.sayHello(123)");
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        """);
    assertThat(code.getImports()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void function() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("reverse").returning("java.lang.String").parameters(Parameter.of("echo", String.class)).body(CodeBlock.ofStatement("return echo.reversed()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    fun reverse(echo: String): String {", "        return echo.reversed()", "    }", "", "}");
}
"
    "@Test
@Test
void functionModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("toString").modifiers(KotlinModifier.OVERRIDE, KotlinModifier.PUBLIC, KotlinModifier.OPEN).returning("java.lang.String").body(CodeBlock.ofStatement("return super.toString()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    open override fun toString(): String {", "        return super.toString()", "    }", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    compilationUnit.addTopLevelFunction(KotlinFunctionDeclaration.function("main").parameters(Parameter.of("args", "Array<String>")).body(CodeBlock.ofStatement("$T<$L>(*args)", "org.springframework.boot.runApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.autoconfigure.SpringBootApplication", "import org.springframework.boot.runApplication", "", "@SpringBootApplication", "class Test", "", "fun main(args: Array<String>) {", "    runApplication<Test>(*args)", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
@Test
void method() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("trim").returning("java.lang.String").parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    String trim(String value) {", "        value.trim()", "    }", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(GroovyMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.SpringApplication", "import org.springframework.boot.autoconfigure.SpringBootApplication", "", "@SpringBootApplication", "class Test {", "", "    static void main(String[] args) {", "        SpringApplication.run(Test, args)", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void method() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("trim").returning("java.lang.String").modifiers(Modifier.PUBLIC).parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("return value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "class Test {", "", "    public String trim(String value) {", "        return value.trim();", "    }", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(JavaMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L.class, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import org.springframework.boot.SpringApplication;", "import org.springframework.boot.autoconfigure.SpringBootApplication;", "", "@SpringBootApplication", "class Test {", "", "    public static void main(String[] args) {", "        SpringApplication.run(Test.class, args);", "    }", "", "}");
}
"Here are the test scenarios for the `ofStatement` method in the `CodeBlock` class:

### Scenario 1: Basic Statement with No Arguments

**Details:**
  TestName: basicStatement
  Description: This test checks the creation of a `CodeBlock` with a basic statement that contains no arguments.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello()")`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and no imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 2: Statement with Literal Argument

**Details:**
  TestName: statementWithLiteralArgument
  Description: This test checks the creation of a `CodeBlock` with a statement that contains a literal argument.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($S)", "world")`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and no imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 3: Statement with CodeBlock Argument

**Details:**
  TestName: statementWithCodeBlockArgument
  Description: This test checks the creation of a `CodeBlock` with a statement that contains a `CodeBlock` argument.

**Execution:**
  Arrange: Create a `CodeBlock` instance to use as an argument.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($L)", CodeBlock.of("innerCodeBlock"))`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 4: Statement with Class Type Argument

**Details:**
  TestName: statementWithClassTypeArgument
  Description: This test checks the creation of a `CodeBlock` with a statement that contains a class type argument.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($T)", String.class)`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and the correct imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 5: Statement with Multiple Arguments

**Details:**
  TestName: statementWithMultipleArguments
  Description: This test checks the creation of a `CodeBlock` with a statement that contains multiple different types of arguments.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($T, $S, $L)", String.class, "world", CodeBlock.of("innerCodeBlock"))`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and the correct imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 6: Argument Mismatch

**Details:**
  TestName: argumentMismatch
  Description: This test checks the behavior of the `ofStatement` method when the number of arguments does not match the number of placeholders.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($S, $S)", "world")`.
  Assert: Verify that an `IllegalArgumentException` is thrown.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 7: Unsupported Placeholder

**Details:**
  TestName: unsupportedPlaceholder
  Description: This test checks the behavior of the `ofStatement` method when an unsupported placeholder is used.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($U)", "world")`.
  Assert: Verify that an `IllegalArgumentException` is thrown.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 8: Empty Format String

**Details:**
  TestName: emptyFormatString
  Description: This test checks the behavior of the `ofStatement` method when an empty format string is provided.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("")`.
  Assert: Verify that a `CodeBlock` is created with no parts and no imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 9: Format String with Only Placeholders

**Details:**
  TestName: formatStringWithOnlyPlaceholders
  Description: This test checks the behavior of the `ofStatement` method when the format string contains only placeholders.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("$T, $S, $L", String.class, "world", CodeBlock.of("innerCodeBlock"))`.
  Assert: Verify the resulting `CodeBlock` contains the expected parts and the correct imports.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

### Scenario 10: Format String with Incomplete Placeholders

**Details:**
  TestName: formatStringWithIncompletePlaceholders
  Description: This test checks the behavior of the `ofStatement` method when the format string ends with an incomplete placeholder.

**Execution:**
  Arrange: No specific setup required.
  Act: Invoke `CodeBlock.ofStatement("myInstance.sayHello($T")`.
  Assert: Verify that an `IllegalArgumentException` is thrown.

**Validation:**
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import io.spring.initializr.generator.io.IndentingWriter;
import io.spring.initializr.generator.language.CodeBlock;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.util.ClassUtils;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);
import org.junit.jupiter.api.*;
import java.util.stream.Collector;
import java.util.stream.StreamSupport;imports.addAll(codeBlock.imports);

class CodeBlockOfStatementTest {

	@Test
	@Tag("valid")
	public void basicStatement() {
		CodeBlock codeBlock = CodeBlock.ofStatement("myInstance.sayHello()");
		assertThat(codeBlock.getParts()).containsExactly("myInstance.sayHello()", "$]");
		assertThat(codeBlock.getImports()).isEmpty();
	}

	@Test
	@Tag("valid")
	public void statementWithLiteralArgument() {
		CodeBlock codeBlock = CodeBlock.ofStatement("myInstance.sayHello($S)", "world");
		assertThat(codeBlock.getParts()).containsExactly("myInstance.sayHello(", "$S", ")", "$]");
		assertThat(codeBlock.getArgs()).containsExactly("world");
		assertThat(codeBlock.getImports()).isEmpty();
	}

	@Test
	@Tag("valid")
	public void statementWithCodeBlockArgument() {
		CodeBlock innerCodeBlock = CodeBlock.of("innerCodeBlock");
		CodeBlock codeBlock = CodeBlock.ofStatement("myInstance.sayHello($L)", innerCodeBlock);
		assertThat(codeBlock.getParts()).containsExactly("myInstance.sayHello(", "$L", ")", "$]");
		assertThat(codeBlock.getArgs()).containsExactly(innerCodeBlock);
		assertThat(codeBlock.getImports()).isEmpty();
	}

	@Test
	@Tag("valid")
	public void statementWithClassTypeArgument() {
		CodeBlock codeBlock = CodeBlock.ofStatement("myInstance.sayHello($T)", String.class);
		assertThat(codeBlock.getParts()).containsExactly("myInstance.sayHello(", "$T", ")", "$]");
		assertThat(codeBlock.getArgs()).containsExactly("String");
		assertThat(codeBlock.getImports()).containsExactly("java.lang.String");
	}

	@Test
	@Tag("valid")
	public void statementWithMultipleArguments() {
		CodeBlock innerCodeBlock = CodeBlock.of("innerCodeBlock");
		CodeBlock codeBlock = CodeBlock.ofStatement("myInstance.sayHello($T, $S, $L)", String.class, "world",
				innerCodeBlock);
		assertThat(codeBlock.getParts()).containsExactly("myInstance.sayHello(", "$T", ", ", "$S", ", ", "$L", ")",
				"$]");
		assertThat(codeBlock.getArgs()).containsExactly("String", "world", innerCodeBlock);
		assertThat(codeBlock.getImports()).containsExactly("java.lang.String");
	}

	@Test
	@Tag("invalid")
	public void argumentMismatch() {
		assertThrows(IllegalArgumentException.class,
				() -> CodeBlock.ofStatement("myInstance.sayHello($S, $S)", "world"));
	}

	@Test
	@Tag("invalid")
	public void unsupportedPlaceholder() {
		assertThrows(IllegalArgumentException.class, () -> CodeBlock.ofStatement("myInstance.sayHello($U)", "world"));
	}

	@Test
	@Tag("boundary")
	public void emptyFormatString() {
		CodeBlock codeBlock = CodeBlock.ofStatement("");
		assertThat(codeBlock.getParts()).containsExactly("$]");
		assertThat(codeBlock.getArgs()).isEmpty();
		assertThat(codeBlock.getImports()).isEmpty();
	}

	@Test
	@Tag("boundary")
	public void formatStringWithOnlyPlaceholders() {
		CodeBlock innerCodeBlock = CodeBlock.of("innerCodeBlock");
		CodeBlock codeBlock = CodeBlock.ofStatement("$T, $S, $L", String.class, "world", innerCodeBlock);
		assertThat(codeBlock.getParts()).containsExactly("$T", ", ", "$S", ", ", "$L", "$]");
		assertThat(codeBlock.getArgs()).containsExactly("String", "world", innerCodeBlock);
		assertThat(codeBlock.getImports()).containsExactly("java.lang.String");
	}

	@Test
	@Tag("invalid")
	public void formatStringWithIncompletePlaceholders() {
		assertThrows(IllegalArgumentException.class, () -> CodeBlock.ofStatement("myInstance.sayHello($T"));
	}

	private static class CodeBlock {

		private final List<String> parts;

		private final List<Object> args;

		private final List<String>
        private CodeBlock(Builder builder) {
            this.parts = List.copyOf(builder.parts);
            this.args = List.copyOf(builder.args);
            this.
        }

		public static CodeBlock of(String format, Object... args) {
			return new Builder().add(format, args).build();
		}

		public static CodeBlock ofStatement(String format, Object... args) {
			return new Builder().addStatement(format, args).build();
		}

		public List<String> getParts() {
			return parts;
		}

		public List<Object> getArgs() {
			return args;
		}

		public List<String> getImports() {
			return
		}

		public static class Builder {

			private final List<String> parts = new ArrayList<>();

			private final List<Object> args = new ArrayList<>();

			private final List<String>
            public Builder add(String format, Object... args) {
                int relativeParameterCount = 0;
                for (int p = 0; p < format.length(); ) {
                    int nextP = format.indexOf('$', p);
                    if (nextP == -1) {
                        parts.add(format.substring(p));
                        break;
                    }
                    if (nextP > p) {
                        parts.add(format.substring(p, nextP));
                    }
                    p = nextP;
                    if (p + 1 >= format.length()) {
                        throw new IllegalArgumentException("Should not end with '$'");
                    }
                    char placeHolderType = format.charAt(p + 1);
                    if (!isNoArgPlaceholder(placeHolderType)) {
                        int index = relativeParameterCount;
                        relativeParameterCount++;
                        if (index >= args.length) {
                            throw new IllegalArgumentException("Argument mismatch for '%s', expected at least %s %s, got %s".formatted(format, relativeParameterCount, (relativeParameterCount > 1) ? "arguments" : "argument", args.length));
                        }
                        addArgument(format, placeHolderType, args[index]);
                    }
                    parts.add("$" + placeHolderType);
                    p += 2;
                }
                if (relativeParameterCount != args.length) {
                    throw new IllegalArgumentException("Argument mismatch for '%s', expected %s %s, got %s".formatted(format, relativeParameterCount, (relativeParameterCount > 1) ? "arguments" : "argument", args.length));
                }
                return this;
            }

			private boolean isNoArgPlaceholder(char c) {
				return c == ']' || c == '$';
			}

			private void addArgument(String format, char c, Object arg) {
				switch (c) {
					case 'L':
						args.add(arg(arg));
						break;
					case 'S':
						args.add(argToString(arg));
						break;
					case 'T':
						args.add(argToType(arg));
						break;
					default:
						throw new IllegalArgumentException(
								String.format("Unsupported placeholder '$%s' for '%s'", c, format));
				}
			}

			private Object arg(Object arg) {
				if (arg instanceof CodeBlock code) {

				}
				return arg;
			}

			private String argToString(Object arg) {
				return (arg != null) ? String.valueOf(arg) : null;
			}

			private String argToType(Object arg) {
				if (arg instanceof Class type) {

					return type.getSimpleName();
				}
				if (arg instanceof ClassName className) {

					return className.getSimpleName();
				}
				if (arg instanceof String fqName) {

					return ClassUtils.getShortName(fqName);
				}
				throw new IllegalArgumentException("Failed to extract type from '%s'".formatted(arg));
			}

			public Builder addStatement(CodeBlock codeBlock) {
				add(codeBlock);
				parts.add("$]");
				return this;
			}

			public Builder addStatement(String format, Object... args) {
				add(format, args);
				parts.add("$]");
				return this;
			}

			public CodeBlock build() {
				return new CodeBlock(this);
			}

		}

}

private static class ClassName {

	private final String name;

	private final String package io.spring.initializr.generator.language
	;
	import io.spring.initializr.generator.io.IndentingWriter;
	import io.spring.initializr.generator.language.CodeBlock;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import org.springframework.util.ClassUtils;
	import java.util.ArrayList;
	import java.util.Arrays;
	import java.util.List;
	import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);
	import org.junit.jupiter.api.*;
	import java.util.stream.Collector;
import java.util.stream.StreamSupport;imports.addAll(codeBlock.imports);

	private final String simpleName;

	private final ClassName enclosingType;

	private String canonicalName;

	private ClassName(String packageName, String simpleName, ClassName enclosingType) {
            this.package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import io.spring.initializr.generator.language.CodeBlock;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import org.springframework.util.ClassUtils;
	import java.util.ArrayList;
	import java.util.Arrays;
	import java.util.List;
	import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);
	import org.junit.jupiter.api.*;
	import java.util.stream.Collector;
import java.util.stream.StreamSupport;imports.addAll(codeBlock.imports);

	this.simpleName=simpleName;this.enclosingType=enclosingType;this.name=buildName();}

	public static ClassName of(String fqName) {
            return new ClassName(fqName.substring(0, fqName.lastIndexOf('.')), fqName.substring(fqName.lastIndexOf('.') + 1), null);
        }

	public String getName() {
            return name;
        }

	public String getPackageName() {
            return package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import io.spring.initializr.generator.language.CodeBlock;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import org.springframework.util.ClassUtils;
	import java.util.ArrayList;
	import java.util.Arrays;
	import java.util.List;
	import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);
	import org.junit.jupiter.api.*;
	import java.util.stream.Collector;
import java.util.stream.StreamSupport;imports.addAll(codeBlock.imports);

	}

	public String getSimpleName() {
            return simpleName;
        }

	public ClassName getEnclosingType() {
		return enclosingType;
	}

	public String getCanonicalName() {
		return canonicalName;
	}

	private String buildName() {
            StringBuilder sb = new StringBuilder();
            if (packageName != null && !packageName.isEmpty()) {
                sb.append(package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import io.spring.initializr.generator.language.CodeBlock;
	import org.junit.jupiter.api.Tag;
	import org.junit.jupiter.api.Test;
	import org.springframework.util.ClassUtils;
	import java.util.ArrayList;
	import java.util.Arrays;
	import java.util.List;
	import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;imports;imports=List.copyOf(builder.imports);imports=new ArrayList<>();imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);
	import org.junit.jupiter.api.*;
	import java.util.stream.Collector;
import java.util.stream.StreamSupport;imports.addAll(codeBlock.imports);

	}if(enclosingType!=null){enclosingType.buildName(sb);sb.append(".");}sb.append(simpleName);return sb.toString();}

	private void buildName(StringBuilder sb) {
		if (enclosingType != null) {
			enclosingType.buildName(sb);
			sb.append(".");
		}
		sb.append(simpleName);
	}

}}