/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=write_c5538ce45b
ROOST_METHOD_SIG_HASH=write_e0fd313aa1

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeFileWriterTests.java
Tests:
    "@Test
@Test
void writeBasicServices() {
    ComposeFile file = new ComposeFile();
    file.services().add("first", withSuffix(1));
    file.services().add("second", withSuffix(2));
    assertThat(write(file)).isEqualToIgnoringNewLines("""
        services:
        	first:
        		image: 'image-1:image-tag-1'
        	second:
        		image: 'image-2:image-tag-2'
        """);
}
"
    "@Test
@Test
void writeDetailedService() {
    ComposeFile file = new ComposeFile();
    file.services().add("elasticsearch", (builder) -> builder.image("elasticsearch").imageTag("8.6.1").imageWebsite("https:
    assertThat(write(file)).isEqualToIgnoringNewLines("""
        services:
        	elasticsearch:
        		image: 'elasticsearch:8.6.1'
        		environment:
        			- 'ELASTIC_PASSWORD=secret'
        			- 'discovery.type=single-node'
        		labels:
        			- "foo=bar"
        		ports:
        			- '9200'
        			- '9300'
        		command: 'bin/run thing'
        """);
}
"
    "@Test
@Test
void servicesAreOrderedByName() {
    ComposeFile file = new ComposeFile();
    file.services().add("b", withSuffix(2));
    file.services().add("a", withSuffix(1));
    assertThat(write(file)).isEqualToIgnoringNewLines("""
        services:
        	a:
        		image: 'image-1:image-tag-1'
        	b:
        		image: 'image-2:image-tag-2'
        """);
}
"
    "@Test
private String write(ComposeFile file) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, "\t"::repeat);
    new ComposeFileWriter().writeTo(writer, file);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/text/MustacheSectionTests.java
Tests:
    "@Test
@Test
void renderSection() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.singletonMap("key", "hello"));
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("hello%n"));
}
"
    "@Test
@Test
void renderSectionWithMissingKey() {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.singletonMap("another", "hello"));
    assertThatThrownBy(() -> section.write(new PrintWriter(new StringWriter()))).isInstanceOf(MustacheException.class).hasMessageContaining("key");
}
"
    "@Test
@Test
void renderSectionWithCustomModelResolution() throws IOException {
    MustacheSection section = new MustacheSection(this.renderer, "test", Collections.emptyMap()) {

        @Override
        protected Map<String, Object> resolveModel(Map<String, Object> model) {
            return Collections.singletonMap("key", "custom");
        }
    };
    StringWriter writer = new StringWriter();
    section.write(new PrintWriter(writer));
    assertThat(writer.toString()).isEqualTo(String.format("custom%n"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/KotlinDslGradleBuildWriterTests.java
Tests:
    "@Test
@Test
void gradleBuildWithCoordinates() {
    GradleBuild build = new GradleBuild();
    build.settings().group("com.example").version("1.0.1-SNAPSHOT");
    assertThat(write(build)).contains("""
        group = "com.example"
        version = "1.0.1-SNAPSHOT"
        """);
}
"
    "@Test
@ParameterizedTest
@MethodSource("sourceCompatibilityParameters")
void gradleBuildWithSourceCompatibilities(String sourceCompatibility, String javaVersionConstant) {
    GradleBuild build = new GradleBuild();
    build.settings().sourceCompatibility(sourceCompatibility);
    assertThat(write(build)).contains("""
        java {
        	toolchain {
        		languageVersion = JavaLanguageVersion.of(%s)
        	}
        }
        """.formatted(javaVersionConstant));
}
"
    "@Test
@Test
void gradleBuildWithBuildscriptDependency() {
    GradleBuild build = new GradleBuild();
    build.buildscript((buildscript) -> buildscript.dependency("org.springframework.boot:spring-boot-gradle-plugin:2.1.0.RELEASE"));
    assertThatIllegalStateException().isThrownBy(() -> write(build));
}
"
    "@Test
@Test
void gradleBuildWithBuildscriptExtProperty() {
    GradleBuild build = new GradleBuild();
    build.buildscript((buildscript) -> buildscript.ext("kotlinVersion", "\1.2.51\""));
    assertThatIllegalStateException().isThrownBy(() -> write(build));
}
"
    "@Test
@Test
void gradleBuildWithBuiltinPlugin() {
    GradleBuild build = new GradleBuild();
    build.plugins().add("java");
    build.plugins().add("war");
    assertThat(write(build)).contains("""
        plugins {
        	java
        	war
        }""");
}
"
    "@Test
@Test
void gradleBuildWithKotlinPluginAndVersion() {
    GradleBuild build = new GradleBuild();
    build.plugins().add("org.jetbrains.kotlin.jvm", (plugin) -> plugin.setVersion("1.3.21"));
    build.plugins().add("org.jetbrains.kotlin.plugin.spring", (plugin) -> plugin.setVersion("1.3.21"));
    assertThat(write(build)).contains("""
        plugins {
        	kotlin("jvm") version "1.3.21"
        	kotlin("plugin.spring") version "1.3.21"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithPluginAndVersion() {
    GradleBuild build = new GradleBuild();
    build.plugins().add("org.springframework.boot", (plugin) -> plugin.setVersion("2.1.0.RELEASE"));
    assertThat(write(build)).contains("""
        plugins {
        	id("org.springframework.boot") version "2.1.0.RELEASE"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithApplyPlugin() {
    GradleBuild build = new GradleBuild();
    build.plugins().apply("io.spring.dependency-management");
    assertThatIllegalStateException().isThrownBy(() -> write(build));
}
"
    "@Test
@Test
void gradleBuildWithMavenCentralRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add("maven-central");
    assertThat(write(build)).contains("""
        repositories {
        	mavenCentral()
        }""");
}
"
    "@Test
@Test
void gradleBuildWithRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add(MavenRepository.withIdAndUrl("spring-milestones", "https:
    assertThat(write(build)).contains("""
        repositories {
        	maven { url = uri("https:
        }""");
}
"
    "@Test
@Test
void gradleBuildWithSnapshotRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add(MavenRepository.withIdAndUrl("spring-snapshots", "https:
    assertThat(write(build)).contains("""
        repositories {
        	maven { url = uri("https:
        }""");
}
"
    "@Test
@Test
void gradleBuildWithPluginRepository() {
    GradleBuild build = new GradleBuild();
    build.pluginRepositories().add(MavenRepository.withIdAndUrl("spring-milestones", "https:
    assertThat(write(build)).doesNotContain("repositories {");
}
"
    "@Test
@Test
void gradleBuildWithTaskWithTypesCustomizedWithNestedAssignments() {
    GradleBuild build = new GradleBuild();
    build.tasks().customizeWithType("org.jetbrains.kotlin.gradle.tasks.KotlinCompile", (task) -> task.nested("kotlinOptions", (kotlinOptions) -> kotlinOptions.attribute("freeCompilerArgs", "listOf(\"-Xjsr305=strict\")")));
    build.tasks().customizeWithType("org.jetbrains.kotlin.gradle.tasks.KotlinCompile", (task) -> task.nested("kotlinOptions", (kotlinOptions) -> kotlinOptions.attribute("jvmTarget", "\"1.8\"")));
    assertThat(write(build)).containsOnlyOnce("import org.jetbrains.kotlin.gradle.tasks.KotlinCompile").contains("""
        tasks.withType<KotlinCompile> {
        	kotlinOptions {
        		freeCompilerArgs = listOf("-Xjsr305=strict")
        		jvmTarget = "1.8"
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskWithTypesAndShortTypes() {
    GradleBuild build = new GradleBuild();
    build.tasks().customizeWithType("JavaCompile", (javaCompile) -> javaCompile.attribute("options.fork", "true"));
    assertThat(write(build)).doesNotContain("import JavaCompile").contains("""
        tasks.withType<JavaCompile> {
        	options.fork = true
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithInvocations() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("asciidoctor", (task) -> {
        task.invoke("inputs.dir", "snippetsDir");
        task.invoke("dependsOn", "test");
    });
    assertThat(write(build)).contains("""
        tasks.asciidoctor {
        	inputs.dir(snippetsDir)
        	dependsOn(test)
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithAssignments() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("compileKotlin", (task) -> {
        task.attribute("kotlinOptions.freeCompilerArgs", "listOf(\"-Xjsr305=strict\")");
        task.attribute("kotlinOptions.jvmTarget", "\"1.8\"");
    });
    assertThat(write(build)).contains("""
        tasks.compileKotlin {
        	kotlinOptions.freeCompilerArgs = listOf("-Xjsr305=strict")
        	kotlinOptions.jvmTarget = "1.8"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithNestedCustomization() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("compileKotlin", (compileKotlin) -> compileKotlin.nested("kotlinOptions", (kotlinOptions) -> {
        kotlinOptions.attribute("freeCompilerArgs", "listOf(\"-Xjsr305=strict\")");
        kotlinOptions.attribute("jvmTarget", "\"1.8\"");
    }));
    assertThat(write(build)).contains("""
        tasks.compileKotlin {
        	kotlinOptions {
        		freeCompilerArgs = listOf("-Xjsr305=strict")
        		jvmTarget = "1.8"
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExt() {
    GradleBuild build = new GradleBuild();
    build.properties().property("java.version", "\"1.8\"").property("alpha", "file(\"build/example\")");
    assertThat(write(build)).contains("""
        extra["alpha"] = file("build/example")
        extra["java.version"] = "1.8"
        """);
}
"
    "@Test
@Test
void gradleBuildWithVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("version.property", false), "1.2.3").version(VersionProperty.of("internal.property", true), "4.5.6").version("external.property", "7.8.9");
    assertThat(write(build)).contains("""
        extra["external.property"] = "7.8.9"
        extra["internalProperty"] = "4.5.6"
        extra["version.property"] = "1.2.3"
        """);
}
"
    "@Test
@Test
void gradleBuildWithVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("kotlin-stdlib", Dependency.withCoordinates("org.jetbrains.kotlin", "kotlin-stdlib-jdk8").version(VersionReference.ofProperty("kotlin.version")).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${property("kotlinVersion")}")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExternalVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("acme", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofProperty(VersionProperty.of("acme.version", false))).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("com.example:acme:${property("acme.version")}")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExtAndVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("test-version", true), "1.0").version("alpha-version", "0.1").property("myProperty", "42");
    assertThat(write(build)).contains("""
        extra["myProperty"] = 42
        extra["alpha-version"] = "0.1"
        extra["testVersion"] = "1.0"
        """);
}
"
    "@Test
@Test
void gradleBuildWithConfiguration() {
    GradleBuild build = new GradleBuild();
    build.configurations().add("developmentOnly");
    assertThat(write(build)).contains("val developmentOnly by configurations.creating");
}
"
    "@Test
@Test
void gradleBuildWithConfigurationCustomization() {
    GradleBuild build = new GradleBuild();
    build.configurations().add("custom");
    build.configurations().customize("runtimeClasspath", (configuration) -> configuration.extendsFrom("custom"));
    build.configurations().customize("runtimeClasspath", (configuration) -> configuration.extendsFrom("builtIn"));
    assertThat(write(build)).contains("""
        val custom by configurations.creating
        configurations {
        	runtimeClasspath {
        		extendsFrom(custom, configurations.builtIn.get())
        	}
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithConfigurationCustomizations() {
    GradleBuild build = new GradleBuild();
    build.configurations().add("custom");
    build.configurations().customize("runtimeClasspath", (configuration) -> configuration.extendsFrom("custom"));
    build.configurations().customize("testRuntimeClasspath", (configuration) -> configuration.extendsFrom("builtIn"));
    assertThat(write(build)).contains("""
        val custom by configurations.creating
        configurations {
        	runtimeClasspath {
        		extendsFrom(custom)
        	}
        	testRuntimeClasspath {
        		extendsFrom(configurations.builtIn.get())
        	}
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithAnnotationProcessorDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("annotation-processor", "org.springframework.boot", "spring-boot-configuration-processor", DependencyScope.ANNOTATION_PROCESSOR);
    assertThat(write(build)).contains("""
        dependencies {
        	annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCompileDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", "org.springframework.boot", "spring-boot-starter", DependencyScope.COMPILE);
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("org.springframework.boot:spring-boot-starter")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNoScopeDependencyDefaultsToCompile() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("org.springframework.boot:spring-boot-starter")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("driver", Dependency.withCoordinates("com.example", "jdbc-driver").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME));
    assertThat(write(build)).contains("""
        dependencies {
        	runtimeOnly("com.example:jdbc-driver:1.0.0")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithProvidedRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("tomcat", "org.springframework.boot", "spring-boot-starter-tomcat", DependencyScope.PROVIDED_RUNTIME);
    assertThat(write(build)).contains("""
        dependencies {
        	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTestCompileDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", "org.springframework.boot", "spring-boot-starter-test", DependencyScope.TEST_COMPILE);
    assertThat(write(build)).contains("""
        dependencies {
        	testImplementation("org.springframework.boot:spring-boot-starter-test")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCompileOnlyDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", "org.springframework.boot", "spring-boot-starter-foobar", DependencyScope.COMPILE_ONLY);
    assertThat(write(build)).contains("""
        dependencies {
        	compileOnly("org.springframework.boot:spring-boot-starter-foobar")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTestRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("embed-mongo", "de.flapdoodle.embed", "de.flapdoodle.embed.mongo", DependencyScope.TEST_RUNTIME);
    assertThat(write(build)).contains("""
        dependencies {
        	testRuntimeOnly("de.flapdoodle.embed:de.flapdoodle.embed.mongo")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithClassifierDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("com.example", "acme").scope(DependencyScope.COMPILE).classifier("test-jar"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("com.example:acme:test-jar")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExclusions() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", Dependency.withCoordinates("com.example", "test").scope(DependencyScope.COMPILE).exclusions(new Exclusion("com.example.legacy", "legacy-one"), new Exclusion("com.example.another", "legacy-two")));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("com.example:test") {
        		exclude(group = "com.example.legacy", module = "legacy-one")
        		exclude(group = "com.example.another", module = "legacy-two")
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCustomDependencyConfiguration() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", GradleDependency.withCoordinates("org.springframework.boot", "spring-boot-starter-foobar").scope(DependencyScope.RUNTIME).configuration("myRuntime"));
    assertThat(write(build)).contains("""
        dependencies {
        	myRuntime("org.springframework.boot:spring-boot-starter-foobar")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNonNullArtifactTypeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter").scope(DependencyScope.COMPILE).type("tar.gz"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("org.springframework.boot:spring-boot-starter@tar.gz")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNonNullArtifactTypeAndClassifierDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("com.example", "acme").scope(DependencyScope.COMPILE).type("tar.gz").classifier("test-jar"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("com.example:acme:test-jar@tar.gz")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithOrderedDependencies() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("beta", Dependency.withCoordinates("com.example", "beta"));
    build.dependencies().add("alpha", Dependency.withCoordinates("com.example", "alpha"));
    build.dependencies().add("web", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter-web"));
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("org.springframework.boot:spring-boot-starter")
        	implementation("org.springframework.boot:spring-boot-starter-web")
        	implementation("com.example:alpha")
        	implementation("com.example:beta")
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithOrderedDependenciesAndCustomComparator() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("beta", Dependency.withCoordinates("com.example", "beta"));
    build.dependencies().add("alpha", Dependency.withCoordinates("com.example", "alpha"));
    build.dependencies().add("web", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter-web"));
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    KotlinDslGradleBuildWriter writer = new KotlinDslGradleBuildWriter() {

        @Override
        protected Comparator<Dependency> getDependencyComparator() {
            return Comparator.comparing(Dependency::getArtifactId);
        }
    };
    assertThat(write(writer, build)).contains("""
        dependencies {
        	implementation("com.example:alpha")
        	implementation("com.example:beta")
        	implementation("org.springframework.boot:spring-boot-starter")
        	implementation("org.springframework.boot:spring-boot-starter-web")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithBom() {
    GradleBuild build = new GradleBuild();
    build.boms().add("test", BillOfMaterials.withCoordinates("com.example", "my-project-dependencies").version(VersionReference.ofValue("1.0.0.RELEASE")));
    assertThat(write(build)).contains("""
        dependencyManagement {
        	imports {
        		mavenBom("com.example:my-project-dependencies:1.0.0.RELEASE")
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithOrderedBoms() {
    GradleBuild build = new GradleBuild();
    build.boms().add("bom1", BillOfMaterials.withCoordinates("com.example", "my-project-dependencies").version(VersionReference.ofValue("1.0.0.RELEASE")).order(5));
    build.boms().add("bom2", BillOfMaterials.withCoordinates("com.example", "root-dependencies").version(VersionReference.ofProperty("root.version")).order(2));
    assertThat(write(build)).contains("""
        dependencyManagement {
        	imports {
        		mavenBom("com.example:my-project-dependencies:1.0.0.RELEASE")
        		mavenBom("com.example:root-dependencies:${property("rootVersion")}")
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCustomVersion() {
    GradleBuild build = new GradleBuild();
    build.settings().version("1.2.4.RELEASE");
    assertThat(write(build)).contains("version = \"1.2.4.RELEASE\"");
}
"
    "@Test
@Test
void shouldCustomizeExtensions() {
    GradleBuild build = new GradleBuild();
    build.extensions().customize("kotlin", (kotlin) -> kotlin.nested("compilerOptions", (compilerOptions) -> {
        compilerOptions.attributeWithType("jvmTarget", "JvmTarget.JVM_21", "org.jetbrains.kotlin.gradle.dsl.JvmTarget");
        compilerOptions.invoke("freeCompilerArgs.addAll", "\"-Xjsr305=strict\"", "\"-Xexport-kdoc\"");
    }));
    String written = write(build);
    assertThat(written).contains("import org.jetbrains.kotlin.gradle.dsl.JvmTarget");
    assertThat(written).contains("""
        kotlin {
        	compilerOptions {
        		freeCompilerArgs.addAll("-Xjsr305=strict", "-Xexport-kdoc")
        		jvmTarget = JvmTarget.JVM_21
        	}
        }""");
}
"
    "@Test
protected String write(GradleBuild build) {
    return write(new KotlinDslGradleBuildWriter(), build);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationTests.java
Tests:
    "@Test
@Test
void annotationWithNoAttribute() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).build();
    assertThat(write(test)).isEqualTo("@Test");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@ParameterizedTest
@MethodSource("parameters")
void annotationWithPrimitives(Object parameter, String expectedCode) {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", parameter).build();
    assertThat(write(test)).isEqualTo("@Test(test = " + expectedCode + ")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithString() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", "value").build();
    assertThat(write(test)).isEqualTo("@Test(test = \"value\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithClass() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", Test.class).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithClassName() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ClassName.of(Test.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithTypeReferenceInvokeConfiguredFormattingOptions() {
    ClassName typeReference = ClassName.of("com.example.Another");
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.classReference(typeReference)).willReturn(CodeBlock.of("$T::class", typeReference));
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", typeReference).build();
    assertThat(write(test, options)).isEqualTo("@Test(test = Another::class)");
    verify(options).classReference(typeReference);
    assertThat(test.getImports()).containsOnly("com.example.Test", typeReference.getName());
}
"
    "@Test
@Test
void annotationWithEnum() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ChronoUnit.CENTURIES).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithEnumCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", CodeBlock.of("$T.CENTURIES", ChronoUnit.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithNestedAnnotation() {
    Annotation nested = Annotation.of(ClassName.of("com.example.Nested")).set("counter", 42).build();
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", nested).build();
    assertThat(write(test)).isEqualTo("@Test(test = @Nested(counter = 42))");
    assertThat(test.getImports()).containsOnly("com.example.Test", "com.example.Nested");
}
"
    "@Test
@Test
void annotationWithOnlyValueUsesShortcut() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("value", "test").build();
    assertThat(write(test)).isEqualTo("@Test(\"test\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithSeveralParameters() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("enabled", false).set("counter", 42).build();
    assertThat(write(test)).isEqualTo("@Test(enabled = false, counter = 42)");
}
"
    "@Test
@Test
void annotationWithParameterArray() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("counters", 2, 4, 8, 10).build();
    assertThat(write(test)).isEqualTo("@Test(counters = { 2, 4, 8, 10 })");
}
"
    "@Test
@Test
void annotationWithParameterArrayAsValueUsesShortcut() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("value", 2, 4, 8, 10).build();
    assertThat(write(test)).isEqualTo("@Test({ 2, 4, 8, 10 })");
}
"
    "@Test
@Test
void annotationWithParameterClassAndCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("types", StringWriter.class, CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"
    "@Test
@Test
void annotationWithAmendedValues() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).add("types", StringWriter.class).add("types", CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"
    "@Test
private String write(Annotation annotation) {
    return write(annotation, CodeBlock.JAVA_FORMATTING_OPTIONS);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GroovyDslGradleBuildWriterTests.java
Tests:
    "@Test
@Test
void gradleBuildWithCoordinates() {
    GradleBuild build = new GradleBuild();
    build.settings().group("com.example").version("1.0.1-SNAPSHOT");
    assertThat(write(build).lines()).contains("group = 'com.example'", "version = '1.0.1-SNAPSHOT'");
}
"
    "@Test
@Test
void gradleBuildWithSourceCompatibility() {
    GradleBuild build = new GradleBuild();
    build.settings().sourceCompatibility("17");
    assertThat(write(build)).contains("""
        java {
        	toolchain {
        		languageVersion = JavaLanguageVersion.of(17)
        	}
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithBuildscriptDependency() {
    GradleBuild build = new GradleBuild();
    build.repositories().add("maven-central");
    build.buildscript((buildscript) -> buildscript.dependency("org.springframework.boot:spring-boot-gradle-plugin:2.1.0.RELEASE"));
    assertThat(write(build)).contains("""
        buildscript {
        	repositories {
        		mavenCentral()
        	}
        	dependencies {
        		classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.1.0.RELEASE'
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithBuildscriptExtProperty() {
    GradleBuild build = new GradleBuild();
    build.repositories().add("maven-central");
    build.buildscript((buildscript) -> buildscript.ext("kotlinVersion", "'1.2.51'"));
    assertThat(write(build)).contains("""
        buildscript {
        	ext {
        		kotlinVersion = '1.2.51'
        	}""");
}
"
    "@Test
@Test
void gradleBuildWithPlugin() {
    GradleBuild build = new GradleBuild();
    build.plugins().add("java");
    assertThat(write(build)).contains("""
        plugins {
        	id 'java'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithPluginAndVersion() {
    GradleBuild build = new GradleBuild();
    build.plugins().add("org.springframework.boot", (plugin) -> plugin.setVersion("2.1.0.RELEASE"));
    assertThat(write(build)).contains("""
        plugins {
        	id 'org.springframework.boot' version '2.1.0.RELEASE'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithApplyPlugin() {
    GradleBuild build = new GradleBuild();
    build.plugins().apply("io.spring.dependency-management");
    assertThat(write(build).lines()).contains("apply plugin: 'io.spring.dependency-management'");
}
"
    "@Test
@Test
void gradleBuildWithMavenCentralRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add("maven-central");
    assertThat(write(build)).contains("""
        repositories {
        	mavenCentral()
        }""");
}
"
    "@Test
@Test
void gradleBuildWithRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add(MavenRepository.withIdAndUrl("spring-milestones", "https:
    assertThat(write(build)).contains("""
        repositories {
        	maven { url 'https:
        }""");
}
"
    "@Test
@Test
void gradleBuildWithSnapshotRepository() {
    GradleBuild build = new GradleBuild();
    build.repositories().add(MavenRepository.withIdAndUrl("spring-snapshots", "https:
    assertThat(write(build)).contains("""
        repositories {
        	maven { url 'https:
        }""");
}
"
    "@Test
@Test
void gradleBuildWithPluginRepository() {
    GradleBuild build = new GradleBuild();
    build.pluginRepositories().add(MavenRepository.withIdAndUrl("spring-milestones", "https:
    assertThat(write(build)).doesNotContain("repositories {");
}
"
    "@Test
@Test
void gradleBuildWithTaskWithTypesCustomizedWithNestedAssignments() {
    GradleBuild build = new GradleBuild();
    build.tasks().customizeWithType("org.jetbrains.kotlin.gradle.tasks.KotlinCompile", (task) -> task.nested("kotlinOptions", (kotlinOptions) -> kotlinOptions.attribute("freeCompilerArgs", "['-Xjsr305=strict']")));
    build.tasks().customizeWithType("org.jetbrains.kotlin.gradle.tasks.KotlinCompile", (task) -> task.nested("kotlinOptions", (kotlinOptions) -> kotlinOptions.attribute("jvmTarget", "'1.8'")));
    assertThat(write(build)).containsOnlyOnce("import org.jetbrains.kotlin.gradle.tasks.KotlinCompile").contains("""
        tasks.withType(KotlinCompile) {
        	kotlinOptions {
        		freeCompilerArgs = ['-Xjsr305=strict']
        		jvmTarget = '1.8'
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskWithTypesAndShortTypes() {
    GradleBuild build = new GradleBuild();
    build.tasks().customizeWithType("JavaCompile", (javaCompile) -> javaCompile.attribute("options.fork", "true"));
    assertThat(write(build)).doesNotContain("import JavaCompile").contains("""
        tasks.withType(JavaCompile) {
        	options.fork = true
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithInvocations() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("asciidoctor", (task) -> {
        task.invoke("inputs.dir", "snippetsDir");
        task.invoke("dependsOn", "test");
    });
    assertThat(write(build)).contains("""
        tasks.named('asciidoctor') {
        	inputs.dir snippetsDir
        	dependsOn test
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithInvocationAndNoArgument() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("test", (task) -> task.invoke("myMethod"));
    assertThat(write(build)).contains("""
        tasks.named('test') {
        	myMethod()
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithAssignments() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("compileKotlin", (task) -> {
        task.attribute("kotlinOptions.freeCompilerArgs", "['-Xjsr305=strict']");
        task.attribute("kotlinOptions.jvmTarget", "'1.8'");
    });
    assertThat(write(build)).contains("""
        tasks.named('compileKotlin') {
        	kotlinOptions.freeCompilerArgs = ['-Xjsr305=strict']
        	kotlinOptions.jvmTarget = '1.8'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTaskCustomizedWithNestedCustomization() {
    GradleBuild build = new GradleBuild();
    build.tasks().customize("compileKotlin", (compileKotlin) -> compileKotlin.nested("kotlinOptions", (kotlinOptions) -> {
        kotlinOptions.attribute("freeCompilerArgs", "['-Xjsr305=strict']");
        kotlinOptions.attribute("jvmTarget", "'1.8'");
    }));
    assertThat(write(build)).contains("""
        tasks.named('compileKotlin') {
        	kotlinOptions {
        		freeCompilerArgs = ['-Xjsr305=strict']
        		jvmTarget = '1.8'
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExt() {
    GradleBuild build = new GradleBuild();
    build.properties().property("java.version", "'1.8'").property("alpha", "file(\"build/example\")");
    assertThat(write(build)).contains("""
        ext {
        	set('alpha', file("build/example"))
        	set('java.version', '1.8')
        }""");
}
"
    "@Test
@Test
void gradleBuildWithVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("version.property", false), "1.2.3").version(VersionProperty.of("internal.property", true), "4.5.6").version("external.property", "7.8.9");
    assertThat(write(build)).contains("""
        ext {
        	set('external.property', "7.8.9")
        	set('internalProperty', "4.5.6")
        	set('version.property', "1.2.3")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("kotlin-stdlib", Dependency.withCoordinates("org.jetbrains.kotlin", "kotlin-stdlib-jdk8").version(VersionReference.ofProperty("kotlin.version")).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExternalVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("acme", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofProperty(VersionProperty.of("acme.version", false))).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation "com.example:acme:${property('acme.version')}"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExtAndVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("test-version"), "1.0").version("alpha-version", "0.1").property("myProperty", "'42'");
    assertThat(write(build)).contains("""
        ext {
        	set('myProperty', '42')
        	set('alpha-version', "0.1")
        	set('testVersion', "1.0")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithConfiguration() {
    GradleBuild build = new GradleBuild();
    build.configurations().add("developmentOnly");
    assertThat(write(build)).contains("""
        configurations {
        	developmentOnly
        }""");
}
"
    "@Test
@Test
void gradleBuildWithConfigurationCustomization() {
    GradleBuild build = new GradleBuild();
    build.configurations().customize("developmentOnly", (configuration) -> configuration.extendsFrom("compile"));
    build.configurations().customize("developmentOnly", (configuration) -> configuration.extendsFrom("testCompile"));
    assertThat(write(build)).contains("""
        configurations {
        	developmentOnly {
        		extendsFrom compile, testCompile
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithConfigurationCustomizations() {
    GradleBuild build = new GradleBuild();
    build.configurations().customize("developmentOnly", (configuration) -> configuration.extendsFrom("compile"));
    build.configurations().customize("testOnly", (configuration) -> configuration.extendsFrom("testCompile"));
    assertThat(write(build)).contains("""
        configurations {
        	developmentOnly {
        		extendsFrom compile
        	}
        	testOnly {
        		extendsFrom testCompile
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithAnnotationProcessorDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("annotation-processor", "org.springframework.boot", "spring-boot-configuration-processor", DependencyScope.ANNOTATION_PROCESSOR);
    assertThat(write(build)).contains("""
        dependencies {
        	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCompileDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", "org.springframework.boot", "spring-boot-starter", DependencyScope.COMPILE);
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'org.springframework.boot:spring-boot-starter'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNoScopeDependencyDefaultsToCompile() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'org.springframework.boot:spring-boot-starter'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("driver", Dependency.withCoordinates("com.example", "jdbc-driver").version(VersionReference.ofValue("1.0.0")).scope(DependencyScope.RUNTIME));
    assertThat(write(build)).contains("""
        dependencies {
        	runtimeOnly 'com.example:jdbc-driver:1.0.0'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithProvidedRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("tomcat", "org.springframework.boot", "spring-boot-starter-tomcat", DependencyScope.PROVIDED_RUNTIME);
    assertThat(write(build)).contains("""
        dependencies {
        	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTestCompileDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", "org.springframework.boot", "spring-boot-starter-test", DependencyScope.TEST_COMPILE);
    assertThat(write(build)).contains("""
        dependencies {
        	testImplementation 'org.springframework.boot:spring-boot-starter-test'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCompileOnlyDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", "org.springframework.boot", "spring-boot-starter-foobar", DependencyScope.COMPILE_ONLY);
    assertThat(write(build)).contains("""
        dependencies {
        	compileOnly 'org.springframework.boot:spring-boot-starter-foobar'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithTestRuntimeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("embed-mongo", "de.flapdoodle.embed", "de.flapdoodle.embed.mongo", DependencyScope.TEST_RUNTIME);
    assertThat(write(build)).contains("""
        dependencies {
        	testRuntimeOnly 'de.flapdoodle.embed:de.flapdoodle.embed.mongo'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithClassifierDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("com.example", "acme").classifier("test-jar"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'com.example:acme:test-jar'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExclusions() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", Dependency.withCoordinates("com.example", "test").scope(DependencyScope.COMPILE).exclusions(new Exclusion("com.example.legacy", "legacy-one"), new Exclusion("com.example.another", "legacy-two")));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation('com.example:test') {
        		exclude group: 'com.example.legacy', module: 'legacy-one'
        		exclude group: 'com.example.another', module: 'legacy-two'
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCustomDependencyConfiguration() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("test", GradleDependency.withCoordinates("org.springframework.boot", "spring-boot-starter-foobar").scope(DependencyScope.RUNTIME).configuration("myRuntime"));
    assertThat(write(build)).contains("""
        dependencies {
        	myRuntime 'org.springframework.boot:spring-boot-starter-foobar'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNonNullArtifactTypeDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter").scope(DependencyScope.COMPILE).type("tar.gz"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'org.springframework.boot:spring-boot-starter@tar.gz'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithNonNullArtifactTypeAndClassifierDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("root", Dependency.withCoordinates("com.example", "acme").scope(DependencyScope.COMPILE).type("tar.gz").classifier("test-jar"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'com.example:acme:test-jar@tar.gz'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithOrderedDependencies() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("beta", Dependency.withCoordinates("com.example", "beta"));
    build.dependencies().add("alpha", Dependency.withCoordinates("com.example", "alpha"));
    build.dependencies().add("web", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter-web"));
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation 'org.springframework.boot:spring-boot-starter'
        	implementation 'org.springframework.boot:spring-boot-starter-web'
        	implementation 'com.example:alpha'
        	implementation 'com.example:beta'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithOrderedDependenciesAndCustomComparator() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("beta", Dependency.withCoordinates("com.example", "beta"));
    build.dependencies().add("alpha", Dependency.withCoordinates("com.example", "alpha"));
    build.dependencies().add("web", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter-web"));
    build.dependencies().add("root", Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter"));
    GroovyDslGradleBuildWriter writer = new GroovyDslGradleBuildWriter() {

        @Override
        protected Comparator<Dependency> getDependencyComparator() {
            return Comparator.comparing(Dependency::getArtifactId);
        }
    };
    assertThat(write(writer, build)).contains("""
        dependencies {
        	implementation 'com.example:alpha'
        	implementation 'com.example:beta'
        	implementation 'org.springframework.boot:spring-boot-starter'
        	implementation 'org.springframework.boot:spring-boot-starter-web'
        }""");
}
"
    "@Test
@Test
void gradleBuildWithBom() {
    GradleBuild build = new GradleBuild();
    build.boms().add("test", BillOfMaterials.withCoordinates("com.example", "my-project-dependencies").version(VersionReference.ofValue("1.0.0.RELEASE")));
    assertThat(write(build)).contains("""
        dependencyManagement {
        	imports {
        		mavenBom 'com.example:my-project-dependencies:1.0.0.RELEASE'
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithOrderedBoms() {
    GradleBuild build = new GradleBuild();
    build.boms().add("bom1", BillOfMaterials.withCoordinates("com.example", "my-project-dependencies").version(VersionReference.ofValue("1.0.0.RELEASE")).order(5));
    build.boms().add("bom2", BillOfMaterials.withCoordinates("com.example", "root-dependencies").version(VersionReference.ofProperty("root.version")).order(2));
    assertThat(write(build)).contains("""
        dependencyManagement {
        	imports {
        		mavenBom 'com.example:my-project-dependencies:1.0.0.RELEASE'
        		mavenBom "com.example:root-dependencies:${rootVersion}"
        	}
        }""");
}
"
    "@Test
@Test
void gradleBuildWithCustomVersion() {
    GradleBuild build = new GradleBuild();
    build.settings().version("1.2.4.RELEASE");
    assertThat(write(build)).contains("version = '1.2.4.RELEASE'");
}
"
    "@Test
@Test
void shouldCustomizeExtensions() {
    GradleBuild build = new GradleBuild();
    build.extensions().customize("kotlin", (kotlin) -> kotlin.nested("compilerOptions", (compilerOptions) -> {
        compilerOptions.attributeWithType("jvmTarget", "JvmTarget.JVM_21", "org.jetbrains.kotlin.gradle.dsl.JvmTarget");
        compilerOptions.invoke("freeCompilerArgs.addAll", "'-Xjsr305=strict'", "'-Xexport-kdoc'");
    }));
    String written = write(build);
    assertThat(written).contains("import org.jetbrains.kotlin.gradle.dsl.JvmTarget");
    assertThat(written).contains("""
        kotlin {
        	compilerOptions {
        		freeCompilerArgs.addAll '-Xjsr305=strict', '-Xexport-kdoc'
        		jvmTarget = JvmTarget.JVM_21
        	}
        }""");
}
"
    "@Test
protected String write(GradleBuild build) {
    return write(new GroovyDslGradleBuildWriter(), build);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlockWithEndOfStatementPlaceholderInvokeConfiguredFormattingOptions() {
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.statementSeparator()).willReturn(";");
    CodeBlock code = CodeBlock.of("invoke(param)$]");
    assertThat(write(code, options)).isEqualToNormalizingNewlines("""
        invoke(param);
        """);
    verify(options).statementSeparator();
}
"
    "@Test
private String writeJava(CodeBlock code) {
    return write(code, CodeBlock.JAVA_FORMATTING_OPTIONS);
}
"
    "@Test
private String write(CodeBlock code, FormattingOptions options) {
    StringWriter out = new StringWriter();
    IndentingWriter writer = new IndentingWriter(out, new SimpleIndentStrategy("\t"));
    code.write(writer, options);
    return out.toString();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleBuildWriterTests.java
Tests:
    "@Test
@Test
void gradleBuildWithSnippet() {
    GradleBuild build = new GradleBuild();
    build.snippets().add((writer) -> {
        writer.println("custom {");
        writer.indented(() -> {
            writer.println("first = 1");
            writer.println("second = 2");
        });
        writer.println("}");
    });
    assertThat(write(build)).contains("""
        custom {
        	first = 1
        	second = 2
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithSnippetsAreSeparated() {
    GradleBuild build = new GradleBuild();
    build.snippets().add((writer) -> {
        writer.println("custom {");
        writer.indented(() -> {
            writer.println("first = 1");
            writer.println("second = 2");
        });
        writer.println("}");
    });
    build.snippets().add((writer) -> {
        writer.println("another {");
        writer.indented(() -> {
            writer.println("third = 3");
            writer.println("fourth = 4");
        });
        writer.println("}");
    });
    assertThat(write(build)).contains("""
        custom {
        	first = 1
        	second = 2
        }
        
        another {
        	third = 3
        	fourth = 4
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithSnippetAndImports() {
    GradleBuild build = new GradleBuild();
    build.snippets().add(Set.of("com.example.CustomTask"), (writer) -> writer.println("custom { }"));
    assertThat(write(build)).containsOnlyOnce("import com.example.CustomTask");
}
"
    "@Test
protected abstract String write(GradleBuild build);
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/io/text/BulletedSectionTests.java
Tests:
    "@Test
@Test
void bulletedSectionEmptyDoesNotInvokeRender() throws IOException {
    BulletedSection<String> section = new BulletedSection<>(this.renderer, "test");
    PrintWriter writer = mock(PrintWriter.class);
    section.write(writer);
    verifyNoMoreInteractions(writer, this.renderer);
}
"
    "@Test
@Test
void bulletedSectionWithDefaultItemName() throws IOException {
    given(this.renderer.render(eq("template"), any())).willReturn("output");
    BulletedSection<String> section = new BulletedSection<>(this.renderer, "template");
    section.addItem("test");
    section.write(new PrintWriter(new StringWriter()));
    verify(this.renderer).render(eq("template"), this.modelCaptor.capture());
    Map<String, Object> model = this.modelCaptor.getValue();
    assertThat(model).containsOnly(entry("items", Collections.singletonList("test")));
}
"
    "@Test
@Test
void bulletedSectionWithCustomItemName() throws IOException {
    given(this.renderer.render(eq("template"), any())).willReturn("output");
    BulletedSection<String> section = new BulletedSection<>(this.renderer, "template", "elements");
    section.addItem("test");
    section.write(new PrintWriter(new StringWriter()));
    verify(this.renderer).render(eq("template"), this.modelCaptor.capture());
    Map<String, Object> model = this.modelCaptor.getValue();
    assertThat(model).containsOnly(entry("elements", Collections.singletonList("test")));
}
"Sure, here are the generated test scenarios for the `write` method in the `CodeBlock` class, ensuring to cover various edge cases and error handling scenarios:

```java
/**
 * Scenario 1: Test that $L placeholder correctly handles CodeBlock arguments
 */
Scenario 1: Test that $L placeholder correctly handles CodeBlock arguments

Details:
  TestName: testPlaceholderWithCodeBlockArgument
  Description: This test verifies that the $L placeholder correctly processes CodeBlock arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $L placeholder and a CodeBlock argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the expected CodeBlock content.

Validation:
  Ensure that the CodeBlock argument is correctly embedded in the output, verifying the handling of CodeBlock instances by the $L placeholder.
  This test is crucial for validating the correct integration of nested CodeBlock instances within the main CodeBlock.

/**
 * Scenario 2: Test that $L placeholder correctly handles non-CodeBlock arguments
 */
Scenario 2: Test that $L placeholder correctly handles non-CodeBlock arguments

Details:
  TestName: testPlaceholderWithNonCodeBlockArgument
  Description: This test checks that the $L placeholder correctly processes non-CodeBlock arguments by verifying the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $L placeholder and a non-CodeBlock argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the string representation of the non-CodeBlock argument.

Validation:
  Ensure that non-CodeBlock arguments are properly converted to strings and included in the output, confirming the correct handling of diverse argument types by the $L placeholder.
  This test is essential for validating the method's flexibility in processing various types of arguments.

/**
 * Scenario 3: Test that $S placeholder correctly handles null strings
 */
Scenario 3: Test that $S placeholder correctly handles null strings

Details:
  TestName: testStringPlaceholderWithNull
  Description: This test verifies that the $S placeholder correctly handles null string arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $S placeholder and a null string argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains "null".

Validation:
  Ensure that null string arguments are correctly represented as "null" in the output, confirming the $S placeholder's handling of null values.
  This test is important for validating the method's robustness in dealing with potential null inputs.

/**
 * Scenario 4: Test that $S placeholder correctly handles non-null strings
 */
Scenario 4: Test that $S placeholder correctly handles non-null strings

Details:
  TestName: testStringPlaceholderWithNonNullString
  Description: This test checks that the $S placeholder correctly processes non-null string arguments by verifying the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $S placeholder and a non-null string argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the quoted string representation of the argument.

Validation:
  Ensure that non-null string arguments are correctly quoted and included in the output, confirming the $S placeholder's handling of string values.
  This test is essential for validating the method's accuracy in processing and formatting string inputs.

/**
 * Scenario 5: Test that $T placeholder correctly handles Class arguments
 */
Scenario 5: Test that $T placeholder correctly handles Class arguments

Details:
  TestName: testTypePlaceholderWithClassArgument
  Description: This test verifies that the $T placeholder correctly processes Class arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $T placeholder and a Class argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the simple name of the Class.

Validation:
  Ensure that Class arguments are correctly represented by their simple names in the output, confirming the $T placeholder's handling of Class types.
  This test is crucial for validating the method's ability to correctly process and format Class arguments.

/**
 * Scenario 6: Test that $T placeholder correctly handles ClassName arguments
 */
Scenario 6: Test that $T placeholder correctly handles ClassName arguments

Details:
  TestName: testTypePlaceholderWithClassNameArgument
  Description: This test checks that the $T placeholder correctly processes ClassName arguments by verifying the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $T placeholder and a ClassName argument. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the simple name of the ClassName.

Validation:
  Ensure that ClassName arguments are correctly represented by their simple names in the output, confirming the $T placeholder's handling of ClassName types.
  This test is essential for validating the method's compatibility with ClassName arguments.

/**
 * Scenario 7: Test that $] placeholder correctly handles statement separators
 */
Scenario 7: Test that $] placeholder correctly handles statement separators

Details:
  TestName: testStatementSeparatorPlaceholder
  Description: This test verifies that the $] placeholder correctly handles statement separators by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $] placeholder. Set up an IndentingWriter and a FormattingOptions instance with a custom statement separator.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the custom statement separator.

Validation:
  Ensure that the statement separator is correctly applied at the end of the output, confirming the $] placeholder's handling of statement separators.
  This test is important for validating the method's ability to handle and apply custom statement separators.

/**
 * Scenario 8: Test that $ placeholder correctly handles dollar signs
 */
Scenario 8: Test that $ placeholder correctly handles dollar signs

Details:
  TestName: testDollarSignPlaceholder
  Description: This test verifies that the $ placeholder correctly handles dollar signs by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a $ placeholder. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains a single dollar sign.

Validation:
  Ensure that the dollar sign is correctly included in the output, confirming the $ placeholder's handling of dollar signs.
  This test is crucial for validating the method's ability to correctly process and include literal dollar signs in the output.

/**
 * Scenario 9: Test that default parts are correctly printed
 */
Scenario 9: Test that default parts are correctly printed

Details:
  TestName: testDefaultPartPrinting
  Description: This test verifies that default parts are correctly printed by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a default part. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output contains the default part.

Validation:
  Ensure that default parts are correctly included in the output, confirming the method's handling of default parts.
  This test is important for validating the method's basic functionality in processing and including default parts in the output.

/**
 * Scenario 10: Test handling of multiple parts and arguments
 */
Scenario 10: Test handling of multiple parts and arguments

Details:
  TestName: testHandlingOfMultiplePartsAndArguments
  Description: This test verifies the method's ability to handle multiple parts and arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with multiple parts and various types of arguments. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes all parts and arguments in the expected order.

Validation:
  Ensure that multiple parts and arguments are correctly processed and included in the output, confirming the method's ability to handle complex input scenarios.
  This test is crucial for validating the method's robustness and flexibility in dealing with varied and comprehensive input data.

/**
 * Scenario 11: Test handling of mismatched arguments
 */
Scenario 11: Test handling of mismatched arguments

Details:
  TestName: testHandlingOfMismatchedArguments
  Description: This test verifies that the method correctly handles mismatched arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a format string that expects more arguments than provided. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that an IllegalArgumentException is thrown indicating the argument mismatch.

Validation:
  Ensure that the method throws an IllegalArgumentException with an appropriate message when the number of arguments does not match the expected number in the format string.
  This test is important for validating the method's error handling and robustness in dealing with argument mismatches.

/**
 * Scenario 12: Test handling of unsupported placeholders
 */
Scenario 12: Test handling of unsupported placeholders

Details:
  TestName: testHandlingOfUnsupportedPlaceholders
  Description: This test verifies that the method correctly handles unsupported placeholders by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with an unsupported placeholder in the format string. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that an IllegalArgumentException is thrown indicating the unsupported placeholder.

Validation:
  Ensure that the method throws an IllegalArgumentException with an appropriate message when encountering an unsupported placeholder.
  This test is important for validating the method's error handling and robustness in dealing with unsupported placeholders.

/**
 * Scenario 13: Test handling of null format string
 */
Scenario 13: Test handling of null format string

Details:
  TestName: testHandlingOfNullFormatString
  Description: This test verifies that the method correctly handles a null format string by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a null format string. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output is empty or handles the null format string gracefully.

Validation:
  Ensure that the method gracefully handles a null format string by either returning an empty output or throwing an appropriate exception.
  This test is important for validating the method's robustness in dealing with potential null inputs.

/**
 * Scenario 14: Test handling of empty format string
 */
Scenario 14: Test handling of empty format string

Details:
  TestName: testHandlingOfEmptyFormatString
  Description: This test verifies that the method correctly handles an empty format string by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with an empty format string. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output is empty.

Validation:
  Ensure that the method gracefully handles an empty format string by returning an empty output.
  This test is important for validating the method's robustness in dealing with potential empty inputs.

/**
 * Scenario 15: Test handling of format string ending with a placeholder
 */
Scenario 15: Test handling of format string ending with a placeholder

Details:
  TestName: testHandlingOfFormatStringEndingWithPlaceholder
  Description: This test verifies that the method correctly handles a format string ending with a placeholder by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a format string ending with a placeholder. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that an IllegalArgumentException is thrown indicating the format string ending with a placeholder.

Validation:
  Ensure that the method throws an IllegalArgumentException with an appropriate message when the format string ends with a placeholder.
  This test is important for validating the method's error handling and robustness in dealing with format strings ending with placeholders.

/**
 * Scenario 16: Test handling of nested CodeBlocks
 */
Scenario 16: Test handling of nested CodeBlocks

Details:
  TestName: testHandlingOfNestedCodeBlocks
  Description: This test verifies that the method correctly handles nested CodeBlocks by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with nested CodeBlocks. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes the content of all nested CodeBlocks.

Validation:
  Ensure that nested CodeBlocks are correctly processed and included in the output, confirming the method's ability to handle nested structures.
  This test is crucial for validating the method's robustness and flexibility in dealing with nested CodeBlock instances.

/**
 * Scenario 17: Test handling of complex nested CodeBlocks
 */
Scenario 17: Test handling of complex nested CodeBlocks

Details:
  TestName: testHandlingOfComplexNestedCodeBlocks
  Description: This test verifies that the method correctly handles complex nested CodeBlocks by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with multiple levels of nested CodeBlocks. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes the content of all nested CodeBlocks at the appropriate levels.

Validation:
  Ensure that complex nested CodeBlocks are correctly processed and included in the output, confirming the method's ability to handle intricate nested structures.
  This test is important for validating the method's robustness and flexibility in dealing with complex nested CodeBlock instances.

/**
 * Scenario 18: Test handling of large number of parts and arguments
 */
Scenario 18: Test handling of large number of parts and arguments

Details:
  TestName: testHandlingOfLargeNumberOfPartsAndArguments
  Description: This test verifies that the method correctly handles a large number of parts and arguments by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a large number of parts and arguments. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes all parts and arguments in the expected order.

Validation:
  Ensure that the method efficiently processes and includes a large number of parts and arguments in the output, confirming the method's performance and scalability.
  This test is important for validating the method's robustness and efficiency in dealing with extensive input data.

/**
 * Scenario 19: Test handling of mixed placeholders
 */
Scenario 19: Test handling of mixed placeholders

Details:
  TestName: testHandlingOfMixedPlaceholders
  Description: This test verifies that the method correctly handles mixed placeholders by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a mix of different placeholders and various types of arguments. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes all parts and arguments in the expected order and format.

Validation:
  Ensure that mixed placeholders are correctly processed and included in the output, confirming the method's ability to handle diverse input scenarios.
  This test is crucial for validating the method's versatility and robustness in dealing with mixed and varied input data.

/**
 * Scenario 20: Test handling of complex format string with mixed placeholders
 */
Scenario 20: Test handling of complex format string with mixed placeholders

Details:
  TestName: testHandlingOfComplexFormatStringWithMixedPlaceholders
  Description: This test verifies that the method correctly handles a complex format string with mixed placeholders by checking the output of the write method.

Execution:
  Arrange: Create a CodeBlock instance with a complex format string containing a mix of different placeholders and various types of arguments. Set up an IndentingWriter and a FormattingOptions instance.
  Act: Invoke the write method with the prepared CodeBlock instance, IndentingWriter, and FormattingOptions.
  Assert: Verify that the output correctly includes all parts and arguments in the expected order and format.

Validation:
  Ensure that a complex format string with mixed placeholders is correctly processed and included in the output, confirming the method's ability to handle intricate and varied input scenarios.
  This test is important for validating the method's robustness and flexibility in dealing with complex and comprehensive input data.
```
These scenarios cover a wide range of cases, including normal operation, edge cases, and error handling, to ensure that the `write` method functions correctly under various conditions.,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;
import io.spring.initializr.generator.io.IndentingWriter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.Arrays;
import java.util.Collections;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.StreamSupport;
import org.springframework.util.ClassUtils;
imports;
imports = List.copyOf(builder.imports);
imports = new ArrayList<>();
imports.addAll(codeBlock.imports);
imports.addAll(code.getImports());
imports.add(type.getName());
imports.add(className.getName());
imports.add(fqName);

class CodeBlockWriteTest {
    private IndentingWriter writer;
    private FormattingOptions options;
    @BeforeEach
    void setUp() {
        writer = mock(IndentingWriter.class);
        options = mock(FormattingOptions.class);
    }
    @Tag("valid")
    @Test
    void testPlaceholderWithCodeBlockArgument() {
        CodeBlock innerCodeBlock = CodeBlock.of("Inner CodeBlock");
        CodeBlock codeBlock = CodeBlock.of("$L", innerCodeBlock);
        codeBlock.write(writer, options);
        verify(writer).print("Inner CodeBlock");
    }
    @Tag("valid")
    @Test
    void testPlaceholderWithNonCodeBlockArgument() {
        CodeBlock codeBlock = CodeBlock.of("$L", "Non-CodeBlock Argument");
        codeBlock.write(writer, options);
        verify(writer).print("Non-CodeBlock Argument");
    }
    @Tag("valid")
    @Test
    void testStringPlaceholderWithNull() {
        CodeBlock codeBlock = CodeBlock.of("$S", (String) null);
        codeBlock.write(writer, options);
        verify(writer).print("null");
    }
    @Tag("valid")
    @Test
    void testStringPlaceholderWithNonNullString() {
        CodeBlock codeBlock = CodeBlock.of("$S", "Non-Null String");
        codeBlock.write(writer, options);
        verify(writer).print("\"Non-Null String\"");
    }
    @Tag("valid")
    @Test
    void testTypePlaceholderWithClassArgument() {
        CodeBlock codeBlock = CodeBlock.of("$T", "java.lang.String");
        codeBlock.write(writer, options);
        verify(writer).print("String");
    }
    @Tag("valid")
    @Test
    void testTypePlaceholderWithClassNameArgument() {
        ClassName className = ClassName.of("java.lang.String");
        CodeBlock codeBlock = CodeBlock.of("$T", className);
        codeBlock.write(writer, options);
        verify(writer).print("String");
    }
    @Tag("valid")
    @Test
    void testStatementSeparatorPlaceholder() {
        Mockito.when(options.statementSeparator()).thenReturn(";");
        CodeBlock codeBlock = CodeBlock.of("Some code$]");
        codeBlock.write(writer, options);
        verify(writer).print("Some code");
        verify(writer).println(";");
    }
    @Tag("valid")
    @Test
    void testDollarSignPlaceholder() {
        CodeBlock codeBlock = CodeBlock.of("$");
        codeBlock.write(writer, options);
        verify(writer).print("$");
    }
    @Tag("valid")
    @Test
    void testDefaultPartPrinting() {
        CodeBlock codeBlock = CodeBlock.of("Default part");
        codeBlock.write(writer, options);
        verify(writer).print("Default part");
    }
    @Tag("valid")
    @Test
    void testHandlingOfMultiplePartsAndArguments() {
        CodeBlock codeBlock = CodeBlock.of("First part $L, $S, $T", "arg1", "arg2", "arg3");
        codeBlock.write(writer, options);
        verify(writer).print("First part arg1, \"arg2\", arg3");
    }
    @Tag("boundary")
    @Test
    void testHandlingOfLargeNumberOfPartsAndArguments() {
        StringBuilder format = new StringBuilder();
        Object[] args = new Object[1000];
        for (int i = 0; i < 1000; i++) {
            format.append("$L, ");
            args[i] = "arg" + i;
        }
        CodeBlock codeBlock = CodeBlock.of(format.toString(), args);
        codeBlock.write(writer, options);
        for (int i = 0; i < 1000; i++) {
            verify(writer).print("arg" + i);
        }
    }
    @Tag("valid")
    @Test
    void testHandlingOfMixedPlaceholders() {
        ClassName className = ClassName.of("java.util.List");
        CodeBlock nestedCodeBlock = CodeBlock.of("Nested CodeBlock");
        CodeBlock codeBlock = CodeBlock.of("Class: $T, CodeBlock: $L, String: $S", className, nestedCodeBlock, "String arg");
        codeBlock.write(writer, options);
        verify(writer).print("Class: List, CodeBlock: Nested CodeBlock, String: \"String arg\"");
    }
    @Tag("integration")
    @Test
    void testHandlingOfComplexNestedCodeBlocks() {
        CodeBlock innerMostCodeBlock = CodeBlock.of("InnerMost CodeBlock");
        CodeBlock innerCodeBlock = CodeBlock.of("Inner $L", innerMostCodeBlock);
        CodeBlock codeBlock = CodeBlock.of("Outer $L", innerCodeBlock);
        codeBlock.write(writer, options);
        verify(writer).print("Outer Inner InnerMost CodeBlock");
    }
    @Tag("valid")
    @Test
    void testHandlingOfComplexFormatStringWithMixedPlaceholders() {
        ClassName className = ClassName.of("java.util.Map");
        CodeBlock nestedCodeBlock = CodeBlock.of("Nested $L", "NestedArg");
        CodeBlock codeBlock = CodeBlock.of("Class: $T, Nested: $L, String: $S", className, nestedCodeBlock, "String arg");
        codeBlock.write(writer, options);
        verify(writer).print("Class: Map, Nested: Nested NestedArg, String: \"String arg\"");
    }
    @Tag("valid")
    @Test
    void testHandlingOfNestedCodeBlocks() {
        CodeBlock innerCodeBlock = CodeBlock.of("Inner CodeBlock");
        CodeBlock codeBlock = CodeBlock.of("Outer $L", innerCodeBlock);
        codeBlock.write(writer, options);
        verify(writer).print("Outer Inner CodeBlock");
    }
}