/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getImports_eeeaa4979a
ROOST_METHOD_SIG_HASH=getImports_7403fa5d12

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationTests.java
Tests:
    "@Test
@Test
void annotationWithNoAttribute() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).build();
    assertThat(write(test)).isEqualTo("@Test");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@ParameterizedTest
@MethodSource("parameters")
void annotationWithPrimitives(Object parameter, String expectedCode) {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", parameter).build();
    assertThat(write(test)).isEqualTo("@Test(test = " + expectedCode + ")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithString() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", "value").build();
    assertThat(write(test)).isEqualTo("@Test(test = \"value\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithClass() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", Test.class).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithClassName() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ClassName.of(Test.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithTypeReferenceInvokeConfiguredFormattingOptions() {
    ClassName typeReference = ClassName.of("com.example.Another");
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.classReference(typeReference)).willReturn(CodeBlock.of("$T::class", typeReference));
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", typeReference).build();
    assertThat(write(test, options)).isEqualTo("@Test(test = Another::class)");
    verify(options).classReference(typeReference);
    assertThat(test.getImports()).containsOnly("com.example.Test", typeReference.getName());
}
"
    "@Test
@Test
void annotationWithEnum() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ChronoUnit.CENTURIES).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithEnumCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", CodeBlock.of("$T.CENTURIES", ChronoUnit.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithNestedAnnotation() {
    Annotation nested = Annotation.of(ClassName.of("com.example.Nested")).set("counter", 42).build();
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", nested).build();
    assertThat(write(test)).isEqualTo("@Test(test = @Nested(counter = 42))");
    assertThat(test.getImports()).containsOnly("com.example.Test", "com.example.Nested");
}
"
    "@Test
@Test
void annotationWithOnlyValueUsesShortcut() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("value", "test").build();
    assertThat(write(test)).isEqualTo("@Test(\"test\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithParameterClassAndCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("types", StringWriter.class, CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"
    "@Test
@Test
void annotationWithAmendedValues() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).add("types", StringWriter.class).add("types", CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", StringUtils.class);
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassNameAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", ClassName.of(StringUtils.class));
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndFullyQualifiedClassNameAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", "com.example.StringUtils");
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly("com.example.StringUtils");
}
"
    "@Test
@Test
void codeBlockDoesNotAddNewLine() {
    CodeBlock code = CodeBlock.of("(123, 456)");
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlocksCanBeAdded() {
    CodeBlock code = CodeBlock.builder().add("(123").add(CodeBlock.of(", 456)")).build();
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithSingleStatement() {
    CodeBlock code = CodeBlock.ofStatement("myInstance.sayHello(123)");
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        """);
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithMultipleStatements() {
    CodeBlock code = CodeBlock.builder().addStatement("myInstance.sayHello(123)").addStatement(CodeBlock.of("myInstance.sayHello(456)")).build();
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        myInstance.sayHello(456);
        """);
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithParameterCodeBlockAddsImports() {
    CodeBlock code = CodeBlock.of("$L", CodeBlock.of("$T.truncate(myString)", ClassName.of(StringUtils.class)));
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationContainerTests.java
Tests:
    "@Test
@Test
void valuesWithSimpleAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeReuseConfiguration() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "another"));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).containsExactly("test", "another");
        });
    });
}
"
    "@Test
@Test
void addAnnotationSeveralTimeCanReplaceAttribute() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 42).build()));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.set("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 24).build()));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test", "com.example.Nested");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).singleElement().isInstanceOfSatisfying(Annotation.class, (nested) -> {
                assertThat(nested.getClassName()).isEqualTo(NESTED_CLASS_NAME);
                assertThat(nested.getAttributes()).singleElement().satisfies((nestedAttribute) -> {
                    assertThat(nestedAttribute.getName()).isEqualTo("counter");
                    assertThat(nestedAttribute.getValues()).containsExactly(24);
                });
            });
        });
    });
}
"Here are the test scenarios for the `getImports` method of the `CodeBlock` class, ensuring to cover various aspects and edge cases:

### Scenario 1: Basic Functional Test for `getImports`

**Details:**
  - TestName: `basicGetImports`
  - Description: This test checks that the `getImports` method returns the correct list of imports when the `imports` field is initialized with a specific set of imports.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with a predefined list of imports.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list of imports matches the expected list.

**Validation:**
  - The assertion aims to verify that the `getImports` method correctly returns the imports that were set during the initialization of the `CodeBlock` object. This test is crucial for ensuring that the method works as expected in the simplest, most common scenario.

### Scenario 2: Test `getImports` with Empty List

**Details:**
  - TestName: `getImportsWithEmptyList`
  - Description: This test checks that the `getImports` method returns an empty list when the `imports` field is initialized with an empty list.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with an empty list of imports.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list is empty.

**Validation:**
  - This test ensures that the `getImports` method correctly handles the case where no imports are present. It is essential for validating the behavior of the method when there are no imports to return.

### Scenario 3: Test `getImports` with Null List

**Details:**
  - TestName: `getImportsWithNullList`
  - Description: This test checks that the `getImports` method returns an empty list when the `imports` field is null.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with a null `imports` field.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list is empty.

**Validation:**
  - This test ensures that the `getImports` method gracefully handles the scenario where the `imports` field is not initialized. It is crucial for preventing null pointer exceptions and ensuring robust behavior.

### Scenario 4: Test `getImports` after Adding Imports

**Details:**
  - TestName: `getImportsAfterAddingImports`
  - Description: This test checks that the `getImports` method returns the correct list of imports after dynamically adding imports to the `CodeBlock` object.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with an empty list of imports and then add a set of imports using the builder pattern.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list of imports matches the expected list.

**Validation:**
  - This test ensures that the `getImports` method correctly reflects the state of the `imports` field after modifications. It is important for validating the method's behavior in dynamic scenarios where imports are added after the `CodeBlock` object is created.

### Scenario 5: Test `getImports` with Duplicated Imports

**Details:**
  - TestName: `getImportsWithDuplicatedImports`
  - Description: This test checks that the `getImports` method returns a list of unique imports even if the `imports` field contains duplicate entries.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with a list of imports that includes duplicates.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list of imports contains only unique entries.

**Validation:**
  - This test ensures that the `getImports` method handles duplicate imports correctly by returning a list of unique imports. It is crucial for maintaining data integrity and preventing duplicate imports in the output.

### Scenario 6: Test `getImports` after Clearing Imports

**Details:**
  - TestName: `getImportsAfterClearingImports`
  - Description: This test checks that the `getImports` method returns an empty list after clearing the `imports` field.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with a predefined list of imports and then clear the imports.
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list is empty.

**Validation:**
  - This test ensures that the `getImports` method correctly reflects the state of the `imports` field after it has been cleared. It is important for validating the method's behavior in scenarios where imports are removed.

### Scenario 7: Test `getImports` with Mixed Imports

**Details:**
  - TestName: `getImportsWithMixedImports`
  - Description: This test checks that the `getImports` method returns the correct list of imports when the `imports` field contains a mix of different types of imports.

**Execution:**
  - Arrange: Initialize a `CodeBlock` object with a list of imports that includes various types of imports (e.g., standard Java imports, custom imports, fully qualified names).
  - Act: Call the `getImports` method.
  - Assert: Verify that the returned list of imports matches the expected list.

**Validation:**
  - This test ensures that the `getImports` method correctly handles a diverse set of imports. It is important for validating the method's behavior in real-world scenarios where imports can vary in type and format.

These scenarios cover various aspects of the `getImports` method, ensuring comprehensive testing and validation.,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import io.spring.initializr.generator.io.IndentingWriter;
import org.springframework.util.ClassUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import java.util.ArrayList;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.stream.Collector;
import java.util.stream.StreamSupport;

public class CodeBlockGetImportsTest {

	@Tag("valid")
	@Test
	public void basicGetImports() {
		List<String>

		CodeBlock codeBlock=new CodeBlock(CodeBlock.builder().addImports(assertEquals(
	}

	@Tag("valid")
	@Test
	public void getImportsWithEmptyList() {
		CodeBlock codeBlock = new CodeBlock(CodeBlock.builder().addImports(new ArrayList<>()));
		assertEquals(new ArrayList<>(), codeBlock.getImports());
	}

	@Tag("valid")
	@Test
	public void getImportsWithNullList() {
		CodeBlock codeBlock = new CodeBlock(CodeBlock.builder());
		assertEquals(new ArrayList<>(), codeBlock.getImports());
	}

	@Tag("valid")
	@Test
	public void getImportsAfterAddingImports() {
		CodeBlock codeBlock=new CodeBlock(CodeBlock.builder());List<String>

		codeBlock=new CodeBlock(CodeBlock.builder().addImports(assertEquals(
	}

	@Tag("valid")
	@Test
	public void getImportsWithDuplicatedImports() {
		List<String>

		CodeBlock codeBlock=new CodeBlock(CodeBlock.builder().addImports(List<String>expected=new ArrayList<>();expected.add("java.util.ArrayList");expected.add("java.util.List");assertEquals(expected,codeBlock.getImports());
	}

	@Tag("valid")
	@Test
	public void getImportsAfterClearingImports() {
		List<String>

		CodeBlock codeBlock=new CodeBlock(CodeBlock.builder().addImports(codeBlock=new CodeBlock(CodeBlock.builder());assertEquals(new ArrayList<>(),codeBlock.getImports());
	}

	@Tag("valid")
	@Test
	public void getImportsWithMixedImports() {
		List<String>

		CodeBlock codeBlock=new CodeBlock(CodeBlock.builder().addImports(assertEquals(
	}

	private static class CodeBlock {
        private final List<String>
        private final List<String> parts;
        private final List<Object> args;
        private CodeBlock(Builder builder) {
            this.parts = List.copyOf(builder.parts);
            this.args = List.copyOf(builder.args);
            this.
        }
        public List<String> getImports() {
            return this.
        }
        public void write(IndentingWriter writer, FormattingOptions options) {
            int argIndex = 0;
            for (String part : this.parts) {
                switch (part) {
                    case "$L" -> {
                        Object value = this.args.get(argIndex++);
                        if (value instanceof CodeBlock code) {
                            code.write(writer, options);
                        } else {
                            writer.print(String.valueOf(value));
                        }
                    }
                    case "$S" -> {
                        String value = (String) this.args.get(argIndex++);
                        String valueToEmit = (value != null) ? quote(value) : "null";
                        writer.print(valueToEmit);
                    }
                    case "$T" -> {
                        String className = (String) this.args.get(argIndex++);
                        writer.print(className);
                    }
                    case "$]" -> writer.println(options.statementSeparator());
                    case "$" -> writer.print("$");
                    default -> writer.print(part);
                }
            }
        }
        private static String quote(String value) {
            StringBuilder result = new StringBuilder(value.length() + 2);
            result.append('"');
            for (int i = 0; i < value.length(); i++) {
                char c = value.charAt(i);
                if (c == '\'') {
                    result.append("'");
                    continue;
                }
                if (c == '\"') {
                    result.append("\\\"");
                    continue;
                }
                result.append(c);
            }
            result.append('"');
            return result.toString();
        }
        public static CodeBlock of(String format, Object... args) {
            return new Builder().add(format, args).build();
        }
        public static CodeBlock ofStatement(String format, Object... args) {
            return new Builder().addStatement(format, args).build();
        }
        public static CodeBlock join(Iterable<CodeBlock> codeBlocks, String separator) {
            return StreamSupport.stream(codeBlocks.spliterator(), false).collect(joining(separator));
        }
        public static Collector<CodeBlock, ?, CodeBlock> joining(String separator) {
            return Collector.of(() -> new CodeBlockJoiner(separator, builder()), CodeBlockJoiner::add, CodeBlockJoiner::merge, CodeBlockJoiner::join);
        }
        public static Builder builder() {
            return new Builder();
        }
    }

	private static class Builder {

		private final List<String> parts = new ArrayList<>();

		private final List<Object> args = new ArrayList<>();

		private final List<String>
        public Builder add(CodeBlock codeBlock) {
            this.parts.addAll(codeBlock.parts);
            this.args.addAll(codeBlock.args);
            this.
            return this;
        }

		public Builder add(String format, Object... args) {
			int relativeParameterCount = 0;
			for (int p = 0; p < format.length();) {
				if (format.charAt(p) != '$') {
					int nextP = format.indexOf('$', p + 1);
					nextP = (nextP != -1) ? nextP : format.length();
					this.parts.add(format.substring(p, nextP));
					p = nextP;
					continue;
				}
				p++;
				if (p >= format.length()) {
					throw new IllegalArgumentException("Should not end with '$'");
				}
				if (format.charAt(p) == '$') {
					this.parts.add("$");
					p++;
					continue;
				}
				if (format.charAt(p) == '[' || format.charAt(p) == ']') {
					this.parts.add(format.substring(p - 1, p + 1));
					p++;
					continue;
				}
				this.parts.add("%s".formatted(format));
				char placeHolderType = format.charAt(p++);
				if (!isNoArgPlaceholder(placeHolderType)) {
					int index = relativeParameterCount;
					relativeParameterCount++;
					if (index >= args.length) {
						throw new IllegalArgumentException("Argument mismatch for '%s', expected at least %s %s, got %s"
							.formatted(format, relativeParameterCount,
									(relativeParameterCount > 1) ? "arguments" : "argument", args.length));
					}
					addArgument(format, placeHolderType, args[index]);
				}
				this.parts.add("$" + placeHolderType);
			}
			if (relativeParameterCount != args.length) {
				throw new IllegalArgumentException(
						"Argument mismatch for '%s', expected %s %s, got %s".formatted(format, relativeParameterCount,
								(relativeParameterCount > 1) ? "arguments" : "argument", args.length));
			}
			return this;
		}

		private boolean isNoArgPlaceholder(char c) {
			return c == '[' || c == ']';
		}

		private void addArgument(String format, char c, Object arg) {
			switch (c) {
				case 'L' -> this.args.add(arg(arg));
				case 'S' -> this.args.add(argToString(arg));
				case 'T' -> this.args.add(argToType(arg));
				default -> throw new IllegalArgumentException(
						String.format("Unsupported placeholder '$%s' for '%s'", c, format));
			}
		}

		private Object arg(Object arg) {
			if(arg instanceof CodeBlock code){this.}return arg;
		}

		private String argToString(Object arg) {
			return (arg != null) ? String.valueOf(arg) : null;
		}

		private String argToType(Object arg) {
			if(arg instanceof Class type){this.return type.getSimpleName();}if(arg instanceof ClassName className){this.return className.getSimpleName();}if(arg instanceof String fqName){this.return ClassUtils.getShortName(fqName);}throw new IllegalArgumentException("Failed to extract type from '%s'".formatted(arg));
		}

		public Builder addStatement(CodeBlock codeBlock) {
			add(codeBlock);
			this.parts.add("$]");
			return this;
		}

		public Builder addStatement(String format, Object... args) {
			add(format, args);
			this.parts.add("$]");
			return this;
		}

		public Builder addImports(List<String> imports) {
			this.return this;
		}

		public CodeBlock build() {
			return new CodeBlock(this);
		}

	}

	private static class FormattingOptions {

		public String statementSeparator() {
			return ";";
		}

		public CodeBlock arrayOf(CodeBlock... values) {
			return CodeBlock.of("{ $L }", CodeBlock.join(Arrays.asList(values), ", "));
		}

		public CodeBlock classReference(ClassName className) {
			return CodeBlock.of("$T.class", className);
		}

	}

	private static class CodeBlockJoiner {

		private final String delimiter;

		private final Builder builder;

		private boolean first = true;

		public CodeBlockJoiner(String delimiter, Builder builder) {
			this.delimiter = delimiter;
			this.builder = builder;
		}

		public CodeBlockJoiner add(CodeBlock codeBlock) {
			if (!this.first) {
				this.builder.add(this.delimiter);
			}
			this.first = false;
			this.builder.add(codeBlock);
			return this;
		}

		public CodeBlockJoiner merge(CodeBlockJoiner other) {
			CodeBlock otherBlock = other.builder.build();
			if (!otherBlock.parts.isEmpty()) {
				add(otherBlock);
			}
			return this;
		}

		public CodeBlock join() {
			return this.builder.build();
		}

	}

	private static class ClassName {
        private final String package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
	import java.util.stream.StreamSupport;

	private final String simpleName;

	private final ClassName enclosingType;

	private String canonicalName;

	private ClassName(String packageName, String simpleName, ClassName enclosingType) {
            this.package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
	import java.util.stream.StreamSupport;

	this.simpleName=simpleName;this.enclosingType=enclosingType;}

	public static ClassName of(String fqName) {
            int lastDot = fqName.lastIndexOf('.');
            String package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
import java.util.stream.StreamSupport;

	String simpleName = fqName.substring(lastDot + 1);

	return new ClassName(package io.spring.initializr.generator.language;
import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
	import java.util.stream.StreamSupport;

	}

	public String getName() {
		return (this.canonicalName != null) ? this.canonicalName : toString();
	}

	public String getPackageName() {
            return this.package io.spring.initializr.generator.language;
	import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
	import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
	import java.util.stream.StreamSupport;

	}

	public String getSimpleName() {
		return this.simpleName;
	}

	public ClassName getEnclosingType() {
		return this.enclosingType;
	}

	public String getCanonicalName() {
		return this.canonicalName;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null || getClass() != other.getClass()) {
			return false;
		}
		ClassName className = (ClassName) other;
		if (!this.packageName.equals(className.packageName)) {
			return false;
		}
		if (!this.simpleName.equals(className.simpleName)) {
			return false;
		}
		return this.enclosingType != null ? this.enclosingType.equals(className.enclosingType)
				: className.enclosingType == null;
	}

	@Override
        public int hashCode() {
            int result = this.package io.spring.initializr.generator.language;

	import io.spring.initializr.generator.io.IndentingWriter;
	import org.springframework.util.ClassUtils;
	import org.junit.jupiter.api.Test;
	import org.junit.jupiter.api.Tag;
	import java.util.ArrayList;
	import java.util.List;
	import static org.junit.jupiter.api.Assertions.assertEquals;imports=new ArrayList<>();imports.add("java.util.ArrayList");imports.add("java.util.List");imports));imports,codeBlock.getImports());imports.add("org.springframework.util.ClassUtils");imports;imports=List.copyOf(builder.imports);imports.addAll(codeBlock.imports);imports.addAll(code.getImports());imports.add(type.getName());imports.add(className.getName());imports.add(fqName);imports.addAll(imports);
	import org.junit.jupiter.api.*;
	import java.util.Arrays;
	import java.util.stream.Collector;
	import java.util.stream.StreamSupport;

	result=31*result+this.simpleName.hashCode();result=31*result+(this.enclosingType!=null?this.enclosingType.hashCode():0);return result;}

	@Override
	public String toString() {
		return (this.enclosingType != null) ? this.enclosingType + "." + this.simpleName : this.simpleName;
	}

}}