/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getTypeDeclarations_b80d3244a4
ROOST_METHOD_SIG_HASH=getTypeDeclarations_8b718569e6

```java
Scenario 1: Verify that getTypeDeclarations returns an unmodifiable list of type declarations.

  Details:
    TestName: returnsUnmodifiableList
    Description: This test ensures that the getTypeDeclarations method returns an unmodifiable list of type declarations. It checks that the returned list cannot be modified by attempting to add or remove elements.

  Execution:
    Arrange: Create a CompilationUnit instance and add some type declarations using the createTypeDeclaration method.
    Act: Call the getTypeDeclarations method and attempt to modify the returned list.
    Assert: Verify that UnsupportedOperationException is thrown when attempting to modify the list.

  Validation:
    The assertion aims to verify that the list returned by getTypeDeclarations is indeed unmodifiable, ensuring that it cannot be altered after creation. This is important for maintaining the integrity of the type declarations list.

Scenario 2: Verify that getTypeDeclarations returns an empty list when no type declarations are present.

  Details:
    TestName: returnsEmptyListWhenNoTypeDeclarations
    Description: This test checks that the getTypeDeclarations method returns an empty list when no type declarations have been added to the CompilationUnit instance.

  Execution:
    Arrange: Create a CompilationUnit instance without adding any type declarations.
    Act: Call the getTypeDeclarations method.
    Assert: Verify that the returned list is empty.

  Validation:
    The assertion ensures that the method correctly handles the case where no type declarations exist, returning an empty list. This helps in validating the initial state of the CompilationUnit instance.

Scenario 3: Verify that getTypeDeclarations returns a list with the correct number of type declarations.

  Details:
    TestName: returnsListWithCorrectNumberOfTypeDeclarations
    Description: This test ensures that the getTypeDeclarations method returns a list containing the correct number of type declarations that have been added to the CompilationUnit instance.

  Execution:
    Arrange: Create a CompilationUnit instance and add a specific number of type declarations using the createTypeDeclaration method.
    Act: Call the getTypeDeclarations method.
    Assert: Verify that the size of the returned list matches the number of type declarations added.

  Validation:
    The assertion checks that the method accurately reflects the number of type declarations added, ensuring the list's integrity and correctness.

Scenario 4: Verify that getTypeDeclarations returns the same list on subsequent calls.

  Details:
    TestName: returnsSameListOnSubsequentCalls
    Description: This test ensures that the getTypeDeclarations method returns the same unmodifiable list on subsequent calls, even if the original type declarations list is modified.

  Execution:
    Arrange: Create a CompilationUnit instance and add some type declarations using the createTypeDeclaration method.
    Act: Call the getTypeDeclarations method multiple times.
    Assert: Verify that the returned lists are the same instance.

  Validation:
    The assertion ensures that the method returns the same unmodifiable list on subsequent calls, even if the original type declarations list is modified. This is crucial for maintaining consistency in the returned list.

Scenario 5: Verify that getTypeDeclarations returns a list with the correct type declarations.

  Details:
    TestName: returnsListWithCorrectTypeDeclarations
    Description: This test ensures that the getTypeDeclarations method returns a list containing the correct type declarations that have been added to the CompilationUnit instance.

  Execution:
    Arrange: Create a CompilationUnit instance and add specific type declarations using the createTypeDeclaration method.
    Act: Call the getTypeDeclarations method.
    Assert: Verify that the returned list contains the same type declarations that were added.

  Validation:
    The assertion checks that the method accurately reflects the type declarations added to the list, ensuring the list's correctness and consistency.

```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.springframework.util.Assert;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;

class CompilationUnitGetTypeDeclarationsTest {

	@Test
	@Tag("valid")
	public void returnsUnmodifiableList() {
		CompilationUnit<String> compilationUnit = new CompilationUnit<>("com.example", "TestUnit");
		compilationUnit.createTypeDeclaration("Type1");
		compilationUnit.createTypeDeclaration("Type2");
		List<String> typeDeclarations = compilationUnit.getTypeDeclarations();
		assertThrows(UnsupportedOperationException.class, () -> typeDeclarations.add("Type3"));
		assertThrows(UnsupportedOperationException.class, () -> typeDeclarations.remove(0));
	}

	@Test
	@Tag("valid")
	public void returnsEmptyListWhenNoTypeDeclarations() {
		CompilationUnit<String> compilationUnit = new CompilationUnit<>("com.example", "TestUnit");
		List<String> typeDeclarations = compilationUnit.getTypeDeclarations();
		assertTrue(typeDeclarations.isEmpty());
	}

	@Test
	@Tag("valid")
	public void returnsListWithCorrectNumberOfTypeDeclarations() {
		CompilationUnit<String> compilationUnit = new CompilationUnit<>("com.example", "TestUnit");
		compilationUnit.createTypeDeclaration("Type1");
		compilationUnit.createTypeDeclaration("Type2");
		compilationUnit.createTypeDeclaration("Type3");
		List<String> typeDeclarations = compilationUnit.getTypeDeclarations();
		assertEquals(3, typeDeclarations.size());
	}

	@Test
	@Tag("valid")
	public void returnsSameListOnSubsequentCalls() {
		CompilationUnit<String> compilationUnit = new CompilationUnit<>("com.example", "TestUnit");
		compilationUnit.createTypeDeclaration("Type1");
		List<String> typeDeclarations1 = compilationUnit.getTypeDeclarations();
		List<String> typeDeclarations2 = compilationUnit.getTypeDeclarations();
		assertSame(typeDeclarations1, typeDeclarations2);
	}

	@Test
	@Tag("valid")
	public void returnsListWithCorrectTypeDeclarations() {
		CompilationUnit<String> compilationUnit = new CompilationUnit<>("com.example", "TestUnit");
		compilationUnit.createTypeDeclaration("Type1");
		compilationUnit.createTypeDeclaration("Type2");
		List<String> typeDeclarations = compilationUnit.getTypeDeclarations();
		assertTrue(typeDeclarations.contains("Type1"));
		assertTrue(typeDeclarations.contains("Type2"));
	}

}