/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=createTypeDeclaration_479578924d
ROOST_METHOD_SIG_HASH=createTypeDeclaration_4b9e5626f3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void emptyTypeDeclaration() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    compilationUnit.createTypeDeclaration("Test");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(KotlinModifier.PUBLIC, KotlinModifier.ABSTRACT);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "abstract class Test");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithSuperClass() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.TestParent", "", "class Test : TestParent()");
}
"
    "@Test
@Test
void shouldImplementInterfaces() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "", "class Test : Interface1, Interface2");
}
"
    "@Test
@Test
void shouldExtendAndImplement() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "import com.example.build.TestParent", "", "class Test : TestParent(), Interface1, Interface2");
}
"
    "@Test
@Test
void function() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("reverse").returning("java.lang.String").parameters(Parameter.of("echo", String.class)).body(CodeBlock.ofStatement("return echo.reversed()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    fun reverse(echo: String): String {", "        return echo.reversed()", "    }", "", "}");
}
"
    "@Test
@Test
void functionModifiers() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("toString").modifiers(KotlinModifier.OVERRIDE, KotlinModifier.PUBLIC, KotlinModifier.OPEN).returning("java.lang.String").body(CodeBlock.ofStatement("return super.toString()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    open override fun toString(): String {", "        return super.toString()", "    }", "", "}");
}
"
    "@Test
@Test
void valProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("java.lang.String").emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    val testProp: String", "", "}");
}
"
    "@Test
@Test
void valPropertyImport() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("com.example.another.One").emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.One", "", "class Test {", "", "    val testProp: One", "", "}");
}
"
    "@Test
@Test
void valGetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a TEST")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("withGetter").returning("java.lang.String").getter().withBody(CodeBlock.of("testProp.toLowerCase()")).buildAccessor().emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    val testProp: String = \"This is a TEST\"", "", "    val withGetter: String", "        get() = testProp.toLowerCase()", "", "}");
}
"
    "@Test
@Test
void varProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "", "}");
}
"
    "@Test
@Test
void varSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        set", "", "}");
}
"
    "@Test
@Test
void varAnnotateSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().withAnnotation(ClassName.of("org.springframework.beans.factory.annotation.Autowired")).buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        @Autowired set", "", "}");
}
"
    "@Test
@Test
void varProperties() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("Int").value(CodeBlock.of("42")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testDouble").returning("Double").value(CodeBlock.of("1986.0")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testFloat").value(CodeBlock.of("99.999f")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testLong").returning("Long").value(CodeBlock.of("1986L")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: Int = 42", "", "    var testDouble: Double = 1986.0", "", "    var testFloat = 99.999f", "", "    var testLong: Long = 1986L", "", "}");
}
"
    "@Test
@Test
void varEmptyProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("Int").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: Int", "", "}");
}
"
    "@Test
@Test
void varLateinitProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").modifiers(KotlinModifier.LATEINIT).returning("Int").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    lateinit var testProp: Int", "", "}");
}
"
    "@Test
@Test
void importsFromSamePackageAreDiscarded() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("another").returning("com.example.Another").empty());
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("sibling").returning("com.example.Sibling").empty());
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("external").returning("com.example.another.External").empty());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).doesNotContain("import com.example.Another").doesNotContain("import com.example.Sibling").contains("import com.example.another.External");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    compilationUnit.addTopLevelFunction(KotlinFunctionDeclaration.function("main").parameters(Parameter.of("args", "Array<String>")).body(CodeBlock.ofStatement("$T<$L>(*args)", "org.springframework.boot.runApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.autoconfigure.SpringBootApplication", "import org.springframework.boot.runApplication", "", "@SpringBootApplication", "class Test", "", "fun main(args: Array<String>) {", "    runApplication<Test>(*args)", "}");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.kt");
}
"
    "@Test
@Test
void functionWithSimpleAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    KotlinFunctionDeclaration function = KotlinFunctionDeclaration.function("something").body(CodeBlock.of(""));
    function.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addFunctionDeclaration(function);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.test.TestAnnotation", "", "class Test {", "", "    @TestAnnotation", "    fun something() {", "    }", "", "}");
}
"
    "@Test
@Test
void functionWithParameterAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("something").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    fun something(@Service service: MyService) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
@Test
void emptyTypeDeclaration() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    compilationUnit.createTypeDeclaration("Test");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "}");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithModifiers() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PUBLIC | Modifier.ABSTRACT);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "abstract class Test {", "", "}");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithSuperClass() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.TestParent", "", "class Test extends TestParent {", "", "}");
}
"
    "@Test
@Test
void shouldAddImplements() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "", "class Test implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void shouldAddExtendsAndImplements() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "import com.example.build.TestParent", "", "class Test extends TestParent implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void method() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("trim").returning("java.lang.String").parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    String trim(String value) {", "        value.trim()", "    }", "", "}");
}
"
    "@Test
@Test
void importsFromSamePackageAreDiscarded() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(GroovyFieldDeclaration.field("another").returning("com.example.Another"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("sibling").returning("com.example.Sibling"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("external").returning("com.example.another.External"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).doesNotContain("import com.example.Another").doesNotContain("import com.example.Sibling").contains("import com.example.another.External");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(GroovyMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.SpringApplication", "import org.springframework.boot.autoconfigure.SpringBootApplication", "", "@SpringBootApplication", "class Test {", "", "    static void main(String[] args) {", "        SpringApplication.run(Test, args)", "    }", "", "}");
}
"
    "@Test
@Test
void field() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testString").returning("java.lang.String"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    String testString", "", "}");
}
"
    "@Test
@Test
void fieldsWithValues() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testNoInit").returning("boolean"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testInteger").value("42").returning("java.lang.Integer"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testDouble").modifiers(Modifier.PRIVATE).value("1986.0").returning("double"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testLong").value("1986L").returning("long"));
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testNullBoolean").value(null).returning("java.lang.Boolean"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    boolean testNoInit", "", "    Integer testInteger = 42", "", "    private double testDouble = 1986.0", "", "    long testLong = 1986L", "", "    Boolean testNullBoolean = null", "", "}");
}
"
    "@Test
@Test
void privateField() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testString").modifiers(Modifier.PRIVATE).returning("java.lang.String"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    private String testString", "", "}");
}
"
    "@Test
@Test
void fieldImport() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(GroovyFieldDeclaration.field("testString").modifiers(Modifier.PUBLIC).returning("com.example.another.One"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.One", "", "class Test {", "", "    public One testString", "", "}");
}
"
    "@Test
@Test
void fieldAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    GroovyFieldDeclaration field = GroovyFieldDeclaration.field("testString").returning("java.lang.String");
    field.annotations().add(ClassName.of("org.springframework.beans.factory.annotation.Autowired"));
    test.addFieldDeclaration(field);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.beans.factory.annotation.Autowired", "", "class Test {", "", "    @Autowired", "    String testString", "", "}");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.groovy");
}
"
    "@Test
@Test
void methodWithSimpleAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    GroovyMethodDeclaration method = GroovyMethodDeclaration.method("something").returning("void").parameters().body(CodeBlock.of(""));
    method.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addMethodDeclaration(method);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.test.TestAnnotation", "", "class Test {", "", "    @TestAnnotation", "    void something() {", "    }", "", "}");
}
"
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void emptyTypeDeclaration() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    compilationUnit.createTypeDeclaration("Test");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "class Test {", "", "}");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithModifiers() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PROTECTED | Modifier.ABSTRACT);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "protected abstract class Test {", "", "}");
}
"
    "@Test
@Test
void emptyTypeDeclarationWithSuperClass() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.build.TestParent;", "", "class Test extends TestParent {", "", "}");
}
"
    "@Test
@Test
void shouldAddImplements() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.build.Interface1;", "import com.example.build.Interface2;", "", "class Test implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void shouldAddExtendsAndImplements() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.build.Interface1;", "import com.example.build.Interface2;", "import com.example.build.TestParent;", "", "class Test extends TestParent implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void method() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("trim").returning("java.lang.String").modifiers(Modifier.PUBLIC).parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("return value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "class Test {", "", "    public String trim(String value) {", "        return value.trim();", "    }", "", "}");
}
"
    "@Test
@Test
void field() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PUBLIC);
    test.addFieldDeclaration(JavaFieldDeclaration.field("testString").modifiers(Modifier.PRIVATE).returning("java.lang.String"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "public class Test {", "", "    private String testString;", "", "}");
}
"
    "@Test
@Test
void fieldImport() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(JavaFieldDeclaration.field("testString").modifiers(Modifier.PUBLIC).returning("com.another.One"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.another.One;", "", "class Test {", "", "    public One testString;", "", "}");
}
"
    "@Test
@Test
void fieldAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PUBLIC);
    JavaFieldDeclaration field = JavaFieldDeclaration.field("testString").modifiers(Modifier.PRIVATE).returning("java.lang.String");
    field.annotations().add(ClassName.of("org.springframework.beans.factory.annotation.Autowired"));
    test.addFieldDeclaration(field);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import org.springframework.beans.factory.annotation.Autowired;", "", "public class Test {", "", "    @Autowired", "    private String testString;", "", "}");
}
"
    "@Test
@Test
void fields() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PUBLIC);
    test.addFieldDeclaration(JavaFieldDeclaration.field("testString").modifiers(Modifier.PRIVATE).value("\"Test String\"").returning("java.lang.String"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testChar").modifiers(Modifier.PRIVATE | Modifier.TRANSIENT).value("'\\u03a9'").returning("char"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testInt").modifiers(Modifier.PRIVATE | Modifier.FINAL).value(1337).returning("int"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testDouble").modifiers(Modifier.PRIVATE).value("3.14").returning("Double"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testLong").modifiers(Modifier.PRIVATE).value("1986L").returning("Long"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testFloat").modifiers(Modifier.PUBLIC).value("99.999f").returning("float"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("testBool").value("true").returning("boolean"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "public class Test {", "", "    private String testString = \"Test String\";", "", "    private transient char testChar = '\\u03a9';", "", "    private final int testInt = 1337;", "", "    private Double testDouble = 3.14;", "", "    private Long testLong = 1986L;", "", "    public float testFloat = 99.999f;", "", "    boolean testBool = true;", "", "}");
}
"
    "@Test
@Test
void importsFromSamePackageAreDiscarded() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFieldDeclaration(JavaFieldDeclaration.field("another").returning("com.example.Another"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("sibling").returning("com.example.Sibling"));
    test.addFieldDeclaration(JavaFieldDeclaration.field("external").returning("com.example.another.External"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).doesNotContain("import com.example.Another;").doesNotContain("import com.example.Sibling;").contains("import com.example.another.External;");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(JavaMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L.class, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import org.springframework.boot.SpringApplication;", "import org.springframework.boot.autoconfigure.SpringBootApplication;", "", "@SpringBootApplication", "class Test {", "", "    public static void main(String[] args) {", "        SpringApplication.run(Test.class, args);", "    }", "", "}");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.java");
}
"
    "@Test
@Test
void methodWithSimpleAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    JavaMethodDeclaration method = JavaMethodDeclaration.method("something").returning("void").parameters().body(CodeBlock.of(""));
    method.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addMethodDeclaration(method);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.test.TestAnnotation;", "", "class Test {", "", "    @TestAnnotation", "    void something() {", "    }", "", "}");
}
"
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.another.MyService;", "import com.example.stereotype.Service;", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"```java
Scenario 1: Test Creation of Type Declaration with Valid Name

Details:
  TestName: validTypeDeclarationCreation
  Description: This test checks that a valid type declaration can be created and added to the typeDeclarations list.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a valid name.
  Assert: Verify that the type declaration is added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Test Creation of Type Declaration with Null Name

Details:
  TestName: typeDeclarationCreationWithNullName
  Description: This test checks that the method throws an IllegalArgumentException when a null name is provided.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a null name.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Test Creation of Type Declaration with Empty Name

Details:
  TestName: typeDeclarationCreationWithEmptyName
  Description: This test checks that the method throws an IllegalArgumentException when an empty name is provided.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with an empty name.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Test Creation of Type Declaration with Existing Name

Details:
  TestName: typeDeclarationCreationWithExistingName
  Description: This test checks that the method does not add a duplicate type declaration to the typeDeclarations list.

Execution:
  Arrange: Create an instance of the CompilationUnit class and add a type declaration with a specific name.
  Act: Invoke the createTypeDeclaration method with the same name.
  Assert: Verify that the typeDeclarations list still contains only one entry with the specific name.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Test Creation of Multiple Type Declarations

Details:
  TestName: multipleTypeDeclarationsCreation
  Description: This test checks that multiple type declarations can be created and added to the typeDeclarations list.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method multiple times with different names.
  Assert: Verify that all type declarations are added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Test Type Declarations List Integrity

Details:
  TestName: typeDeclarationsListIntegrity
  Description: This test checks that the typeDeclarations list remains unmodifiable after creation.

Execution:
  Arrange: Create an instance of the CompilationUnit class and add a type declaration.
  Act: Attempt to modify the typeDeclarations list directly.
  Assert: Verify that an UnsupportedOperationException is thrown.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: Test Creation of Type Declaration with Special Characters in Name

Details:
  TestName: typeDeclarationCreationWithSpecialCharacters
  Description: This test checks that a type declaration can be created with a name containing special characters.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a name containing special characters.
  Assert: Verify that the type declaration is added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 8: Test Creation of Type Declaration with Spaces in Name

Details:
  TestName: typeDeclarationCreationWithSpaces
  Description: This test checks that a type declaration can be created with a name containing spaces.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a name containing spaces.
  Assert: Verify that the type declaration is added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 9: Test Creation of Type Declaration with Long Name

Details:
  TestName: typeDeclarationCreationWithLongName
  Description: This test checks that a type declaration can be created with a very long name.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a very long name.
  Assert: Verify that the type declaration is added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 10: Test Creation of Type Declaration with Name Containing Non-ASCII Characters

Details:
  TestName: typeDeclarationCreationWithNonAsciiCharacters
  Description: This test checks that a type declaration can be created with a name containing non-ASCII characters.

Execution:
  Arrange: Create an instance of the CompilationUnit class.
  Act: Invoke the createTypeDeclaration method with a name containing non-ASCII characters.
  Assert: Verify that the type declaration is added to the typeDeclarations list.

Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.springframework.util.Assert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

public class CompilationUnitCreateTypeDeclarationTest {

	private CompilationUnit compilationUnit;

	@BeforeEach
	public void setUp() {
		this.compilationUnit = new CompilationUnit("io.spring.initializr.generator.language", "CompilationUnit");
	}

	@Test
	@Tag("valid")
	public void validTypeDeclarationCreation() {
		String name = "ValidType";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		assertNotNull(typeDeclaration);
		assertEquals(name, ((CompilationUnit) typeDeclaration).getName());
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration));
	}

	@Test
	@Tag("invalid")
	public void typeDeclarationCreationWithNullName() {
		assertThrows(IllegalArgumentException.class, () -> {
			compilationUnit.createTypeDeclaration(null);
		});
	}

	@Test
	@Tag("invalid")
	public void typeDeclarationCreationWithEmptyName() {
		assertThrows(IllegalArgumentException.class, () -> {
			compilationUnit.createTypeDeclaration("");
		});
	}

	@Test
	@Tag("valid")
	public void typeDeclarationCreationWithExistingName() {
		String name = "ExistingType";
		Object typeDeclaration1 = compilationUnit.createTypeDeclaration(name);
		Object typeDeclaration2 = compilationUnit.createTypeDeclaration(name);
		assertEquals(typeDeclaration1, typeDeclaration2);
		assertEquals(1, compilationUnit.getTypeDeclarations().size());
	}

	@Test
	@Tag("valid")
	public void multipleTypeDeclarationsCreation() {
		String name1 = "Type1";
		String name2 = "Type2";
		String name3 = "Type3";
		Object typeDeclaration1 = compilationUnit.createTypeDeclaration(name1);
		Object typeDeclaration2 = compilationUnit.createTypeDeclaration(name2);
		Object typeDeclaration3 = compilationUnit.createTypeDeclaration(name3);
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration1));
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration2));
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration3));
		assertEquals(3, compilationUnit.getTypeDeclarations().size());
	}

	@Test
	@Tag("integration")
	public void typeDeclarationsListIntegrity() {
		String name = "Type";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		List<Object> typeDeclarations = compilationUnit.getTypeDeclarations();
		assertThrows(UnsupportedOperationException.class, () -> {
			typeDeclarations.add(new Object());
		});
	}

	@Test
	@Tag("valid")
	public void typeDeclarationCreationWithSpecialCharacters() {
		String name = "Type@#$%^&*()";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		assertNotNull(typeDeclaration);
		assertEquals(name, ((CompilationUnit) typeDeclaration).getName());
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration));
	}

	@Test
	@Tag("valid")
	public void typeDeclarationCreationWithSpaces() {
		String name = "Type With Spaces";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		assertNotNull(typeDeclaration);
		assertEquals(name, ((CompilationUnit) typeDeclaration).getName());
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration));
	}

	@Test
	@Tag("boundary")
	public void typeDeclarationCreationWithLongName() {
		String name = "ThisIsAVeryLongNameThatExceedsTheNormalLengthAndIsMeantToTestTheBoundaryConditionsOfTheSystem";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		assertNotNull(typeDeclaration);
		assertEquals(name, ((CompilationUnit) typeDeclaration).getName());
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration));
	}

	@Test
	@Tag("valid")
	public void typeDeclarationCreationWithNonAsciiCharacters() {
		String name = "TypeWithNonAsciiCharacters日本語";
		Object typeDeclaration = compilationUnit.createTypeDeclaration(name);
		assertNotNull(typeDeclaration);
		assertEquals(name, ((CompilationUnit) typeDeclaration).getName());
		assertTrue(compilationUnit.getTypeDeclarations().contains(typeDeclaration));
	}

}