/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=of_bd52bd1601
ROOST_METHOD_SIG_HASH=of_ca4da70227

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationTests.java
Tests:
    "@Test
@Test
void annotationWithInvalidParameterValue() {
    assertThatIllegalArgumentException().isThrownBy(() -> Annotation.of(ClassName.of("com.example.Test")).set("test", new StringWriter())).withMessage("Incompatible type. Found: 'java.io.StringWriter', required: primitive, String, Class, an Enum, an Annotation, or a CodeBlock");
}
"
    "@Test
@Test
void annotationWithMixedParameterValues() {
    assertThatIllegalArgumentException().isThrownBy(() -> Annotation.of(ClassName.of("com.example.Test")).set("test", "value", true)).withMessage("Parameter value must not have mixed types, got [STRING, PRIMITIVE]");
}
"
    "@Test
@Test
void annotationWithAmendedValueAndTypeMismatch() {
    assertThatIllegalArgumentException().isThrownBy(() -> Annotation.of(ClassName.of("com.example.Test")).set("test", "value").add("test", true)).withMessage("Incompatible type. 'STRING' is not compatible with 'PRIMITIVE'");
}
"
    "@Test
@Test
void annotationWithNoAttribute() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).build();
    assertThat(write(test)).isEqualTo("@Test");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@ParameterizedTest
@MethodSource("parameters")
void annotationWithPrimitives(Object parameter, String expectedCode) {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", parameter).build();
    assertThat(write(test)).isEqualTo("@Test(test = " + expectedCode + ")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
static Stream<Arguments> parameters() {
    return Stream.of(Arguments.arguments(1, "1"), Arguments.arguments(0x4f, "79"), Arguments.arguments((short) 4, "4"), Arguments.arguments(500L, "500"), Arguments.arguments((float) 3.14, "3.14"), Arguments.arguments(3.156, "3.156"), Arguments.arguments(true, "true"), Arguments.arguments('t', "'t'"));
}
"
    "@Test
@Test
void annotationWithString() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", "value").build();
    assertThat(write(test)).isEqualTo("@Test(test = \"value\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithClass() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", Test.class).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithClassName() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ClassName.of(Test.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = Test.class)");
    assertThat(test.getImports()).containsOnly("com.example.Test", Test.class.getName());
}
"
    "@Test
@Test
void annotationWithTypeReferenceInvokeConfiguredFormattingOptions() {
    ClassName typeReference = ClassName.of("com.example.Another");
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.classReference(typeReference)).willReturn(CodeBlock.of("$T::class", typeReference));
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", typeReference).build();
    assertThat(write(test, options)).isEqualTo("@Test(test = Another::class)");
    verify(options).classReference(typeReference);
    assertThat(test.getImports()).containsOnly("com.example.Test", typeReference.getName());
}
"
    "@Test
@Test
void annotationWithEnum() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", ChronoUnit.CENTURIES).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithEnumCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", CodeBlock.of("$T.CENTURIES", ChronoUnit.class)).build();
    assertThat(write(test)).isEqualTo("@Test(test = ChronoUnit.CENTURIES)");
    assertThat(test.getImports()).containsOnly("com.example.Test", ChronoUnit.class.getName());
}
"
    "@Test
@Test
void annotationWithNestedAnnotation() {
    Annotation nested = Annotation.of(ClassName.of("com.example.Nested")).set("counter", 42).build();
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("test", nested).build();
    assertThat(write(test)).isEqualTo("@Test(test = @Nested(counter = 42))");
    assertThat(test.getImports()).containsOnly("com.example.Test", "com.example.Nested");
}
"
    "@Test
@Test
void annotationWithOnlyValueUsesShortcut() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("value", "test").build();
    assertThat(write(test)).isEqualTo("@Test(\"test\")");
    assertThat(test.getImports()).containsOnly("com.example.Test");
}
"
    "@Test
@Test
void annotationWithSeveralParameters() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("enabled", false).set("counter", 42).build();
    assertThat(write(test)).isEqualTo("@Test(enabled = false, counter = 42)");
}
"
    "@Test
@Test
void annotationWithParameterArray() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("counters", 2, 4, 8, 10).build();
    assertThat(write(test)).isEqualTo("@Test(counters = { 2, 4, 8, 10 })");
}
"
    "@Test
@Test
void annotationWithParameterArrayAsValueUsesShortcut() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("value", 2, 4, 8, 10).build();
    assertThat(write(test)).isEqualTo("@Test({ 2, 4, 8, 10 })");
}
"
    "@Test
@Test
void annotationWithParameterClassAndCodeBlock() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).set("types", StringWriter.class, CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"
    "@Test
@Test
void annotationWithAmendedValues() {
    Annotation test = Annotation.of(ClassName.of("com.example.Test")).add("types", StringWriter.class).add("types", CodeBlock.of("$T.class", "com.example.io.AnotherWriter")).build();
    assertThat(write(test)).isEqualTo("@Test(types = { StringWriter.class, AnotherWriter.class })");
    assertThat(test.getImports()).containsOnly("com.example.Test", StringWriter.class.getName(), "com.example.io.AnotherWriter");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void shouldImplementInterfaces() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "", "class Test : Interface1, Interface2");
}
"
    "@Test
@Test
void shouldExtendAndImplement() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "import com.example.build.TestParent", "", "class Test : TestParent(), Interface1, Interface2");
}
"
    "@Test
@Test
void function() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("reverse").returning("java.lang.String").parameters(Parameter.of("echo", String.class)).body(CodeBlock.ofStatement("return echo.reversed()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    fun reverse(echo: String): String {", "        return echo.reversed()", "    }", "", "}");
}
"
    "@Test
@Test
void valGetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a TEST")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.val("withGetter").returning("java.lang.String").getter().withBody(CodeBlock.of("testProp.toLowerCase()")).buildAccessor().emptyValue());
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    val testProp: String = \"This is a TEST\"", "", "    val withGetter: String", "        get() = testProp.toLowerCase()", "", "}");
}
"
    "@Test
@Test
void varProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "", "}");
}
"
    "@Test
@Test
void varSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        set", "", "}");
}
"
    "@Test
@Test
void varAnnotateSetterProperty() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("java.lang.String").setter().withAnnotation(ClassName.of("org.springframework.beans.factory.annotation.Autowired")).buildAccessor().value(CodeBlock.of("$S", "This is a test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: String = \"This is a test\"", "        @Autowired set", "", "}");
}
"
    "@Test
@Test
void varProperties() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testProp").returning("Int").value(CodeBlock.of("42")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testDouble").returning("Double").value(CodeBlock.of("1986.0")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testFloat").value(CodeBlock.of("99.999f")));
    test.addPropertyDeclaration(KotlinPropertyDeclaration.var("testLong").returning("Long").value(CodeBlock.of("1986L")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    var testProp: Int = 42", "", "    var testDouble: Double = 1986.0", "", "    var testFloat = 99.999f", "", "    var testLong: Long = 1986L", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    compilationUnit.addTopLevelFunction(KotlinFunctionDeclaration.function("main").parameters(Parameter.of("args", "Array<String>")).body(CodeBlock.ofStatement("$T<$L>(*args)", "org.springframework.boot.runApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.autoconfigure.SpringBootApplication", "import org.springframework.boot.runApplication", "", "@SpringBootApplication", "class Test", "", "fun main(args: Array<String>) {", "    runApplication<Test>(*args)", "}");
}
"
    "@Test
@Test
void annotationWithClassArrayAttribute() throws IOException {
    List<String> lines = writeClassAnnotation("org.springframework.test.TestApplication", (builder) -> builder.set("target", ClassName.of("com.example.another.One"), ClassName.of("com.example.another.Two")));
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.One", "import com.example.another.Two", "import org.springframework.test.TestApplication", "", "@TestApplication(target = [One::class, Two::class])", "class Test");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.kt");
}
"
    "@Test
@Test
void functionWithSimpleAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    KotlinFunctionDeclaration function = KotlinFunctionDeclaration.function("something").body(CodeBlock.of(""));
    function.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addFunctionDeclaration(function);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.test.TestAnnotation", "", "class Test {", "", "    @TestAnnotation", "    fun something() {", "    }", "", "}");
}
"
    "@Test
@Test
void functionWithParameterAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("something").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    fun something(@Service service: MyService) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionPropertyTests.java
Tests:
    "@Test
@Test
void testStandardProperty() {
    assertThat(VersionProperty.of("spring-boot.version").toStandardFormat()).isEqualTo("spring-boot.version");
}
"
    "@Test
@Test
void testCamelCaseProperty() {
    assertThat(VersionProperty.of("spring-boot.version").toCamelCaseFormat()).isEqualTo("springBootVersion");
}
"
    "@Test
@Test
void testStandardPropertyWithNoSeparator() {
    assertThat(VersionProperty.of("springbootversion").toStandardFormat()).isEqualTo("springbootversion");
}
"
    "@Test
@Test
void testCamelCasePropertyWithNoSeparator() {
    assertThat(VersionProperty.of("springbootversion").toCamelCaseFormat()).isEqualTo("springbootversion");
}
"
    "@Test
@Test
void testInvalidPropertyUpperCase() {
    assertThatIllegalArgumentException().isThrownBy(() -> VersionProperty.of("Spring-boot.version"));
}
"
    "@Test
@Test
void testInvalidPropertyIllegalCharacter() {
    assertThatIllegalArgumentException().isThrownBy(() -> VersionProperty.of("spring-boot_version")).withMessageContaining("Unsupported character");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/ClassNameTests.java
Tests:
    "@Test
@Test
void classNameWithTopLevelClassName() {
    classNameWithTopLevelClass(ClassName.of("com.example.Example"));
}
"
    "@Test
@Test
void classNameWithTopLevelClass() {
    classNameWithTopLevelClass(ClassName.of(Example.class));
}
"
    "@Test
@Test
void classNameWithInnerClassName() {
    classNameWithInnerClass(ClassName.of("com.example.Example$Inner"));
}
"
    "@Test
@Test
void classNameWithInnerClass() {
    classNameWithInnerClass(ClassName.of(Inner.class));
}
"
    "@Test
@Test
void classNameWithNestedInnerClassName() {
    classNameWithNestedInnerClass(ClassName.of("com.example.Example$Inner$Nested"));
}
"
    "@Test
@Test
void classNameWithNestedInnerClass() {
    classNameWithNestedInnerClass(ClassName.of(Nested.class));
}
"
    "@Test
static Stream<Arguments> primitivesAndPrimitivesArray() {
    return Stream.of(Arguments.of(ClassName.of("boolean"), "boolean"), Arguments.of(ClassName.of("byte"), "byte"), Arguments.of(ClassName.of("short"), "short"), Arguments.of(ClassName.of("int"), "int"), Arguments.of(ClassName.of("long"), "long"), Arguments.of(ClassName.of("char"), "char"), Arguments.of(ClassName.of("float"), "float"), Arguments.of(ClassName.of("double"), "double"), Arguments.of(ClassName.of("boolean[]"), "boolean[]"), Arguments.of(ClassName.of("byte[]"), "byte[]"), Arguments.of(ClassName.of("short[]"), "short[]"), Arguments.of(ClassName.of("int[]"), "int[]"), Arguments.of(ClassName.of("long[]"), "long[]"), Arguments.of(ClassName.of("char[]"), "char[]"), Arguments.of(ClassName.of("float[]"), "float[]"), Arguments.of(ClassName.of("double[]"), "double[]"));
}
"
    "@Test
static Stream<Arguments> arrays() {
    return Stream.of(Arguments.of(ClassName.of("java.lang.Object[]"), "java.lang.Object[]"), Arguments.of(ClassName.of("java.lang.Integer[]"), "java.lang.Integer[]"), Arguments.of(ClassName.of("com.example.Test[]"), "com.example.Test[]"));
}
"
    "@Test
@Test
void classNameInRootPackage() {
    ClassName type = ClassName.of("MyRootClass");
    assertThat(type.getCanonicalName()).isEqualTo("MyRootClass");
    assertThat(type.getPackageName()).isEmpty();
}
"
    "@Test
@ParameterizedTest(name = "{0}")
@ValueSource(strings = { "com.example.Tes(t", "com.example..Test" })
void classNameWithInvalidClassName(String invalidClassName) {
    assertThatIllegalStateException().isThrownBy(() -> ClassName.of(invalidClassName)).withMessageContaining("Invalid class name");
}
"
    "@Test
@Test
void equalsWithIdenticalNameIsTrue() {
    assertThat(ClassName.of(String.class)).isEqualTo(ClassName.of("java.lang.String"));
}
"
    "@Test
@Test
void equalsWithNonClassNameIsFalse() {
    assertThat(ClassName.of(String.class)).isNotEqualTo("java.lang.String");
}
"
    "@Test
@Test
void toStringUsesCanonicalName() {
    assertThat(ClassName.of(String.class)).hasToString("java.lang.String");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void shouldAddImplements() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.build.Interface1;", "import com.example.build.Interface2;", "", "class Test implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void shouldAddExtendsAndImplements() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.build.Interface1;", "import com.example.build.Interface2;", "import com.example.build.TestParent;", "", "class Test extends TestParent implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void method() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("trim").returning("java.lang.String").modifiers(Modifier.PUBLIC).parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("return value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "class Test {", "", "    public String trim(String value) {", "        return value.trim();", "    }", "", "}");
}
"
    "@Test
@Test
void fieldAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.modifiers(Modifier.PUBLIC);
    JavaFieldDeclaration field = JavaFieldDeclaration.field("testString").modifiers(Modifier.PRIVATE).returning("java.lang.String");
    field.annotations().add(ClassName.of("org.springframework.beans.factory.annotation.Autowired"));
    test.addFieldDeclaration(field);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import org.springframework.beans.factory.annotation.Autowired;", "", "public class Test {", "", "    @Autowired", "    private String testString;", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(JavaMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L.class, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import org.springframework.boot.SpringApplication;", "import org.springframework.boot.autoconfigure.SpringBootApplication;", "", "@SpringBootApplication", "class Test {", "", "    public static void main(String[] args) {", "        SpringApplication.run(Test.class, args);", "    }", "", "}");
}
"
    "@Test
@Test
void annotationWithClassArrayAttribute() throws IOException {
    List<String> lines = writeClassAnnotation("org.springframework.test.TestApplication", (builder) -> builder.set("target", ClassName.of("com.another.One"), ClassName.of("com.another.Two")));
    assertThat(lines).containsExactly("package com.example;", "", "import com.another.One;", "import com.another.Two;", "import org.springframework.test.TestApplication;", "", "@TestApplication(target = { One.class, Two.class })", "class Test {", "", "}");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.java");
}
"
    "@Test
@Test
void methodWithSimpleAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    JavaMethodDeclaration method = JavaMethodDeclaration.method("something").returning("void").parameters().body(CodeBlock.of(""));
    method.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addMethodDeclaration(method);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.test.TestAnnotation;", "", "class Test {", "", "    @TestAnnotation", "    void something() {", "    }", "", "}");
}
"
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.another.MyService;", "import com.example.stereotype.Service;", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenBuildWriterTests.java
Tests:
    "@Test
@Test
void pomWithVersionProperties() {
    MavenBuild build = new MavenBuild();
    build.properties().version(VersionProperty.of("version.property", false), "1.2.3").version(VersionProperty.of("internal.property", true), "4.5.6").version("external.property", "7.8.9");
    generatePom(build, (pom) -> {
        assertThat(pom).textAtPath("/project/properties/version.property").isEqualTo("1.2.3");
        assertThat(pom).textAtPath("/project/properties/internal.property").isEqualTo("4.5.6");
        assertThat(pom).textAtPath("/project/properties/external.property").isEqualTo("7.8.9");
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/KotlinDslGradleBuildWriterTests.java
Tests:
    "@Test
@ParameterizedTest
@MethodSource("sourceCompatibilityParameters")
void gradleBuildWithSourceCompatibilities(String sourceCompatibility, String javaVersionConstant) {
    GradleBuild build = new GradleBuild();
    build.settings().sourceCompatibility(sourceCompatibility);
    assertThat(write(build)).contains("""
        java {
        	toolchain {
        		languageVersion = JavaLanguageVersion.of(%s)
        	}
        }
        """.formatted(javaVersionConstant));
}
"
    "@Test
static Stream<Arguments> sourceCompatibilityParameters() {
    return Stream.of(Arguments.arguments("1.8", "8"), Arguments.arguments("8", "8"), Arguments.arguments(null, "8"), Arguments.arguments("11", "11"), Arguments.arguments("17", "17"), Arguments.arguments("21", "21"), Arguments.arguments("22", "22"));
}
"
    "@Test
@Test
void gradleBuildWithVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("version.property", false), "1.2.3").version(VersionProperty.of("internal.property", true), "4.5.6").version("external.property", "7.8.9");
    assertThat(write(build)).contains("""
        extra["external.property"] = "7.8.9"
        extra["internalProperty"] = "4.5.6"
        extra["version.property"] = "1.2.3"
        """);
}
"
    "@Test
@Test
void gradleBuildWithExternalVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("acme", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofProperty(VersionProperty.of("acme.version", false))).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation("com.example:acme:${property("acme.version")}")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExtAndVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("test-version", true), "1.0").version("alpha-version", "0.1").property("myProperty", "42");
    assertThat(write(build)).contains("""
        extra["myProperty"] = 42
        extra["alpha-version"] = "0.1"
        extra["testVersion"] = "1.0"
        """);
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GroovyDslGradleBuildWriterTests.java
Tests:
    "@Test
@Test
void gradleBuildWithSourceCompatibility() {
    GradleBuild build = new GradleBuild();
    build.settings().sourceCompatibility("17");
    assertThat(write(build)).contains("""
        java {
        	toolchain {
        		languageVersion = JavaLanguageVersion.of(17)
        	}
        }
        """);
}
"
    "@Test
@Test
void gradleBuildWithVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("version.property", false), "1.2.3").version(VersionProperty.of("internal.property", true), "4.5.6").version("external.property", "7.8.9");
    assertThat(write(build)).contains("""
        ext {
        	set('external.property', "7.8.9")
        	set('internalProperty', "4.5.6")
        	set('version.property', "1.2.3")
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExternalVersionedDependency() {
    GradleBuild build = new GradleBuild();
    build.dependencies().add("acme", Dependency.withCoordinates("com.example", "acme").version(VersionReference.ofProperty(VersionProperty.of("acme.version", false))).scope(DependencyScope.COMPILE));
    assertThat(write(build)).contains("""
        dependencies {
        	implementation "com.example:acme:${property('acme.version')}"
        }""");
}
"
    "@Test
@Test
void gradleBuildWithExtAndVersionProperties() {
    GradleBuild build = new GradleBuild();
    build.properties().version(VersionProperty.of("test-version"), "1.0").version("alpha-version", "0.1").property("myProperty", "'42'");
    assertThat(write(build)).contains("""
        ext {
        	set('myProperty', '42')
        	set('alpha-version', "0.1")
        	set('testVersion', "1.0")
        }""");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionReferenceTests.java
Tests:
    "@Test
@Test
void ofPropertyWithVersionProperty() {
    VersionProperty property = VersionProperty.of("test.version", true);
    VersionReference reference = VersionReference.ofProperty(property);
    assertThat(reference.isProperty()).isTrue();
    assertThat(reference.getProperty()).isEqualTo(property);
    assertThat(reference.getValue()).isNull();
    assertThat(reference).hasToString("${test.version}");
}
"
    "@Test
@Test
void equalsWithDifferentPropertyScope() {
    assertThat(VersionReference.ofProperty(VersionProperty.of("test.version", false))).isNotEqualTo(VersionReference.ofProperty(VersionProperty.of("test.version", true)));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlockWithPlaceholderAndTooFewArguments() {
    assertThatIllegalArgumentException().isThrownBy(() -> CodeBlock.of("$T.doStuff()")).withMessage("Argument mismatch for '$T.doStuff()', expected at least 1 argument, got 0");
}
"
    "@Test
@Test
void codeBlockWithPlaceholderAndTooManyArguments() {
    assertThatIllegalArgumentException().isThrownBy(() -> CodeBlock.of("$T.doStuff()", String.class, Integer.class)).withMessage("Argument mismatch for '$T.doStuff()', expected 1 argument, got 2");
}
"
    "@Test
@Test
void codeBlockWithInvalidPlaceholder() {
    assertThatIllegalArgumentException().isThrownBy(() -> CodeBlock.of("$X.doStuff()", 123)).withMessage("Unsupported placeholder '$X' for '$X.doStuff()'");
}
"
    "@Test
@Test
void codeBlockWithTrailingDollarSign() {
    assertThatIllegalArgumentException().isThrownBy(() -> CodeBlock.of("doStuff()$")).withMessage("Should not end with '$': 'doStuff()$'");
}
"
    "@Test
@Test
void codeBlockWithStringPlaceholder() {
    CodeBlock code = CodeBlock.of("return myUtil.truncate($S)", "value");
    assertThat(writeJava(code)).isEqualTo("return myUtil.truncate(\"value\")");
}
"
    "@Test
@Test
void codeBlockWithStringPlaceholderAndDoubleQuote() {
    CodeBlock code = CodeBlock.of("return myUtil.truncate($S)", "va\"lue");
    assertThat(writeJava(code)).isEqualTo("return myUtil.truncate(\"va\\\"lue\")");
}
"
    "@Test
@Test
void codeBlockWithStringPlaceholderAndEscapedSingleQuote() {
    CodeBlock code = CodeBlock.of("return myUtil.truncate($S)", "va\'lue");
    assertThat(writeJava(code)).isEqualTo("return myUtil.truncate(\"va'lue\")");
}
"
    "@Test
@Test
void codeBlockWithLiteralPlaceholder() {
    CodeBlock code = CodeBlock.of("return $L.truncate(myString)", "myUtil");
    assertThat(writeJava(code)).isEqualTo("return myUtil.truncate(myString)");
}
"
    "@Test
@Test
void codeBlockWithLiteralPlaceHolderUsingCodeBlock() {
    CodeBlock code = CodeBlock.of("return myUtil.add($L, $L)", CodeBlock.of("1"), CodeBlock.of("2"));
    assertThat(writeJava(code)).isEqualTo("return myUtil.add(1, 2)");
}
"
    "@Test
@Test
void codeBlockWithLiteralPlaceHolderUsingNestedCodeBlock() {
    CodeBlock code = CodeBlock.of("return myUtil.add($L)", CodeBlock.of("$L, $L", CodeBlock.of("1"), CodeBlock.of("2")));
    assertThat(writeJava(code)).isEqualTo("return myUtil.add(1, 2)");
}
"
    "@Test
@Test
void codeBlockWithDollarSignPlaceholder() {
    CodeBlock code = CodeBlock.of("
    assertThat(writeJava(code)).isEqualTo("
}
"
    "@Test
@Test
void codeBlockWithEndOfStatementPlaceholderInvokeConfiguredFormattingOptions() {
    FormattingOptions options = mock(FormattingOptions.class);
    given(options.statementSeparator()).willReturn(";");
    CodeBlock code = CodeBlock.of("invoke(param)$]");
    assertThat(write(code, options)).isEqualToNormalizingNewlines("""
        invoke(param);
        """);
    verify(options).statementSeparator();
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", StringUtils.class);
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndClassNameAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", ClassName.of(StringUtils.class));
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndFullyQualifiedClassNameAddsImport() {
    CodeBlock code = CodeBlock.of("return $T.truncate(myString)", "com.example.StringUtils");
    assertThat(writeJava(code)).isEqualTo("return StringUtils.truncate(myString)");
    assertThat(code.getImports()).containsExactly("com.example.StringUtils");
}
"
    "@Test
@Test
void codeBlockWithTypePlaceholderAndNonResolvableType() {
    assertThatIllegalArgumentException().isThrownBy(() -> CodeBlock.of("return $T.truncate(myString)", true)).withMessageContaining("Failed to extract type from 'true'");
}
"
    "@Test
@Test
void codeBlockDoesNotAddNewLine() {
    CodeBlock code = CodeBlock.of("(123, 456)");
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlocksCanBeAdded() {
    CodeBlock code = CodeBlock.builder().add("(123").add(CodeBlock.of(", 456)")).build();
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithMultipleStatements() {
    CodeBlock code = CodeBlock.builder().addStatement("myInstance.sayHello(123)").addStatement(CodeBlock.of("myInstance.sayHello(456)")).build();
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        myInstance.sayHello(456);
        """);
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithParameterCodeBlockAddsImports() {
    CodeBlock code = CodeBlock.of("$L", CodeBlock.of("$T.truncate(myString)", ClassName.of(StringUtils.class)));
    assertThat(code.getImports()).containsExactly(StringUtils.class.getName());
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/gradle/GradleBuildWriterTests.java
Tests:
    "@Test
@Test
void gradleBuildWithSnippetAndImports() {
    GradleBuild build = new GradleBuild();
    build.snippets().add(Set.of("com.example.CustomTask"), (writer) -> writer.println("custom { }"));
    assertThat(write(build)).containsOnlyOnce("import com.example.CustomTask");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/container/docker/compose/ComposeServiceContainerTests.java
Tests:
    "@Test
@Test
void environmentIsMerged() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> service.imageAndTag("my-image").environment(Map.of("a", "aa", "z", "zz")));
    container.add("test", (service) -> service.environment(Map.of("a", "aaa", "b", "bb")));
    assertThat(container.values()).singleElement().satisfies((service) -> assertThat(service.getEnvironment()).containsExactly(entry("a", "aaa"), entry("b", "bb"), entry("z", "zz")));
}
"
    "@Test
@Test
void labelIsMerged() {
    ComposeServiceContainer container = new ComposeServiceContainer();
    container.add("test", (service) -> service.imageAndTag("my-image").labels(Map.of("a", "aa", "z", "zz")));
    container.add("test", (service) -> service.labels(Map.of("a", "aaa", "b", "bb")));
    assertThat(container.values()).singleElement().satisfies((service) -> assertThat(service.getLabels()).containsExactly(entry("a", "aaa"), entry("b", "bb"), entry("z", "zz")));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionRangeTests.java
Tests:
    "@Test
static Stream<Arguments> matchInRangeParameters() {
    return Stream.of(Arguments.arguments("1.2.2.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.2", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.M3", "[1.2.0.M1,1.2.0.RC1]"), Arguments.arguments("1.2.0-M3", "[1.2.0-M1,1.2.0-RC1]"), Arguments.arguments("1.2.0.RC1", "[1.2.0.M1,1.2.0.RC2]"), Arguments.arguments("1.2.0-RC1", "[1.2.0-M1,1.2.0-RC2]"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.2-SNAPSHOT", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.0", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.M1", "[1.2.0.M1,1.2.0.RC1]"), Arguments.arguments("1.2.0-M1", "[1.2.0-M1,1.2.0-RC1]"), Arguments.arguments("1.2.0.RC1", "[1.2.0.RC1,1.2.0.RC2]"), Arguments.arguments("1.2.0-RC1", "[1.2.0-RC1,1.2.0-RC2]"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "[1.2.2.BUILD-SNAPSHOT,1.2.5.RELEASE]"), Arguments.arguments("1.2.2-SNAPSHOT", "[1.2.2-SNAPSHOT,1.2.5]"), Arguments.arguments("1.2.5.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.5", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.M3", "[1.2.0.M1,1.2.0.M3]"), Arguments.arguments("1.2.0-M3", "[1.2.0-M1,1.2.0-M3]"), Arguments.arguments("1.2.0.RC2", "[1.2.0.RC1,1.2.0.RC2]"), Arguments.arguments("1.2.0-RC2", "[1.2.0-RC1,1.2.0-RC2]"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "[1.2.0.RELEASE,1.2.2.BUILD-SNAPSHOT]"), Arguments.arguments("1.2.2-SNAPSHOT", "[1.2.0,1.2.2-SNAPSHOT]"), Arguments.arguments("1.2.0.RELEASE", "1.2.0.RELEASE"), Arguments.arguments("1.2.0", "1.2.0"), Arguments.arguments("1.2.0.M3", "1.2.0.M3"), Arguments.arguments("1.2.0-M3", "1.2.0-M3"), Arguments.arguments("1.2.0.RC1", "1.2.0.RC1"), Arguments.arguments("1.2.0-RC1", "1.2.0-RC1"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "1.2.2.BUILD-SNAPSHOT"), Arguments.arguments("1.2.2-SNAPSHOT", "1.2.2-SNAPSHOT"), Arguments.arguments("1.2.5.RELEASE", "1.2.0.RELEASE"), Arguments.arguments("1.2.5", "1.2.0"), Arguments.arguments("2.2.0.M3", "1.2.0.M3"), Arguments.arguments("2.2.0-M3", "1.2.0-M3"), Arguments.arguments("1.4.0.RC1", "1.2.0.RC1"), Arguments.arguments("1.4.0-RC1", "1.2.0-RC1"), Arguments.arguments("1.3.2.BUILD-SNAPSHOT", "1.2.2.BUILD-SNAPSHOT"), Arguments.arguments("1.3.2-SNAPSHOT", "1.2.2-SNAPSHOT"));
}
"
    "@Test
static Stream<Arguments> matchOutRangeParameters() {
    return Stream.of(Arguments.arguments("1.1.9.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.1.9", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.6.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.6", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.M2", "[1.2.0.M3,1.2.0.RC1]"), Arguments.arguments("1.2.0-M2", "[1.2.0-M3,1.2.0-RC1]"), Arguments.arguments("1.2.0.M4", "[1.2.0.M1,1.2.0.M3]"), Arguments.arguments("1.2.0-M4", "[1.2.0-M1,1.2.0-M3]"), Arguments.arguments("1.2.0.RC1", "[1.2.0.RC2,1.2.0.RC3]"), Arguments.arguments("1.2.0-RC1", "[1.2.0-RC2,1.2.0-RC3]"), Arguments.arguments("1.2.0.RC4", "[1.2.0.RC2,1.2.0.RC3]"), Arguments.arguments("1.2.0-RC4", "[1.2.0-RC2,1.2.0-RC3]"), Arguments.arguments("1.1.9.BUILD-SNAPSHOT", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.1.9-SNAPSHOT", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.6.BUILD-SNAPSHOT", "[1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.6-SNAPSHOT", "[1.2.0,1.2.5]"), Arguments.arguments("1.2.0.RELEASE", "(1.2.0.RELEASE,1.2.5.RELEASE]"), Arguments.arguments("1.2.0", "(1.2.0,1.2.5]"), Arguments.arguments("1.2.0.M1", "(1.2.0.M1,1.2.0.RC1]"), Arguments.arguments("1.2.0-M1", "(1.2.0-M1,1.2.0-RC1]"), Arguments.arguments("1.2.0.RC1", "(1.2.0.RC1,1.2.0.RC2]"), Arguments.arguments("1.2.0-RC1", "(1.2.0-RC1,1.2.0-RC2]"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "(1.2.2.BUILD-SNAPSHOT,1.2.5.RELEASE]"), Arguments.arguments("1.2.2-SNAPSHOT", "(1.2.2-SNAPSHOT,1.2.5]"), Arguments.arguments("1.2.5.RELEASE", "[1.2.0.RELEASE,1.2.5.RELEASE)"), Arguments.arguments("1.2.5", "[1.2.0,1.2.5)"), Arguments.arguments("1.2.0.M3", "[1.2.0.M1,1.2.0.M3)"), Arguments.arguments("1.2.0-M3", "[1.2.0-M1,1.2.0-M3)"), Arguments.arguments("1.2.0.RC2", "[1.2.0.RC1,1.2.0.RC2)"), Arguments.arguments("1.2.0-RC2", "[1.2.0-RC1,1.2.0-RC2)"), Arguments.arguments("1.2.2.BUILD-SNAPSHOT", "[1.2.0.RELEASE,1.2.2.BUILD-SNAPSHOT)"), Arguments.arguments("1.2.2-SNAPSHOT", "[1.2.0,1.2.2-SNAPSHOT)"), Arguments.arguments("1.2.0.RELEASE", "1.2.1.RELEASE"), Arguments.arguments("1.2.0", "1.2.1"), Arguments.arguments("1.2.0.M2", "1.2.0.M3"), Arguments.arguments("1.2.0-M2", "1.2.0-M3"), Arguments.arguments("1.2.0.RC1", "1.2.0.RC2"), Arguments.arguments("1.2.0-RC1", "1.2.0-RC2"), Arguments.arguments("1.2.1.BUILD-SNAPSHOT", "1.2.2.BUILD-SNAPSHOT"), Arguments.arguments("1.2.1-SNAPSHOT", "1.2.2-SNAPSHOT"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/AnnotationContainerTests.java
Tests:
    "@Test
@Test
void hasWithNonMatchingAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.has(ClassName.of("com.example.Another"))).isFalse();
}
"
    "@Test
@Test
void addAnnotationSeveralTimeCanReplaceAttribute() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 42).build()));
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.set("value", Annotation.of(NESTED_CLASS_NAME).add("counter", 24).build()));
    assertThat(container.values()).singleElement().satisfies((annotation) -> {
        assertThat(annotation.getClassName()).isEqualTo(TEST_CLASS_NAME);
        assertThat(annotation.getImports()).containsOnly("com.example.Test", "com.example.Nested");
        assertThat(annotation.getAttributes()).singleElement().satisfies((attribute) -> {
            assertThat(attribute.getName()).isEqualTo("value");
            assertThat(attribute.getValues()).singleElement().isInstanceOfSatisfying(Annotation.class, (nested) -> {
                assertThat(nested.getClassName()).isEqualTo(NESTED_CLASS_NAME);
                assertThat(nested.getAttributes()).singleElement().satisfies((nestedAttribute) -> {
                    assertThat(nestedAttribute.getName()).isEqualTo("counter");
                    assertThat(nestedAttribute.getValues()).containsExactly(24);
                });
            });
        });
    });
}
"
    "@Test
@Test
void removeWithNonMatchingAnnotation() {
    AnnotationContainer container = new AnnotationContainer();
    container.add(TEST_CLASS_NAME, (annotation) -> annotation.add("value", "test"));
    assertThat(container.remove(ClassName.of("com.example.Another"))).isFalse();
    assertThat(container.isEmpty()).isFalse();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
@Test
void shouldAddImplements() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "", "class Test implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void shouldAddExtendsAndImplements() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.extend("com.example.build.TestParent");
    test.implement(List.of("com.example.build.Interface1", "com.example.build.Interface2"));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.build.Interface1", "import com.example.build.Interface2", "import com.example.build.TestParent", "", "class Test extends TestParent implements Interface1, Interface2 {", "", "}");
}
"
    "@Test
@Test
void method() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("trim").returning("java.lang.String").parameters(Parameter.of("value", String.class)).body(CodeBlock.ofStatement("value.trim()")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "class Test {", "", "    String trim(String value) {", "        value.trim()", "    }", "", "}");
}
"
    "@Test
@Test
void springBootApplication() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
    test.addMethodDeclaration(GroovyMethodDeclaration.method("main").modifiers(Modifier.PUBLIC | Modifier.STATIC).returning("void").parameters(Parameter.of("args", String[].class)).body(CodeBlock.ofStatement("$T.run($L, args)", "org.springframework.boot.SpringApplication", "Test")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.boot.SpringApplication", "import org.springframework.boot.autoconfigure.SpringBootApplication", "", "@SpringBootApplication", "class Test {", "", "    static void main(String[] args) {", "        SpringApplication.run(Test, args)", "    }", "", "}");
}
"
    "@Test
@Test
void fieldAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    GroovyFieldDeclaration field = GroovyFieldDeclaration.field("testString").returning("java.lang.String");
    field.annotations().add(ClassName.of("org.springframework.beans.factory.annotation.Autowired"));
    test.addFieldDeclaration(field);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import org.springframework.beans.factory.annotation.Autowired", "", "class Test {", "", "    @Autowired", "    String testString", "", "}");
}
"
    "@Test
@Test
void annotationWithClassArrayAttribute() throws IOException {
    List<String> lines = writeClassAnnotation("org.springframework.test.TestApplication", (builder) -> builder.set("target", ClassName.of("com.example.another.One"), ClassName.of("com.example.another.Two")));
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.One", "import com.example.another.Two", "import org.springframework.test.TestApplication", "", "@TestApplication(target = [ One, Two ])", "class Test {", "", "}");
}
"
    "@Test
private List<String> writeClassAnnotation(String annotationClassName, Consumer<Builder> annotation) throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.annotations().add(ClassName.of(annotationClassName), annotation);
    return writeSingleType(sourceCode, "com/example/Test.groovy");
}
"
    "@Test
@Test
void methodWithSimpleAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    GroovyMethodDeclaration method = GroovyMethodDeclaration.method("something").returning("void").parameters().body(CodeBlock.of(""));
    method.annotations().add(ClassName.of("com.example.test.TestAnnotation"));
    test.addMethodDeclaration(method);
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.test.TestAnnotation", "", "class Test {", "", "    @TestAnnotation", "    void something() {", "    }", "", "}");
}
"
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/version/VersionTests.java
Tests:
    "@Test
@Test
void orderVersionSchemeWithQualifiedVersions() {
    List<String> sortedVersions = Stream.of("2.3.0.BUILD-SNAPSHOT", "2.3.0.RC1", "2.3.0.M2", "2.3.0.M1", "2.3.0.RELEASE", "2.3.0.RC2").map(this::parse).sorted().map(Version::toString).collect(Collectors.toList());
    assertThat(sortedVersions).containsExactly("2.3.0.M1", "2.3.0.M2", "2.3.0.RC1", "2.3.0.RC2", "2.3.0.BUILD-SNAPSHOT", "2.3.0.RELEASE");
}
"
    "@Test
@Test
void orderVersionSchemeWithSemVer() {
    List<String> sortedVersions = Stream.of("2.3.0-SNAPSHOT", "2.3.0-RC1", "2.3.0-M2", "2.3.0-M1", "2.3.0", "2.3.0-RC2").map(this::parse).sorted().map(Version::toString).collect(Collectors.toList());
    assertThat(sortedVersions).containsExactly("2.3.0-M1", "2.3.0-M2", "2.3.0-RC1", "2.3.0-RC2", "2.3.0-SNAPSHOT", "2.3.0");
}
"
    "@Test
@Test
void orderVersionSchemeWithCalVer() {
    List<String> sortedVersions = Stream.of("2020.0.0-SNAPSHOT", "2020.0.0-RC1", "2020.0.0-M2", "2020.0.0-M1", "2020.0.0", "2020.0.0-RC2").map(this::parse).sorted().map(Version::toString).collect(Collectors.toList());
    assertThat(sortedVersions).containsExactly("2020.0.0-M1", "2020.0.0-M2", "2020.0.0-RC1", "2020.0.0-RC2", "2020.0.0-SNAPSHOT", "2020.0.0");
}
"Here are the test scenarios for the `of` method in the `Parameter` class:

```plaintext
Scenario 1: Valid Inputs for Name and Type

Details:
  TestName: validNameAndType
  Description: This test checks if the `of` method correctly creates a `Parameter` object with valid inputs for both name and type.

Execution:
  Arrange: Prepare valid name and type strings.
  Act: Invoke the `of` method with the valid name and type.
  Assert: Verify that the returned `Parameter` object has the correct name and type.

Validation:
  Ensure that the method correctly initializes the `Parameter` object with the provided name and type.

---

Scenario 2: Null Name

Details:
  TestName: nullName
  Description: This test checks the behavior of the `of` method when the name is null.

Execution:
  Arrange: Prepare a null name and a valid type string.
  Act: Invoke the `of` method with the null name and valid type.
  Assert: Verify that the method throws an appropriate exception (e.g., `NullPointerException`).

Validation:
  Ensure that the method handles null names gracefully and provides clear feedback to the user.

---

Scenario 3: Empty Name

Details:
  TestName: emptyName
  Description: This test checks the behavior of the `of` method when the name is an empty string.

Execution:
  Arrange: Prepare an empty string for the name and a valid type string.
  Act: Invoke the `of` method with the empty name and valid type.
  Assert: Verify that the method throws an appropriate exception (e.g., `IllegalArgumentException`).

Validation:
  Ensure that the method handles empty names gracefully and provides clear feedback to the user.

---

Scenario 4: Null Type

Details:
  TestName: nullType
  Description: This test checks the behavior of the `of` method when the type is null.

Execution:
  Arrange: Prepare a valid name string and a null type.
  Act: Invoke the `of` method with the valid name and null type.
  Assert: Verify that the method throws an appropriate exception (e.g., `NullPointerException`).

Validation:
  Ensure that the method handles null types gracefully and provides clear feedback to the user.

---

Scenario 5: Empty Type

Details:
  TestName: emptyType
  Description: This test checks the behavior of the `of` method when the type is an empty string.

Execution:
  Arrange: Prepare a valid name string and an empty string for the type.
  Act: Invoke the `of` method with the valid name and empty type.
  Assert: Verify that the method throws an appropriate exception (e.g., `IllegalArgumentException`).

Validation:
  Ensure that the method handles empty types gracefully and provides clear feedback to the user.

---

Scenario 6: Name with Special Characters

Details:
  TestName: nameWithSpecialCharacters
  Description: This test checks the behavior of the `of` method when the name contains special characters.

Execution:
  Arrange: Prepare a name string with special characters and a valid type string.
  Act: Invoke the `of` method with the name containing special characters and valid type.
  Assert: Verify that the method correctly initializes the `Parameter` object with the provided name.

Validation:
  Ensure that the method correctly handles names with special characters and initializes the `Parameter` object accordingly.

---

Scenario 7: Type with Special Characters

Details:
  TestName: typeWithSpecialCharacters
  Description: This test checks the behavior of the `of` method when the type contains special characters.

Execution:
  Arrange: Prepare a valid name string and a type string containing special characters.
  Act: Invoke the `of` method with the valid name and type containing special characters.
  Assert: Verify that the method correctly initializes the `Parameter` object with the provided type.

Validation:
  Ensure that the method correctly handles types with special characters and initializes the `Parameter` object accordingly.

---

Scenario 8: Annotations Initialization

Details:
  TestName: annotationsInitialization
  Description: This test checks if the `of` method initializes the `annotations` field correctly.

Execution:
  Arrange: Prepare valid name and type strings.
  Act: Invoke the `of` method with the valid name and type.
  Assert: Verify that the `annotations` field in the returned `Parameter` object is not null and initialized correctly.

Validation:
  Ensure that the method correctly initializes the `annotations` field in the `Parameter` object.

---

Scenario 9: Multiple Instances with Same Name and Type

Details:
  TestName: multipleInstancesWithSameNameAndType
  Description: This test checks if creating multiple `Parameter` objects with the same name and type results in distinct objects.

Execution:
  Arrange: Prepare valid name and type strings.
  Act: Invoke the `of` method multiple times with the same name and type.
  Assert: Verify that each invocation returns a distinct `Parameter` object.

Validation:
  Ensure that the method creates distinct `Parameter` objects for the same name and type.

---

Scenario 10: Builder Pattern Usage

Details:
  TestName: builderPatternUsage
  Description: This test checks if the `of` method correctly utilizes the builder pattern to create the `Parameter` object.

Execution:
  Arrange: Prepare valid name and type strings.
  Act: Invoke the `of` method with the valid name and type.
  Assert: Verify that the builder pattern is used to set the name and type, and that the `build` method is called.

Validation:
  Ensure that the method correctly uses the builder pattern to create the `Parameter` object.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.function.Consumer;
import org.junit.jupiter.api.*;

public class ParameterOfTest {

	@Test
	@Tag("valid")
	public void testValidNameAndType() {
		String name = "validName";
		String type = "validType";
		Parameter parameter = Parameter.of(name, type);
		assertEquals(name, parameter.getName());
		assertEquals(type, parameter.getType());
	}

	@Test
	@Tag("invalid")
	public void testNullName() {
		String name = null;
		String type = "validType";
		assertThrows(NullPointerException.class, () -> Parameter.of(name, type));
	}

	@Test
	@Tag("invalid")
	public void testEmptyName() {
		String name = "";
		String type = "validType";
		assertThrows(IllegalArgumentException.class, () -> Parameter.of(name, type));
	}

	@Test
	@Tag("invalid")
	public void testNullType() {
		String name = "validName";
		String type = null;
		assertThrows(NullPointerException.class, () -> Parameter.of(name, type));
	}

	@Test
	@Tag("invalid")
	public void testEmptyType() {
		String name = "validName";
		String type = "";
		assertThrows(IllegalArgumentException.class, () -> Parameter.of(name, type));
	}

	@Test
	@Tag("valid")
	public void testNameWithSpecialCharacters() {
		String name = "name@123";
		String type = "validType";
		Parameter parameter = Parameter.of(name, type);
		assertEquals(name, parameter.getName());
		assertEquals(type, parameter.getType());
	}

	@Test
	@Tag("valid")
	public void testTypeWithSpecialCharacters() {
		String name = "validName";
		String type = "type@123";
		Parameter parameter = Parameter.of(name, type);
		assertEquals(name, parameter.getName());
		assertEquals(type, parameter.getType());
	}

	@Test
	@Tag("valid")
	public void testAnnotationsInitialization() {
		String name = "validName";
		String type = "validType";
		Parameter parameter = Parameter.of(name, type);
		assertNotNull(parameter.annotations());
		assertTrue(parameter.annotations().isEmpty());
	}

	@Test
	@Tag("valid")
	public void testMultipleInstancesWithSameNameAndType() {
		String name = "validName";
		String type = "validType";
		Parameter parameter1 = Parameter.of(name, type);
		Parameter parameter2 = Parameter.of(name, type);
		assertNotSame(parameter1, parameter2);
	}

	@Test
	@Tag("valid")
	public void testBuilderPatternUsage() {
		String name = "validName";
		String type = "validType";
		Parameter parameter = Parameter.of(name, type);
		assertEquals(name, parameter.getName());
		assertEquals(type, parameter.getType());
	}

}