/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=builder_4e6da3c5b4
ROOST_METHOD_SIG_HASH=builder_caac54eb73

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/maven/MavenDistributionManagementTests.java
Tests:
    "@Test
@Test
void distributionManagementEmpty() {
    MavenDistributionManagement result = builder().build();
    assertThat(result.isEmpty()).isTrue();
    assertThat(result.getRelocation().isEmpty()).isTrue();
    assertThat(result.getRepository().isEmpty()).isTrue();
    assertThat(result.getSite().isEmpty()).isTrue();
    assertThat(result.getSnapshotRepository().isEmpty()).isTrue();
}
"
    "@Test
@Test
void distributionManagementWithDownloadUrl() {
    MavenDistributionManagement mdm = builder().downloadUrl("https:
    assertThat(mdm.getDownloadUrl()).isEqualTo("https:
}
"
    "@Test
@Test
void distributionManagementWithRepository() {
    MavenDistributionManagement mdm = builder().repository((repository) -> repository.id("released-repo").name("released repo").url("https:
    DeploymentRepository repository = mdm.getRepository();
    assertThat(repository.getId()).isEqualTo("released-repo");
    assertThat(repository.getName()).isEqualTo("released repo");
    assertThat(repository.getUrl()).isEqualTo("https:
    assertThat(repository.getLayout()).isEqualTo("default");
    assertThat(repository.getUniqueVersion()).isNull();
}
"
    "@Test
@Test
void distributionManagementWithSnapshotRepository() {
    MavenDistributionManagement mdm = builder().snapshotRepository((repository) -> repository.id("snapshot-repo").name("snapshot repo").url("scp:
    DeploymentRepository snapshotRepository = mdm.getSnapshotRepository();
    assertThat(snapshotRepository.getId()).isEqualTo("snapshot-repo");
    assertThat(snapshotRepository.getName()).isEqualTo("snapshot repo");
    assertThat(snapshotRepository.getUrl()).isEqualTo("scp:
    assertThat(snapshotRepository.getLayout()).isNull();
    assertThat(snapshotRepository.getUniqueVersion()).isTrue();
}
"
    "@Test
@Test
void distributionManagementWithSite() {
    MavenDistributionManagement mdm = builder().site((site) -> site.id("website").name("web site")).site((site) -> site.url("scp:
    Site site = mdm.getSite();
    assertThat(site.getId()).isEqualTo("website");
    assertThat(site.getName()).isEqualTo("web site");
    assertThat(site.getUrl()).isEqualTo("scp:
}
"
    "@Test
@Test
void distributionManagementWithRelocation() {
    MavenDistributionManagement mdm = builder().relocation((relocation) -> relocation.groupId("com.example.new").artifactId("project").version("1.0.0")).relocation((relocation) -> relocation.message("Moved to com.example.new")).build();
    assertThat(mdm.getRelocation().getGroupId()).isEqualTo("com.example.new");
    assertThat(mdm.getRelocation().getArtifactId()).isEqualTo("project");
    assertThat(mdm.getRelocation().getVersion()).isEqualTo("1.0.0");
    assertThat(mdm.getRelocation().getMessage()).isEqualTo("Moved to com.example.new");
}
"
    "@Test
private MavenDistributionManagement.Builder builder() {
    return new MavenDistributionManagement.Builder();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/CodeBlockTests.java
Tests:
    "@Test
@Test
void codeBlocksCanBeAdded() {
    CodeBlock code = CodeBlock.builder().add("(123").add(CodeBlock.of(", 456)")).build();
    assertThat(writeJava(code)).isEqualTo("(123, 456)");
    assertThat(code.getImports()).isEmpty();
}
"
    "@Test
@Test
void codeBlockWithMultipleStatements() {
    CodeBlock code = CodeBlock.builder().addStatement("myInstance.sayHello(123)").addStatement(CodeBlock.of("myInstance.sayHello(456)")).build();
    assertThat(writeJava(code)).isEqualToNormalizingNewlines("""
        myInstance.sayHello(123);
        myInstance.sayHello(456);
        """);
    assertThat(code.getImports()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void functionWithParameterAnnotation() throws IOException {
    KotlinSourceCode sourceCode = new KotlinSourceCode();
    KotlinCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    KotlinTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addFunctionDeclaration(KotlinFunctionDeclaration.function("something").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.kt");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    fun something(@Service service: MyService) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    GroovySourceCode sourceCode = new GroovySourceCode();
    GroovyCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    GroovyTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(GroovyMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.groovy");
    assertThat(lines).containsExactly("package com.example", "", "import com.example.another.MyService", "import com.example.stereotype.Service", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
@Test
void methodWithParameterAnnotation() throws IOException {
    JavaSourceCode sourceCode = new JavaSourceCode();
    JavaCompilationUnit compilationUnit = sourceCode.createCompilationUnit("com.example", "Test");
    JavaTypeDeclaration test = compilationUnit.createTypeDeclaration("Test");
    test.addMethodDeclaration(JavaMethodDeclaration.method("something").returning("void").parameters(Parameter.builder("service").type(ClassName.of("com.example.another.MyService")).annotate(ClassName.of("com.example.stereotype.Service")).build()).body(CodeBlock.of("")));
    List<String> lines = writeSingleType(sourceCode, "com/example/Test.java");
    assertThat(lines).containsExactly("package com.example;", "", "import com.example.another.MyService;", "import com.example.stereotype.Service;", "", "class Test {", "", "    void something(@Service MyService service) {", "    }", "", "}");
}
"```plaintext
Scenario 1: Test builder method with a non-null name

Details:
  TestName: builderWithNonNullName
  Description: This test checks if the builder method correctly initializes the field 'name' with a non-null value provided as a parameter.
Execution:
  Arrange: Prepare a non-null String value for the 'name' parameter.
  Act: Invoke the builder method with the prepared 'name' value.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value.
Validation:
  Clarify that the assertion verifies the correct initialization of the 'name' field when a valid (non-null) value is supplied.
  Elaborate that this is a fundamental test to ensure the builder pattern properly initializes the object's state.

Scenario 2: Test builder method with null name

Details:
  TestName: builderWithNullName
  Description: This test checks if the builder method handles a null value for the 'name' parameter gracefully.
Execution:
  Arrange: Prepare a null value for the 'name' parameter.
  Act: Invoke the builder method with the null 'name' value.
  Assert: Verify that the 'name' field in the created Builder object is null.
Validation:
  Clarify that the assertion ensures the builder can handle null values for the 'name' parameter without throwing exceptions.
  Elaborate that this test is crucial for validating the robustness of the builder when handling edge cases like null inputs.

Scenario 3: Test builder method with empty string name

Details:
  TestName: builderWithEmptyStringName
  Description: This test checks if the builder method correctly initializes the field 'name' with an empty string value provided as a parameter.
Execution:
  Arrange: Prepare an empty string value for the 'name' parameter.
  Act: Invoke the builder method with the empty string 'name' value.
  Assert: Verify that the 'name' field in the created Builder object is an empty string.
Validation:
  Clarify that the assertion ensures the builder correctly handles empty string inputs for the 'name' parameter.
  Elaborate that this test is essential for ensuring the builder behaves correctly with valid but edge-case inputs like empty strings.

Scenario 4: Test builder method with a long string name

Details:
  TestName: builderWithLongStringName
  Description: This test checks if the builder method correctly handles long string values for the 'name' parameter.
Execution:
  Arrange: Prepare a long string value for the 'name' parameter (e.g., a string longer than 255 characters).
  Act: Invoke the builder method with the long string 'name' value.
  Assert: Verify that the 'name' field in the created Builder object matches the provided long string value.
Validation:
  Clarify that the assertion ensures the builder can handle long string inputs for the 'name' parameter without issues.
  Elaborate that this test is important for validating the builder's performance and correctness with large inputs.

Scenario 5: Test builder method with special characters in name

Details:
  TestName: builderWithSpecialCharactersName
  Description: This test checks if the builder method correctly handles names containing special characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing special characters (e.g., !@#$%^&*()).
  Act: Invoke the builder method with the 'name' value containing special characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with special characters.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with special characters.
  Elaborate that this test is vital for verifying the builder's ability to handle diverse and potentially complex input data.

Scenario 6: Test builder method with leading and trailing whitespace in name

Details:
  TestName: builderWithWhitespaceName
  Description: This test checks if the builder method correctly handles names with leading and trailing whitespace.
Execution:
  Arrange: Prepare a string value for the 'name' parameter with leading and trailing whitespace.
  Act: Invoke the builder method with the 'name' value containing leading and trailing whitespace.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with leading and trailing whitespace.
Validation:
  Clarify that the assertion ensures the builder preserves whitespace in the 'name' parameter as expected.
  Elaborate that this test is essential for validating the builder's behavior with whitespace inputs.

Scenario 7: Test builder method with name containing Unicode characters

Details:
  TestName: builderWithUnicodeName
  Description: This test checks if the builder method correctly handles names containing Unicode characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing Unicode characters.
  Act: Invoke the builder method with the 'name' value containing Unicode characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with Unicode characters.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with Unicode characters.
  Elaborate that this test is important for verifying the builder's ability to handle internationalized input data.

Scenario 8: Test builder method with name consisting of just numbers

Details:
  TestName: builderWithNumericName
  Description: This test checks if the builder method correctly handles names consisting solely of numeric characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter consisting of just numbers.
  Act: Invoke the builder method with the 'name' value consisting of just numbers.
  Assert: Verify that the 'name' field in the created Builder object matches the provided numeric value.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names that are numeric.
  Elaborate that this test is crucial for validating the builder's behavior with purely numeric inputs.

Scenario 9: Test builder method with name containing mixed case characters

Details:
  TestName: builderWithMixedCaseName
  Description: This test checks if the builder method correctly handles names containing mixed case characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter with mixed case characters.
  Act: Invoke the builder method with the 'name' value containing mixed case characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with mixed case characters.
Validation:
  Clarify that the assertion ensures the builder preserves the case of characters in the 'name' parameter as expected.
  Elaborate that this test is essential for validating the builder's behavior with case-sensitive inputs.

Scenario 10: Test builder method with name containing spaces

Details:
  TestName: builderWithNameContainingSpaces
  Description: This test checks if the builder method correctly handles names containing spaces.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing spaces.
  Act: Invoke the builder method with the 'name' value containing spaces.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with spaces.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with spaces.
  Elaborate that this test is important for verifying the builder's ability to handle names with spaces.

Scenario 11: Test builder method with name containing tabs

Details:
  TestName: builderWithNameContainingTabs
  Description: This test checks if the builder method correctly handles names containing tab characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing tab characters.
  Act: Invoke the builder method with the 'name' value containing tab characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with tab characters.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with tab characters.
  Elaborate that this test is important for verifying the builder's ability to handle names with non-standard whitespace characters.

Scenario 12: Test builder method with name containing newlines

Details:
  TestName: builderWithNameContainingNewlines
  Description: This test checks if the builder method correctly handles names containing newline characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing newline characters.
  Act: Invoke the builder method with the 'name' value containing newline characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with newline characters.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with newline characters.
  Elaborate that this test is important for verifying the builder's ability to handle names with newline characters.

Scenario 13: Test builder method with name containing carriage returns

Details:
  TestName: builderWithNameContainingCarriageReturns
  Description: This test checks if the builder method correctly handles names containing carriage return characters.
Execution:
  Arrange: Prepare a string value for the 'name' parameter containing carriage return characters.
  Act: Invoke the builder method with the 'name' value containing carriage return characters.
  Assert: Verify that the 'name' field in the created Builder object matches the provided value with carriage return characters.
Validation:
  Clarify that the assertion ensures the builder correctly processes and stores names with carriage return characters.
  Elaborate that this test is important for verifying the builder's ability to handle names with carriage return characters.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatNullPointerException;
import static org.assertj.core.api.Assertions.assertThatIllegalArgumentException;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import java.util.function.Consumer;

public class ParameterBuilderTest {

	@Test
	@Tag("valid")
	public void builderWithNonNullName() {
		String name = "testName";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("invalid")
	public void builderWithNullName() {
		assertThatNullPointerException().isThrownBy(() -> Parameter.builder(null));
	}

	@Test
	@Tag("boundary")
	public void builderWithEmptyStringName() {
		String name = "";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("boundary")
	public void builderWithLongStringName() {
		String name = "a".repeat(256);
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithSpecialCharactersName() {
		String name = "!@#$%^&*()";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("boundary")
	public void builderWithWhitespaceName() {
		String name = "  testName  ";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithUnicodeName() {
		String name = "你好";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("boundary")
	public void builderWithNumericName() {
		String name = "12345";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithMixedCaseName() {
		String name = "TeStNaMe";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithNameContainingSpaces() {
		String name = "test name";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithNameContainingTabs() {
		String name = "test\tname";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithNameContainingNewlines() {
		String name = "test\nname";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

	@Test
	@Tag("valid")
	public void builderWithNameContainingCarriageReturns() {
		String name = "test\rname";
		Parameter.Builder builder = Parameter.builder(name);
		assertThat(builder).isNotNull();
		assertThat(builder.name).isEqualTo(name);
	}

}