/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getRootDirectory_2050ea3b0b
ROOST_METHOD_SIG_HASH=getRootDirectory_0bacc8c65a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BuildSystemTests.java
Tests:
    "@Test
@Test
void defaultMainSource(@TempDir Path directory) {
    SourceStructure mainCodeStructure = BuildSystem.forId("gradle").getMainSource(directory, new JavaLanguage());
    assertThat(mainCodeStructure.getRootDirectory()).isEqualTo(directory.resolve("src/main"));
    assertThat(mainCodeStructure.getSourcesDirectory()).isEqualTo(directory.resolve("src/main/java"));
}
"
    "@Test
@Test
void defaultTestSource(@TempDir Path directory) {
    SourceStructure testCodeStructure = BuildSystem.forId("gradle").getTestSource(directory, new KotlinLanguage());
    assertThat(testCodeStructure.getRootDirectory()).isEqualTo(directory.resolve("src/test"));
    assertThat(testCodeStructure.getSourcesDirectory()).isEqualTo(directory.resolve("src/test/kotlin"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/SourceStructureTests.java
Tests:
    "@Test
@Test
void resolveBuildResource(@TempDir Path dir) {
    SourceStructure sourceStructure = new SourceStructure(dir.resolve("src/main"), JAVA_LANGUAGE);
    Path configFile = sourceStructure.getRootDirectory().resolve("assembly/bundle.xml");
    assertThat(configFile).isEqualByComparingTo(dir.resolve("src/main/assembly/bundle.xml"));
}
"```plaintext
Scenario 1: Verify Root Directory Initialization

Details:
  TestName: rootDirectoryInitializedCorrectly
  Description: This test checks if the rootDirectory is initialized correctly when a SourceStructure object is created.
Execution:
  Arrange: Create a SourceStructure object with a given root directory.
  Act: Invoke the getRootDirectory method.
  Assert: Verify that the root directory returned by getRootDirectory is the same as the one provided during object creation.
Validation:
  Clarify: The assertion aims to verify that the root directory is properly set and retrievable.
  Elaborate: This test ensures that the initialization of the root directory is correct, which is fundamental for other operations that depend on the root directory.

Scenario 2: Verify Null Root Directory

Details:
  TestName: rootDirectoryIsNull
  Description: This test checks the behavior of getRootDirectory when the rootDirectory is not explicitly set.
Execution:
  Arrange: Create a SourceStructure object without setting the root directory.
  Act: Invoke the getRootDirectory method.
  Assert: Verify that the root directory returned by getRootDirectory is null.
Validation:
  Clarify: The assertion aims to verify that the root directory remains null when not explicitly initialized.
  Elaborate: This test ensures that the behavior is consistent when the root directory is not set, which is important for handling default or optional directory settings.

Scenario 3: Verify Root Directory Modification

Details:
  TestName: rootDirectoryCannotBeModified
  Description: This test checks if the rootDirectory can be modified after it has been set.
Execution:
  Arrange: Create a SourceStructure object with a given root directory.
  Act: Attempt to modify the root directory.
  Assert: Verify that the root directory remains unchanged.
Validation:
  Clarify: The assertion aims to verify that the root directory is immutable after initialization.
  Elaborate: This test ensures that the immutability of the root directory is maintained, which is crucial for consistency across different operations.

Scenario 4: Verify Root Directory Path

Details:
  TestName: rootDirectoryPathCorrect
  Description: This test checks if the root directory path is correctly returned.
Execution:
  Arrange: Create a SourceStructure object with a specific path.
  Act: Invoke the getRootDirectory method.
  Assert: Verify that the path returned matches the expected path.
Validation:
  Clarify: The assertion aims to verify that the path returned by getRootDirectory is the exact path provided during object creation.
  Elaborate: This test ensures that the path retrieval is accurate, which is essential for file operations that depend on the correct directory path.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.nio.file.Files;

class SourceStructureGetRootDirectoryTest {

	private Path rootDirectory;

	private SourceStructure sourceStructure;

	private Language language;

	@BeforeEach
	void setUp() {
		rootDirectory = Paths.get("src/test/resources");
		language = Language.forId("java", Language.DEFAULT_JVM_VERSION);
		sourceStructure = new SourceStructure(rootDirectory, language);
	}

	@Test
	@Tag("valid")
	public void testRootDirectoryInitializedCorrectly() {
		assertEquals(rootDirectory, sourceStructure.getRootDirectory());
	}

	@Test
	@Tag("invalid")
	public void testRootDirectoryIsNull() {
		SourceStructure nullRootStructure = new SourceStructure(null, language);
		assertNull(nullRootStructure.getRootDirectory());
	}

	@Test
	@Tag("valid")
	public void testRootDirectoryPathCorrect() {
		Path expectedPath = Paths.get("src/test/resources");
		assertEquals(expectedPath, sourceStructure.getRootDirectory());
	}

	@Test
	@Tag("boundary")
	public void testRootDirectoryCannotBeModified() {
		Path newPath = Paths.get("src/test/resources/new");
		sourceStructure.getRootDirectory().resolve(newPath);
		assertEquals(rootDirectory, sourceStructure.getRootDirectory());
	}

}