/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getCompilationUnits_ad55912275
ROOST_METHOD_SIG_HASH=getCompilationUnits_a9610f8746

```plaintext
Scenario 1: Verify that getCompilationUnits returns an unmodifiable list

Details:
  TestName: getCompilationUnitsReturnsUnmodifiableList
  Description: This test ensures that the getCompilationUnits method returns an unmodifiable list of compilation units. It verifies that modifications to the returned list throw an UnsupportedOperationException.
Execution:
  Arrange: Initialize the SourceCode object and add a compilation unit using the createCompilationUnit method.
  Act: Invoke the getCompilationUnits method.
  Assert: Attempt to modify the returned list and verify that an UnsupportedOperationException is thrown.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  The test checks that the returned list is indeed unmodifiable, ensuring that consumers of this method cannot alter the internal state of the SourceCode object directly.

Scenario 2: Verify that getCompilationUnits returns the correct list of compilation units

Details:
  TestName: getCompilationUnitsReturnsCorrectList
  Description: This test verifies that the getCompilationUnits method returns the correct list of compilation units that have been added to the SourceCode object.
Execution:
  Arrange: Initialize the SourceCode object and add multiple compilation units using the createCompilationUnit method.
  Act: Invoke the getCompilationUnits method.
  Assert: Compare the returned list with the expected list of compilation units.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  The test ensures that the list of compilation units is correctly maintained and returned, reflecting the internal state of the SourceCode object.

Scenario 3: Verify that getCompilationUnits returns an empty list when no compilation units have been added

Details:
  TestName: getCompilationUnitsReturnsEmptyListWhenNoCompilationUnits
  Description: This test checks that the getCompilationUnits method returns an empty list when no compilation units have been added to the SourceCode object.
Execution:
  Arrange: Initialize the SourceCode object without adding any compilation units.
  Act: Invoke the getCompilationUnits method.
  Assert: Verify that the returned list is empty.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  The test ensures that the method handles the case where no compilation units have been added gracefully, returning an empty list.

Scenario 4: Verify that getCompilationUnits returns a list with a single compilation unit when only one has been added

Details:
  TestName: getCompilationUnitsReturnsListWithSingleCompilationUnit
  Description: This test verifies that the getCompilationUnits method returns a list containing a single compilation unit when only one has been added to the SourceCode object.
Execution:
  Arrange: Initialize the SourceCode object and add a single compilation unit using the createCompilationUnit method.
  Act: Invoke the getCompilationUnits method.
  Assert: Verify that the returned list contains exactly one compilation unit.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  The test ensures that the method correctly handles the case where only a single compilation unit is present, returning a list with that single unit.

Scenario 5: Verify that getCompilationUnits returns a list with multiple compilation units in the correct order

Details:
  TestName: getCompilationUnitsReturnsListInCorrectOrder
  Description: This test ensures that the getCompilationUnits method returns a list of compilation units in the order they were added.
Execution:
  Arrange: Initialize the SourceCode object and add multiple compilation units in a specific order using the createCompilationUnit method.
  Act: Invoke the getCompilationUnits method.
  Assert: Verify that the returned list contains the compilation units in the same order they were added.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
  The test ensures that the order of compilation units is preserved, which is crucial for maintaining the integrity of the internal state of the SourceCode object.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

class SourceCodeGetCompilationUnitsTest {

	private BiFunction<String, String, C> compilationUnitFactory;

	private SourceCode sourceCode;

	@BeforeEach
	void setUp() {
		compilationUnitFactory = Mockito.mock(BiFunction.class);
		sourceCode = new SourceCode(compilationUnitFactory);
	}

	@Test
    @Tag("valid")
    void getCompilationUnitsReturnsUnmodifiableList() {
        C compilationUnit = mock(C.class);
        when(compilationUnitFactory.apply(anyString(), anyString())).thenReturn(compilationUnit);
        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        List<C> result = sourceCode.getCompilationUnits();
        assertThrows(UnsupportedOperationException.class, () -> result.add(compilationUnit));
    }

	@Test
    @Tag("valid")
    void getCompilationUnitsReturnsCorrectList() {
        C compilationUnit1 = mock(C.class);
        C compilationUnit2 = mock(C.class);
        when(compilationUnitFactory.apply(anyString(), anyString())).thenReturn(compilationUnit1, compilationUnit2);
        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        List<C> expected = new ArrayList<>();
        expected.add(compilationUnit1);
        expected.add(compilationUnit2);
        List<C> result = sourceCode.getCompilationUnits();
        assertEquals(expected, result);
    }

	@Test
	@Tag("valid")
	void getCompilationUnitsReturnsEmptyListWhenNoCompilationUnits() {
		List<C> result = sourceCode.getCompilationUnits();
		assertTrue(result.isEmpty());
	}

	@Test
    @Tag("valid")
    void getCompilationUnitsReturnsListWithSingleCompilationUnit() {
        C compilationUnit = mock(C.class);
        when(compilationUnitFactory.apply(anyString(), anyString())).thenReturn(compilationUnit);
        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        List<C> result = sourceCode.getCompilationUnits();
        assertEquals(1, result.size());
        assertEquals(compilationUnit, result.get(0));
    }

	@Test
    @Tag("valid")
    void getCompilationUnitsReturnsListInCorrectOrder() {
        C compilationUnit1 = mock(C.class);
        C compilationUnit2 = mock(C.class);
        when(compilationUnitFactory.apply(anyString(), anyString())).thenReturn(compilationUnit1, compilationUnit2);
        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        sourceCode.createCompilationUnit("package io.spring.initializr.generator.language;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

        List<C> result = sourceCode.getCompilationUnits();
        assertEquals(2, result.size());
        assertEquals(compilationUnit1, result.get(0));
        assertEquals(compilationUnit2, result.get(1));
    }

}