/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

Test generated by RoostGPT for test java-spring-io using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getSourcesDirectory_29a245fe5b
ROOST_METHOD_SIG_HASH=getSourcesDirectory_e3c1e5eb3d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/buildsystem/BuildSystemTests.java
Tests:
    "@Test
@Test
void defaultMainSource(@TempDir Path directory) {
    SourceStructure mainCodeStructure = BuildSystem.forId("gradle").getMainSource(directory, new JavaLanguage());
    assertThat(mainCodeStructure.getRootDirectory()).isEqualTo(directory.resolve("src/main"));
    assertThat(mainCodeStructure.getSourcesDirectory()).isEqualTo(directory.resolve("src/main/java"));
}
"
    "@Test
@Test
void defaultTestSource(@TempDir Path directory) {
    SourceStructure testCodeStructure = BuildSystem.forId("gradle").getTestSource(directory, new KotlinLanguage());
    assertThat(testCodeStructure.getRootDirectory()).isEqualTo(directory.resolve("src/test"));
    assertThat(testCodeStructure.getSourcesDirectory()).isEqualTo(directory.resolve("src/test/kotlin"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/kotlin/KotlinSourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(KotlinSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/SourceStructureTests.java
Tests:
    "@Test
@Test
void resolveSourceWithPath(@TempDir Path dir) {
    SourceStructure sourceStructure = new SourceStructure(dir.resolve("src/main"), JAVA_LANGUAGE);
    Path configFile = sourceStructure.getSourcesDirectory().resolve("com/example/specific.xml");
    assertThat(configFile).isEqualByComparingTo(dir.resolve("src/main/java/com/example/specific.xml"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/groovy/GroovySourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(GroovySourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-io/17b22f30-aedf-459f-8a4e-4fdf2e214f95/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriterTests.java
Tests:
    "@Test
private Path writeSourceCode(JavaSourceCode sourceCode) throws IOException {
    Path srcDirectory = this.directory.resolve(UUID.randomUUID().toString());
    SourceStructure sourceStructure = new SourceStructure(srcDirectory, LANGUAGE);
    this.writer.writeTo(sourceStructure, sourceCode);
    return sourceStructure.getSourcesDirectory();
}
"```plaintext
Scenario 1: Verify that getSourcesDirectory returns the initialized sourcesDirectory

Details:
  TestName: returnsInitializedSourcesDirectory
  Description: This test verifies that the getSourcesDirectory method returns the correctly initialized sourcesDirectory when the object is created with a valid Path.
Execution:
  Arrange: Create an instance of SourceStructure with a valid Path for sourcesDirectory.
  Act: Invoke getSourcesDirectory on the created SourceStructure instance.
  Assert: Ensure that the returned Path matches the expected sourcesDirectory.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  Verify that the sourcesDirectory is correctly set during object initialization and returned as expected.
  Elaborate on the significance of the test in the context of application behavior or business logic. This ensures that the object initialization logic is working correctly and the sourcesDirectory is accessible as expected.

Scenario 2: Verify that getSourcesDirectory returns the same Path if called multiple times

Details:
  TestName: returnsSamePathOnMultipleCalls
  Description: This test verifies that calling getSourcesDirectory multiple times on the same SourceStructure instance returns the same Path.
Execution:
  Arrange: Create an instance of SourceStructure with a valid Path for sourcesDirectory.
  Act: Invoke getSourcesDirectory multiple times on the created SourceStructure instance.
  Assert: Ensure that each invocation returns the same Path.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  Ensure that the sourcesDirectory remains consistent across multiple calls.
  Elaborate on the significance of the test in the context of application behavior or business logic. This verifies the immutability of the sourcesDirectory after initialization.

Scenario 3: Verify that getSourcesDirectory handles null sourcesDirectory correctly

Details:
  TestName: handlesNullSourcesDirectory
  Description: This test verifies that the getSourcesDirectory method handles a null sourcesDirectory by returning null.
Execution:
  Arrange: Create an instance of SourceStructure with a null Path for sourcesDirectory.
  Act: Invoke getSourcesDirectory on the created SourceStructure instance.
  Assert: Ensure that the returned Path is null.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  Ensure that the method gracefully handles a null sourcesDirectory.
  Elaborate on the significance of the test in the context of application behavior or business logic. This verifies the robustness of the method under unexpected conditions.

Scenario 4: Verify that getSourcesDirectory returns the correct directory when used in conjunction with other methods

Details:
  TestName: returnsCorrectDirectoryWithOtherMethods
  Description: This test verifies that the getSourcesDirectory method returns the correct directory when used in conjunction with other methods like resolveSourceFile and createSourceFile.
Execution:
  Arrange: Create an instance of SourceStructure with a valid Path for sourcesDirectory.
  Act: Invoke getSourcesDirectory on the created SourceStructure instance and use the returned Path to resolve and create a source file.
  Assert: Ensure that the resolved and created source file Path matches the expected Path.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.  Ensure that the sourcesDirectory is correctly used in conjunction with other methods.
  Elaborate on the significance of the test in the context of application behavior or business logic. This verifies the integration of the getSourcesDirectory method with other functionalities of the class.
```,
*/

// ********RoostGPT********

package io.spring.initializr.generator.language;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

class SourceStructureGetSourcesDirectoryTest {

	private SourceStructure sourceStructure;

	private Path rootDirectory;

	private Language language;

	@BeforeEach
	void setUp() {
		rootDirectory = Paths.get("root");
		language = Language.forId("java", Language.DEFAULT_JVM_VERSION);
		sourceStructure = new SourceStructure(rootDirectory, language);
	}

	@Test
	@Tag("valid")
	void returnsInitializedSourcesDirectory() {
		Path expectedSourcesDirectory = rootDirectory.resolve(language.id());
		assertEquals(expectedSourcesDirectory, sourceStructure.getSourcesDirectory());
	}

	@Test
	@Tag("valid")
	void returnsSamePathOnMultipleCalls() {
		Path firstCall = sourceStructure.getSourcesDirectory();
		Path secondCall = sourceStructure.getSourcesDirectory();
		assertEquals(firstCall, secondCall);
	}

	@Test
	@Tag("invalid")
	void handlesNullSourcesDirectory() {
		// TODO: Uncomment below line to test for null sourcesDirectory
		// sourceStructure = new SourceStructure(null, language);
		assertNull(sourceStructure.getSourcesDirectory());
	}

	@Test
    @Tag("integration")
    void returnsCorrectDirectoryWithOtherMethods() throws IOException {
        String package io.spring.initializr.generator.language;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

        String fileName = "TestFile";
        Path resolvedFile = sourceStructure.resolveSourceFile(package io.spring.initializr.generator.language;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

        Path createdFile = sourceStructure.createSourceFile(package io.spring.initializr.generator.language;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

        Path expectedFilePath = sourceStructure.getSourcesDirectory().resolve(package io.spring.initializr.generator.language;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

        assertEquals(expectedFilePath, resolvedFile);
        assertEquals(expectedFilePath, createdFile);
    }

}