/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=contribute_28e818ddc0
ROOST_METHOD_SIG_HASH=contribute_a94e4219ee

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/contributor/MultipleResourcesProjectContributorTests.java
Tests:
    "@Test
@Test
void contribute(@TempDir Path directory) throws IOException {
    new MultipleResourcesProjectContributor("classpath:/data/multi").contribute(directory);
    assertThat(directory.resolve("one.properties")).exists().isRegularFile();
    assertThat(directory.resolve("two.xml")).exists().isRegularFile();
}
"
    "@Test
@Test
void contributeWithTrailingSlash(@TempDir Path directory) throws IOException {
    new MultipleResourcesProjectContributor("classpath:/data/multi/").contribute(directory);
    assertThat(directory.resolve("one.properties")).exists().isRegularFile();
    assertThat(directory.resolve("two.xml")).exists().isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/info/BomRangesInfoContributorTests.java
Tests:
    "@Test
private static Info getInfo(InitializrMetadata metadata) {
    Info.Builder builder = new Info.Builder();
    new BomRangesInfoContributor(new SimpleInitializrMetadataProvider(metadata)).contribute(builder);
    return builder.build();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/MavenBuildProjectContributorTests.java
Tests:
    "@Test
@Test
void mavenBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    MavenBuild build = new MavenBuild();
    new MavenBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path pomFile = projectDir.resolve("pom.xml");
    assertThat(pomFile).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/container/docker/compose/ComposeProjectContributorTests.java
Tests:
    "@Test
@Test
void composeFileIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    ComposeFile compose = new ComposeFile();
    compose.services().add("test", (service) -> service.image("my-image:1.2.3"));
    new ComposeProjectContributor(compose, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path composeFile = projectDir.resolve("compose.yaml");
    assertThat(composeFile).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/GradleWrapperContributorTests.java
Tests:
    "@Test
@ParameterizedTest(name = "Gradle {0}")
@ValueSource(strings = "8")
void gradleWrapperSetExecutableFlagOnScripts(String gradleVersion) throws IOException {
    Path projectDir = contribute(gradleVersion);
    assertThat(projectDir.resolve("gradlew")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("gradlew.bat")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("gradle/wrapper/gradle-wrapper.jar")).isRegularFile().satisfies(isNotExecutable());
    assertThat(projectDir.resolve("gradle/wrapper/gradle-wrapper.properties")).isRegularFile().satisfies(isNotExecutable());
}
"
    "@Test
Path contribute(String gradleVersion) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new GradleWrapperContributor(gradleVersion).contribute(projectDir);
    return projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/properties/ApplicationPropertiesContributorTests.java
Tests:
    "@Test
@Test
void applicationConfigurationWithDefaultSettings() throws IOException {
    new ApplicationPropertiesContributor(new ApplicationProperties()).contribute(this.directory);
    assertThat(new ProjectStructure(this.directory)).textFile("src/main/resources/application.properties").isEmpty();
}
"
    "@Test
@Test
void shouldAddStringProperty() throws IOException {
    ApplicationProperties properties = new ApplicationProperties();
    properties.add("spring.application.name", "test");
    ApplicationPropertiesContributor contributor = new ApplicationPropertiesContributor(properties);
    contributor.contribute(this.directory);
    assertThat(new ProjectStructure(this.directory)).textFile("src/main/resources/application.properties").lines().contains("spring.application.name=test");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/GradleBuildProjectContributorTests.java
Tests:
    "@Test
@Test
void groovyDslGradleBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    GradleBuild build = new GradleBuild();
    groovyDslGradleBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path buildGradle = projectDir.resolve("build.gradle");
    assertThat(buildGradle).isRegularFile();
}
"
    "@Test
@Test
void kotlinDslGradleBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    GradleBuild build = new GradleBuild();
    kotlinDslGradleBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path buildGradleKts = projectDir.resolve("build.gradle.kts");
    assertThat(buildGradleKts).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/scm/git/GitProjectGenerationConfigurationTests.java
Tests:
    "@Test
@Test
void gitIgnoreIsContributedToProject(@TempDir Path directory) {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setBuildSystem(new GradleBuildSystem());
    Path projectDirectory = this.projectTester.withDirectory(directory).generate(description, (context) -> {
        GitIgnoreContributor contributor = context.getBean(GitIgnoreContributor.class);
        contributor.contribute(directory);
        return directory;
    });
    assertThat(projectDirectory.resolve(".gitignore")).isRegularFile();
}
"
    "@Test
@Test
void gitAttributesIsContributedToProject(@TempDir Path directory) {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setBuildSystem(new GradleBuildSystem());
    Path projectDirectory = this.projectTester.withDirectory(directory).generate(description, (context) -> {
        GitAttributesContributor contributor = context.getBean(GitAttributesContributor.class);
        contributor.contribute(directory);
        return directory;
    });
    assertThat(projectDirectory.resolve(".gitattributes")).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/MavenWrapperContributorTests.java
Tests:
    "@Test
@ParameterizedTest(name = "Maven {0}")
@ValueSource(strings = "3")
void mavenWrapperSetExecutableFlagOnScripts(String mavenVersion) throws IOException {
    Path projectDir = contribute(mavenVersion);
    assertThat(projectDir.resolve("mvnw")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("mvnw.cmd")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve(".mvn/wrapper/maven-wrapper.properties")).isRegularFile().satisfies(isNotExecutable());
}
"
    "@Test
Path contribute(String mavenVersion) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new MavenWrapperContributor(mavenVersion).contribute(projectDir);
    return projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/info/DependencyRangesInfoContributorTests.java
Tests:
    "@Test
private static Info getInfo(InitializrMetadata metadata) {
    Info.Builder builder = new Info.Builder();
    new DependencyRangesInfoContributor(new SimpleInitializrMetadataProvider(metadata)).contribute(builder);
    return builder.build();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/controller/custom/CustomProjectContributor.java
Tests:
    "@Test
@Override
public void contribute(Path projectRoot) throws IOException {
    if (this.description instanceof CustomProjectDescription && ((CustomProjectDescription) this.description).isCustomFlag()) {
        Files.createFile(projectRoot.resolve("custom.txt"));
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/configuration/WebFoldersContributorTests.java
Tests:
    "@Test
@Test
void webFoldersCreatedWithWebDependency() throws IOException {
    Dependency simple = Dependency.withId("simple", "com.example", "simple", null, Dependency.SCOPE_COMPILE);
    Dependency web = Dependency.withId("web", "com.example", "web", null, Dependency.SCOPE_COMPILE);
    web.setFacets(Collections.singletonList("web"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", simple, web).build();
    Build build = createBuild(metadata);
    build.dependencies().add("simple");
    build.dependencies().add("web");
    Path projectDir = contribute(build, metadata);
    assertThat(projectDir.resolve("src/main/resources/templates")).isDirectory();
    assertThat(projectDir.resolve("src/main/resources/static")).isDirectory();
}
"
    "@Test
@Test
void webFoldersNotCreatedWithoutWebDependency() throws IOException {
    Dependency simple = Dependency.withId("simple", "com.example", "simple", null, Dependency.SCOPE_COMPILE);
    Dependency web = Dependency.withId("web", "com.example", "web", null, Dependency.SCOPE_COMPILE);
    web.setFacets(Collections.singletonList("web"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", simple, web).build();
    Build build = createBuild(metadata);
    build.dependencies().add("simple");
    Path projectDir = contribute(build, metadata);
    assertThat(projectDir.resolve("src/main/resources/templates")).doesNotExist();
    assertThat(projectDir.resolve("src/main/resources/static")).doesNotExist();
}
"
    "@Test
private Path contribute(Build build, InitializrMetadata metadata) throws IOException {
    MutableProjectDescription projectDescription = new MutableProjectDescription();
    projectDescription.setPlatformVersion(Version.parse("1.0.0"));
    new WebFoldersContributor(build, metadata, projectDescription).contribute(this.projectDir);
    return this.projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/documentation/HelpDocumentProjectContributorTests.java
Tests:
    "@Test
@Test
void helpDocumentEmptyDoesNotCreateFile() throws IOException {
    HelpDocument document = new HelpDocument(this.templateRenderer);
    assertThat(document.isEmpty()).isTrue();
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new HelpDocumentProjectContributor(document).contribute(projectDir);
    Path helpDocument = projectDir.resolve("HELP.md");
    assertThat(helpDocument).doesNotExist();
}
"
    "@Test
private ListAssert<String> assertHelpDocument(HelpDocument document) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new HelpDocumentProjectContributor(document).contribute(projectDir);
    return new TextAssert(projectDir.resolve("HELP.md")).lines();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/SettingsGradleProjectContributorTests.java
Tests:
    "@Test
private TextAssert assertSettings(SettingsGradleProjectContributor contributor) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    contributor.contribute(projectDir);
    return new TextAssert(projectDir.resolve("test.gradle"));
}
""""
Scenario 1: Testing the successful execution of source code contribution.

Details:
  TestName: testSuccessfulContribution.
  Description: This test scenario is supposed to validate if the method contribute effectively generates the source code, compiles it and writes it to the build system properly.
Execution:
  Arrange: Create a mock object for Path and set up required dependencies such as sourceFactory, description, mainTypeCustomizers, mainCompilationUnitCustomizers, and mainSourceCodeCustomizers.
  Act: Call the method contribute with the mocked projectRoot.
  Assert: Verify if the correct methods on mock objects were called and sourceCodeWriter correctly writes the compiled source code.
Validation:
  This assertion verifies if the source code is correctly compiled and written to the project root directory. This is important in maintaining the integrity of the application and ensuring it is working as expected.

Scenario 2: Testing if IOException is thrown when there is a problem writing to the build system.

Details:
  TestName: testIoExceptionOnWriteFailure.
  Description: This test scenario is intended to validate if the contribute method appropriately handles the IOException and propagates it in the event of a failure in writing to the build system.
Execution:
  Arrange: Create a mock object for Path and create necessary mock objects such as sourceFactory, description etc. Make the sourceWriter throw an IOException when writeTo method is called.
  Act: Call the contribute method with the mocked projectRoot.
  Assert: Assert that IOException is thrown.
Validation:
  The assertion checks if an IOException is correctly thrown when there is a failure in writing the source code to the build system. This helps maintain the robustness of the code and prevent unexpected behavior.

Scenario 3: Testing the correct order of source code customization and writing.

Details:
  TestName: testCorrectCustomizationOrder.
  Description: This scenario tests the correct order of source code customization and final writing to the build system.
Execution:
  Arrange: Create a mock object for Path and set up necessary dependencies like sourceFactory, description, mainTypeCustomizers, mainCompilationUnitCustomizers, and mainSourceCodeCustomizers.
  Act: Invoke the contribute method with the mocked projectRoot.
  Assert: Check that methods were invoked in correct order: customizeMainApplicationType, customizeMainCompilationUnit, customizeMainSourceCode, and then sourceWriter.writeTo.
Validation:
  This assertion verifies if the source code goes through customization correctly before it is written to the build system. This test is vital as the order of execution can affect the correctness of the written code.

Scenario 4: Ensure sourceFactory and description are called to create and compile the source code.

Details:
  TestName: testSourceFactoryAndDescriptionUsage.
  Description: This test validates that sourceFactory and description are utilized in the creation and compilation of source code.
Execution:
  Arrange: Mock the necessary objects like Path, sourceFactory, description, and sourceCodeWriter.
  Act: Call contribute method with the mock projectRoot.
  Assert: Assert that sourceFactory.get and description.getApplicationName methods are called.
Validation:
  It verifies that sourceFactory and description are used to generate and compile the source code. It is essential to ensure that source code generation works as expected and uses the correct inputs.
"""
*/

// ********RoostGPT********

package io.spring.initializr.generator.spring.code;

import io.spring.initializr.generator.language.SourceCode;
import io.spring.initializr.generator.language.TypeDeclaration;
import io.spring.initializr.generator.language.CompilationUnit;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.contributor.ProjectContributor;
import io.spring.initializr.generator.spring.util.LambdaSafe;
import org.springframework.beans.factory.ObjectProvider;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.function.Supplier;
import java.util.stream.Collectors;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import io.spring.initializr.generator.language.SourceCodeWriter;

class MainSourceCodeProjectContributorContributeTest {

	@Test
	@Tag("valid")
	public void testSuccessfulContribution() {
		MainSourceCodeProjectContributor contributor = mock(MainSourceCodeProjectContributor.class);
		Path projectRoot = mock(Path.class);
		SourceCode sourceCode = mock(SourceCode.class);
		// Assume
		doNothing().when(contributor).contribute(projectRoot);
		// Act
		contributor.contribute(projectRoot);
		// Assert
		verify(contributor, times(1)).contribute(projectRoot);
	}

	@Test
	@Tag("invalid")
	public void testIoExceptionOnWriteFailure() {
		MainSourceCodeProjectContributor contributor = mock(MainSourceCodeProjectContributor.class);
		Path projectRoot = mock(Path.class);
		SourceCode sourceCode = mock(SourceCode.class);
		// Assume
		doThrow(new IOException()).when(contributor).contribute(projectRoot);
		// Act & Assert
		assertThrows(IOException.class, () -> contributor.contribute(projectRoot));
	}

	@Test
	@Tag("valid")
	public void testCorrectCustomizationOrder() {
		// use InOrder verifier for sequence of method calls
		InOrder inOrder = inOrder(contributor, mainApplicationType, compilationUnit, sourceCode, sourceWriter);
		contributor.contribute(projectRoot);
		// Verify the order
		inOrder.verify(contributor).customizeMainApplicationType(any());
		inOrder.verify(contributor).customizeMainCompilationUnit(any());
		inOrder.verify(contributor).customizeMainSourceCode(any());
		inOrder.verify(sourceWriter).writeTo(any(), any());
	}

	@Test
	@Tag("valid")
	public void testSourceFactoryAndDescriptionUsage() {
		MainSourceCodeProjectContributor contributor = mock(MainSourceCodeProjectContributor.class);
		Path projectRoot = mock(Path.class);
		SourceCode sourceCode = mock(SourceCode.class);
		// Assume
		when(contributor.sourceFactory.get()).thenReturn(sourceCode);
		when(contributor.description.getApplicationName()).thenReturn("testApp");
		// Act
		contributor.contribute(projectRoot);
		// Assert
		verify(contributor.sourceFactory).get();
		verify(contributor.description).getApplicationName();
	}

}