/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=junitJupiterSpringBootTestTypeCustomizer_ad3c909ed4
ROOST_METHOD_SIG_HASH=junitJupiterSpringBootTestTypeCustomizer_f50effa21c

"""

  Scenario 1: Validate if a new "SpringBootTest" annotation is added to the TypeDeclaration

  Details:
    TestName: testSpringBootTestAnnotationAddedSuccessfully.
    Description: This test is meant to verify if a "SpringBootTest" annotation is added to the provided TypeDeclaration when junitJupiterSpringBootTestTypeCustomizer() method is called.
  Execution:
    Arrange: Initialize a mock of TypeDeclaration.
    Act: Invoke the junitJupiterSpringBootTestTypeCustomizer method with the mock object.
    Assert: Use JUnit assertions to compare if the "SpringBootTest" annotation was added to the mocked TypeDeclaration.
  Validation:
    The assertion aims to verify that the "SpringBootTest" annotation was successfully added to the TypeDeclaration. The successful annotation demonstrates the capability of the method to make the correct modifications to TypeDeclaration.

  Scenario 2: Validate the customizer's behavior with null TypeDeclaration

  Details:
    TestName: testCustomizerWithNullTypeDeclaration.
    Description: This test verifies the behavior of the junitJupiterSpringBootTestTypeCustomizer method when a null TypeDeclaration is provided.
  Execution:
    Arrange: Do not setup any mocks as the TypeDeclaration is null.
    Act: Invoke the junitJupiterSpringBootTestTypeCustomizer method with null as the argument.
    Assert: Use JUnit assertions to validate if an appropriate exception (e.g., NullPointerException or IllegalArgumentException) is thrown.
  Validation:
    The assertion is meant to establish whether the method can handle null input while making the necessary modifications to TypeDeclaration. The test aims to scrutinize the method's robustness and error handling.

  Scenario 3: Validate the result when mock TypeDeclaration already has the "SpringBootTest" annotation

  Details:
    TestName: testCustomizerWithExistingSpringBootTestAnnotation.
    Description: This test is designed to check how the method handles a scenario where the mock TypeDeclaration already contains the "SpringBootTest" annotation.
  Execution:
    Arrange: Create a mock of TypeDeclaration and add the "SpringBootTest" annotation to it.
    Act: Invoke the junitJupiterSpringBootTestTypeCustomizer method with the annotated mock.
    Assert: Use JUnit assertions to check if the annotation is added only once, i.e., the original annotation wasn't duplicated.
  Validation:
    The assertion checks the handling of already annotated TypeDeclaration by the method. The intended result - the annotation's single instance - signifies the method's ability to avoid unnecessary annotation duplication.

"""
*/

// ********RoostGPT********

package io.spring.initializr.generator.spring.code;

import static org.mockito.Mockito.verify;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import io.spring.initializr.generator.language.TypeDeclaration;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;
import io.spring.initializr.generator.condition.ConditionalOnPackaging;
import io.spring.initializr.generator.condition.ConditionalOnPlatformVersion;
import io.spring.initializr.generator.language.ClassName;
import io.spring.initializr.generator.packaging.war.WarPackaging;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationConfiguration;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

public class SourceCodeProjectGenerationConfigurationJunitJupiterSpringBootTestTypeCustomizerTest {

	@Test
	@Tag("valid")
	public void testSpringBootTestAnnotationAddedSuccessfully() {
		// Arrange
		TypeDeclaration mockedTypeDeclaration = Mockito.mock(TypeDeclaration.class);
		SourceCodeProjectGenerationConfiguration config = new SourceCodeProjectGenerationConfiguration();
		// Act
		config.junitJupiterSpringBootTestTypeCustomizer().customize(mockedTypeDeclaration);
		// Assert
		verify(mockedTypeDeclaration).annotations()
			.add(ClassName.of("org.springframework.boot.test.context.SpringBootTest"));
	}

	@Test
	@Tag("invalid")
	public void testCustomizerWithNullTypeDeclaration() {
		// Arrange
		SourceCodeProjectGenerationConfiguration config = new SourceCodeProjectGenerationConfiguration();
		// Act & Assert
		assertThrows(NullPointerException.class, () -> {
			config.junitJupiterSpringBootTestTypeCustomizer().customize(null);
		});
	}

	@Test
	@Tag("valid")
	public void testCustomizerWithExistingSpringBootTestAnnotation() {
		// Arrange
		TypeDeclaration mockedTypeDeclaration = Mockito.mock(TypeDeclaration.class);
		Mockito
			.when(mockedTypeDeclaration.annotations()
				.contains(ClassName.of("org.springframework.boot.test.context.SpringBootTest")))
			.thenReturn(true);
		SourceCodeProjectGenerationConfiguration config = new SourceCodeProjectGenerationConfiguration();
		// Act
		config.junitJupiterSpringBootTestTypeCustomizer().customize(mockedTypeDeclaration);
		// Assert
		verify(mockedTypeDeclaration, Mockito.times(1)).annotations()
			.add(ClassName.of("org.springframework.boot.test.context.SpringBootTest"));

	}

}