/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=springBootApplicationAnnotator_0b5eb46fcc
ROOST_METHOD_SIG_HASH=springBootApplicationAnnotator_d1065844ea

"""
  Scenario 1: Tests to check if springBootApplicationAnnotator applies the @SpringBootApplication annotation correctly

  Details:
    TestName: testSpringBootApplicationAnnotation
    Description: This test is meant to check whether the MainApplicationTypeCustomizer returned by springBootApplicationAnnotator method correctly adds the @SpringBootApplication annotation to the given TypeDeclaration.

  Execution:
    Arrange: Create a mock TypeDeclaration object.
    Act: Invoke the springBootApplicationAnnotator method and pass the mock TypeDeclaration object to the returned MainApplicationTypeCustomizer.
    Assert: Use JUnit assertions to verify that the @SpringBootApplication annotation has been added to the mock TypeDeclaration object.

  Validation:
    This assertion aims to verify that the springBootApplicationAnnotator method returns a MainApplicationTypeCustomizer which correctly annotates the given TypeDeclaration with @SpringBootApplication. The expected result is based on the functionality of springBootApplicationAnnotator which is designed to configure the main application type with the @SpringBootApplication annotation. This test is significant as it verifies whether the method under test is able to correctly configure the main application with the intended annotation.

  ----------------------------------------------------------------------------------

  Scenario 2: Test to check the effect of springBootApplicationAnnotator on an already annotated TypeDeclaration

  Details:
    TestName: testAlreadyAnnotatedTypeDeclaration
    Description: This test is meant to verify the behavior of springBootApplicationAnnotator when the provided TypeDeclaration already has an annotation.

  Execution:
    Arrange: Create a mock TypeDeclaration that is already annotated with @SpringBootApplication.
    Act: Invoke the springBootApplicationAnnotator method and pass the mock TypeDeclaration object to the returned MainApplicationTypeCustomizer.
    Assert: Use JUnit assertions to verify that the @SpringBootApplication annotation has not been added twice to the mock TypeDeclaration object.

  Validation:
    The assertion is aimed at ensuring that the MainApplicationTypeCustomizer returned by the springBootApplicationAnnotator method does not duplicate annotations. This is based on the assumption that a type declaration can only have one instance of any specific annotation. This test is central to the method’s functionality since it allows us to verify its behavior when dealing with already-annotated TypeDeclaration objects.
 """
*/

// ********RoostGPT********

package io.spring.initializr.generator.spring.code;

import io.spring.initializr.generator.language.TypeDeclaration;
import io.spring.initializr.generator.language.Annotation;
import io.spring.initializr.generator.language.ClassName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import io.spring.initializr.generator.condition.ConditionalOnPackaging;
import io.spring.initializr.generator.condition.ConditionalOnPlatformVersion;
import io.spring.initializr.generator.packaging.war.WarPackaging;
import io.spring.initializr.generator.project.ProjectDescription;
import io.spring.initializr.generator.project.ProjectGenerationConfiguration;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

public class SourceCodeProjectGenerationConfigurationSpringBootApplicationAnnotatorTest {

	private SourceCodeProjectGenerationConfiguration configuration;

	private TypeDeclaration mockTypeDeclaration;

	@BeforeEach
	public void setup() {
		configuration = new SourceCodeProjectGenerationConfiguration();
		mockTypeDeclaration = Mockito.mock(TypeDeclaration.class);
	}

	@Test
	@Tag("valid")
	public void testSpringBootApplicationAnnotation() {
		configuration.springBootApplicationAnnotator().customize(mockTypeDeclaration);
		Mockito.verify(mockTypeDeclaration)
			.annotations()
			.add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
	}

	@Test
	@Tag("valid")
	public void testAlreadyAnnotatedTypeDeclaration() {
		Mockito
			.when(mockTypeDeclaration.annotations()
				.has(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication")))
			.thenReturn(true);
		configuration.springBootApplicationAnnotator().customize(mockTypeDeclaration);
		Mockito.verify(mockTypeDeclaration, Mockito.never())
			.annotations()
			.add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"));
	}

}