/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-spring-movie using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=contribute_0c3025b7f2
ROOST_METHOD_SIG_HASH=contribute_a94e4219ee

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator/src/test/java/io/spring/initializr/generator/project/contributor/MultipleResourcesProjectContributorTests.java
Tests:
    "@Test
@Test
void contribute(@TempDir Path directory) throws IOException {
    new MultipleResourcesProjectContributor("classpath:/data/multi").contribute(directory);
    assertThat(directory.resolve("one.properties")).exists().isRegularFile();
    assertThat(directory.resolve("two.xml")).exists().isRegularFile();
}
"
    "@Test
@Test
void contributeWithTrailingSlash(@TempDir Path directory) throws IOException {
    new MultipleResourcesProjectContributor("classpath:/data/multi/").contribute(directory);
    assertThat(directory.resolve("one.properties")).exists().isRegularFile();
    assertThat(directory.resolve("two.xml")).exists().isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/info/BomRangesInfoContributorTests.java
Tests:
    "@Test
private static Info getInfo(InitializrMetadata metadata) {
    Info.Builder builder = new Info.Builder();
    new BomRangesInfoContributor(new SimpleInitializrMetadataProvider(metadata)).contribute(builder);
    return builder.build();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/MavenBuildProjectContributorTests.java
Tests:
    "@Test
@Test
void mavenBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    MavenBuild build = new MavenBuild();
    new MavenBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path pomFile = projectDir.resolve("pom.xml");
    assertThat(pomFile).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/container/docker/compose/ComposeProjectContributorTests.java
Tests:
    "@Test
@Test
void composeFileIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    ComposeFile compose = new ComposeFile();
    compose.services().add("test", (service) -> service.image("my-image:1.2.3"));
    new ComposeProjectContributor(compose, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path composeFile = projectDir.resolve("compose.yaml");
    assertThat(composeFile).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/GradleWrapperContributorTests.java
Tests:
    "@Test
@ParameterizedTest(name = "Gradle {0}")
@ValueSource(strings = "8")
void gradleWrapperSetExecutableFlagOnScripts(String gradleVersion) throws IOException {
    Path projectDir = contribute(gradleVersion);
    assertThat(projectDir.resolve("gradlew")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("gradlew.bat")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("gradle/wrapper/gradle-wrapper.jar")).isRegularFile().satisfies(isNotExecutable());
    assertThat(projectDir.resolve("gradle/wrapper/gradle-wrapper.properties")).isRegularFile().satisfies(isNotExecutable());
}
"
    "@Test
Path contribute(String gradleVersion) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new GradleWrapperContributor(gradleVersion).contribute(projectDir);
    return projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/properties/ApplicationPropertiesContributorTests.java
Tests:
    "@Test
@Test
void applicationConfigurationWithDefaultSettings() throws IOException {
    new ApplicationPropertiesContributor(new ApplicationProperties()).contribute(this.directory);
    assertThat(new ProjectStructure(this.directory)).textFile("src/main/resources/application.properties").isEmpty();
}
"
    "@Test
@Test
void shouldAddStringProperty() throws IOException {
    ApplicationProperties properties = new ApplicationProperties();
    properties.add("spring.application.name", "test");
    ApplicationPropertiesContributor contributor = new ApplicationPropertiesContributor(properties);
    contributor.contribute(this.directory);
    assertThat(new ProjectStructure(this.directory)).textFile("src/main/resources/application.properties").lines().contains("spring.application.name=test");
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/GradleBuildProjectContributorTests.java
Tests:
    "@Test
@Test
void groovyDslGradleBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    GradleBuild build = new GradleBuild();
    groovyDslGradleBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path buildGradle = projectDir.resolve("build.gradle");
    assertThat(buildGradle).isRegularFile();
}
"
    "@Test
@Test
void kotlinDslGradleBuildIsContributedInProjectStructure(@TempDir Path projectDir) throws IOException {
    GradleBuild build = new GradleBuild();
    kotlinDslGradleBuildProjectContributor(build, IndentingWriterFactory.withDefaultSettings()).contribute(projectDir);
    Path buildGradleKts = projectDir.resolve("build.gradle.kts");
    assertThat(buildGradleKts).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/scm/git/GitProjectGenerationConfigurationTests.java
Tests:
    "@Test
@Test
void gitIgnoreIsContributedToProject(@TempDir Path directory) {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setBuildSystem(new GradleBuildSystem());
    Path projectDirectory = this.projectTester.withDirectory(directory).generate(description, (context) -> {
        GitIgnoreContributor contributor = context.getBean(GitIgnoreContributor.class);
        contributor.contribute(directory);
        return directory;
    });
    assertThat(projectDirectory.resolve(".gitignore")).isRegularFile();
}
"
    "@Test
@Test
void gitAttributesIsContributedToProject(@TempDir Path directory) {
    MutableProjectDescription description = new MutableProjectDescription();
    description.setBuildSystem(new GradleBuildSystem());
    Path projectDirectory = this.projectTester.withDirectory(directory).generate(description, (context) -> {
        GitAttributesContributor contributor = context.getBean(GitAttributesContributor.class);
        contributor.contribute(directory);
        return directory;
    });
    assertThat(projectDirectory.resolve(".gitattributes")).isRegularFile();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/maven/MavenWrapperContributorTests.java
Tests:
    "@Test
@ParameterizedTest(name = "Maven {0}")
@ValueSource(strings = "3")
void mavenWrapperSetExecutableFlagOnScripts(String mavenVersion) throws IOException {
    Path projectDir = contribute(mavenVersion);
    assertThat(projectDir.resolve("mvnw")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve("mvnw.cmd")).isRegularFile().isExecutable();
    assertThat(projectDir.resolve(".mvn/wrapper/maven-wrapper.properties")).isRegularFile().satisfies(isNotExecutable());
}
"
    "@Test
Path contribute(String mavenVersion) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new MavenWrapperContributor(mavenVersion).contribute(projectDir);
    return projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-actuator/src/test/java/io/spring/initializr/actuate/info/DependencyRangesInfoContributorTests.java
Tests:
    "@Test
private static Info getInfo(InitializrMetadata metadata) {
    Info.Builder builder = new Info.Builder();
    new DependencyRangesInfoContributor(new SimpleInitializrMetadataProvider(metadata)).contribute(builder);
    return builder.build();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-web/src/test/java/io/spring/initializr/web/controller/custom/CustomProjectContributor.java
Tests:
    "@Test
@Override
public void contribute(Path projectRoot) throws IOException {
    if (this.description instanceof CustomProjectDescription && ((CustomProjectDescription) this.description).isCustomFlag()) {
        Files.createFile(projectRoot.resolve("custom.txt"));
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/configuration/WebFoldersContributorTests.java
Tests:
    "@Test
@Test
void webFoldersCreatedWithWebDependency() throws IOException {
    Dependency simple = Dependency.withId("simple", "com.example", "simple", null, Dependency.SCOPE_COMPILE);
    Dependency web = Dependency.withId("web", "com.example", "web", null, Dependency.SCOPE_COMPILE);
    web.setFacets(Collections.singletonList("web"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", simple, web).build();
    Build build = createBuild(metadata);
    build.dependencies().add("simple");
    build.dependencies().add("web");
    Path projectDir = contribute(build, metadata);
    assertThat(projectDir.resolve("src/main/resources/templates")).isDirectory();
    assertThat(projectDir.resolve("src/main/resources/static")).isDirectory();
}
"
    "@Test
@Test
void webFoldersNotCreatedWithoutWebDependency() throws IOException {
    Dependency simple = Dependency.withId("simple", "com.example", "simple", null, Dependency.SCOPE_COMPILE);
    Dependency web = Dependency.withId("web", "com.example", "web", null, Dependency.SCOPE_COMPILE);
    web.setFacets(Collections.singletonList("web"));
    InitializrMetadata metadata = InitializrMetadataTestBuilder.withDefaults().addDependencyGroup("test", simple, web).build();
    Build build = createBuild(metadata);
    build.dependencies().add("simple");
    Path projectDir = contribute(build, metadata);
    assertThat(projectDir.resolve("src/main/resources/templates")).doesNotExist();
    assertThat(projectDir.resolve("src/main/resources/static")).doesNotExist();
}
"
    "@Test
private Path contribute(Build build, InitializrMetadata metadata) throws IOException {
    MutableProjectDescription projectDescription = new MutableProjectDescription();
    projectDescription.setPlatformVersion(Version.parse("1.0.0"));
    new WebFoldersContributor(build, metadata, projectDescription).contribute(this.projectDir);
    return this.projectDir;
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/documentation/HelpDocumentProjectContributorTests.java
Tests:
    "@Test
@Test
void helpDocumentEmptyDoesNotCreateFile() throws IOException {
    HelpDocument document = new HelpDocument(this.templateRenderer);
    assertThat(document.isEmpty()).isTrue();
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new HelpDocumentProjectContributor(document).contribute(projectDir);
    Path helpDocument = projectDir.resolve("HELP.md");
    assertThat(helpDocument).doesNotExist();
}
"
    "@Test
private ListAssert<String> assertHelpDocument(HelpDocument document) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    new HelpDocumentProjectContributor(document).contribute(projectDir);
    return new TextAssert(projectDir.resolve("HELP.md")).lines();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-spring-movie/f4cb706f-9c77-40b7-8faa-ca3c16f5b199/source/initializr/initializr-generator-spring/src/test/java/io/spring/initializr/generator/spring/build/gradle/SettingsGradleProjectContributorTests.java
Tests:
    "@Test
private TextAssert assertSettings(SettingsGradleProjectContributor contributor) throws IOException {
    Path projectDir = Files.createTempDirectory(this.directory, "project-");
    contributor.contribute(projectDir);
    return new TextAssert(projectDir.resolve("test.gradle"));
}
""""
Scenario 1: Contribute Success With Source Code Contents

Details:
    TestName: testContributeWithSourceCodeContents
    Description: This test aims to verify the success of the contribute() method when source code is available. The test will check if source code is successfully written to the file path provided in the project root.
Execution:
    Arrange: Mock the methods of the sourceFactory, description and sourceWriter to return a valid sourceCode, testName and write the sourceCode to the file represented by the path respectively. Also mock the projectRoot Path object.
    Act: Invoke the contribute() method with the mock projectRoot Path object.
    Assert: Check if sourceWriter's writeTo() method was invoked with the correct parameters - description's getBuildSystem().getTestSource(projectRoot, description.getLanguage()) and sourceCode.
Validation:
    The assertion verifies if the given source code was written successfully to the expected file path. A success scenario would mean that the writeTo method does not throw any exceptions and is executed as expected.

Scenario 2: Contribute Failure On File Write

Details:
    TestName: testContributeFailureOnFileWrite
    Description: This test targets IO errors that may occur while writing to a file. It is meant to check the exception-handling mechanism of the contribute method.
Execution:
    Arrange: Mock the methods of the sourceFactory, description and sourceWriter. Use the mock to simulate IOException when the writeTo() method of sourceWriter is invoked.
    Act: Invoke the contribute() method with a valid projectRoot Path object.
    Assert: Expect an IOException to be thrown.
Validation:
    This test will verify that the contribute() method correctly propagates IOExceptions. This is important as it allows for effective error handling and reporting on upper layers of the application.

Scenario 3: Contribute Failure On Invalid Path

Details:
    TestName: testContributeFailureOnInvalidPath
    Description: This test checks if contribute() method can handle and report errors when given an invalid Path which can't be resolved.
Execution:
    Arrange: Mock the methods of the sourceFactory and description. The projectRoot path passed to the method will be a non-existing or invalid path.
    Act: Invoke the contribute() method with the invalid projectRoot Path object.
    Assert: Expect an IOException to be thrown.
Validation:
    This assertion verifies if contribute() method can handle and propagate IOExceptions when provided with an invalid projectRoot Path object. This validation is essential as part of validating the resiliency of the method.

Scenario 4: Contribute With Null Source Code

Details:
    TestName: testContributeWithNullSourceCode
    Description: This test will verify if contribute() method behaves correctly when provided with null source code. This can help catch any NullPointerExceptions that can be caused by null inputs.
Execution:
    Arrange: Mock the methods of the sourceFactory and description to return null for the source code and a valid testName respectively.
    Act: Invoke the contribute() method with a valid projectRoot Path object.
    Assert: Expect a NullPointerException to be thrown.
Validation:
    This assertion verifies if contribute() method can handle and propagate NullPointerException when given null source code. This scenario will validate how null inputs are handled by the method.
"""

*/

// ********RoostGPT********

package io.spring.initializr.generator.spring.code;

import java.io.IOException;
import java.nio.file.Path;
import java.util.function.Supplier;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.ObjectProvider;
import io.spring.initializr.generator.buildsystem.BuildSystem;
import io.spring.initializr.generator.language.SourceCode;
import io.spring.initializr.generator.language.SourceCodeWriter;
import io.spring.initializr.generator.project.ProjectDescription;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;
import org.junit.jupiter.api.*;
import java.util.List;
import java.util.stream.Collectors;
import io.spring.initializr.generator.language.CompilationUnit;
import io.spring.initializr.generator.language.TypeDeclaration;
import io.spring.initializr.generator.project.contributor.ProjectContributor;
import io.spring.initializr.generator.spring.util.LambdaSafe;

public class TestSourceCodeProjectContributorContributeTest {

	@Mock
	private ProjectDescription description;

	@Mock
	private Supplier<SourceCode> sourceFactory;

	@Mock
	private SourceCodeWriter<SourceCode> sourceWriter;

	@Mock
	private ObjectProvider<TestApplicationTypeCustomizer<?>> testApplicationTypeCustomizers;

	@Mock
	private ObjectProvider<TestSourceCodeCustomizer<?, ?, ?>> testSourceCodeCustomizers;

	private TestSourceCodeProjectContributor contributor;

	@BeforeEach
	public void setup() {
		MockitoAnnotations.openMocks(this);
		this.contributor = new TestSourceCodeProjectContributor(description, sourceFactory, sourceWriter,
				testApplicationTypeCustomizers, testSourceCodeCustomizers);
	}

	@Test
	@Tag("valid")
	public void testContributeWithSourceCodeContents() throws IOException {
		Path projectRoot = Mockito.mock(Path.class);
		SourceCode sourceCode = Mockito.mock(SourceCode.class);
		BuildSystem buildSystem = Mockito.mock(BuildSystem.class);

		Mockito.when(sourceFactory.get()).thenReturn(sourceCode);
		Mockito.when(description.getBuildSystem()).thenReturn(buildSystem);

		contributor.contribute(projectRoot);
		Mockito.verify(sourceWriter).writeTo(Mockito.any(), Mockito.eq(sourceCode));
	}

	@Test
	@Tag("invalid")
	public void testContributeFailureOnFileWrite() {
		Path projectRoot = Mockito.mock(Path.class);

		Mockito.doThrow(IOException.class).when(sourceWriter).writeTo(Mockito.any(), Mockito.any());

		Executable executable = () -> {
			contributor.contribute(projectRoot);
		};
		assertThrows(IOException.class, executable);
	}

	@Test
	@Tag("invalid")
	public void testContributeFailureOnInvalidPath() {
		Path projectRoot = Path.of("invalid/path");

		Executable executable = () -> {
			contributor.contribute(projectRoot);
		};
		assertThrows(IOException.class, executable);
	}

	@Test
	@Tag("invalid")
	public void testContributeWithNullSourceCode() {
		Path projectRoot = Mockito.mock(Path.class);

		Mockito.when(sourceFactory.get()).thenReturn(null);

		Executable executable = () -> {
			contributor.contribute(projectRoot);
		};
		assertThrows(NullPointerException.class, executable);
	}

}